#!/usr/bin/env python3
"""Generate BFL translation of Isaiah chapters 41-66."""
import json

# Load part 1
with open('v:/GitHub/orgs/devzolo/bible/static/data/bfl/_isaias_ch1_40.json','r',encoding='utf-8') as f:
    chapters = json.load(f)

# ── Chapter 41 (29 verses) ──
chapters.append({"c":41,"verses":[
{"v":1,"t":"Fiquem em silêncio diante de mim, ilhas! Que as nações renovem as forças! Aproximem-se e falem. Vamos juntos ao julgamento."},
{"v":2,"t":"Quem despertou do oriente aquele que a justiça chama para o seu serviço? Entrega-lhe nações e o faz dominar reis. Com a espada os transforma em pó, com o arco os espalha como palha."},
{"v":3,"t":"Ele os persegue e passa em segurança, por um caminho que nunca tinha pisado."},
{"v":4,"t":"Quem fez e realizou isso? Aquele que chama as gerações desde o princípio. Eu, o Senhor, sou o primeiro e serei o último."},
{"v":5,"t":"As ilhas viram e ficaram com medo. Os confins da terra tremeram. Aproximaram-se e vieram."},
{"v":6,"t":"Cada um ajuda o vizinho e diz ao irmão: Seja forte!"},
{"v":7,"t":"O artesão encoraja o ourives. O que alisa com o martelo anima o que bate na bigorna, dizendo: A solda está boa! E prega o ídolo com pregos para que não caia."},
{"v":8,"t":"Mas você, Israel, meu servo, Jacó, a quem escolhi, descendente de Abraão, meu amigo —"},
{"v":9,"t":"você a quem peguei dos confins da terra, a quem chamei dos cantos mais distantes, a quem disse: Você é meu servo! Eu o escolhi e não o rejeitei."},
{"v":10,"t":"Não tenha medo, pois eu estou com você. Não fique assustado, pois eu sou o seu Deus. Eu o fortaleço e o ajudo. Eu o seguro com a mão direita da minha justiça."},
{"v":11,"t":"Todos os que se irritam contra você ficarão envergonhados e humilhados. Os que lutam contra você serão como nada e desaparecerão."},
{"v":12,"t":"Você procurará os seus inimigos, mas não os encontrará. Os que guerreiam contra você serão como nada, como zero."},
{"v":13,"t":"Porque eu, o Senhor seu Deus, seguro a sua mão direita. Eu lhe digo: Não tenha medo! Eu ajudo você."},
{"v":14,"t":"Não tenha medo, vermezinho de Jacó, povinho de Israel! Eu o ajudo, diz o Senhor. O seu redentor é o Santo de Israel."},
{"v":15,"t":"Eu farei de você um instrumento novo de debulhar, com dentes afiados. Você debulhará e esmagará montanhas e reduzirá colinas a palha."},
{"v":16,"t":"Você os joeirará e o vento os levará, a tempestade os espalhará. Mas você se alegrará no Senhor e se orgulhará no Santo de Israel."},
{"v":17,"t":"Os pobres e necessitados procuram água e não encontram. A língua deles seca de sede. Eu, o Senhor, os responderei. Eu, o Deus de Israel, não os abandonarei."},
{"v":18,"t":"Abrirei rios nos montes pelados e fontes no meio dos vales. Transformarei o deserto em lago de água e a terra seca em nascentes."},
{"v":19,"t":"Plantarei no deserto cedros, acácias, murtas e oliveiras. Porei no ermo ciprestes, olmos e pinheiros juntos."},
{"v":20,"t":"Para que vejam, saibam, pensem e entendam juntos que a mão do Senhor fez isso, e o Santo de Israel criou."},
{"v":21,"t":"Apresentem a sua causa, diz o Senhor. Tragam as suas provas, diz o Rei de Jacó."},
{"v":22,"t":"Tragam os ídolos e digam o que vai acontecer. Contem o que aconteceu antes, para que pensemos e saibamos o resultado. Ou anunciem o que virá."},
{"v":23,"t":"Digam o que acontecerá no futuro, para que saibamos que vocês são deuses. Façam algo, bom ou mau, para que fiquemos impressionados e com medo."},
{"v":24,"t":"Vocês não são nada, e a obra de vocês é zero. Quem os escolhe é algo horrível."},
{"v":25,"t":"Eu despertei alguém do norte, e ele veio. Do nascer do sol, invocou o meu nome. Ele pisará governantes como lama, como o oleiro pisa o barro."},
{"v":26,"t":"Quem anunciou isso desde o princípio, para que soubéssemos? Quem disse antes, para que disséssemos: Está certo? Ninguém anunciou, ninguém disse, ninguém ouviu palavras de vocês."},
{"v":27,"t":"Eu fui o primeiro a dizer a Sião: Olhem, aqui estão eles! E a Jerusalém eu dei um mensageiro de boas notícias."},
{"v":28,"t":"Eu olho, mas não há ninguém. Entre eles não há conselheiro que responda quando pergunto."},
{"v":29,"t":"Todos eles são nada. As obras deles são zero. As imagens de metal são vento e vazio."},
]})

# ── Chapter 42 (25 verses) ──
chapters.append({"c":42,"verses":[
{"v":1,"t":"Eis o meu servo, a quem sustento, o meu escolhido, em quem a minha alma tem prazer. Coloquei o meu Espírito sobre ele. Ele trará justiça às nações."},
{"v":2,"t":"Ele não gritará, não levantará a voz, nem a fará ouvir na rua."},
{"v":3,"t":"Não quebrará a cana rachada, nem apagará o pavio que ainda fumega. Com fidelidade ele trará justiça."},
{"v":4,"t":"Ele não desanimará nem desistirá até estabelecer a justiça na terra. As ilhas distantes esperam pela lei dele."},
{"v":5,"t":"Assim diz o Senhor Deus, que criou os céus e os estendeu, que espalhou a terra e tudo que nela brota, que dá fôlego ao povo sobre ela e espírito aos que andam nela:"},
{"v":6,"t":"Eu, o Senhor, chamei você com justiça. Segurei a sua mão. Eu o guardei e fiz de você aliança para o povo e luz para as nações."},
{"v":7,"t":"Para abrir os olhos dos cegos, para tirar os prisioneiros da cadeia e os que vivem na escuridão da prisão."},
{"v":8,"t":"Eu sou o Senhor. Este é o meu nome. Não darei a minha glória a nenhum outro, nem o meu louvor a ídolos."},
{"v":9,"t":"As coisas anteriores aconteceram. Agora anuncio coisas novas. Antes que brotem, eu as declaro a vocês."},
{"v":10,"t":"Cantem ao Senhor um cântico novo! Cantem o louvor dele desde os confins da terra! Os que navegam pelo mar e tudo que nele há, as ilhas e os que moram nelas."},
{"v":11,"t":"Que o deserto e as cidades levantem a voz, as aldeias onde Quedar mora. Que os moradores de Selá cantem de alegria. Do topo dos montes, gritem!"},
{"v":12,"t":"Deem glória ao Senhor e anunciem o louvor dele nas ilhas."},
{"v":13,"t":"O Senhor sairá como guerreiro. Despertará o zelo como homem de guerra. Gritará, sim, rugirá. Prevalecerá contra os inimigos."},
{"v":14,"t":"Por muito tempo fiquei em silêncio. Me contive e fiquei quieto. Agora grito como mulher em trabalho de parto, arfando e ofegando."},
{"v":15,"t":"Devastarei montes e colinas e secarei toda a vegetação. Transformarei rios em ilhas e secarei os lagos."},
{"v":16,"t":"Guiarei os cegos por um caminho que não conhecem. Por veredas desconhecidas eu os conduzirei. Transformarei a escuridão em luz diante deles e os lugares ásperos em planície. Estas coisas farei e não os abandonarei."},
{"v":17,"t":"Os que confiam em ídolos e dizem a imagens de metal: Vocês são os nossos deuses — esses serão rejeitados com vergonha."},
{"v":18,"t":"Ouçam, surdos! Olhem, cegos, para que possam ver!"},
{"v":19,"t":"Quem é cego senão o meu servo? Quem é surdo como o mensageiro que envio? Quem é tão cego como o meu aliado, tão cego como o servo do Senhor?"},
{"v":20,"t":"Você viu muitas coisas, mas não prestou atenção. Os ouvidos estão abertos, mas ninguém ouve."},
{"v":21,"t":"O Senhor quis, por causa da sua justiça, tornar a lei grande e gloriosa."},
{"v":22,"t":"Mas este é um povo roubado e saqueado. Todos estão presos em buracos e escondidos em prisões. Foram roubados e ninguém os resgata. Foram saqueados e ninguém diz: Devolvam!"},
{"v":23,"t":"Quem entre vocês ouvirá isso? Quem prestará atenção e ouvirá para o futuro?"},
{"v":24,"t":"Quem entregou Jacó ao saqueador e Israel aos ladrões? Não foi o Senhor, contra quem pecamos? Eles não quiseram andar nos caminhos dele nem obedecer à lei dele."},
{"v":25,"t":"Por isso ele derramou sobre eles o calor da sua ira e a violência da guerra. O fogo os cercou por todos os lados, mas não entenderam. Queimou-os, mas não deram importância."},
]})

# ── Chapter 43 (28 verses) ──
chapters.append({"c":43,"verses":[
{"v":1,"t":"Mas agora, assim diz o Senhor, aquele que criou você, Jacó, que formou você, Israel: Não tenha medo, porque eu resgatei você. Chamei você pelo nome. Você é meu."},
{"v":2,"t":"Quando você passar pelas águas, eu estarei com você. Quando passar pelos rios, eles não o afogarão. Quando andar pelo fogo, não se queimará. As chamas não o queimarão."},
{"v":3,"t":"Porque eu sou o Senhor seu Deus, o Santo de Israel, o seu Salvador. Dei o Egito como resgate por você, a Etiópia e Sebá em troca de você."},
{"v":4,"t":"Já que você é precioso aos meus olhos, honrado, e eu o amo, darei homens em troca de você e povos pela sua vida."},
{"v":5,"t":"Não tenha medo, pois estou com você. Do oriente trarei os seus filhos e do ocidente os reunirei."},
{"v":6,"t":"Direi ao norte: Entregue! E ao sul: Não os retenha! Traga os meus filhos de longe e as minhas filhas dos confins da terra."},
{"v":7,"t":"Todos os que são chamados pelo meu nome, que criei para a minha glória, que formei e fiz."},
{"v":8,"t":"Tragam o povo que tem olhos mas é cego, que tem ouvidos mas é surdo."},
{"v":9,"t":"Que todas as nações se juntem e os povos se reúnam. Quem entre eles pode anunciar isso? Quem pode nos contar o que aconteceu antes? Que tragam testemunhas e provem que tinham razão, para que os outros ouçam e digam: É verdade."},
{"v":10,"t":"Vocês são as minhas testemunhas, diz o Senhor, e o meu servo que escolhi. Para que saibam e creiam em mim, e entendam que eu sou. Antes de mim nenhum deus se formou, e depois de mim não haverá outro."},
{"v":11,"t":"Eu, eu sou o Senhor, e fora de mim não há salvador."},
{"v":12,"t":"Eu anunciei, salvei e proclamei, e não havia deus estranho entre vocês. Vocês são minhas testemunhas, diz o Senhor, e eu sou Deus."},
{"v":13,"t":"Desde o princípio eu sou. Ninguém pode livrar da minha mão. Eu faço, e quem desfará?"},
{"v":14,"t":"Assim diz o Senhor, o seu Redentor, o Santo de Israel: Por vocês eu enviei contra Babilônia e derrubarei todas as trancas. Os caldeus gritarão de desespero nos seus navios."},
{"v":15,"t":"Eu sou o Senhor, o Santo de vocês, o Criador de Israel, o Rei de vocês."},
{"v":16,"t":"Assim diz o Senhor, que abriu caminho no mar e vereda nas águas poderosas."},
{"v":17,"t":"Que fez sair carros e cavalos, exército e guerreiros. Eles caíram juntos e não se levantaram. Apagaram-se como pavio."},
{"v":18,"t":"Não se lembrem das coisas passadas. Não pensem nas coisas antigas."},
{"v":19,"t":"Vejam, eu estou fazendo uma coisa nova! Já está brotando. Vocês não percebem? Eu abrirei caminho no deserto e rios no ermo."},
{"v":20,"t":"Os animais do campo me honrarão, os chacais e as avestruzes, porque dou água no deserto e rios no ermo, para dar de beber ao meu povo escolhido."},
{"v":21,"t":"O povo que formei para mim contará o meu louvor."},
{"v":22,"t":"Mas você não me invocou, Jacó. Você se cansou de mim, Israel."},
{"v":23,"t":"Você não me trouxe ovelhas em sacrifício nem me honrou com ofertas. Eu não sobrecarreguei você com ofertas de cereais nem o cansei com incenso."},
{"v":24,"t":"Você não me comprou especiarias com o seu dinheiro nem me satisfez com a gordura dos sacrifícios. Em vez disso, me sobrecarregou com os seus pecados e me cansou com as suas maldades."},
{"v":25,"t":"Eu, eu mesmo, sou o que apago as suas transgressões, por amor a mim. Não me lembrarei dos seus pecados."},
{"v":26,"t":"Faça-me lembrar! Vamos discutir juntos! Apresente a sua defesa para provar que está certo."},
{"v":27,"t":"O seu primeiro pai pecou, e os seus líderes se revoltaram contra mim."},
{"v":28,"t":"Por isso eu profanei os líderes do santuário. Entreguei Jacó à destruição e Israel ao desprezo."},
]})

# ── Chapter 44 (28 verses) ──
chapters.append({"c":44,"verses":[
{"v":1,"t":"Agora ouça, Jacó, meu servo, Israel, que eu escolhi."},
{"v":2,"t":"O Senhor que te fez e te formou desde o ventre, que te ajuda, diz: Não tenha medo, Jacó, meu servo, Jesurum, que eu escolhi."},
{"v":3,"t":"Derramarei água sobre o sedento e rios sobre a terra seca. Derramarei o meu Espírito sobre os seus descendentes e a minha bênção sobre os seus filhos."},
{"v":4,"t":"Eles brotarão como capim entre as águas, como salgueiros junto aos córregos."},
{"v":5,"t":"Um dirá: Eu sou do Senhor. Outro usará o nome de Jacó. Outro escreverá na mão: Do Senhor, e tomará o nome de Israel."},
{"v":6,"t":"Assim diz o Senhor, o Rei de Israel e seu Redentor, o Senhor dos Exércitos: Eu sou o primeiro e eu sou o último. Fora de mim não há Deus."},
{"v":7,"t":"Quem é como eu? Que declare e apresente provas! Que anuncie as coisas desde que eu estabeleci o povo antigo, e as que virão no futuro."},
{"v":8,"t":"Não tenham medo nem fiquem assustados. Eu não disse isso a vocês desde muito tempo? Eu anunciei. Vocês são minhas testemunhas. Existe algum Deus além de mim? Não há outra Rocha. Não conheço nenhuma."},
{"v":9,"t":"Todos os que fazem ídolos são nada. As coisas preciosas deles não servem para nada. As testemunhas deles não veem nem sabem. Serão envergonhados."},
{"v":10,"t":"Quem forma um deus ou funde um ídolo que não serve para nada?"},
{"v":11,"t":"Todos os que fazem isso serão envergonhados. Os artesãos são apenas humanos. Que se reúnam e fiquem de pé — todos ficarão com medo e vergonha."},
{"v":12,"t":"O ferreiro trabalha com o ferro no carvão, dá forma com martelos e trabalha com braço forte. Fica com fome e perde a força. Não bebe água e desmaia."},
{"v":13,"t":"O carpinteiro estica a linha, marca com giz, trabalha com a plaina e traça com o compasso. Faz o ídolo com forma humana, com beleza de homem, para ficar numa casa."},
{"v":14,"t":"Ele corta cedros, escolhe ciprestes e carvalhos. Planta pinheiro e a chuva o faz crescer."},
{"v":15,"t":"O homem usa a madeira para fazer fogo. Pega um pedaço e se aquece. Acende fogo e assa pão. Mas com o resto faz um deus e o adora. Faz um ídolo e se curva diante dele!"},
{"v":16,"t":"Metade da madeira ele queima no fogo. Sobre a metade assa carne, come e fica satisfeito. Também se aquece e diz: Que bom! Estou quente, estou vendo o fogo!"},
{"v":17,"t":"E com o que sobra faz um deus, o seu ídolo. Curva-se diante dele, adora e ora: Salve-me, pois você é o meu deus!"},
{"v":18,"t":"Eles não sabem nem entendem. Os olhos estão fechados para não ver, e o coração para não entender."},
{"v":19,"t":"Ninguém pensa, ninguém tem conhecimento nem inteligência para dizer: Metade eu queimei no fogo, assei pão sobre as brasas, assei carne e comi. E com o resto vou fazer algo horrível? Vou me curvar diante de um pedaço de madeira?"},
{"v":20,"t":"Ele se alimenta de cinzas. O coração enganado o desviou. Ele não consegue se livrar nem dizer: Isto que está na minha mão direita é mentira!"},
{"v":21,"t":"Lembre-se destas coisas, Jacó, e Israel, pois você é meu servo. Eu o formei. Você é meu servo. Israel, não me esquecerei de você."},
{"v":22,"t":"Apaguei as suas transgressões como nuvem e os seus pecados como névoa. Volte para mim, porque eu o resgatei."},
{"v":23,"t":"Cantem, céus, pois o Senhor fez isso! Gritem, profundezas da terra! Cantem de alegria, montes, florestas e todas as árvores! O Senhor resgatou Jacó e será glorificado em Israel!"},
{"v":24,"t":"O Senhor, o seu Redentor, que o formou desde o ventre, diz: Eu sou o Senhor, que fiz todas as coisas, que sozinho estendi os céus e espalhei a terra — quem estava comigo?"},
{"v":25,"t":"Eu desfaço os sinais dos mentirosos e torno os adivinhos loucos. Faço os sábios recuarem e transformo o conhecimento deles em tolice."},
{"v":26,"t":"Eu confirmo a palavra do meu servo e cumpro o conselho dos meus mensageiros. Eu digo sobre Jerusalém: Será habitada! E sobre as cidades de Judá: Serão reconstruídas! Eu levantarei as ruínas."},
{"v":27,"t":"Eu digo ao mar profundo: Seque! Eu secarei os seus rios."},
{"v":28,"t":"Eu digo de Ciro: Ele é o meu pastor e cumprirá tudo o que eu quero. Ele dirá sobre Jerusalém: Seja reconstruída! E sobre o templo: Que o alicerce seja colocado!"},
]})

# ── Chapter 45 (25 verses) ──
chapters.append({"c":45,"verses":[
{"v":1,"t":"Assim diz o Senhor ao seu ungido, a Ciro, a quem segurei pela mão direita para derrubar nações diante dele, para desarmar reis, para abrir portas diante dele que não serão fechadas:"},
{"v":2,"t":"Eu irei adiante de você e aplanarei os montes. Quebrarei as portas de bronze e cortarei as trancas de ferro."},
{"v":3,"t":"Darei a você tesouros escondidos nas trevas e riquezas guardadas em segredo, para que saiba que eu sou o Senhor, o Deus de Israel, que o chama pelo nome."},
{"v":4,"t":"Por causa de Jacó, meu servo, e de Israel, meu escolhido, eu o chamei pelo nome e lhe dei um título de honra, mesmo que você não me conheça."},
{"v":5,"t":"Eu sou o Senhor, e não há outro. Fora de mim não há Deus. Eu o equipei, mesmo que você não me conheça."},
{"v":6,"t":"Para que saibam, do nascer ao pôr do sol, que não há ninguém além de mim. Eu sou o Senhor, e não há outro."},
{"v":7,"t":"Eu formo a luz e crio as trevas. Faço a paz e crio a calamidade. Eu, o Senhor, faço todas estas coisas."},
{"v":8,"t":"Gotejam, céus, lá de cima! Que as nuvens derramem justiça! Abra-se a terra e produza salvação, e a justiça brote junto! Eu, o Senhor, criei isso."},
{"v":9,"t":"Que pena de quem briga com o seu Criador! O caco de barro entre outros cacos de barro! O barro dirá ao oleiro: O que você está fazendo? A sua obra dirá: Ele não tem mãos?"},
{"v":10,"t":"Que pena de quem diz ao pai: O que você gerou? Ou à mãe: O que você deu à luz?"},
{"v":11,"t":"O Senhor, o Santo de Israel e seu Criador, diz: Vocês me perguntam sobre o futuro dos meus filhos e me dão ordens sobre a obra das minhas mãos?"},
{"v":12,"t":"Eu fiz a terra e criei o ser humano sobre ela. As minhas mãos estenderam os céus, e eu dei ordens a todo o exército de estrelas."},
{"v":13,"t":"Eu despertei Ciro com justiça e aplanarei todos os caminhos dele. Ele reconstruirá a minha cidade e libertará os meus exilados, sem cobrar preço nem receber suborno, diz o Senhor dos Exércitos."},
{"v":14,"t":"O Senhor diz: O produto do Egito, o comércio da Etiópia e os altos sabeus virão até você e serão seus. Andarão atrás de você em correntes. Curvar-se-ão e suplicarão: Deus está somente em você, e não há outro Deus."},
{"v":15,"t":"Tu és o Deus que se esconde, ó Deus de Israel, Salvador."},
{"v":16,"t":"Todos os que fazem ídolos serão envergonhados e humilhados juntos."},
{"v":17,"t":"Mas Israel será salvo pelo Senhor com salvação eterna. Vocês não serão envergonhados nem humilhados por toda a eternidade."},
{"v":18,"t":"Porque o Senhor, que criou os céus — ele é Deus! — que formou a terra e a fez — ele a estabeleceu! Não a criou vazia, mas a formou para ser habitada — diz: Eu sou o Senhor, e não há outro."},
{"v":19,"t":"Não falei em segredo, em lugar escuro da terra. Não disse aos descendentes de Jacó: Busquem-me em vão. Eu, o Senhor, falo a verdade e declaro o que é certo."},
{"v":20,"t":"Reúnam-se e venham! Aproximem-se juntos, sobreviventes das nações! Nada sabem os que carregam ídolos de madeira e oram a um deus que não pode salvar."},
{"v":21,"t":"Declarem e apresentem o caso. Que se aconselhem juntos. Quem anunciou isso desde antigamente? Quem disse desde o princípio? Não fui eu, o Senhor? Não há outro Deus além de mim, Deus justo e Salvador. Não há outro além de mim."},
{"v":22,"t":"Voltem-se para mim e sejam salvos, todos os confins da terra! Porque eu sou Deus, e não há outro."},
{"v":23,"t":"Eu jurei por mim mesmo. Da minha boca saiu a verdade, uma palavra que não voltará atrás: Todo joelho se dobrará diante de mim, e toda língua jurará por mim."},
{"v":24,"t":"Dirão de mim: Somente no Senhor há justiça e força. Todos os que se irritam contra ele virão até ele envergonhados."},
{"v":25,"t":"No Senhor, toda a descendência de Israel será justificada e se orgulhará."},
]})

# ── Chapter 46 (13 verses) ──
chapters.append({"c":46,"verses":[
{"v":1,"t":"Bel se curva, Nebo se abaixa. Os ídolos deles são postos sobre animais de carga. As cargas que vocês carregavam são fardos pesados para animais cansados."},
{"v":2,"t":"Juntos se curvam e se abaixam. Não conseguem salvar a carga e eles mesmos vão para o cativeiro."},
{"v":3,"t":"Ouçam-me, casa de Jacó, todo o resto da casa de Israel, vocês que foram carregados por mim desde o ventre, sustentados desde o nascimento."},
{"v":4,"t":"Até a velhice eu sou o mesmo. Até os cabelos brancos eu os carregarei. Eu fiz e eu sustentarei. Eu carregarei e salvarei."},
{"v":5,"t":"Com quem vocês me compararão ou me igualarão? Com quem me medirão para que sejamos parecidos?"},
{"v":6,"t":"Alguns tiram ouro da bolsa e pesam prata na balança. Contratam ourives para fazer um deus. Então se curvam e adoram."},
{"v":7,"t":"Carregam-no nos ombros. Colocam-no no lugar e ali fica. Não se move do lugar. Se alguém grita para ele, não responde. Não salva ninguém da angústia."},
{"v":8,"t":"Lembrem-se disso e tenham coragem. Pensem bem, rebeldes!"},
{"v":9,"t":"Lembrem-se das coisas passadas, desde a antiguidade. Eu sou Deus, e não há outro. Eu sou Deus, e não há ninguém como eu."},
{"v":10,"t":"Eu anuncio o fim desde o princípio e desde a antiguidade coisas que ainda não aconteceram. Eu digo: O meu plano se cumprirá, e farei tudo o que eu quiser."},
{"v":11,"t":"Do oriente chamo uma ave de rapina, de terra distante o homem do meu plano. Eu falei e farei acontecer. Eu planejei e executarei."},
{"v":12,"t":"Ouçam-me, vocês de coração duro, que estão longe da justiça."},
{"v":13,"t":"Eu aproximo a minha justiça. Não está longe. A minha salvação não vai demorar. Darei salvação a Sião e a minha glória a Israel."},
]})

# ── Chapter 47 (15 verses) ──
chapters.append({"c":47,"verses":[
{"v":1,"t":"Desça e sente-se no pó, virgem filha de Babilônia! Sente-se no chão sem trono, filha dos caldeus! Você nunca mais será chamada de delicada e mimada."},
{"v":2,"t":"Pegue a mó e moa farinha. Tire o véu, levante a saia, descubra as pernas e atravesse os rios."},
{"v":3,"t":"A sua nudez será exposta e a sua vergonha será vista. Eu tomarei vingança e não pouparei ninguém."},
{"v":4,"t":"O nosso Redentor — o Senhor dos Exércitos é o nome dele — é o Santo de Israel."},
{"v":5,"t":"Sente-se em silêncio e entre na escuridão, filha dos caldeus! Você nunca mais será chamada de senhora dos reinos."},
{"v":6,"t":"Eu estava com raiva do meu povo. Profanei a minha herança e os entreguei nas suas mãos. Você não teve compaixão deles. Sobre os idosos colocou um jugo muito pesado."},
{"v":7,"t":"Você disse: Serei senhora para sempre! Não pensou nisso nem se lembrou do que aconteceria."},
{"v":8,"t":"Agora ouça isto, você que vive nos prazeres e se sente segura. Que diz no coração: Eu sou, e não há outra. Não ficarei viúva nem perderei filhos."},
{"v":9,"t":"Mas as duas coisas virão sobre você num instante, num único dia: perda de filhos e viuvez. Virão sobre você em toda a sua força, apesar das muitas feitiçarias e dos seus encantamentos poderosos."},
{"v":10,"t":"Você confiou na sua maldade e disse: Ninguém me vê. A sua sabedoria e o seu conhecimento a desviaram. Você disse no coração: Eu sou, e não há outra."},
{"v":11,"t":"Mas o mal virá sobre você sem que saiba como evitar. A desgraça cairá sobre você sem que possa afastá-la. A destruição virá de repente, quando você não espera."},
{"v":12,"t":"Continue com os seus encantamentos e as muitas feitiçarias em que trabalhou desde a juventude. Quem sabe você possa ter sucesso. Quem sabe consiga assustar alguém."},
{"v":13,"t":"Você se cansou com tantos conselhos. Que se levantem e salvem você os que mapeiam os céus, os que observam as estrelas, os que predizem o futuro a cada lua nova."},
{"v":14,"t":"Eles são como palha. O fogo os queimará. Não poderão se salvar do poder da chama. Não é brasa para se aquecer nem fogo para se sentar diante dele."},
{"v":15,"t":"Assim serão para você aqueles com quem se cansou, os que comerciaram com você desde a juventude. Cada um vagará por seu lado. Ninguém a salvará."},
]})

# ── Chapter 48 (22 verses) ──
chapters.append({"c":48,"verses":[
{"v":1,"t":"Ouçam isto, casa de Jacó, vocês que se chamam pelo nome de Israel e saíram das águas de Judá. Juram pelo nome do Senhor e invocam o Deus de Israel, mas não com verdade nem com justiça."},
{"v":2,"t":"Eles se dizem da cidade santa e se apoiam no Deus de Israel, cujo nome é Senhor dos Exércitos."},
{"v":3,"t":"Eu anunciei as coisas passadas desde o princípio. Elas saíram da minha boca e eu as proclamei. De repente agi, e elas aconteceram."},
{"v":4,"t":"Porque eu sabia que você é teimoso, que o seu pescoço é duro como ferro e a sua testa como bronze."},
{"v":5,"t":"Por isso anunciei para você desde o princípio. Antes que acontecesse, eu lhe disse. Para que não dissesse: O meu ídolo fez isso! A minha imagem de madeira e metal ordenou!"},
{"v":6,"t":"Você ouviu tudo. Agora veja! Vocês não vão declarar isso? De agora em diante, anuncio coisas novas, segredos que você não conhecia."},
{"v":7,"t":"Elas são criadas agora, não desde muito tempo. Antes de hoje você não tinha ouvido falar delas, para que não dissesse: Eu já sabia!"},
{"v":8,"t":"Você nunca ouviu, nunca soube, os seus ouvidos não estavam abertos desde antes. Porque eu sabia que você é muito traiçoeiro. Desde o nascimento você é chamado de rebelde."},
{"v":9,"t":"Por amor ao meu nome atraso a minha ira. Por causa da minha honra me contenho para não destruir você."},
{"v":10,"t":"Eu o purifiquei, mas não como prata. Eu o provei na fornalha do sofrimento."},
{"v":11,"t":"Por amor a mim, por amor a mim eu faço isso. Porque como o meu nome poderia ser profanado? Não darei a minha glória a outro."},
{"v":12,"t":"Ouça-me, Jacó, e Israel, a quem chamei. Eu sou. Eu sou o primeiro e eu sou o último."},
{"v":13,"t":"A minha mão fundou a terra e a minha mão direita estendeu os céus. Quando eu os chamo, aparecem juntos."},
{"v":14,"t":"Reúnam-se, todos vocês, e ouçam. Qual dos ídolos anunciou estas coisas? O Senhor o ama. Ele executará o propósito do Senhor contra Babilônia e o braço dele estará contra os caldeus."},
{"v":15,"t":"Eu, eu mesmo falei. Sim, eu o chamei, o trouxe e ele terá sucesso no seu caminho."},
{"v":16,"t":"Aproximem-se de mim e ouçam. Desde o princípio eu não falei em segredo. Desde o tempo em que essas coisas aconteceram, eu estava lá. E agora o Senhor Deus me enviou com o seu Espírito."},
{"v":17,"t":"Assim diz o Senhor, o seu Redentor, o Santo de Israel: Eu sou o Senhor seu Deus, que ensina o que é melhor para você, que o guia pelo caminho que deve seguir."},
{"v":18,"t":"Se você tivesse prestado atenção aos meus mandamentos, a sua paz seria como um rio e a sua justiça como as ondas do mar."},
{"v":19,"t":"Os seus descendentes seriam como a areia, e os filhos do seu ventre como os grãos de areia. O nome deles nunca seria apagado nem destruído diante de mim."},
{"v":20,"t":"Saiam de Babilônia! Fujam dos caldeus! Com voz de alegria anunciem e proclamem! Espalhem até os confins da terra! Digam: O Senhor resgatou o seu servo Jacó!"},
{"v":21,"t":"Eles não tiveram sede quando ele os guiou pelo deserto. Fez a água brotar da rocha para eles. Rachou a rocha e a água jorrou."},
{"v":22,"t":"Não há paz para os perversos, diz o Senhor."},
]})

# ── Chapter 49 (26 verses) ──
chapters.append({"c":49,"verses":[
{"v":1,"t":"Ouçam-me, ilhas! Prestem atenção, povos distantes! O Senhor me chamou desde o ventre. Desde as entranhas da minha mãe ele mencionou o meu nome."},
{"v":2,"t":"Ele fez da minha boca uma espada afiada. Na sombra da sua mão me escondeu. Fez de mim uma flecha polida. Na sua aljava me guardou."},
{"v":3,"t":"Ele me disse: Você é meu servo, Israel, em quem eu serei glorificado."},
{"v":4,"t":"Mas eu disse: Trabalhei à toa. Gastei minhas forças por nada. Porém o meu direito está com o Senhor e a minha recompensa com o meu Deus."},
{"v":5,"t":"Agora diz o Senhor, que me formou desde o ventre para ser seu servo, para trazer Jacó de volta e reunir Israel: Eu sou honrado aos olhos do Senhor, e o meu Deus é a minha força."},
{"v":6,"t":"Ele disse: É pouco você ser meu servo apenas para restaurar as tribos de Jacó e trazer de volta os sobreviventes de Israel. Eu farei de você luz para as nações, para que a minha salvação chegue até os confins da terra."},
{"v":7,"t":"Assim diz o Senhor, o Redentor de Israel e Santo dele, ao desprezado, ao rejeitado pelas nações, ao servo dos governantes: Reis verão e se levantarão. Príncipes se curvarão, por causa do Senhor, que é fiel, o Santo de Israel, que o escolheu."},
{"v":8,"t":"O Senhor diz: No tempo favorável eu o ouvi. No dia da salvação eu o ajudei. Eu o guardarei e farei de você aliança para o povo, para restaurar a terra e redistribuir as heranças devastadas."},
{"v":9,"t":"Para dizer aos prisioneiros: Saiam! E aos que estão na escuridão: Apareçam! Eles se alimentarão à beira dos caminhos. Em todas as colinas peladas haverá pasto."},
{"v":10,"t":"Não terão fome nem sede. O calor e o sol não os atingirão. Aquele que tem compaixão deles os guiará e os levará às fontes de água."},
{"v":11,"t":"Eu transformarei todos os meus montes em caminhos, e as minhas estradas serão levantadas."},
{"v":12,"t":"Vejam! Estes vêm de longe. Estes do norte e do oeste. E estes da terra de Sinim."},
{"v":13,"t":"Cantem de alegria, céus! Exulte, terra! Cantem, montes! Porque o Senhor consolou o seu povo e terá compaixão dos que sofrem."},
{"v":14,"t":"Mas Sião disse: O Senhor me abandonou. O meu Senhor se esqueceu de mim."},
{"v":15,"t":"Será que uma mãe pode se esquecer do bebê que amamenta? Será que não terá compaixão do filho que gerou? Mesmo que ela se esqueça, eu não me esquecerei de você!"},
{"v":16,"t":"Eu gravei você nas palmas das minhas mãos. Os seus muros estão sempre diante de mim."},
{"v":17,"t":"Os seus construtores se apressam. Os que destruíram e arrasaram você sairão de você."},
{"v":18,"t":"Levante os olhos e veja ao redor. Todos se reúnem e vêm até você. Eu juro pela minha vida, diz o Senhor: Você se vestirá de todos eles como enfeite e os usará como noiva."},
{"v":19,"t":"As suas ruínas, os seus desertos e a terra destruída — agora serão pequenos demais para os moradores. Os que devoravam você estarão longe."},
{"v":20,"t":"Os filhos nascidos no seu tempo de perda dirão aos seus ouvidos: Este lugar é pequeno demais para mim. Dê-me espaço para morar!"},
{"v":21,"t":"Você dirá no coração: Quem me gerou estes? Eu estava sem filhos e sozinha, exilada e rejeitada. Quem os criou? Eu fiquei sozinha. Estes, de onde vieram?"},
{"v":22,"t":"O Senhor Deus diz: Eu levantarei a mão para as nações e erguerei a minha bandeira para os povos. Eles trarão os seus filhos nos braços e as filhas nos ombros."},
{"v":23,"t":"Reis serão os pais adotivos de vocês e rainhas as amas. Eles se curvarão diante de você com o rosto no chão e lamberão o pó dos seus pés. Então você saberá que eu sou o Senhor. Os que esperam em mim não serão envergonhados."},
{"v":24,"t":"Será que se pode tomar a presa do guerreiro? O prisioneiro do tirano pode ser libertado?"},
{"v":25,"t":"Mas o Senhor diz: Sim! Os prisioneiros serão tirados do guerreiro e a presa do tirano será resgatada. Eu lutarei contra quem luta contra você e salvarei os seus filhos."},
{"v":26,"t":"Eu farei os seus opressores comerem a própria carne e beberem o próprio sangue como vinho. E todos saberão que eu, o Senhor, sou o seu Salvador e Redentor, o Poderoso de Jacó."},
]})

# ── Chapter 50 (11 verses) ──
chapters.append({"c":50,"verses":[
{"v":1,"t":"O Senhor diz: Onde está a certidão de divórcio da mãe de vocês, que eu despachei? A qual dos meus credores eu vendi vocês? Vejam! Vocês foram vendidos por causa dos seus pecados, e a mãe de vocês foi mandada embora por causa das transgressões de vocês."},
{"v":2,"t":"Por que, quando eu vim, não havia ninguém? Quando chamei, ninguém respondeu? A minha mão é tão curta que não pode resgatar? Não tenho poder para livrar? Com uma repreensão eu seco o mar e transformo rios em deserto. Os peixes fede por falta de água e morrem de sede."},
{"v":3,"t":"Eu visto os céus de escuridão e os cubro com pano grosso."},
{"v":4,"t":"O Senhor Deus me deu língua de discípulo, para saber falar palavra que sustente o cansado. Ele me desperta todas as manhãs. Desperta o meu ouvido para ouvir como discípulo."},
{"v":5,"t":"O Senhor Deus abriu os meus ouvidos, e eu não me rebelei nem voltei atrás."},
{"v":6,"t":"Ofereci as costas aos que batiam e o rosto aos que arrancavam a barba. Não escondi o rosto da vergonha e dos cuspes."},
{"v":7,"t":"O Senhor Deus me ajuda. Por isso não fiquei envergonhado. Endureci o rosto como pedra e sei que não serei envergonhado."},
{"v":8,"t":"Perto está aquele que me justifica. Quem vai me acusar? Compareçamos juntos! Quem é o meu acusador? Que se aproxime de mim!"},
{"v":9,"t":"O Senhor Deus me ajuda. Quem vai me condenar? Todos eles se desgastarão como roupa. A traça os comerá."},
{"v":10,"t":"Quem entre vocês teme o Senhor e obedece a voz do seu servo? Quem anda na escuridão e não tem luz? Confie no nome do Senhor e se apoie no seu Deus."},
{"v":11,"t":"Mas todos vocês que acendem fogo e se armam de tochas — andem na luz do próprio fogo e das tochas que acenderam! Isto receberão da minha mão: vocês se deitarão em dor."},
]})

# ── Chapter 51 (23 verses) ──
chapters.append({"c":51,"verses":[
{"v":1,"t":"Ouçam-me, vocês que buscam a justiça, que procuram o Senhor. Olhem para a rocha de onde foram cortados e para a cisterna de onde foram cavados."},
{"v":2,"t":"Olhem para Abraão, pai de vocês, e para Sara, que os gerou. Quando o chamei, ele era um só. Eu o abençoei e multipliquei."},
{"v":3,"t":"O Senhor consolará Sião. Consolará todos os seus lugares arrasados. Transformará o deserto em Éden e o ermo no jardim do Senhor. Haverá alegria, ação de graças e som de música."},
{"v":4,"t":"Preste atenção, meu povo, e ouça, minha nação. De mim sairá a lei, e eu farei a minha justiça brilhar como luz para os povos."},
{"v":5,"t":"A minha justiça está perto, a minha salvação já vem. Os meus braços julgarão os povos. As ilhas esperam por mim e confiam no meu braço."},
{"v":6,"t":"Levantem os olhos para os céus e olhem para a terra. Os céus desaparecerão como fumaça, a terra se gastará como roupa, e os moradores morrerão como moscas. Mas a minha salvação durará para sempre e a minha justiça nunca falhará."},
{"v":7,"t":"Ouçam-me, vocês que conhecem a justiça, povo que tem a minha lei no coração. Não tenham medo do insulto dos homens nem se assustem com as ofensas deles."},
{"v":8,"t":"A traça os comerá como roupa e o bicho os roerá como lã. Mas a minha justiça durará para sempre e a minha salvação por todas as gerações."},
{"v":9,"t":"Acorde, acorde, vista-se de força, braço do Senhor! Acorde como nos dias antigos, como nas gerações passadas! Não foi você que despedaçou o monstro e furou o dragão?"},
{"v":10,"t":"Não foi você que secou o mar, as águas do grande abismo? Que fez um caminho no fundo do mar para os resgatados passarem?"},
{"v":11,"t":"Os resgatados do Senhor voltarão e chegarão a Sião com cânticos e alegria eterna. Alegria e felicidade os alcançarão, e a tristeza e o suspiro fugirão."},
{"v":12,"t":"Eu, eu sou aquele que consola vocês. Quem é você para ter medo de um ser humano mortal, de um filho de homem que é como capim?"},
{"v":13,"t":"E se esqueceu do Senhor, que o fez, que estendeu os céus e fundou a terra? Você vive com medo o dia inteiro por causa da fúria do opressor que quer destruir. Mas onde está a fúria do opressor?"},
{"v":14,"t":"O prisioneiro curvado logo será libertado. Não morrerá na cova nem faltará pão."},
{"v":15,"t":"Eu sou o Senhor seu Deus, que agita o mar e faz as ondas rugirem. O Senhor dos Exércitos é o meu nome."},
{"v":16,"t":"Eu pus as minhas palavras na sua boca e o cobri com a sombra da minha mão — para plantar os céus, fundar a terra e dizer a Sião: Você é o meu povo."},
{"v":17,"t":"Acorde, acorde, levante-se, Jerusalém! Você bebeu da mão do Senhor o cálice da sua ira. Bebeu até o fundo o cálice que faz cambalear."},
{"v":18,"t":"De todos os filhos que gerou, nenhum a guia. De todos os filhos que criou, nenhum a segura pela mão."},
{"v":19,"t":"Duas coisas caíram sobre você. Quem terá pena? Destruição e ruína, fome e espada. Quem a consolará?"},
{"v":20,"t":"Os seus filhos desmaiaram. Jazem nas esquinas como antílope na rede, cheios da ira do Senhor, da repreensão do seu Deus."},
{"v":21,"t":"Por isso ouça, você que sofre, que está bêbada, mas não de vinho."},
{"v":22,"t":"O seu Senhor, o Senhor, o seu Deus que defende a causa do povo, diz: Eu tirei da sua mão o cálice que faz cambalear. Você não beberá mais do cálice da minha ira."},
{"v":23,"t":"Eu o colocarei na mão dos que atormentaram você, dos que disseram: Deite-se para que passemos por cima! E você fez das costas chão e rua para eles passarem."},
]})

# ── Chapter 52 (15 verses) ──
chapters.append({"c":52,"verses":[
{"v":1,"t":"Acorde, acorde, vista-se de força, Sião! Vista as suas roupas mais bonitas, Jerusalém, cidade santa! Porque nunca mais entrarão em você os impuros."},
{"v":2,"t":"Sacuda o pó! Levante-se, sente-se, Jerusalém! Solte as correntes do seu pescoço, cativa filha de Sião!"},
{"v":3,"t":"O Senhor diz: Vocês foram vendidos de graça e serão resgatados sem dinheiro."},
{"v":4,"t":"O Senhor Deus diz: O meu povo desceu ao Egito e morou lá. Depois a Assíria o oprimiu sem motivo."},
{"v":5,"t":"E agora, o que eu tenho aqui? Diz o Senhor. O meu povo foi levado de graça. Os que o dominam gritam de triunfo, diz o Senhor, e o meu nome é insultado o dia inteiro."},
{"v":6,"t":"Por isso o meu povo conhecerá o meu nome. Naquele dia saberão que eu sou aquele que diz: Aqui estou!"},
{"v":7,"t":"Como são lindos sobre os montes os pés do mensageiro que traz boas notícias, que anuncia a paz, que traz notícias de coisas boas, que anuncia a salvação, que diz a Sião: O seu Deus reina!"},
{"v":8,"t":"Ouça! Os seus vigias levantam a voz. Juntos gritam de alegria, porque verão com os próprios olhos o Senhor voltando a Sião."},
{"v":9,"t":"Gritem de alegria juntos, ruínas de Jerusalém! Porque o Senhor consolou o seu povo. Ele resgatou Jerusalém."},
{"v":10,"t":"O Senhor descobriu o braço santo diante de todas as nações. Todos os confins da terra verão a salvação do nosso Deus."},
{"v":11,"t":"Saiam, saiam, saiam de lá! Não toquem em nada impuro! Saiam do meio dela! Purifiquem-se, vocês que carregam os utensílios do Senhor!"},
{"v":12,"t":"Vocês não sairão com pressa nem fugirão correndo. Porque o Senhor irá adiante de vocês, e o Deus de Israel será a retaguarda."},
{"v":13,"t":"O meu servo agirá com sabedoria. Será exaltado, levantado e elevado ao mais alto lugar."},
{"v":14,"t":"Assim como muitos ficaram horrorizados ao vê-lo — tão desfigurado estava, que não parecia ser humano, a aparência dele não era de um homem —"},
{"v":15,"t":"assim ele surpreenderá muitas nações. Reis fecharão a boca diante dele. Porque verão o que nunca lhes foi contado e entenderão o que nunca tinham ouvido."},
]})

# ── Chapter 53 (12 verses) ──
chapters.append({"c":53,"verses":[
{"v":1,"t":"Quem acreditou na nossa mensagem? A quem foi revelado o braço do Senhor?"},
{"v":2,"t":"Ele cresceu diante dele como broto tenro, como raiz em terra seca. Não tinha beleza nem esplendor que nos atraísse, nada na aparência para que o desejássemos."},
{"v":3,"t":"Era desprezado e rejeitado pelos homens, homem de dores, que conhecia o sofrimento. Como alguém de quem as pessoas escondem o rosto, era desprezado, e nós não o valorizávamos."},
{"v":4,"t":"No entanto, ele carregou as nossas doenças e levou as nossas dores. Nós pensávamos que ele estava sendo castigado, ferido por Deus e humilhado."},
{"v":5,"t":"Mas ele foi ferido por causa das nossas transgressões e esmagado por causa das nossas maldades. O castigo que nos trouxe paz caiu sobre ele, e pelas feridas dele fomos curados."},
{"v":6,"t":"Todos nós andávamos perdidos como ovelhas. Cada um seguia o seu próprio caminho. Mas o Senhor colocou sobre ele a maldade de todos nós."},
{"v":7,"t":"Ele foi maltratado e humilhado, mas não abriu a boca. Como cordeiro levado ao matadouro, como ovelha muda diante dos tosquiadores, ele não abriu a boca."},
{"v":8,"t":"Foi preso e condenado injustamente. Quem da sua geração se importou? Porque ele foi cortado da terra dos vivos. Por causa da transgressão do meu povo, ele foi ferido."},
{"v":9,"t":"Fizeram o túmulo dele com os perversos e com os ricos na sua morte, embora não tivesse feito violência e não houvesse mentira na boca dele."},
{"v":10,"t":"Mas foi a vontade do Senhor esmagá-lo e fazê-lo sofrer. Quando a vida dele for dada como oferta pelo pecado, ele verá a sua descendência, viverá muitos dias, e a vontade do Senhor prosperará na mão dele."},
{"v":11,"t":"Depois do sofrimento da sua alma, ele verá a luz e ficará satisfeito. Pelo conhecimento dele, o meu servo justo justificará a muitos, pois carregará as maldades deles."},
{"v":12,"t":"Por isso eu lhe darei uma parte entre os grandes, e ele dividirá os despojos com os fortes. Porque derramou a sua vida até a morte e foi contado entre os transgressores. Ele carregou o pecado de muitos e intercedeu pelos transgressores."},
]})

# ── Chapter 54 (17 verses) ──
chapters.append({"c":54,"verses":[
{"v":1,"t":"Cante de alegria, estéril, você que nunca deu à luz! Grite de alegria, você que nunca teve dores de parto! Porque os filhos da abandonada são mais numerosos que os da casada, diz o Senhor."},
{"v":2,"t":"Alargue o espaço da sua tenda! Estenda as cortinas sem economizar! Aumente as cordas e firme as estacas!"},
{"v":3,"t":"Porque você se espalhará para a direita e para a esquerda. Os seus descendentes possuirão nações e habitarão cidades abandonadas."},
{"v":4,"t":"Não tenha medo, porque não será envergonhada. Não fique com vergonha, porque não será humilhada. Você esquecerá a vergonha da juventude e não se lembrará mais da humilhação da viuvez."},
{"v":5,"t":"Porque o seu Criador é o seu marido. O Senhor dos Exércitos é o nome dele. O Santo de Israel é o seu Redentor. Ele é chamado Deus de toda a terra."},
{"v":6,"t":"O Senhor chamou você como mulher abandonada e aflita de espírito, como esposa da juventude que foi rejeitada, diz o seu Deus."},
{"v":7,"t":"Por um breve momento eu a abandonei. Mas com grande compaixão a reunirei de volta."},
{"v":8,"t":"Num momento de ira escondi o rosto de você por um instante. Mas com amor eterno terei compaixão de você, diz o Senhor, o seu Redentor."},
{"v":9,"t":"Isso é como nos dias de Noé para mim. Assim como jurei que as águas de Noé nunca mais cobririam a terra, assim juro que nunca mais ficarei com raiva de você nem a repreenderei."},
{"v":10,"t":"Mesmo que os montes se afastem e as colinas tremam, o meu amor por você não se afastará e a minha aliança de paz não será abalada, diz o Senhor, que tem compaixão de você."},
{"v":11,"t":"Ó aflita, açoitada pela tempestade e sem consolo! Eu assentarei as suas pedras com argamassa de cores e os seus alicerces com safiras."},
{"v":12,"t":"Farei os seus pináculos de rubis, as suas portas de cristal e todos os seus muros de pedras preciosas."},
{"v":13,"t":"Todos os seus filhos serão ensinados pelo Senhor, e grande será a paz deles."},
{"v":14,"t":"Você será estabelecida com justiça. Ficará longe da opressão — não terá o que temer. Ficará longe do terror — ele não chegará perto de você."},
{"v":15,"t":"Se alguém atacar você, não será por minha causa. Quem atacar você cairá diante de você."},
{"v":16,"t":"Fui eu quem criou o ferreiro que sopra o fogo de carvão e produz a arma para o seu trabalho. Também fui eu quem criou o destruidor para destruir."},
{"v":17,"t":"Nenhuma arma feita contra você terá sucesso. Toda língua que se levantar contra você em juízo, você condenará. Esta é a herança dos servos do Senhor, e a justiça que vem de mim, diz o Senhor."},
]})

# ── Chapter 55 (13 verses) ──
chapters.append({"c":55,"verses":[
{"v":1,"t":"Venham, todos os que têm sede, venham às águas! E vocês que não têm dinheiro, venham, comprem e comam! Venham, comprem vinho e leite sem dinheiro e sem custo!"},
{"v":2,"t":"Por que vocês gastam dinheiro com o que não é pão? Por que trabalham por aquilo que não satisfaz? Ouçam-me com atenção e comam o que é bom. Que a alma de vocês se delicie com o melhor."},
{"v":3,"t":"Inclinem o ouvido e venham a mim. Ouçam, e a alma de vocês viverá. Eu farei com vocês uma aliança eterna, o amor fiel prometido a Davi."},
{"v":4,"t":"Eu o dei como testemunha para os povos, como líder e comandante das nações."},
{"v":5,"t":"Você chamará nações que não conhece, e nações que não o conheciam correrão até você, por causa do Senhor seu Deus, o Santo de Israel, que o honrou."},
{"v":6,"t":"Busquem o Senhor enquanto ele pode ser encontrado. Chamem por ele enquanto está perto."},
{"v":7,"t":"Que o perverso abandone o seu caminho, e o homem mau os seus pensamentos. Volte-se para o Senhor, que terá misericórdia, para o nosso Deus, que perdoa generosamente."},
{"v":8,"t":"Os meus pensamentos não são os pensamentos de vocês, e os caminhos de vocês não são os meus caminhos, diz o Senhor."},
{"v":9,"t":"Assim como os céus são mais altos que a terra, assim os meus caminhos são mais altos que os caminhos de vocês, e os meus pensamentos mais altos que os pensamentos de vocês."},
{"v":10,"t":"Assim como a chuva e a neve descem do céu e não voltam sem regar a terra, fazendo-a brotar e dar semente ao que planta e pão ao que come,"},
{"v":11,"t":"assim será a palavra que sai da minha boca. Ela não voltará para mim vazia, mas fará o que eu quero e cumprirá o propósito para o qual a enviei."},
{"v":12,"t":"Vocês sairão com alegria e serão guiados em paz. Os montes e as colinas cantarão de alegria diante de vocês, e todas as árvores do campo baterão palmas."},
{"v":13,"t":"Em vez de espinheiro crescerá cipreste. Em vez de erva daninha crescerá murta. Isso será para o nome do Senhor, como sinal eterno que nunca se apagará."},
]})

# ── Chapter 56 (12 verses) ──
chapters.append({"c":56,"verses":[
{"v":1,"t":"O Senhor diz: Mantenham a justiça e façam o que é certo, porque a minha salvação está perto e a minha justiça está para se revelar."},
{"v":2,"t":"Feliz o homem que faz isso e o ser humano que se agarra a isso: que guarda o sábado sem profaná-lo e segura a mão para não fazer nenhum mal."},
{"v":3,"t":"O estrangeiro que se uniu ao Senhor não diga: O Senhor certamente me separará do seu povo. E o eunuco não diga: Eu sou apenas uma árvore seca."},
{"v":4,"t":"O Senhor diz aos eunucos que guardam os meus sábados, que escolhem o que me agrada e se mantêm firmes na minha aliança:"},
{"v":5,"t":"Eu lhes darei na minha casa e dentro dos meus muros um memorial e um nome melhor do que filhos e filhas. Darei um nome eterno que nunca será apagado."},
{"v":6,"t":"E os estrangeiros que se unirem ao Senhor para servi-lo, para amar o nome do Senhor e para serem seus servos — todos os que guardam o sábado sem profaná-lo e se mantêm firmes na minha aliança —"},
{"v":7,"t":"eu os trarei ao meu monte santo e os alegrarei na minha casa de oração. Os sacrifícios e ofertas deles serão aceitos no meu altar, porque a minha casa será chamada casa de oração para todos os povos."},
{"v":8,"t":"O Senhor Deus, que reúne os dispersos de Israel, diz: Eu ainda reunirei outros além dos que já foram reunidos."},
{"v":9,"t":"Venham, todos os animais do campo! Venham comer, todos os animais da floresta!"},
{"v":10,"t":"Os vigias de Israel são cegos. Todos são ignorantes. São cães mudos que não sabem latir. Deitam-se e sonham. Adoram dormir."},
{"v":11,"t":"São cães gulosos que nunca se satisfazem. São pastores que não sabem entender. Todos seguem o próprio caminho, cada um buscando o próprio lucro."},
{"v":12,"t":"Venham, dizem, vou buscar vinho! Vamos nos embebedar com bebida forte! Amanhã será como hoje, ou até melhor!"},
]})

# ── Chapter 57 (21 verses) ──
chapters.append({"c":57,"verses":[
{"v":1,"t":"O justo morre e ninguém se importa. Os homens fiéis são levados e ninguém percebe que o justo é tirado para ser poupado do mal."},
{"v":2,"t":"Ele entra na paz. Descansam nos seus leitos os que andaram com retidão."},
{"v":3,"t":"Mas vocês, aproximem-se aqui, filhos da feiticeira, descendentes do adúltero e da prostituta."},
{"v":4,"t":"De quem vocês estão zombando? Contra quem abrem a boca e mostram a língua? Vocês não são filhos da transgressão, descendentes da mentira?"},
{"v":5,"t":"Vocês se excitam entre os carvalhos, debaixo de toda árvore verde. Sacrificam filhos nos vales, debaixo das rochas que se projetam."},
{"v":6,"t":"As pedras lisas do vale são a sua parte. Elas são a sua herança. Para elas vocês derramaram ofertas e fizeram sacrifícios de cereais. Eu deveria aceitar isso?"},
{"v":7,"t":"Sobre monte alto e elevado você armou a cama. Lá subiu para oferecer sacrifícios."},
{"v":8,"t":"Atrás da porta e da ombreira você colocou os seus símbolos. Longe de mim, você se despiu, subiu na cama e a abriu bem. Fez acordo com eles. Amou a cama deles. Viu a nudez deles."},
{"v":9,"t":"Você foi ao rei com óleo e multiplicou os perfumes. Mandou embaixadores para longe e desceu até o mundo dos mortos."},
{"v":10,"t":"Você se cansou com tanto caminho, mas não disse: Não adianta. Encontrou nova energia e por isso não desistiu."},
{"v":11,"t":"De quem você teve medo e temor, para que mentisse e não se lembrasse de mim? Não é porque eu fiquei em silêncio por muito tempo que você não me teme?"},
{"v":12,"t":"Eu vou expor a sua justiça e as suas obras. Elas não vão ajudar você."},
{"v":13,"t":"Quando gritar, que a coleção dos seus ídolos a salve! O vento levará todos eles, um sopro os tirará. Mas quem se refugia em mim herdará a terra e possuirá o meu monte santo."},
{"v":14,"t":"E dirão: Construam, construam, preparem o caminho! Tirem os obstáculos do caminho do meu povo!"},
{"v":15,"t":"Porque assim diz o Alto e Exaltado, que vive para sempre, cujo nome é Santo: Eu moro no alto e santo lugar, mas também com o contrito e humilde de espírito, para dar vida ao espírito dos humildes e ao coração dos contritos."},
{"v":16,"t":"Eu não acusarei para sempre nem ficarei com raiva sem parar, senão o espírito definharia diante de mim, as almas que eu criei."},
{"v":17,"t":"Por causa da maldade da ganância dele, fiquei com raiva e o castiguei. Escondi o rosto e fiquei furioso. Mas ele seguiu teimoso pelo caminho do próprio coração."},
{"v":18,"t":"Eu vi os caminhos dele, mas eu o curarei. Eu o guiarei e lhe restaurarei o consolo, a ele e aos que choram por ele."},
{"v":19,"t":"Eu crio o fruto dos lábios: Paz, paz, para o que está longe e para o que está perto, diz o Senhor. Eu o curarei."},
{"v":20,"t":"Mas os perversos são como o mar agitado, que não pode se acalmar, cujas águas lançam lama e sujeira."},
{"v":21,"t":"Não há paz para os perversos, diz o meu Deus."},
]})

# ── Chapter 58 (14 verses) ──
chapters.append({"c":58,"verses":[
{"v":1,"t":"Grite bem alto, não se contenha! Levante a voz como trombeta! Mostre ao meu povo a transgressão deles e à casa de Jacó os pecados deles."},
{"v":2,"t":"Eles me procuram dia a dia e querem saber os meus caminhos, como se fossem uma nação que pratica a justiça e não abandona as leis de Deus. Pedem-me decisões justas e querem estar perto de Deus."},
{"v":3,"t":"Eles dizem: Por que jejuamos e tu não vês? Por que nos humilhamos e tu não percebes? Porque no dia do jejum, vocês fazem o que querem e exploram todos os trabalhadores."},
{"v":4,"t":"Vocês jejuam para brigar e discutir, para dar socos com maldade. O jejum que vocês fazem hoje não fará a sua voz ser ouvida no alto."},
{"v":5,"t":"É esse o jejum que eu escolhi? Um dia em que a pessoa se humilha? Curvar a cabeça como junco e se deitar sobre pano grosso e cinzas? Isso vocês chamam de jejum, um dia agradável ao Senhor?"},
{"v":6,"t":"O jejum que eu escolhi não é este: soltar as correntes da injustiça, desamarrar as cordas do jugo, libertar os oprimidos e quebrar todo jugo?"},
{"v":7,"t":"Não é repartir o pão com o faminto, abrigar os pobres sem teto, vestir o nu e não se esconder do seu próprio parente?"},
{"v":8,"t":"Então a sua luz brilhará como a aurora e a cura chegará rápido. A sua justiça irá à frente e a glória do Senhor será a retaguarda."},
{"v":9,"t":"Então você chamará e o Senhor responderá. Gritará por ajuda e ele dirá: Aqui estou! Se tirar do meio de você o jugo, o dedo que acusa e a fala maldosa,"},
{"v":10,"t":"se você oferecer ao faminto o que deseja e satisfizer o necessitado, então a sua luz brilhará na escuridão e a sua noite será como o meio-dia."},
{"v":11,"t":"O Senhor o guiará sempre. Saciará a sua alma nos lugares secos e fortalecerá os seus ossos. Você será como jardim regado e como nascente cujas águas nunca secam."},
{"v":12,"t":"Os seus descendentes reconstruirão as ruínas antigas. Você levantará alicerces de muitas gerações. Você será chamado reparador de brechas, restaurador de ruas para morar."},
{"v":13,"t":"Se você deixar de pisar o sábado, de fazer o que quer no meu dia santo, se chamar o sábado de prazer e o santo dia do Senhor de honrado, se honrá-lo não seguindo os seus caminhos, não fazendo o que quer nem falando o que bem entende,"},
{"v":14,"t":"então você se deliciará no Senhor. Eu farei você cavalgar sobre os altos da terra e alimentar você com a herança de Jacó, seu pai. A boca do Senhor falou."},
]})

# ── Chapter 59 (21 verses) ──
chapters.append({"c":59,"verses":[
{"v":1,"t":"A mão do Senhor não é tão curta que não possa salvar. O ouvido dele não é tão surdo que não possa ouvir."},
{"v":2,"t":"São as maldades de vocês que fazem separação entre vocês e o seu Deus. São os pecados de vocês que escondem o rosto dele, para que não ouça."},
{"v":3,"t":"As mãos de vocês estão manchadas de sangue e os dedos de maldade. Os lábios falam mentira e a língua murmura maldade."},
{"v":4,"t":"Ninguém apresenta a causa com justiça nem defende a verdade. Confiam em coisas vazias e falam mentiras. Concebem maldade e dão à luz destruição."},
{"v":5,"t":"Chocam ovos de cobra e tecem teia de aranha. Quem comer dos ovos morrerá, e se quebrar um, sairá uma víbora."},
{"v":6,"t":"As teias deles não servem para roupa. Ninguém pode se vestir com o que fazem. As obras deles são obras de maldade, e violência está nas mãos deles."},
{"v":7,"t":"Os pés deles correm para o mal e se apressam para derramar sangue inocente. Os pensamentos deles são de maldade. Destruição e ruína estão nos caminhos deles."},
{"v":8,"t":"O caminho da paz eles não conhecem. Não há justiça nos passos deles. Fizeram caminhos tortos. Quem anda neles não conhece a paz."},
{"v":9,"t":"Por isso a justiça está longe de nós e a retidão não nos alcança. Esperamos luz, mas há trevas. Esperamos claridade, mas andamos na escuridão."},
{"v":10,"t":"Apalpamos a parede como cegos. Andamos como quem não tem olhos. Tropeçamos ao meio-dia como à noite. No meio dos fortes, somos como mortos."},
{"v":11,"t":"Todos nós rosnamos como ursos e gememos como pombas. Esperamos justiça, mas não vem. Esperamos salvação, mas ela está longe."},
{"v":12,"t":"As nossas transgressões são muitas diante de ti, e os nossos pecados testemunham contra nós. As transgressões estão conosco e conhecemos as nossas maldades."},
{"v":13,"t":"Transgredir e negar o Senhor, afastar-se do nosso Deus, falar de opressão e revolta, conceber e proferir do coração palavras de mentira."},
{"v":14,"t":"A justiça foi empurrada para trás e a retidão fica de longe. A verdade tropeçou na praça e a honestidade não pode entrar."},
{"v":15,"t":"A verdade desapareceu, e quem se afasta do mal é roubado. O Senhor viu e ficou descontente porque não havia justiça."},
{"v":16,"t":"Ele viu que não havia ninguém e ficou espantado que ninguém intercedesse. Então o seu próprio braço trouxe salvação e a sua justiça o sustentou."},
{"v":17,"t":"Vestiu a justiça como armadura e colocou o capacete da salvação na cabeça. Vestiu as roupas da vingança e se cobriu com o manto do zelo."},
{"v":18,"t":"De acordo com as obras, assim ele retribuirá: fúria para os adversários, castigo para os inimigos, paga para as ilhas distantes."},
{"v":19,"t":"Do oeste temerão o nome do Senhor e do nascer do sol a glória dele. Pois ele virá como rio impetuoso impulsionado pelo sopro do Senhor."},
{"v":20,"t":"Um Redentor virá a Sião, aos que se arrependerem da transgressão em Jacó, diz o Senhor."},
{"v":21,"t":"Quanto a mim, esta é a minha aliança com eles, diz o Senhor: O meu Espírito que está sobre você e as minhas palavras que coloquei na sua boca não se afastarão da sua boca, nem da boca dos seus filhos, nem da boca dos filhos dos seus filhos, de agora em diante e para sempre, diz o Senhor."},
]})

# ── Chapter 60 (22 verses) ──
chapters.append({"c":60,"verses":[
{"v":1,"t":"Levante-se, brilhe, porque a sua luz chegou! A glória do Senhor nasceu sobre você!"},
{"v":2,"t":"A escuridão cobrirá a terra e trevas espessas os povos. Mas sobre você o Senhor nascerá, e a glória dele aparecerá sobre você."},
{"v":3,"t":"As nações caminharão na sua luz, e os reis no brilho do seu nascer."},
{"v":4,"t":"Levante os olhos e veja ao redor. Todos se reúnem e vêm até você. Os seus filhos vêm de longe e as filhas são trazidas nos braços."},
{"v":5,"t":"Você verá e ficará radiante. O coração vai bater forte e se encher de alegria, porque a riqueza do mar virá até você e os tesouros das nações chegarão."},
{"v":6,"t":"Multidões de camelos cobrirão a terra, dromedários de Midiã e Efá. Todos de Sabá virão trazendo ouro e incenso, proclamando os louvores do Senhor."},
{"v":7,"t":"Todos os rebanhos de Quedar se reunirão para você. Os carneiros de Nebaiote servirão para o altar. Serão aceitos no meu altar e eu glorificarei a minha casa gloriosa."},
{"v":8,"t":"Quem são esses que voam como nuvens, como pombas para as suas janelas?"},
{"v":9,"t":"As ilhas esperam por mim. Os navios de Társis vêm primeiro, trazendo seus filhos de longe, com prata e ouro, para o nome do Senhor seu Deus, o Santo de Israel, que o honrou."},
{"v":10,"t":"Estrangeiros reconstruirão os seus muros e os reis deles servirão a você. Na minha ira eu castiguei você, mas no meu favor eu tive compaixão."},
{"v":11,"t":"As suas portas estarão sempre abertas. Não fecharão nem de dia nem de noite, para que as riquezas das nações sejam trazidas, com os reis delas em procissão."},
{"v":12,"t":"A nação e o reino que não servirem você perecerão. Essas nações serão completamente destruídas."},
{"v":13,"t":"A glória do Líbano virá até você — o cipreste, o olmo e o pinheiro juntos — para embelezar o meu santuário. Eu honrarei o lugar dos meus pés."},
{"v":14,"t":"Os filhos dos que oprimiram você virão curvados diante de você. Todos os que desprezaram você se curvarão aos seus pés e chamarão você de Cidade do Senhor, Sião do Santo de Israel."},
{"v":15,"t":"Em vez de ser abandonada e odiada, sem ninguém passando por você, eu farei de você o orgulho eterno e a alegria de todas as gerações."},
{"v":16,"t":"Você mamará o leite das nações e será amamentada pelo peito dos reis. Então saberá que eu, o Senhor, sou o seu Salvador e Redentor, o Poderoso de Jacó."},
{"v":17,"t":"Em vez de bronze, trarei ouro. Em vez de ferro, prata. Em vez de madeira, bronze. Em vez de pedras, ferro. Farei da paz o seu governo e da justiça o seu líder."},
{"v":18,"t":"A violência nunca mais será ouvida na sua terra, nem destruição e ruína nas suas fronteiras. Você chamará os muros de Salvação e as portas de Louvor."},
{"v":19,"t":"O sol não será mais a sua luz de dia, nem a lua brilhará para você. O Senhor será a sua luz eterna e o seu Deus será o seu esplendor."},
{"v":20,"t":"O seu sol nunca mais se porá e a lua nunca mais se esconderá. O Senhor será a sua luz eterna, e os dias do seu luto terminarão."},
{"v":21,"t":"Todo o seu povo será justo. Possuirão a terra para sempre — o broto que eu plantei, a obra das minhas mãos, para a minha glória."},
{"v":22,"t":"O menor se tornará em mil e o mais pequeno em nação poderosa. Eu, o Senhor, apressarei isso no tempo certo."},
]})

# ── Chapter 61 (11 verses) ──
chapters.append({"c":61,"verses":[
{"v":1,"t":"O Espírito do Senhor Deus está sobre mim, porque o Senhor me ungiu para levar boas notícias aos pobres. Ele me enviou para curar os de coração partido, para anunciar liberdade aos presos e soltura aos que estão na cadeia."},
{"v":2,"t":"Para anunciar o ano do favor do Senhor e o dia da vingança do nosso Deus. Para consolar todos os que choram."},
{"v":3,"t":"Para dar aos que choram em Sião uma coroa em vez de cinzas, óleo de alegria em vez de luto, roupa de louvor em vez de espírito de desânimo. Eles serão chamados carvalhos de justiça, plantação do Senhor, para a sua glória."},
{"v":4,"t":"Eles reconstruirão as ruínas antigas e restaurarão os lugares devastados. Renovarão as cidades destruídas, arrasadas por muitas gerações."},
{"v":5,"t":"Estrangeiros ficarão de pé e apascentarão os rebanhos de vocês. Estrangeiros serão os lavradores e os trabalhadores das vinhas."},
{"v":6,"t":"Vocês serão chamados sacerdotes do Senhor. Serão chamados ministros do nosso Deus. Comerão a riqueza das nações e se orgulharão da glória delas."},
{"v":7,"t":"Em vez da vergonha, receberão o dobro. Em vez da humilhação, cantarão de alegria pela parte deles. Na terra possuirão o dobro. A alegria deles será eterna."},
{"v":8,"t":"Porque eu, o Senhor, amo a justiça e odeio o roubo e a maldade. Eu os recompensarei fielmente e farei com eles uma aliança eterna."},
{"v":9,"t":"Os descendentes deles serão conhecidos entre as nações e os filhos entre os povos. Todos os que os virem reconhecerão que são um povo que o Senhor abençoou."},
{"v":10,"t":"Eu me alegro muito no Senhor! A minha alma exulta no meu Deus! Ele me vestiu com as roupas da salvação e me cobriu com o manto da justiça, como noivo que se enfeita com turbante e como noiva que se adorna com as suas joias."},
{"v":11,"t":"Porque, assim como a terra faz brotar as plantas e o jardim faz germinar as sementes, assim o Senhor Deus fará brotar justiça e louvor diante de todas as nações."},
]})

# ── Chapter 62 (12 verses) ──
chapters.append({"c":62,"verses":[
{"v":1,"t":"Por amor a Sião não me calarei e por amor a Jerusalém não descansarei, até que a justiça dela brilhe como o sol e a salvação como tocha acesa."},
{"v":2,"t":"As nações verão a sua justiça e todos os reis a sua glória. Você receberá um nome novo, que a boca do Senhor determinará."},
{"v":3,"t":"Você será uma coroa gloriosa na mão do Senhor, um diadema real na mão do seu Deus."},
{"v":4,"t":"Nunca mais dirão que você é abandonada, nem que a sua terra é deserta. Você será chamada: Meu prazer está nela, e a sua terra: Casada. Porque o Senhor terá prazer em você, e a sua terra terá marido."},
{"v":5,"t":"Assim como o jovem se casa com a virgem, assim os seus filhos se casarão com você. Como o noivo se alegra com a noiva, assim o seu Deus se alegrará com você."},
{"v":6,"t":"Eu coloquei vigias nos seus muros, Jerusalém. Eles nunca ficarão em silêncio, nem de dia nem de noite. Vocês que invocam o Senhor, não descansem!"},
{"v":7,"t":"E não deixem Deus descansar até que ele estabeleça Jerusalém e a torne um louvor na terra!"},
{"v":8,"t":"O Senhor jurou pela mão direita e pelo braço forte: Nunca mais darei o seu trigo como comida para os inimigos. Estrangeiros nunca mais beberão o vinho pelo qual você trabalhou."},
{"v":9,"t":"Os que colherem comerão e louvarão o Senhor. Os que juntarem as uvas beberão nos átrios do meu santuário."},
{"v":10,"t":"Passem, passem pelas portas! Preparem o caminho para o povo! Construam, construam a estrada! Tirem as pedras! Levantem uma bandeira para os povos!"},
{"v":11,"t":"O Senhor proclamou até os confins da terra: Digam à filha de Sião: O seu Salvador vem! A recompensa dele vem com ele, e o pagamento vai adiante dele."},
{"v":12,"t":"Eles serão chamados O Povo Santo, Os Resgatados do Senhor. E você será chamada Procurada, Cidade Não Abandonada."},
]})

# ── Chapter 63 (19 verses) ──
chapters.append({"c":63,"verses":[
{"v":1,"t":"Quem é este que vem de Edom, de Bozra, com roupas vermelhas? Tão esplêndido nas suas vestes, marchando na grandeza da sua força? Sou eu, que falo com justiça, poderoso para salvar."},
{"v":2,"t":"Por que as suas roupas estão vermelhas, como as de quem pisa uvas no lagar?"},
{"v":3,"t":"Eu pisei o lagar sozinho. Dos povos, ninguém estava comigo. Eu os pisei na minha ira e os esmaguei na minha fúria. O sangue deles respingou nas minhas roupas e manchou todas as minhas vestes."},
{"v":4,"t":"Porque o dia da vingança estava no meu coração, e o ano da redenção chegou."},
{"v":5,"t":"Olhei, e não havia quem ajudasse. Fiquei espantado que ninguém me apoiasse. Então o meu próprio braço me salvou, e a minha fúria me sustentou."},
{"v":6,"t":"Pisei os povos na minha ira, embriaguei-os na minha fúria e derramei o sangue deles na terra."},
{"v":7,"t":"Eu contarei o amor fiel do Senhor e os louvores do Senhor, por tudo que o Senhor fez por nós, pela grande bondade com a casa de Israel, que ele concedeu segundo a sua misericórdia e o seu grande amor."},
{"v":8,"t":"Ele disse: Eles são o meu povo, filhos que não me enganarão. E se tornou o Salvador deles."},
{"v":9,"t":"Em toda a angústia deles, ele também sofreu. O anjo da sua presença os salvou. No seu amor e na sua compaixão, ele os resgatou. Ele os levantou e os carregou por todos os dias antigos."},
{"v":10,"t":"Mas eles se revoltaram e entristeceram o Espírito Santo dele. Então ele se tornou inimigo deles e lutou contra eles."},
{"v":11,"t":"Depois se lembraram dos dias antigos, de Moisés e do seu povo. Onde está aquele que os tirou do mar com o pastor do seu rebanho? Onde está aquele que pôs nele o seu Espírito Santo?"},
{"v":12,"t":"Que fez o seu braço glorioso andar à direita de Moisés? Que dividiu as águas diante deles, para fazer um nome eterno?"},
{"v":13,"t":"Que os guiou pelas profundezas como cavalo no deserto, sem que tropeçassem?"},
{"v":14,"t":"Como gado que desce ao vale, o Espírito do Senhor lhes deu descanso. Assim tu guiaste o teu povo, para fazer um nome glorioso para ti."},
{"v":15,"t":"Olha do céu e vê, da tua morada santa e gloriosa. Onde estão o teu zelo e o teu poder? O desejo do teu coração e a tua compaixão estão retidos de mim."},
{"v":16,"t":"Porque tu és o nosso Pai. Abraão não nos conhece e Israel não nos reconhece. Tu, Senhor, és o nosso Pai. O nosso Redentor desde a eternidade é o teu nome."},
{"v":17,"t":"Por que, Senhor, nos deixas andar longe dos teus caminhos e endureces o nosso coração para não te temer? Volta por amor dos teus servos, as tribos da tua herança."},
{"v":18,"t":"Por pouco tempo o teu povo santo possuiu a terra. Os nossos adversários pisaram o teu santuário."},
{"v":19,"t":"Nós nos tornamos como aqueles sobre quem tu nunca governaste, como os que nunca foram chamados pelo teu nome."},
]})

# ── Chapter 64 (12 verses) ──
chapters.append({"c":64,"verses":[
{"v":1,"t":"Se ao menos rasgasses os céus e descesses! Se os montes tremessem diante de ti!"},
{"v":2,"t":"Como o fogo acende a lenha e faz a água ferver, assim o teu nome seria conhecido dos adversários e as nações tremeriam diante de ti!"},
{"v":3,"t":"Quando fizeste coisas terríveis que não esperávamos, tu desceste e os montes tremeram diante de ti."},
{"v":4,"t":"Desde a antiguidade ninguém ouviu, nenhum ouvido percebeu, nenhum olho viu um Deus além de ti, que age em favor daqueles que esperam nele."},
{"v":5,"t":"Tu vens ao encontro do que se alegra em praticar a justiça, dos que se lembram de ti nos teus caminhos. Tu ficaste com raiva porque pecamos. Andamos nisso por muito tempo. Poderemos ser salvos?"},
{"v":6,"t":"Todos nós nos tornamos como algo impuro, e todas as nossas boas ações são como trapo sujo. Todos murchamos como folhas, e as nossas maldades nos levam como o vento."},
{"v":7,"t":"Ninguém invoca o teu nome. Ninguém se esforça para se agarrar a ti. Porque escondeste o rosto de nós e nos entregaste ao poder das nossas maldades."},
{"v":8,"t":"Mas agora, Senhor, tu és o nosso Pai. Nós somos o barro e tu és o oleiro. Todos nós somos obra das tuas mãos."},
{"v":9,"t":"Não fiques tão furioso, Senhor, nem te lembres da maldade para sempre. Olha, nós te pedimos: todos nós somos o teu povo."},
{"v":10,"t":"As tuas cidades santas se tornaram deserto. Sião se tornou deserto. Jerusalém está arrasada."},
{"v":11,"t":"O nosso templo santo e glorioso, onde os nossos pais te louvavam, foi queimado pelo fogo. Tudo o que era precioso para nós está em ruínas."},
{"v":12,"t":"Diante de tudo isso, tu te conterás, Senhor? Ficarás em silêncio e nos humilharás sem parar?"},
]})

# ── Chapter 65 (25 verses) ──
chapters.append({"c":65,"verses":[
{"v":1,"t":"Eu me deixei encontrar por quem não me procurava. Fui achado por quem não me buscava. Eu disse: Aqui estou! Aqui estou! — a uma nação que não invocava o meu nome."},
{"v":2,"t":"O dia inteiro estendi as mãos para um povo rebelde, que anda por caminho que não é bom, seguindo os próprios pensamentos."},
{"v":3,"t":"Um povo que me provoca na cara, o tempo todo. Sacrificam em jardins e queimam incenso sobre altares de tijolos."},
{"v":4,"t":"Sentam-se entre os túmulos e passam a noite em lugares secretos. Comem carne de porco e têm caldo de coisas impuras nas tigelas."},
{"v":5,"t":"Dizem: Fique longe! Não se aproxime de mim, porque eu sou mais santo que você! Esses são fumaça no meu nariz, fogo que arde o dia inteiro."},
{"v":6,"t":"Está escrito diante de mim: Não ficarei em silêncio. Eu retribuirei. Sim, retribuirei no colo deles."},
{"v":7,"t":"As maldades de vocês e as maldades dos pais de vocês juntas, diz o Senhor, que queimaram incenso nos montes e me insultaram nas colinas. Medirei no colo deles a retribuição pelas obras passadas."},
{"v":8,"t":"O Senhor diz: Assim como se encontra suco num cacho de uvas e se diz: Não o destrua, porque há bênção nele — assim eu farei por amor dos meus servos: não destruirei todos."},
{"v":9,"t":"Farei sair de Jacó uma descendência e de Judá herdeiros dos meus montes. Os meus escolhidos possuirão a terra e os meus servos morarão ali."},
{"v":10,"t":"Sarom será pasto para rebanhos e o vale de Acor lugar de descanso para o gado, para o meu povo que me buscou."},
{"v":11,"t":"Mas vocês que abandonam o Senhor, que se esquecem do meu monte santo, que preparam mesa para a Sorte e enchem taça de vinho misturado para o Destino —"},
{"v":12,"t":"eu os destinarei à espada. Todos vocês se curvarão para ser mortos. Porque eu chamei e vocês não responderam. Eu falei e vocês não ouviram. Fizeram o que é mal aos meus olhos e escolheram o que não me agrada."},
{"v":13,"t":"Por isso o Senhor Deus diz: Os meus servos comerão, mas vocês passarão fome. Os meus servos beberão, mas vocês terão sede. Os meus servos se alegrarão, mas vocês ficarão envergonhados."},
{"v":14,"t":"Os meus servos cantarão de alegria no coração, mas vocês gritarão de dor e uivarão de espírito quebrado."},
{"v":15,"t":"Vocês deixarão o nome como maldição para os meus escolhidos. O Senhor Deus matará vocês e dará aos seus servos um nome novo."},
{"v":16,"t":"Quem se abençoar na terra se abençoará pelo Deus da verdade. Quem jurar na terra jurará pelo Deus da verdade. Os sofrimentos passados serão esquecidos e escondidos dos meus olhos."},
{"v":17,"t":"Pois eu estou criando novos céus e nova terra. As coisas passadas não serão lembradas nem virão à mente."},
{"v":18,"t":"Mas alegrem-se e exultem para sempre pelo que eu crio. Porque eu crio Jerusalém para ser alegria e o povo dela para ser prazer."},
{"v":19,"t":"Eu me alegrarei com Jerusalém e terei prazer no meu povo. Nunca mais se ouvirá nela som de choro nem grito de dor."},
{"v":20,"t":"Nunca mais haverá ali bebê que viva poucos dias nem idoso que não complete os seus anos. O jovem morrerá aos cem anos e o pecador será amaldiçoado aos cem anos."},
{"v":21,"t":"Eles construirão casas e morarão nelas. Plantarão vinhas e comerão os frutos."},
{"v":22,"t":"Não construirão para outro morar. Não plantarão para outro comer. Os dias do meu povo serão como os dias da árvore, e os meus escolhidos aproveitarão por muito tempo a obra das suas mãos."},
{"v":23,"t":"Não trabalharão em vão nem terão filhos para a desgraça. Serão descendentes abençoados pelo Senhor, eles e os filhos deles."},
{"v":24,"t":"Antes que chamem, eu responderei. Enquanto ainda estiverem falando, eu ouvirei."},
{"v":25,"t":"O lobo e o cordeiro se alimentarão juntos. O leão comerá capim como o boi. E a serpente comerá pó. Não farão mal nem destruirão em todo o meu santo monte, diz o Senhor."},
]})

# ── Chapter 66 (24 verses) ──
chapters.append({"c":66,"verses":[
{"v":1,"t":"O Senhor diz: O céu é o meu trono e a terra o apoio dos meus pés. Que casa vocês poderiam me construir? Que lugar seria o meu descanso?"},
{"v":2,"t":"A minha mão fez todas estas coisas, e assim todas vieram a existir, diz o Senhor. Mas eu olho para o humilde e arrependido de espírito, que treme diante da minha palavra."},
{"v":3,"t":"Quem mata um boi é como quem mata um homem. Quem sacrifica um cordeiro é como quem quebra o pescoço de um cão. Quem faz oferta de cereais é como quem oferece sangue de porco. Quem queima incenso é como quem adora um ídolo. Eles escolheram os próprios caminhos e a alma deles ama as coisas horríveis."},
{"v":4,"t":"Eu também escolherei punições para eles e trarei sobre eles o que temem. Porque chamei e ninguém respondeu. Falei e ninguém ouviu. Fizeram o mal diante dos meus olhos e escolheram o que não me agrada."},
{"v":5,"t":"Ouçam a palavra do Senhor, vocês que tremem diante da palavra dele: Os seus irmãos que os odeiam e os expulsam por causa do meu nome disseram: Que o Senhor mostre a glória dele para que vejamos a alegria de vocês! Mas eles é que serão envergonhados."},
{"v":6,"t":"Ouçam! Barulho vindo da cidade! Barulho vindo do templo! É a voz do Senhor que dá o pagamento aos inimigos."},
{"v":7,"t":"Antes de sentir as dores, ela deu à luz. Antes que as dores chegassem, teve um filho."},
{"v":8,"t":"Quem já ouviu coisa assim? Quem já viu algo parecido? Pode uma terra nascer num só dia? Pode uma nação ser gerada de uma vez? Pois Sião sentiu as dores e já deu à luz os seus filhos."},
{"v":9,"t":"Será que eu traria até o ponto de nascer e não deixaria nascer? Diz o Senhor. Será que eu, que faço dar à luz, fecharia o ventre? Diz o seu Deus."},
{"v":10,"t":"Alegrem-se com Jerusalém e exultem por ela, todos os que a amam! Alegrem-se muito com ela, todos os que choraram por ela!"},
{"v":11,"t":"Para que mamem e se saciem no peito do consolo dela. Para que bebam com prazer da abundância da glória dela."},
{"v":12,"t":"O Senhor diz: Eu estenderei a paz sobre ela como um rio e a glória das nações como enchente. Vocês mamarão, serão carregados no braço e embalados nos joelhos."},
{"v":13,"t":"Como mãe que consola o filho, assim eu consolarei vocês. Em Jerusalém vocês serão consolados."},
{"v":14,"t":"Vocês verão e o coração se alegrará. Os ossos reverdecerão como relva. A mão do Senhor será conhecida pelos servos e a ira pelos inimigos."},
{"v":15,"t":"Porque o Senhor virá com fogo e os carros dele como tempestade, para descarregar a ira com furor e a repreensão com chamas de fogo."},
{"v":16,"t":"Com fogo e com espada o Senhor julgará toda a humanidade, e os mortos do Senhor serão muitos."},
{"v":17,"t":"Os que se consagram e se purificam para entrar nos jardins, seguindo o líder do meio, que comem carne de porco, coisas horríveis e ratos — todos acabarão juntos, diz o Senhor."},
{"v":18,"t":"Eu conheço as obras e os pensamentos deles. Está chegando o tempo de reunir todas as nações e línguas. Eles virão e verão a minha glória."},
{"v":19,"t":"Colocarei um sinal entre eles e enviarei os sobreviventes às nações — a Társis, Pul e Lude, que usam o arco, a Tubal e Javã, às ilhas distantes que nunca ouviram falar de mim nem viram a minha glória. Eles anunciarão a minha glória entre as nações."},
{"v":20,"t":"Eles trarão todos os irmãos de vocês de todas as nações como oferta ao Senhor — em cavalos, carruagens, liteiras, mulas e camelos — ao meu monte santo, Jerusalém, diz o Senhor. Assim como os filhos de Israel trazem a oferta em vaso limpo à casa do Senhor."},
{"v":21,"t":"E também de entre eles tomarei alguns para sacerdotes e levitas, diz o Senhor."},
{"v":22,"t":"Porque, assim como os novos céus e a nova terra que eu faço permanecerão diante de mim, diz o Senhor, assim permanecerá a descendência e o nome de vocês."},
{"v":23,"t":"De lua nova em lua nova e de sábado em sábado, toda a humanidade virá se curvar diante de mim, diz o Senhor."},
{"v":24,"t":"E eles sairão e verão os corpos dos que se revoltaram contra mim. O verme deles não morrerá e o fogo não se apagará. Serão algo horrível para toda a humanidade."},
]})

# Write complete file
out_path = 'v:/GitHub/orgs/devzolo/bible/static/data/bfl/isaias_trans.json'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(chapters, f, ensure_ascii=False, indent=None)

total_v = sum(len(c['verses']) for c in chapters)
print(f"Complete! {len(chapters)} chapters, {total_v} verses written to {out_path}")
