# -*- coding: utf-8 -*-
"""BFL Translation - Mateus (Matthew) - Chapters 11-20"""
import json, sys, os

chapters = []

# Chapter 11
chapters.append({"c":11,"verses":[
{"v":1,"t":"Quando Jesus terminou de dar instruções aos doze discípulos, seguiu caminho para ensinar e pregar nas cidades deles."},
{"v":2,"t":"João estava na prisão e ouviu falar das coisas que Jesus fazia. Então enviou dois discípulos"},
{"v":3,"t":"para perguntar: Você é aquele que devia vir, ou devemos esperar outro?"},
{"v":4,"t":"Jesus respondeu: Voltem e contem a João o que vocês ouvem e veem:"},
{"v":5,"t":"Os cegos enxergam, os que não andavam agora andam, os leprosos são curados, os surdos ouvem, os mortos ressuscitam, e os pobres recebem a boa notícia."},
{"v":6,"t":"Feliz é aquele que não se ofende por minha causa."},
{"v":7,"t":"Quando eles foram embora, Jesus começou a falar para a multidão sobre João: O que vocês foram ver no deserto? Uma planta balançando ao vento?"},
{"v":8,"t":"O que foram ver? Um homem vestido com roupas finas? Quem veste roupas finas mora em palácios."},
{"v":9,"t":"Então o que foram ver? Um profeta? Sim! E eu digo que ele é mais do que profeta."},
{"v":10,"t":"É dele que as Escrituras falam: Eu envio o meu mensageiro à sua frente. Ele vai preparar o caminho para você."},
{"v":11,"t":"Eu digo a verdade: entre todos os que já nasceram, ninguém foi maior que João Batista. Mas o menor no Reino dos Céus é maior do que ele."},
{"v":12,"t":"Desde os dias de João Batista até agora, o Reino dos Céus é tomado à força, e pessoas determinadas se apoderam dele."},
{"v":13,"t":"Todos os Profetas e a Lei profetizaram até João."},
{"v":14,"t":"Se vocês querem aceitar, ele é o Elias que devia vir."},
{"v":15,"t":"Quem tem ouvidos, ouça!"},
{"v":16,"t":"A que posso comparar esta geração? É como crianças sentadas na praça que gritam umas para as outras:"},
{"v":17,"t":"Nós tocamos flauta para vocês, e vocês não dançaram! Cantamos músicas tristes, e vocês não choraram!"},
{"v":18,"t":"João veio sem comer nem beber, e dizem: Ele tem demônio."},
{"v":19,"t":"O Filho do Homem veio comendo e bebendo, e dizem: Olha esse comilão e beberrão, amigo de cobradores de impostos e pecadores! Mas a sabedoria de Deus é provada pelos seus resultados."},
{"v":20,"t":"Então Jesus começou a criticar as cidades onde tinha feito a maioria dos seus milagres, porque elas não mudaram de vida:"},
{"v":21,"t":"Ai de você, Corazim! Ai de você, Betsaida! Se os milagres que foram feitos em vocês tivessem sido feitos em Tiro e Sidom, já teriam mudado de vida há muito tempo."},
{"v":22,"t":"Por isso eu digo: Tiro e Sidom serão tratadas com menos rigor no dia do julgamento do que vocês."},
{"v":23,"t":"E você, Cafarnaum, acha que será exaltada até o céu? Será rebaixada até o inferno! Se os milagres feitos em você tivessem sido feitos em Sodoma, ela existiria até hoje."},
{"v":24,"t":"Eu digo que Sodoma será tratada com menos rigor no dia do julgamento do que você."},
{"v":25,"t":"Naquela hora, Jesus disse: Eu te louvo, Pai, Senhor do céu e da terra, porque escondeste estas coisas dos sábios e inteligentes e as revelaste aos pequeninos."},
{"v":26,"t":"Sim, Pai, porque foi assim que te agradou fazer."},
{"v":27,"t":"O meu Pai me entregou todas as coisas. Ninguém conhece o Filho a não ser o Pai. E ninguém conhece o Pai a não ser o Filho e aqueles a quem o Filho quiser revelar."},
{"v":28,"t":"Venham a mim, todos vocês que estão cansados e sobrecarregados, e eu darei descanso a vocês."},
{"v":29,"t":"Aceitem o meu ensinamento e aprendam comigo. Eu sou manso e humilde de coração. E vocês encontrarão descanso para a alma."},
{"v":30,"t":"Porque o meu ensinamento é fácil e a minha carga é leve."},
]})

# Chapter 12
chapters.append({"c":12,"verses":[
{"v":1,"t":"Naquele tempo, num sábado, Jesus passou pelas plantações. Os discípulos estavam com fome e começaram a colher espigas e comer."},
{"v":2,"t":"Os fariseus viram e disseram: Olha! Os seus discípulos estão fazendo o que não é permitido no sábado."},
{"v":3,"t":"Jesus respondeu: Vocês não leram o que Davi fez quando ele e seus companheiros estavam com fome?"},
{"v":4,"t":"Ele entrou na casa de Deus e comeu os pães oferecidos a Deus, que só os sacerdotes podiam comer."},
{"v":5,"t":"Vocês não leram na Lei que, nos sábados, os sacerdotes trabalham no templo sem serem culpados?"},
{"v":6,"t":"Eu digo que aqui está alguém maior do que o templo."},
{"v":7,"t":"Se vocês entendessem o que significa 'Eu quero compaixão, não sacrifício', não condenariam os inocentes."},
{"v":8,"t":"Porque o Filho do Homem é Senhor do sábado."},
{"v":9,"t":"Saindo dali, Jesus foi à sinagoga."},
{"v":10,"t":"Havia lá um homem com a mão seca. Para acusar Jesus, perguntaram: É permitido curar no sábado?"},
{"v":11,"t":"Ele respondeu: Se um de vocês tiver uma ovelha e ela cair num buraco no sábado, não vai pegar e tirar ela de lá?"},
{"v":12,"t":"Uma pessoa vale muito mais que uma ovelha! Portanto, é permitido fazer o bem no sábado."},
{"v":13,"t":"Então disse ao homem: Estenda a mão. Ele estendeu, e a mão ficou boa como a outra."},
{"v":14,"t":"Os fariseus saíram e começaram a planejar como matar Jesus."},
{"v":15,"t":"Jesus soube disso e saiu dali. Grandes multidões o seguiram, e ele curou todos."},
{"v":16,"t":"Mas pedia que não contassem quem ele era."},
{"v":17,"t":"Assim se cumpriu o que o profeta Isaías disse:"},
{"v":18,"t":"Este é o meu servo, que eu escolhi. O meu amado, em quem tenho alegria. Colocarei o meu Espírito sobre ele, e ele anunciará justiça a todos os povos."},
{"v":19,"t":"Ele não vai brigar nem gritar. Ninguém vai ouvir a voz dele nas ruas."},
{"v":20,"t":"Não vai quebrar a planta machucada nem apagar a chama fraca, até que faça a justiça vencer."},
{"v":21,"t":"E nele todos os povos colocarão a esperança."},
{"v":22,"t":"Trouxeram a Jesus um homem cego e mudo, dominado por um demônio. Jesus o curou, e o homem passou a falar e a ver."},
{"v":23,"t":"A multidão ficou espantada e dizia: Será que este é o Filho de Davi?"},
{"v":24,"t":"Mas os fariseus ouviram e disseram: É pelo poder de Belzebu, o chefe dos demônios, que ele expulsa os demônios."},
{"v":25,"t":"Jesus, sabendo o que pensavam, disse: Todo reino dividido contra si mesmo será destruído. Toda cidade ou casa dividida contra si mesma não vai sobreviver."},
{"v":26,"t":"Se Satanás expulsa Satanás, está dividido contra si mesmo. Como o reino dele vai continuar?"},
{"v":27,"t":"Se eu expulso demônios pelo poder de Belzebu, pelo poder de quem os seguidores de vocês os expulsam? Por isso, eles mesmos serão os juízes de vocês."},
{"v":28,"t":"Mas se eu expulso demônios pelo Espírito de Deus, então o Reino de Deus já chegou a vocês."},
{"v":29,"t":"Como alguém pode entrar na casa de um homem forte e roubar as coisas dele? Só se amarrar o homem forte primeiro. Aí sim pode roubar a casa."},
{"v":30,"t":"Quem não está comigo está contra mim. E quem não junta comigo, espalha."},
{"v":31,"t":"Por isso eu digo: todo pecado e toda ofensa a Deus serão perdoados. Mas a ofensa contra o Espírito Santo não será perdoada."},
{"v":32,"t":"Quem falar contra o Filho do Homem será perdoado. Mas quem falar contra o Espírito Santo não será perdoado, nem nesta vida nem na que vem."},
{"v":33,"t":"Se a árvore é boa, o fruto é bom. Se a árvore é ruim, o fruto é ruim. Porque a árvore é conhecida pelo fruto."},
{"v":34,"t":"Raça de cobras! Como vocês podem dizer coisas boas sendo maus? Porque a boca fala do que o coração está cheio."},
{"v":35,"t":"A pessoa boa tira coisas boas do tesouro bom do coração. A pessoa má tira coisas ruins do tesouro mau."},
{"v":36,"t":"Eu digo que, no dia do julgamento, as pessoas vão prestar contas de toda palavra inútil que disserem."},
{"v":37,"t":"Porque pelas suas palavras você será absolvido, e pelas suas palavras será condenado."},
{"v":38,"t":"Então alguns mestres da Lei e fariseus disseram: Mestre, queremos ver um sinal da sua parte."},
{"v":39,"t":"Jesus respondeu: Esta geração má e infiel pede um sinal. Mas o único sinal que receberá é o sinal do profeta Jonas."},
{"v":40,"t":"Porque assim como Jonas ficou três dias e três noites dentro do grande peixe, o Filho do Homem ficará três dias e três noites no interior da terra."},
{"v":41,"t":"No dia do julgamento, o povo de Nínive se levantará contra esta geração e a condenará. Porque eles mudaram de vida com a pregação de Jonas. E aqui está alguém maior que Jonas."},
{"v":42,"t":"No dia do julgamento, a rainha do Sul se levantará contra esta geração e a condenará. Porque ela veio de muito longe para ouvir a sabedoria de Salomão. E aqui está alguém maior que Salomão."},
{"v":43,"t":"Quando um espírito mau sai de uma pessoa, ele vaga por lugares secos procurando descanso, mas não encontra."},
{"v":44,"t":"Então diz: Vou voltar para a minha casa de onde saí. Quando chega, encontra a casa vazia, limpa e arrumada."},
{"v":45,"t":"Então vai e traz outros sete espíritos piores do que ele. Eles entram e moram ali. No final, a situação da pessoa fica pior do que antes. É assim que vai acontecer com esta geração má."},
{"v":46,"t":"Enquanto Jesus ainda falava à multidão, a mãe e os irmãos dele chegaram e queriam falar com ele."},
{"v":47,"t":"Alguém avisou: A sua mãe e os seus irmãos estão lá fora querendo falar com o senhor."},
{"v":48,"t":"Jesus respondeu: Quem é a minha mãe? Quem são os meus irmãos?"},
{"v":49,"t":"E, apontando para os discípulos, disse: Aqui estão a minha mãe e os meus irmãos."},
{"v":50,"t":"Porque todo aquele que faz a vontade do meu Pai que está no céu é meu irmão, minha irmã e minha mãe."},
]})

# Chapter 13 - Parables
chapters.append({"c":13,"verses":[
{"v":1,"t":"Naquele dia, Jesus saiu de casa e sentou-se à beira do mar."},
{"v":2,"t":"Uma multidão tão grande se juntou que ele entrou num barco e se sentou. Todo o povo ficou na praia."},
{"v":3,"t":"Ele ensinou muitas coisas usando histórias: Um agricultor saiu para plantar."},
{"v":4,"t":"Enquanto plantava, algumas sementes caíram à beira do caminho. Os pássaros vieram e comeram."},
{"v":5,"t":"Outras caíram em terreno pedregoso, onde havia pouca terra. Brotaram rápido porque a terra era rasa."},
{"v":6,"t":"Mas quando o sol apareceu, queimaram e secaram, porque não tinham raiz."},
{"v":7,"t":"Outras caíram entre espinhos. Os espinhos cresceram e sufocaram as plantas."},
{"v":8,"t":"Outras caíram em terra boa e deram fruto: umas cem vezes mais, outras sessenta, outras trinta."},
{"v":9,"t":"Quem tem ouvidos, ouça!"},
{"v":10,"t":"Os discípulos se aproximaram e perguntaram: Por que o senhor fala usando histórias?"},
{"v":11,"t":"Jesus respondeu: A vocês foi dado conhecer os segredos do Reino dos Céus, mas a eles não."},
{"v":12,"t":"Quem tem receberá mais, e terá em abundância. Mas quem não tem, até o pouco que tem será tirado."},
{"v":13,"t":"Por isso falo por meio de histórias. Porque eles olham e não veem. Ouvem e não entendem."},
{"v":14,"t":"Neles se cumpre a profecia de Isaías: Vocês vão ouvir, mas não vão entender. Vão olhar, mas não vão enxergar."},
{"v":15,"t":"Porque o coração deste povo ficou duro. Eles taparam os ouvidos e fecharam os olhos. Não querem ver com os olhos, ouvir com os ouvidos, entender com o coração e se voltar para mim, para que eu os cure."},
{"v":16,"t":"Mas felizes são os olhos de vocês, porque veem. E os ouvidos de vocês, porque ouvem."},
{"v":17,"t":"Eu digo a verdade: muitos profetas e pessoas justas quiseram ver o que vocês veem e não viram. Quiseram ouvir o que vocês ouvem e não ouviram."},
{"v":18,"t":"Ouçam o que significa a história do agricultor:"},
{"v":19,"t":"Quando alguém ouve a mensagem do Reino e não entende, o mal vem e rouba o que foi plantado no coração. Essa é a semente que caiu à beira do caminho."},
{"v":20,"t":"A semente que caiu no terreno pedregoso é a pessoa que ouve a palavra e logo a recebe com alegria."},
{"v":21,"t":"Mas não tem raiz profunda e dura pouco tempo. Quando vem sofrimento ou perseguição por causa da palavra, desiste logo."},
{"v":22,"t":"A semente que caiu entre espinhos é a pessoa que ouve a palavra. Mas as preocupações da vida e a ilusão da riqueza sufocam a palavra, e ela não dá fruto."},
{"v":23,"t":"Mas a semente que caiu em terra boa é a pessoa que ouve a palavra e a entende. Essa pessoa dá fruto: umas cem vezes mais, outras sessenta, outras trinta."},
{"v":24,"t":"Jesus contou outra história: O Reino dos Céus é como um homem que plantou boa semente no campo."},
{"v":25,"t":"Enquanto todos dormiam, o inimigo dele veio e plantou erva daninha no meio do trigo, e foi embora."},
{"v":26,"t":"Quando o trigo cresceu e deu fruto, a erva daninha também apareceu."},
{"v":27,"t":"Os empregados do dono foram falar com ele: Senhor, o senhor não plantou boa semente? De onde veio a erva daninha?"},
{"v":28,"t":"Ele respondeu: Foi um inimigo que fez isso. Os empregados perguntaram: O senhor quer que a gente arranque a erva daninha?"},
{"v":29,"t":"Ele disse: Não! Porque ao arrancarem a erva daninha, vocês podem arrancar o trigo junto."},
{"v":30,"t":"Deixem os dois crescerem juntos até a colheita. Na hora da colheita, eu direi aos trabalhadores: Juntem primeiro a erva daninha e amarrem em feixes para queimar. Depois juntem o trigo e guardem no meu depósito."},
{"v":31,"t":"Jesus contou outra história: O Reino dos Céus é como uma semente de mostarda que um homem plantou no campo."},
{"v":32,"t":"Ela é a menor de todas as sementes. Mas quando cresce, se torna a maior das plantas. Vira uma árvore tão grande que os pássaros fazem ninhos nos galhos dela."},
{"v":33,"t":"Contou mais uma: O Reino dos Céus é como o fermento que uma mulher misturou em uma grande porção de farinha, até que tudo ficou fermentado."},
{"v":34,"t":"Jesus disse tudo isso ao povo usando histórias. Não falava nada sem usar histórias."},
{"v":35,"t":"Assim se cumpriu o que o profeta disse: Vou falar usando histórias. Vou revelar coisas escondidas desde a criação do mundo."},
{"v":36,"t":"Então Jesus deixou a multidão e entrou em casa. Os discípulos se aproximaram e disseram: Explique para nós a história da erva daninha no campo."},
{"v":37,"t":"Ele respondeu: Quem planta a boa semente é o Filho do Homem."},
{"v":38,"t":"O campo é o mundo. A boa semente são as pessoas que pertencem ao Reino. A erva daninha são as pessoas que pertencem ao mal."},
{"v":39,"t":"O inimigo que plantou a erva daninha é o diabo. A colheita é o fim dos tempos. Os trabalhadores são os anjos."},
{"v":40,"t":"Assim como a erva daninha é juntada e queimada, assim será no fim dos tempos."},
{"v":41,"t":"O Filho do Homem enviará os anjos dele. Eles vão tirar do Reino tudo que faz as pessoas pecarem e todos que praticam o mal."},
{"v":42,"t":"Eles serão jogados no fogo. Ali haverá choro e ranger de dentes."},
{"v":43,"t":"Então os justos brilharão como o sol no Reino do Pai deles. Quem tem ouvidos, ouça!"},
{"v":44,"t":"O Reino dos Céus é como um tesouro escondido num campo. Um homem o encontrou e escondeu de novo. Tão feliz que ficou, foi, vendeu tudo o que tinha e comprou aquele campo."},
{"v":45,"t":"O Reino dos Céus também é como um comerciante que procurava pérolas de qualidade."},
{"v":46,"t":"Quando encontrou uma pérola de grande valor, foi, vendeu tudo o que tinha e a comprou."},
{"v":47,"t":"O Reino dos Céus também é como uma rede jogada no mar, que pega todo tipo de peixe."},
{"v":48,"t":"Quando a rede está cheia, os pescadores a puxam para a praia. Sentam-se e separam os peixes bons nos cestos. Os ruins jogam fora."},
{"v":49,"t":"Assim será no fim dos tempos. Os anjos virão e separarão os maus dos justos."},
{"v":50,"t":"E os jogarão no fogo. Ali haverá choro e ranger de dentes."},
{"v":51,"t":"Jesus perguntou: Vocês entenderam tudo isso? Responderam: Sim, Senhor."},
{"v":52,"t":"Então ele disse: Todo mestre da Lei que aprende sobre o Reino dos Céus é como o dono de uma casa. Ele tira do seu tesouro coisas novas e antigas."},
{"v":53,"t":"Quando Jesus terminou essas histórias, saiu dali."},
{"v":54,"t":"Voltou para a cidade onde tinha crescido e ensinava na sinagoga. As pessoas ficavam admiradas e diziam: De onde vem essa sabedoria e esse poder?"},
{"v":55,"t":"Ele não é o filho do carpinteiro? A mãe dele não se chama Maria? E os irmãos dele não são Tiago, José, Simão e Judas?"},
{"v":56,"t":"As irmãs dele não moram aqui entre nós? De onde vem tudo isso?"},
{"v":57,"t":"E se ofendiam com ele. Mas Jesus disse: Um profeta é respeitado em todo lugar, menos na sua própria cidade e na sua casa."},
{"v":58,"t":"E não fez muitos milagres ali, por causa da falta de fé deles."},
]})

# Chapter 14
chapters.append({"c":14,"verses":[
{"v":1,"t":"Naquela época, o governador Herodes ouviu falar de Jesus"},
{"v":2,"t":"e disse aos seus auxiliares: Esse é João Batista! Ele voltou dos mortos, e por isso tem poder para fazer milagres."},
{"v":3,"t":"Herodes tinha prendido João e o acorrentado na prisão. Fez isso por causa de Herodias, a mulher do seu irmão Filipe."},
{"v":4,"t":"Porque João dizia a Herodes: Não é certo você viver com a mulher do seu irmão."},
{"v":5,"t":"Herodes queria matar João, mas tinha medo do povo, porque todos consideravam João um profeta."},
{"v":6,"t":"No aniversário de Herodes, a filha de Herodias dançou para os convidados e agradou muito a Herodes."},
{"v":7,"t":"Ele prometeu com juramento dar a ela o que quisesse."},
{"v":8,"t":"Instruída pela mãe, ela disse: Quero que me dê aqui, num prato, a cabeça de João Batista."},
{"v":9,"t":"O rei ficou triste, mas por causa do juramento e dos convidados, mandou fazer."},
{"v":10,"t":"Mandou cortar a cabeça de João na prisão."},
{"v":11,"t":"A cabeça foi trazida num prato e entregue à moça, que a levou para a mãe."},
{"v":12,"t":"Os discípulos de João vieram, levaram o corpo e o sepultaram. Depois foram contar a Jesus."},
{"v":13,"t":"Quando Jesus ouviu isso, foi de barco para um lugar deserto e afastado. Mas o povo soube e o seguiu a pé, saindo das cidades."},
{"v":14,"t":"Quando Jesus saiu do barco e viu a grande multidão, teve compaixão e curou os doentes."},
{"v":15,"t":"No fim da tarde, os discípulos se aproximaram e disseram: Este lugar é deserto e já está ficando tarde. Mande o povo embora para que comprem comida nas vilas."},
{"v":16,"t":"Jesus respondeu: Eles não precisam ir embora. Deem vocês mesmos de comer a eles."},
{"v":17,"t":"Os discípulos disseram: Nós só temos cinco pães e dois peixes."},
{"v":18,"t":"Jesus disse: Tragam aqui para mim."},
{"v":19,"t":"Mandou a multidão se sentar na grama. Pegou os cinco pães e os dois peixes, olhou para o céu, deu graças a Deus, partiu os pães e deu aos discípulos. Eles distribuíram ao povo."},
{"v":20,"t":"Todos comeram e ficaram satisfeitos. E ainda sobraram doze cestos cheios de pedaços."},
{"v":21,"t":"Havia por volta de cinco mil homens que comeram, sem contar mulheres e crianças."},
{"v":22,"t":"Logo depois, Jesus mandou os discípulos entrarem no barco e irem na frente para o outro lado. Enquanto isso, ele despediu a multidão."},
{"v":23,"t":"Depois de despedir o povo, subiu ao monte para orar a sós. Quando a noite chegou, ele estava ali sozinho."},
{"v":24,"t":"O barco já estava longe da terra, sendo sacudido pelas ondas, porque o vento era contrário."},
{"v":25,"t":"De madrugada, Jesus foi até eles, andando sobre o mar."},
{"v":26,"t":"Quando os discípulos o viram andando sobre o mar, ficaram apavorados. Disseram: É um fantasma! E gritaram de medo."},
{"v":27,"t":"Mas Jesus logo falou: Coragem! Sou eu. Não tenham medo."},
{"v":28,"t":"Pedro disse: Senhor, se é o senhor, mande eu ir até aí andando sobre a água."},
{"v":29,"t":"Jesus disse: Venha! Pedro saiu do barco e começou a andar sobre a água em direção a Jesus."},
{"v":30,"t":"Mas quando viu a força do vento, ficou com medo. Começou a afundar e gritou: Senhor, me salve!"},
{"v":31,"t":"Na mesma hora, Jesus estendeu a mão e o segurou. Disse: Você tem pouca fé! Por que duvidou?"},
{"v":32,"t":"Quando os dois subiram no barco, o vento parou."},
{"v":33,"t":"Os que estavam no barco o adoraram e disseram: O senhor é mesmo o Filho de Deus!"},
{"v":34,"t":"Atravessaram o lago e chegaram a Genesaré."},
{"v":35,"t":"O povo dali reconheceu Jesus e espalhou a notícia por toda a região. Trouxeram a ele todos os doentes."},
{"v":36,"t":"E pediam que pudessem ao menos tocar na barra da roupa dele. Todos os que tocaram ficaram curados."},
]})

# Chapter 15
chapters.append({"c":15,"verses":[
{"v":1,"t":"Então alguns fariseus e mestres da Lei de Jerusalém vieram a Jesus e disseram:"},
{"v":2,"t":"Por que os seus discípulos desobedecem a tradição dos antigos? Eles não lavam as mãos antes de comer."},
{"v":3,"t":"Jesus respondeu: E por que vocês desobedecem o mandamento de Deus por causa da tradição de vocês?"},
{"v":4,"t":"Deus mandou: Honre seu pai e sua mãe. E: Quem amaldiçoar o pai ou a mãe deve morrer."},
{"v":5,"t":"Mas vocês dizem que se alguém disser ao pai ou à mãe: O que eu poderia usar para ajudá-lo é oferta a Deus,"},
{"v":6,"t":"essa pessoa não precisa honrar o pai ou a mãe. Assim vocês anularam a palavra de Deus por causa da tradição de vocês."},
{"v":7,"t":"Hipócritas! Isaías profetizou bem sobre vocês:"},
{"v":8,"t":"Este povo me honra com os lábios, mas o coração está longe de mim."},
{"v":9,"t":"É inútil me adorarem, ensinando regras feitas por seres humanos."},
{"v":10,"t":"Jesus chamou a multidão e disse: Ouçam e entendam:"},
{"v":11,"t":"Não é o que entra pela boca que torna a pessoa impura. É o que sai da boca que a torna impura."},
{"v":12,"t":"Depois, os discípulos disseram: O senhor sabe que os fariseus ficaram ofendidos com o que disse?"},
{"v":13,"t":"Jesus respondeu: Toda planta que o meu Pai celestial não plantou será arrancada."},
{"v":14,"t":"Deixem eles. São guias cegos. Se um cego guiar outro cego, os dois vão cair no buraco."},
{"v":15,"t":"Pedro disse: Explique essa história para nós."},
{"v":16,"t":"Jesus respondeu: Vocês também não entendem ainda?"},
{"v":17,"t":"Não percebem que tudo que entra pela boca vai para o estômago e depois é eliminado?"},
{"v":18,"t":"Mas o que sai da boca vem do coração, e isso é que torna a pessoa impura."},
{"v":19,"t":"Porque do coração saem os pensamentos maus: assassinatos, adultérios, imoralidade, roubos, mentiras e insultos."},
{"v":20,"t":"São essas coisas que tornam a pessoa impura. Comer sem lavar as mãos não torna ninguém impuro."},
{"v":21,"t":"Saindo dali, Jesus foi para a região de Tiro e Sidom."},
{"v":22,"t":"Uma mulher cananeia daquela região veio gritando: Senhor, Filho de Davi, tenha compaixão de mim! A minha filha está muito atormentada por um demônio."},
{"v":23,"t":"Mas Jesus não respondeu nada. Os discípulos pediram: Mande ela embora, porque não para de gritar atrás de nós."},
{"v":24,"t":"Jesus disse: Eu fui enviado somente para as ovelhas perdidas do povo de Israel."},
{"v":25,"t":"A mulher se aproximou, se ajoelhou e disse: Senhor, me ajude!"},
{"v":26,"t":"Jesus respondeu: Não é certo tirar o pão dos filhos e jogar para os cachorrinhos."},
{"v":27,"t":"Ela disse: É verdade, Senhor. Mas até os cachorrinhos comem as migalhas que caem da mesa dos donos."},
{"v":28,"t":"Então Jesus disse: Mulher, a sua fé é grande! Que aconteça como você quer. E naquela mesma hora a filha dela ficou curada."},
{"v":29,"t":"Jesus saiu dali e foi para a beira do mar da Galileia. Subiu a um monte e se sentou."},
{"v":30,"t":"Grandes multidões vieram com pessoas que não andavam, cegas, mudas, aleijadas e muitas outras. Colocaram aos pés de Jesus, e ele as curou."},
{"v":31,"t":"A multidão ficou admirada ao ver mudos falando, aleijados curados, os que não andavam agora andando e cegos enxergando. E louvaram o Deus de Israel."},
{"v":32,"t":"Jesus chamou os discípulos e disse: Tenho compaixão desta multidão. Já faz três dias que estão comigo e não têm o que comer. Não quero mandá-los embora com fome, para que não desmaiem no caminho."},
{"v":33,"t":"Os discípulos disseram: De onde vamos conseguir pão suficiente neste lugar deserto para alimentar tanta gente?"},
{"v":34,"t":"Jesus perguntou: Quantos pães vocês têm? Responderam: Sete, e alguns peixinhos."},
{"v":35,"t":"Jesus mandou a multidão se sentar no chão."},
{"v":36,"t":"Pegou os sete pães e os peixes, deu graças a Deus, partiu e deu aos discípulos. Os discípulos distribuíram ao povo."},
{"v":37,"t":"Todos comeram e ficaram satisfeitos. E ainda sobraram sete cestos cheios de pedaços."},
{"v":38,"t":"Os que comeram foram quatro mil homens, sem contar mulheres e crianças."},
{"v":39,"t":"Depois de despedir a multidão, Jesus entrou no barco e foi para a região de Magadã."},
]})

# Chapter 16
chapters.append({"c":16,"verses":[
{"v":1,"t":"Os fariseus e saduceus vieram a Jesus e pediram que mostrasse um sinal do céu para testá-lo."},
{"v":2,"t":"Ele respondeu: Quando a tarde chega, vocês dizem: Vai fazer bom tempo, porque o céu está vermelho."},
{"v":3,"t":"De manhã dizem: Hoje vai chover, porque o céu está vermelho escuro. Vocês sabem ler o céu, mas não sabem entender os sinais dos tempos?"},
{"v":4,"t":"Uma geração má e infiel pede um sinal. O único sinal que vai receber é o de Jonas. E se afastou deles."},
{"v":5,"t":"Os discípulos foram para o outro lado do lago e esqueceram de levar pão."},
{"v":6,"t":"Jesus disse: Cuidado com o fermento dos fariseus e saduceus."},
{"v":7,"t":"Eles começaram a discutir entre si: É porque não trouxemos pão."},
{"v":8,"t":"Jesus percebeu e disse: Gente de pouca fé! Por que estão discutindo por não terem trazido pão?"},
{"v":9,"t":"Ainda não entenderam? Não lembram dos cinco pães para cinco mil pessoas e quantos cestos sobraram?"},
{"v":10,"t":"Nem dos sete pães para quatro mil e quantos cestos sobraram?"},
{"v":11,"t":"Como não entendem que eu não estava falando de pão? Cuidado com o fermento dos fariseus e saduceus!"},
{"v":12,"t":"Então entenderam que ele não falava do fermento do pão, mas do ensino dos fariseus e saduceus."},
{"v":13,"t":"Quando Jesus chegou à região de Cesareia de Filipe, perguntou aos discípulos: Quem o povo diz que o Filho do Homem é?"},
{"v":14,"t":"Responderam: Uns dizem que é João Batista. Outros dizem Elias. Outros dizem Jeremias ou um dos profetas."},
{"v":15,"t":"Ele perguntou: E vocês, quem dizem que eu sou?"},
{"v":16,"t":"Simão Pedro respondeu: O senhor é o Cristo, o Filho do Deus vivo."},
{"v":17,"t":"Jesus disse: Feliz é você, Simão, filho de Jonas! Porque não foi uma pessoa que revelou isso a você, mas o meu Pai que está no céu."},
{"v":18,"t":"Eu digo que você é Pedro, que quer dizer rocha. E sobre esta rocha eu vou construir a minha igreja. Nem as forças do inferno vão vencê-la."},
{"v":19,"t":"Eu darei a você as chaves do Reino dos Céus. O que você proibir na terra será proibido no céu. O que você permitir na terra será permitido no céu."},
{"v":20,"t":"Então Jesus ordenou aos discípulos que não contassem a ninguém que ele era o Cristo."},
{"v":21,"t":"A partir daí, Jesus começou a explicar aos discípulos que precisava ir a Jerusalém. Lá iria sofrer muito nas mãos dos líderes religiosos, dos chefes dos sacerdotes e dos mestres da Lei. Seria morto, mas no terceiro dia ressuscitaria."},
{"v":22,"t":"Pedro o levou de lado e começou a repreendê-lo: Deus não permita isso, Senhor! Isso nunca vai acontecer com o senhor!"},
{"v":23,"t":"Mas Jesus se virou e disse a Pedro: Saia da minha frente, Satanás! Você é uma armadilha para mim. Você não pensa nas coisas de Deus, mas nas coisas humanas."},
{"v":24,"t":"Então Jesus disse aos discípulos: Se alguém quer me seguir, negue a si mesmo, pegue a sua cruz e me siga."},
{"v":25,"t":"Porque quem quiser salvar a própria vida vai perdê-la. Mas quem perder a vida por minha causa vai encontrá-la."},
{"v":26,"t":"De que adianta uma pessoa ganhar o mundo inteiro e perder a própria alma? O que alguém pode dar em troca da sua alma?"},
{"v":27,"t":"Porque o Filho do Homem virá na glória do Pai com os anjos. Então dará a cada um de acordo com o que fez."},
{"v":28,"t":"Eu digo a verdade: alguns dos que estão aqui não morrerão antes de verem o Filho do Homem vindo no seu Reino."},
]})

# Chapter 17
chapters.append({"c":17,"verses":[
{"v":1,"t":"Seis dias depois, Jesus levou Pedro, Tiago e João, irmão de Tiago, a um monte alto, só eles."},
{"v":2,"t":"Ali Jesus se transformou diante deles. O rosto brilhou como o sol e as roupas ficaram brancas como luz."},
{"v":3,"t":"De repente apareceram Moisés e Elias, conversando com Jesus."},
{"v":4,"t":"Pedro disse: Senhor, é bom estarmos aqui! Se o senhor quiser, vou fazer três barracas: uma para o senhor, uma para Moisés e uma para Elias."},
{"v":5,"t":"Ele ainda falava quando uma nuvem brilhante os cobriu. Da nuvem veio uma voz que disse: Este é o meu Filho amado, em quem tenho grande alegria. Ouçam o que ele diz!"},
{"v":6,"t":"Quando os discípulos ouviram isso, caíram com o rosto no chão, com muito medo."},
{"v":7,"t":"Jesus se aproximou, tocou neles e disse: Levantem-se. Não tenham medo."},
{"v":8,"t":"Quando olharam, só viram Jesus."},
{"v":9,"t":"Enquanto desciam do monte, Jesus ordenou: Não contem a ninguém o que viram, até que o Filho do Homem ressuscite dos mortos."},
{"v":10,"t":"Os discípulos perguntaram: Por que os mestres da Lei dizem que Elias precisa vir primeiro?"},
{"v":11,"t":"Jesus respondeu: De fato, Elias vem primeiro e vai restaurar todas as coisas."},
{"v":12,"t":"Mas eu digo que Elias já veio. Eles não o reconheceram e fizeram com ele o que quiseram. Da mesma forma, o Filho do Homem vai sofrer nas mãos deles."},
{"v":13,"t":"Então os discípulos entenderam que ele falava de João Batista."},
{"v":14,"t":"Quando chegaram onde estava a multidão, um homem se ajoelhou diante de Jesus"},
{"v":15,"t":"e disse: Senhor, tenha compaixão do meu filho! Ele sofre de ataques e passa muito mal. Muitas vezes cai no fogo ou na água."},
{"v":16,"t":"Eu o trouxe aos seus discípulos, mas eles não conseguiram curá-lo."},
{"v":17,"t":"Jesus disse: Geração sem fé e teimosa! Até quando vou ficar com vocês? Até quando vou aguentar vocês? Tragam o menino aqui."},
{"v":18,"t":"Jesus repreendeu o demônio, que saiu do menino. E naquela mesma hora o menino ficou curado."},
{"v":19,"t":"Depois, os discípulos perguntaram a Jesus em particular: Por que nós não conseguimos expulsá-lo?"},
{"v":20,"t":"Jesus respondeu: Porque a fé de vocês é pequena. Eu digo a verdade: se vocês tiverem fé do tamanho de uma semente de mostarda, dirão a este monte: Saia daqui, e ele vai sair. Nada será impossível para vocês."},
{"v":21,"t":"Mas este tipo de demônio só sai com oração e jejum."},
{"v":22,"t":"Enquanto andavam pela Galileia, Jesus disse: O Filho do Homem vai ser entregue nas mãos de homens."},
{"v":23,"t":"Eles vão matá-lo, mas no terceiro dia ele vai ressuscitar. Os discípulos ficaram muito tristes."},
{"v":24,"t":"Quando chegaram a Cafarnaum, os cobradores do imposto do templo perguntaram a Pedro: O mestre de vocês não paga o imposto do templo?"},
{"v":25,"t":"Pedro respondeu: Paga sim. Quando entrou em casa, Jesus se antecipou e perguntou: Simão, o que você acha? De quem os reis cobram impostos? Dos filhos ou dos outros?"},
{"v":26,"t":"Pedro respondeu: Dos outros. Jesus disse: Então os filhos estão livres."},
{"v":27,"t":"Mas para não ofender ninguém, vá ao mar, jogue o anzol e pegue o primeiro peixe que morder. Abra a boca dele e vai encontrar uma moeda. Pegue-a e pague o imposto por mim e por você."},
]})

# Chapter 18
chapters.append({"c":18,"verses":[
{"v":1,"t":"Naquela hora, os discípulos perguntaram a Jesus: Quem é o maior no Reino dos Céus?"},
{"v":2,"t":"Jesus chamou uma criança, colocou no meio deles"},
{"v":3,"t":"e disse: Eu digo a verdade: se vocês não mudarem e não se tornarem como crianças, não entrarão no Reino dos Céus."},
{"v":4,"t":"Quem se tornar humilde como esta criança, esse é o maior no Reino dos Céus."},
{"v":5,"t":"Quem receber uma criança como esta em meu nome, está me recebendo."},
{"v":6,"t":"Mas quem fizer um destes pequeninos que creem em mim pecar, seria melhor que amarrassem uma pedra grande no pescoço dele e o jogassem no fundo do mar."},
{"v":7,"t":"Ai do mundo por causa das armadilhas! As armadilhas vão aparecer, mas ai de quem as coloca!"},
{"v":8,"t":"Se a sua mão ou o seu pé faz você pecar, corte e jogue fora. É melhor entrar na vida sem mão ou sem pé do que ter as duas mãos e os dois pés e ser jogado no fogo eterno."},
{"v":9,"t":"Se o seu olho faz você pecar, arranque e jogue fora. É melhor entrar na vida com um olho só do que ter dois olhos e ser jogado no fogo do inferno."},
{"v":10,"t":"Cuidado para não desprezar nenhum destes pequeninos. Eu digo que os anjos deles no céu sempre veem a face do meu Pai que está no céu."},
{"v":11,"t":"Porque o Filho do Homem veio salvar quem estava perdido."},
{"v":12,"t":"O que vocês acham? Se um homem tem cem ovelhas e uma se perde, ele não vai deixar as noventa e nove no monte e sair procurando a que se perdeu?"},
{"v":13,"t":"E se encontrar, eu digo a verdade: ele fica mais feliz com aquela ovelha do que com as noventa e nove que não se perderam."},
{"v":14,"t":"Da mesma forma, o Pai de vocês que está no céu não quer que nenhum destes pequeninos se perca."},
{"v":15,"t":"Se o seu irmão pecar contra você, vá e converse com ele a sós. Se ele ouvir, você ganhou o seu irmão de volta."},
{"v":16,"t":"Se não ouvir, leve mais uma ou duas pessoas, para que tudo seja confirmado por duas ou três testemunhas."},
{"v":17,"t":"Se não ouvir nem eles, conte à igreja. Se não ouvir nem a igreja, trate como se fosse um estranho."},
{"v":18,"t":"Eu digo a verdade: tudo que vocês proibirem na terra será proibido no céu. Tudo que vocês permitirem na terra será permitido no céu."},
{"v":19,"t":"Também digo: se dois de vocês concordarem na terra sobre qualquer coisa que pedirem, o meu Pai que está no céu fará por vocês."},
{"v":20,"t":"Porque onde dois ou três estão reunidos em meu nome, eu estou ali no meio deles."},
{"v":21,"t":"Pedro se aproximou e perguntou: Senhor, quantas vezes devo perdoar o meu irmão que pecar contra mim? Até sete?"},
{"v":22,"t":"Jesus respondeu: Não sete, mas setenta vezes sete!"},
{"v":23,"t":"Por isso, o Reino dos Céus pode ser comparado a um rei que quis acertar as contas com os seus empregados."},
{"v":24,"t":"Quando começou, trouxeram um que devia uma quantia enorme."},
{"v":25,"t":"Como não tinha como pagar, o senhor mandou que ele, a esposa, os filhos e tudo que possuía fossem vendidos para pagar a dívida."},
{"v":26,"t":"O empregado se ajoelhou e implorou: Tenha paciência comigo, e eu vou pagar tudo!"},
{"v":27,"t":"O senhor ficou com muita compaixão, soltou o empregado e perdoou toda a dívida."},
{"v":28,"t":"Mas quando esse empregado saiu, encontrou um companheiro que lhe devia uma quantia pequena. Agarrou-o pelo pescoço e disse: Me pague o que me deve!"},
{"v":29,"t":"O companheiro se ajoelhou e implorou: Tenha paciência comigo, e eu vou pagar tudo!"},
{"v":30,"t":"Mas ele não quis. Foi e o colocou na prisão até pagar a dívida."},
{"v":31,"t":"Quando os outros empregados viram o que aconteceu, ficaram muito tristes e foram contar tudo ao senhor."},
{"v":32,"t":"Então o senhor chamou o empregado e disse: Empregado mau! Eu perdoei toda a sua dívida porque você me pediu."},
{"v":33,"t":"Você não devia ter compaixão do seu companheiro, assim como eu tive de você?"},
{"v":34,"t":"O senhor ficou furioso e o entregou para ser castigado até pagar toda a dívida."},
{"v":35,"t":"Assim o meu Pai celestial fará com vocês, se cada um não perdoar o irmão de coração."},
]})

# Chapter 19
chapters.append({"c":19,"verses":[
{"v":1,"t":"Quando Jesus terminou de falar essas coisas, saiu da Galileia e foi para a região da Judeia, além do Jordão."},
{"v":2,"t":"Grandes multidões o seguiram, e ele curou os doentes."},
{"v":3,"t":"Alguns fariseus vieram testá-lo e perguntaram: É permitido um homem se divorciar da esposa por qualquer motivo?"},
{"v":4,"t":"Jesus respondeu: Vocês não leram que o Criador, desde o início, os fez homem e mulher?"},
{"v":5,"t":"E disse: Por isso o homem deixará o pai e a mãe e se unirá à esposa, e os dois serão um só."},
{"v":6,"t":"Eles não são mais dois, mas um só. Portanto, o que Deus uniu, o ser humano não deve separar."},
{"v":7,"t":"Perguntaram: Então por que Moisés mandou dar um documento de divórcio?"},
{"v":8,"t":"Jesus disse: Moisés permitiu o divórcio por causa da teimosia do coração de vocês. Mas no início não era assim."},
{"v":9,"t":"Eu digo: quem se divorciar da esposa, a não ser por infidelidade, e se casar com outra, comete adultério."},
{"v":10,"t":"Os discípulos disseram: Se é assim entre homem e mulher, é melhor não casar!"},
{"v":11,"t":"Jesus disse: Nem todos podem aceitar essa palavra, apenas aqueles a quem foi dado."},
{"v":12,"t":"Alguns não se casam porque nasceram assim. Outros porque foram impedidos por outros. E outros escolheram não se casar por causa do Reino dos Céus. Quem puder aceitar isso, aceite."},
{"v":13,"t":"Trouxeram crianças a Jesus para que ele colocasse as mãos sobre elas e orasse. Mas os discípulos os repreendiam."},
{"v":14,"t":"Jesus disse: Deixem as crianças virem a mim. Não as impeçam! Porque o Reino dos Céus pertence a pessoas como elas."},
{"v":15,"t":"Colocou as mãos sobre elas e depois seguiu caminho."},
{"v":16,"t":"Um jovem se aproximou e perguntou: Bom Mestre, o que devo fazer de bom para ter a vida eterna?"},
{"v":17,"t":"Jesus disse: Por que me chama de bom? Só Deus é bom. Se você quer entrar na vida, obedeça os mandamentos."},
{"v":18,"t":"O jovem perguntou: Quais? Jesus disse: Não mate, não cometa adultério, não roube, não dê falso testemunho,"},
{"v":19,"t":"honre seu pai e sua mãe, e ame o próximo como a si mesmo."},
{"v":20,"t":"O jovem disse: Eu obedeço tudo isso desde novo. O que ainda me falta?"},
{"v":21,"t":"Jesus disse: Se você quer ser perfeito, vá, venda tudo o que tem e dê o dinheiro aos pobres. Você terá um tesouro no céu. Depois, venha e me siga."},
{"v":22,"t":"Quando ouviu isso, o jovem foi embora triste, porque tinha muitas riquezas."},
{"v":23,"t":"Jesus disse aos discípulos: Eu digo a verdade: é difícil um rico entrar no Reino dos Céus."},
{"v":24,"t":"Eu repito: é mais fácil um camelo passar pelo buraco de uma agulha do que um rico entrar no Reino de Deus."},
{"v":25,"t":"Os discípulos ficaram espantados e perguntaram: Quem pode então se salvar?"},
{"v":26,"t":"Jesus olhou para eles e disse: Para os seres humanos isso é impossível. Mas para Deus tudo é possível."},
{"v":27,"t":"Pedro disse: Nós deixamos tudo e seguimos o senhor. O que vamos receber?"},
{"v":28,"t":"Jesus respondeu: Eu digo a verdade: no mundo novo, quando o Filho do Homem se sentar no seu trono de glória, vocês que me seguiram também se sentarão em doze tronos para julgar as doze tribos de Israel."},
{"v":29,"t":"Todo aquele que deixou casas, irmãos, irmãs, pai, mãe, filhos ou terras por minha causa receberá cem vezes mais e terá a vida eterna."},
{"v":30,"t":"Muitos que são os primeiros serão os últimos. E muitos que são os últimos serão os primeiros."},
]})

# Chapter 20
chapters.append({"c":20,"verses":[
{"v":1,"t":"O Reino dos Céus é como o dono de uma fazenda que saiu de manhã cedo para contratar trabalhadores para a sua plantação."},
{"v":2,"t":"Combinou pagar um salário diário e os mandou para a plantação."},
{"v":3,"t":"Por volta das nove horas, saiu e viu outros parados na praça, sem trabalho."},
{"v":4,"t":"Disse a eles: Vão trabalhar na minha plantação também. Eu pago o que for justo. E eles foram."},
{"v":5,"t":"Saiu de novo ao meio-dia e às três da tarde e fez a mesma coisa."},
{"v":6,"t":"Por volta das cinco da tarde, encontrou outros parados e perguntou: Por que vocês ficaram aqui o dia inteiro sem trabalhar?"},
{"v":7,"t":"Responderam: Porque ninguém nos contratou. Ele disse: Vão vocês também para a minha plantação."},
{"v":8,"t":"Quando a noite chegou, o dono disse ao administrador: Chame os trabalhadores e pague o salário, começando pelos últimos e terminando com os primeiros."},
{"v":9,"t":"Os que começaram às cinco da tarde receberam um salário diário cada um."},
{"v":10,"t":"Quando chegou a vez dos primeiros, acharam que iam receber mais. Mas cada um também recebeu um salário diário."},
{"v":11,"t":"Ao receber, reclamaram do dono da fazenda:"},
{"v":12,"t":"Esses últimos trabalharam só uma hora, e o senhor os igualou a nós, que aguentamos o dia inteiro debaixo do sol quente!"},
{"v":13,"t":"Ele respondeu a um deles: Amigo, eu não fui injusto com você. Não combinamos um salário diário?"},
{"v":14,"t":"Pegue o que é seu e vá. Eu quero dar a este último o mesmo que dei a você."},
{"v":15,"t":"Eu não posso fazer o que quiser com o meu dinheiro? Ou você está com inveja porque eu sou generoso?"},
{"v":16,"t":"Assim, os últimos serão primeiros e os primeiros serão últimos."},
{"v":17,"t":"Enquanto subia para Jerusalém, Jesus chamou os doze discípulos à parte e disse no caminho:"},
{"v":18,"t":"Nós estamos indo para Jerusalém. O Filho do Homem será entregue aos chefes dos sacerdotes e aos mestres da Lei. Eles vão condená-lo à morte."},
{"v":19,"t":"Vão entregá-lo aos romanos para zombarem dele, açoitá-lo e crucificá-lo. Mas no terceiro dia ele vai ressuscitar."},
{"v":20,"t":"Então a mãe dos filhos de Zebedeu se aproximou com os filhos, se ajoelhou e fez um pedido a Jesus."},
{"v":21,"t":"Ele perguntou: O que você quer? Ela disse: Mande que estes meus dois filhos se sentem um à sua direita e outro à sua esquerda no seu Reino."},
{"v":22,"t":"Jesus respondeu: Vocês não sabem o que estão pedindo. Vocês podem beber o cálice que eu vou beber? Responderam: Podemos."},
{"v":23,"t":"Jesus disse: Vocês vão beber o meu cálice. Mas sentar à minha direita ou à minha esquerda não depende de mim. Esses lugares são para quem o meu Pai preparou."},
{"v":24,"t":"Quando os outros dez ouviram isso, ficaram irritados com os dois irmãos."},
{"v":25,"t":"Jesus chamou todos e disse: Vocês sabem que os governantes das nações dominam sobre elas, e os poderosos abusam do poder."},
{"v":26,"t":"Entre vocês não deve ser assim. Quem quiser ser grande, sirva os outros."},
{"v":27,"t":"E quem quiser ser o primeiro, seja servo de todos."},
{"v":28,"t":"Porque o Filho do Homem não veio para ser servido, mas para servir e dar a sua vida para salvar muitas pessoas."},
{"v":29,"t":"Quando saíram de Jericó, uma grande multidão seguiu Jesus."},
{"v":30,"t":"Dois cegos estavam sentados à beira do caminho. Quando ouviram que Jesus passava, gritaram: Senhor, Filho de Davi, tenha compaixão de nós!"},
{"v":31,"t":"A multidão mandou que se calassem. Mas eles gritavam ainda mais: Senhor, Filho de Davi, tenha compaixão de nós!"},
{"v":32,"t":"Jesus parou, chamou os dois e perguntou: O que vocês querem que eu faça?"},
{"v":33,"t":"Responderam: Senhor, queremos enxergar!"},
{"v":34,"t":"Jesus teve compaixão e tocou nos olhos deles. Na mesma hora, eles enxergaram e seguiram Jesus."},
]})

# Save chapters 11-20
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'static', 'data', 'bfl', 'mateus_trans_p2.json'), 'w', encoding='utf-8') as f:
    json.dump(chapters, f, ensure_ascii=False, indent=None, separators=(',',':'))

print(f"Matthew chapters 11-20 ready: {sum(len(c['verses']) for c in chapters)} verses")
