# -*- coding: utf-8 -*-
"""BFL Translation - Marcos (Mark) - Chapters 1-8"""
import json, sys, os

chapters = []

# Chapter 1
chapters.append({"c":1,"verses":[
{"v":1,"t":"Início da boa notícia de Jesus Cristo, o Filho de Deus."},
{"v":2,"t":"Como está escrito nos profetas: Eu envio o meu mensageiro à sua frente. Ele vai preparar o seu caminho."},
{"v":3,"t":"Uma voz grita no deserto: Preparem o caminho do Senhor! Endireitem as estradas para ele!"},
{"v":4,"t":"João apareceu no deserto, batizando e pregando: Mudem de vida e sejam batizados para o perdão dos pecados."},
{"v":5,"t":"Toda a região da Judeia e todo o povo de Jerusalém iam até ele. Confessavam os pecados e eram batizados por ele no rio Jordão."},
{"v":6,"t":"João vestia roupas de pelo de camelo, com um cinto de couro. Comia gafanhotos e mel silvestre."},
{"v":7,"t":"Ele pregava: Depois de mim vem alguém mais poderoso do que eu. Eu não sou digno nem de me abaixar para desamarrar as sandálias dele."},
{"v":8,"t":"Eu batizei vocês com água, mas ele vai batizar vocês com o Espírito Santo."},
{"v":9,"t":"Naqueles dias, Jesus veio de Nazaré da Galileia e foi batizado por João no Jordão."},
{"v":10,"t":"Assim que saiu da água, Jesus viu o céu se abrindo e o Espírito descendo sobre ele como uma pomba."},
{"v":11,"t":"Uma voz do céu disse: Você é o meu Filho amado. Em você tenho grande alegria."},
{"v":12,"t":"Logo depois, o Espírito o levou para o deserto."},
{"v":13,"t":"Jesus ficou no deserto quarenta dias, sendo tentado por Satanás. Vivia entre os animais selvagens, e os anjos cuidavam dele."},
{"v":14,"t":"Depois que João foi preso, Jesus foi para a Galileia anunciando a boa notícia de Deus."},
{"v":15,"t":"Ele dizia: O tempo chegou! O Reino de Deus está perto! Mudem de vida e acreditem na boa notícia!"},
{"v":16,"t":"Andando à beira do mar da Galileia, Jesus viu Simão e André, irmão dele, jogando redes no mar. Eles eram pescadores."},
{"v":17,"t":"Jesus disse a eles: Sigam-me, e eu farei de vocês pescadores de pessoas."},
{"v":18,"t":"Na mesma hora, eles largaram as redes e o seguiram."},
{"v":19,"t":"Um pouco mais adiante, viu Tiago e João, filhos de Zebedeu. Estavam no barco, consertando as redes."},
{"v":20,"t":"Jesus os chamou. Eles deixaram o pai Zebedeu no barco com os empregados e o seguiram."},
{"v":21,"t":"Entraram em Cafarnaum. No sábado, Jesus foi à sinagoga e começou a ensinar."},
{"v":22,"t":"As pessoas ficaram admiradas com o ensino dele, porque ensinava com autoridade, e não como os mestres da Lei."},
{"v":23,"t":"Na sinagoga havia um homem dominado por um espírito mau. Ele gritou:"},
{"v":24,"t":"O que você quer conosco, Jesus de Nazaré? Veio nos destruir? Eu sei quem você é: o Santo de Deus!"},
{"v":25,"t":"Jesus ordenou: Cale-se e saia dele!"},
{"v":26,"t":"O espírito mau sacudiu o homem com violência, deu um grito forte e saiu dele."},
{"v":27,"t":"Todos ficaram espantados e perguntavam uns aos outros: O que é isso? Um ensino novo, com autoridade! Ele manda até nos espíritos maus, e eles obedecem!"},
{"v":28,"t":"A fama de Jesus se espalhou rapidamente por toda a região da Galileia."},
{"v":29,"t":"Saindo da sinagoga, foram direto para a casa de Simão e André, junto com Tiago e João."},
{"v":30,"t":"A sogra de Simão estava de cama com febre. Logo contaram a Jesus."},
{"v":31,"t":"Ele se aproximou, pegou a mão dela e a levantou. A febre foi embora, e ela começou a servi-los."},
{"v":32,"t":"Quando o sol se pôs, trouxeram a Jesus todos os doentes e os que tinham demônios."},
{"v":33,"t":"A cidade inteira se juntou na porta."},
{"v":34,"t":"Jesus curou muitos doentes de várias doenças e expulsou muitos demônios. Não deixava os demônios falarem, porque eles sabiam quem ele era."},
{"v":35,"t":"De madrugada, quando ainda estava escuro, Jesus se levantou e saiu para um lugar deserto. Ali ele orou."},
{"v":36,"t":"Simão e os companheiros foram atrás dele."},
{"v":37,"t":"Quando o encontraram, disseram: Todos estão procurando o senhor!"},
{"v":38,"t":"Jesus respondeu: Vamos para as vilas vizinhas, para que eu pregue lá também. Foi para isso que eu vim."},
{"v":39,"t":"E foi por toda a Galileia, pregando nas sinagogas e expulsando demônios."},
{"v":40,"t":"Um homem com lepra se aproximou, se ajoelhou e pediu: Se o senhor quiser, pode me curar."},
{"v":41,"t":"Jesus, cheio de compaixão, estendeu a mão, tocou nele e disse: Eu quero. Seja curado!"},
{"v":42,"t":"Na mesma hora, a lepra desapareceu e o homem ficou curado."},
{"v":43,"t":"Jesus o mandou embora com um aviso sério:"},
{"v":44,"t":"Não conte a ninguém! Vá se mostrar ao sacerdote e leve a oferta que Moisés mandou. Isso provará a sua cura."},
{"v":45,"t":"Mas o homem saiu e espalhou a notícia por toda parte. Depois disso, Jesus não podia mais entrar abertamente nas cidades. Ficava em lugares desertos, e as pessoas vinham até ele de todos os lados."},
]})

# Chapter 2
chapters.append({"c":2,"verses":[
{"v":1,"t":"Alguns dias depois, Jesus voltou a Cafarnaum. Logo se espalhou a notícia de que ele estava em casa."},
{"v":2,"t":"Tanta gente se juntou que não cabia mais ninguém, nem na porta. E Jesus anunciava a palavra a eles."},
{"v":3,"t":"Vieram quatro homens carregando um paralítico."},
{"v":4,"t":"Como não conseguiam chegar perto de Jesus por causa da multidão, abriram um buraco no telhado acima dele. Por ali, desceram a maca com o paralítico."},
{"v":5,"t":"Quando Jesus viu a fé deles, disse ao paralítico: Filho, os seus pecados estão perdoados."},
{"v":6,"t":"Alguns mestres da Lei estavam sentados ali e pensaram:"},
{"v":7,"t":"Por que este homem fala assim? Isso é uma ofensa a Deus! Só Deus pode perdoar pecados!"},
{"v":8,"t":"Jesus percebeu o que pensavam e disse: Por que vocês pensam assim?"},
{"v":9,"t":"O que é mais fácil: dizer ao paralítico 'Os seus pecados estão perdoados' ou 'Levante-se, pegue a sua maca e ande'?"},
{"v":10,"t":"Mas para que vocês saibam que o Filho do Homem tem poder na terra para perdoar pecados — disse ao paralítico:"},
{"v":11,"t":"Eu ordeno: levante-se, pegue a sua maca e vá para casa."},
{"v":12,"t":"O homem se levantou, pegou a maca e saiu diante de todos. Todos ficaram espantados e louvaram a Deus, dizendo: Nunca vimos nada igual!"},
{"v":13,"t":"Jesus voltou à beira do mar. Toda a multidão vinha até ele, e ele os ensinava."},
{"v":14,"t":"Passando por ali, viu Levi, filho de Alfeu, sentado no posto de cobrança de impostos. Disse: Siga-me. Levi se levantou e o seguiu."},
{"v":15,"t":"Jesus estava em casa, à mesa. Muitos cobradores de impostos e pecadores se sentaram com Jesus e os discípulos, porque muitos o seguiam."},
{"v":16,"t":"Os mestres da Lei que eram fariseus viram que ele comia com cobradores de impostos e pecadores. Perguntaram aos discípulos: Por que ele come com cobradores de impostos e pecadores?"},
{"v":17,"t":"Jesus ouviu e respondeu: Não são os saudáveis que precisam de médico, mas os doentes. Eu não vim chamar justos, mas pecadores para que mudem de vida."},
{"v":18,"t":"Os discípulos de João e os fariseus jejuavam. Vieram perguntar: Por que os discípulos de João e os dos fariseus jejuam, mas os seus não?"},
{"v":19,"t":"Jesus respondeu: Os convidados de um casamento podem jejuar enquanto o noivo está com eles? Enquanto o noivo estiver presente, não podem jejuar."},
{"v":20,"t":"Mas virão dias em que o noivo será tirado deles. Aí sim eles vão jejuar."},
{"v":21,"t":"Ninguém costura um remendo de pano novo em roupa velha. Senão, o remendo encolhe, rasga a roupa, e o buraco fica maior."},
{"v":22,"t":"Ninguém coloca vinho novo em vasilhas velhas de couro. Senão, o vinho estoura as vasilhas, e ambos se perdem. Vinho novo precisa de vasilhas novas."},
{"v":23,"t":"Num sábado, Jesus passava pelas plantações. Os discípulos começaram a colher espigas."},
{"v":24,"t":"Os fariseus disseram: Olha! Por que eles fazem no sábado o que não é permitido?"},
{"v":25,"t":"Jesus respondeu: Vocês nunca leram o que Davi fez quando estava com fome, ele e seus companheiros?"},
{"v":26,"t":"Ele entrou na casa de Deus, no tempo do sacerdote Abiatar, e comeu os pães oferecidos a Deus, que só os sacerdotes podiam comer. Deu também aos que estavam com ele."},
{"v":27,"t":"E disse: O sábado foi feito para o ser humano, e não o ser humano para o sábado."},
{"v":28,"t":"Portanto, o Filho do Homem é Senhor até do sábado."},
]})

# Chapter 3
chapters.append({"c":3,"verses":[
{"v":1,"t":"Jesus entrou de novo na sinagoga. Havia ali um homem com a mão seca."},
{"v":2,"t":"Estavam de olho em Jesus para ver se ele curaria no sábado, para poderem acusá-lo."},
{"v":3,"t":"Jesus disse ao homem da mão seca: Levante-se e venha para o meio."},
{"v":4,"t":"Perguntou: O que é permitido no sábado: fazer o bem ou o mal? Salvar uma vida ou destruir? Eles ficaram calados."},
{"v":5,"t":"Jesus olhou para eles com indignação, triste pela dureza do coração deles. Disse ao homem: Estenda a mão. Ele estendeu, e a mão ficou boa."},
{"v":6,"t":"Os fariseus saíram e começaram a planejar com os partidários de Herodes como matar Jesus."},
{"v":7,"t":"Jesus se retirou com os discípulos para a beira do mar. Uma grande multidão o seguiu, vinda da Galileia e da Judeia,"},
{"v":8,"t":"de Jerusalém, da Idumeia, de além do Jordão e da região de Tiro e Sidom. Muita gente, ouvindo o que ele fazia, vinha até ele."},
{"v":9,"t":"Jesus pediu aos discípulos que deixassem um barquinho pronto, por causa da multidão, para que não o esmagassem."},
{"v":10,"t":"Porque curava muitos, e todos que tinham doenças se jogavam sobre ele para tocá-lo."},
{"v":11,"t":"Quando os espíritos maus o viam, se jogavam no chão e gritavam: Você é o Filho de Deus!"},
{"v":12,"t":"Mas Jesus os proibia de dizer quem ele era."},
{"v":13,"t":"Jesus subiu a um monte e chamou os que ele quis. Eles foram até ele."},
{"v":14,"t":"Escolheu doze para estarem com ele e para enviá-los a pregar,"},
{"v":15,"t":"com poder para curar doenças e expulsar demônios:"},
{"v":16,"t":"Simão, a quem deu o nome de Pedro;"},
{"v":17,"t":"Tiago e João, filhos de Zebedeu, a quem deu o nome de Boanerges, que quer dizer Filhos do Trovão;"},
{"v":18,"t":"André, Filipe, Bartolomeu, Mateus, Tomé, Tiago, filho de Alfeu, Tadeu, Simão, o zelote,"},
{"v":19,"t":"e Judas Iscariotes, aquele que o traiu."},
{"v":20,"t":"Jesus entrou numa casa. A multidão se juntou de novo, de modo que eles nem conseguiam comer."},
{"v":21,"t":"Quando a família dele ouviu, foi buscá-lo, pois diziam: Ele perdeu o juízo!"},
{"v":22,"t":"Os mestres da Lei que vieram de Jerusalém diziam: Ele está possuído por Belzebu! É pelo chefe dos demônios que expulsa demônios."},
{"v":23,"t":"Jesus os chamou e falou por meio de comparações: Como Satanás pode expulsar Satanás?"},
{"v":24,"t":"Se um reino se dividir contra si mesmo, não sobrevive."},
{"v":25,"t":"Se uma casa se dividir contra si mesma, não sobrevive."},
{"v":26,"t":"Se Satanás se levantar contra si mesmo e se dividir, não sobrevive. Terá chegado ao fim."},
{"v":27,"t":"Ninguém pode entrar na casa de um homem forte e roubar as coisas dele. Só se primeiro amarrar o homem forte. Aí sim pode roubar a casa."},
{"v":28,"t":"Eu digo a verdade: todos os pecados e todas as ofensas a Deus serão perdoados aos seres humanos."},
{"v":29,"t":"Mas quem ofender o Espírito Santo nunca será perdoado. É culpado de um pecado eterno."},
{"v":30,"t":"Jesus disse isso porque estavam dizendo que ele tinha um espírito mau."},
{"v":31,"t":"Então a mãe e os irmãos de Jesus chegaram. Ficaram do lado de fora e mandaram chamá-lo."},
{"v":32,"t":"A multidão sentada ao redor disse: A sua mãe e os seus irmãos estão lá fora procurando o senhor."},
{"v":33,"t":"Jesus respondeu: Quem é a minha mãe? Quem são os meus irmãos?"},
{"v":34,"t":"Olhou para os que estavam sentados ao redor dele e disse: Aqui estão a minha mãe e os meus irmãos!"},
{"v":35,"t":"Quem faz a vontade de Deus, esse é meu irmão, minha irmã e minha mãe."},
]})

# Chapter 4
chapters.append({"c":4,"verses":[
{"v":1,"t":"Jesus começou a ensinar de novo à beira do mar. Uma multidão tão grande se juntou que ele entrou num barco e se sentou no mar. Todo o povo ficou na praia."},
{"v":2,"t":"Ele os ensinava muitas coisas por meio de histórias. Dizia:"},
{"v":3,"t":"Ouçam! Um agricultor saiu para plantar."},
{"v":4,"t":"Enquanto plantava, algumas sementes caíram à beira do caminho. Os pássaros vieram e comeram."},
{"v":5,"t":"Outras caíram em terreno pedregoso, onde havia pouca terra. Brotaram rápido porque a terra era rasa."},
{"v":6,"t":"Quando o sol apareceu, queimaram e secaram, porque não tinham raiz."},
{"v":7,"t":"Outras caíram entre espinhos. Os espinhos cresceram e as sufocaram. Não deram fruto."},
{"v":8,"t":"Outras caíram em terra boa e deram fruto: trinta, sessenta e até cem vezes mais."},
{"v":9,"t":"E disse: Quem tem ouvidos, ouça!"},
{"v":10,"t":"Quando ficou a sós, os que estavam ao redor dele com os doze perguntaram sobre as histórias."},
{"v":11,"t":"Ele respondeu: A vocês foi dado conhecer os segredos do Reino de Deus. Mas para os de fora, tudo é dito por meio de histórias."},
{"v":12,"t":"Para que olhando, olhem e não vejam. E ouvindo, ouçam e não entendam. Para que não se voltem e sejam perdoados."},
{"v":13,"t":"E disse: Vocês não entendem esta história? Como vão entender as outras?"},
{"v":14,"t":"O agricultor planta a palavra."},
{"v":15,"t":"As sementes à beira do caminho são as pessoas que ouvem a palavra. Mas logo Satanás vem e tira a palavra que foi plantada nelas."},
{"v":16,"t":"As sementes no terreno pedregoso são as pessoas que ouvem a palavra e a recebem com alegria."},
{"v":17,"t":"Mas não têm raiz profunda e duram pouco. Quando vem sofrimento ou perseguição por causa da palavra, logo desistem."},
{"v":18,"t":"As sementes entre espinhos são as pessoas que ouvem a palavra."},
{"v":19,"t":"Mas as preocupações da vida, a ilusão da riqueza e o desejo por outras coisas entram e sufocam a palavra. Ela não dá fruto."},
{"v":20,"t":"Mas as sementes em terra boa são as pessoas que ouvem a palavra, a aceitam e dão fruto: trinta, sessenta e cem vezes mais."},
{"v":21,"t":"E disse: Alguém traz uma lâmpada para colocar debaixo de um balde ou debaixo da cama? Não! A lâmpada é colocada num lugar alto para iluminar."},
{"v":22,"t":"Porque nada está escondido que não venha a ser revelado. Nada está oculto que não venha a ser descoberto."},
{"v":23,"t":"Quem tem ouvidos, ouça!"},
{"v":24,"t":"E disse: Prestem atenção no que ouvem. A medida que vocês usarem será usada para medir vocês, e ainda mais será dado a vocês."},
{"v":25,"t":"Porque a quem tem, mais será dado. De quem não tem, até o que tem será tirado."},
{"v":26,"t":"E disse: O Reino de Deus é como um homem que joga sementes na terra."},
{"v":27,"t":"Ele dorme e acorda, noite e dia, e a semente brota e cresce sem ele saber como."},
{"v":28,"t":"A terra produz por si mesma: primeiro a planta, depois a espiga, depois o grão cheio na espiga."},
{"v":29,"t":"Quando o grão está maduro, ele colhe, porque chegou o tempo da colheita."},
{"v":30,"t":"E disse: A que podemos comparar o Reino de Deus? Com que história podemos descrevê-lo?"},
{"v":31,"t":"É como uma semente de mostarda. Quando é plantada na terra, é a menor de todas as sementes."},
{"v":32,"t":"Mas depois de plantada, cresce e se torna a maior de todas as plantas. Faz galhos tão grandes que os pássaros podem fazer ninhos na sua sombra."},
{"v":33,"t":"Com muitas histórias como essas, Jesus anunciava a palavra ao povo, de acordo com o que podiam entender."},
{"v":34,"t":"Não falava nada sem usar histórias. Mas quando ficava a sós com os discípulos, explicava tudo."},
{"v":35,"t":"Naquele dia, quando a tarde chegou, disse: Vamos para o outro lado do lago."},
{"v":36,"t":"Eles deixaram a multidão e levaram Jesus no barco como estava. Outros barcos também iam com eles."},
{"v":37,"t":"Uma tempestade forte de vento começou. As ondas batiam no barco e ele já estava enchendo de água."},
{"v":38,"t":"Jesus estava na parte de trás, dormindo sobre um travesseiro. Os discípulos o acordaram: Mestre, não se importa que estamos morrendo?"},
{"v":39,"t":"Jesus se levantou, repreendeu o vento e disse ao mar: Silêncio! Fique quieto! O vento parou, e tudo ficou calmo."},
{"v":40,"t":"Disse a eles: Por que estão com tanto medo? Vocês ainda não têm fé?"},
{"v":41,"t":"Eles ficaram apavorados e diziam uns aos outros: Quem é este, que até o vento e o mar obedecem a ele?"},
]})

# Chapter 5
chapters.append({"c":5,"verses":[
{"v":1,"t":"Chegaram ao outro lado do mar, na região dos gadarenos."},
{"v":2,"t":"Assim que Jesus saiu do barco, um homem dominado por um espírito mau saiu dos túmulos e veio ao encontro dele."},
{"v":3,"t":"O homem morava nos túmulos. Ninguém conseguia prendê-lo, nem com correntes."},
{"v":4,"t":"Muitas vezes tinham amarrado os pés e as mãos dele com correntes, mas ele as arrebentava. Ninguém tinha força para controlá-lo."},
{"v":5,"t":"Dia e noite, nos túmulos e nos montes, gritava e se cortava com pedras."},
{"v":6,"t":"Quando viu Jesus de longe, correu e se ajoelhou diante dele."},
{"v":7,"t":"Gritou bem alto: O que você quer comigo, Jesus, Filho do Deus Altíssimo? Pelo amor de Deus, não me atormente!"},
{"v":8,"t":"Porque Jesus tinha dito: Espírito mau, saia deste homem!"},
{"v":9,"t":"Jesus perguntou: Qual é o seu nome? Ele respondeu: Meu nome é Legião, porque somos muitos."},
{"v":10,"t":"E pedia muito que não os mandasse embora daquela região."},
{"v":11,"t":"Perto dali, uma grande manada de porcos comia no monte."},
{"v":12,"t":"Os demônios imploraram: Nos mande para os porcos, para entrarmos neles."},
{"v":13,"t":"Jesus permitiu. Os espíritos maus saíram e entraram nos porcos. A manada toda, cerca de dois mil, correu despenhadeiro abaixo e se afogou no mar."},
{"v":14,"t":"Os que cuidavam dos porcos fugiram e espalharam a notícia pela cidade e pelo campo. As pessoas foram ver o que tinha acontecido."},
{"v":15,"t":"Quando chegaram perto de Jesus, viram o homem que tinha a legião de demônios. Ele estava sentado, vestido e em perfeito juízo. E ficaram com medo."},
{"v":16,"t":"Os que tinham visto contaram o que aconteceu com o homem e com os porcos."},
{"v":17,"t":"Então pediram a Jesus que fosse embora da região deles."},
{"v":18,"t":"Quando Jesus entrou no barco, o homem que tinha sido libertado pediu para ir com ele."},
{"v":19,"t":"Mas Jesus não deixou. Disse: Vá para casa, para a sua família, e conte tudo o que o Senhor fez por você e como teve compaixão de você."},
{"v":20,"t":"O homem foi e começou a contar em Decápolis tudo que Jesus tinha feito por ele. Todos ficaram admirados."},
{"v":21,"t":"Jesus atravessou de volta no barco para o outro lado. Uma grande multidão se juntou ao redor dele, à beira do mar."},
{"v":22,"t":"Veio um dos líderes da sinagoga, chamado Jairo. Quando viu Jesus, se jogou aos pés dele"},
{"v":23,"t":"e pediu com insistência: A minha filha está morrendo! Venha e coloque as mãos sobre ela para que fique curada e viva!"},
{"v":24,"t":"Jesus foi com ele. Uma grande multidão o seguia e o apertava."},
{"v":25,"t":"Havia ali uma mulher que sofria de hemorragia havia doze anos."},
{"v":26,"t":"Ela tinha sofrido muito com vários médicos. Gastou tudo que tinha e não melhorou. Pelo contrário, piorou."},
{"v":27,"t":"Quando ouviu falar de Jesus, veio por trás, no meio da multidão, e tocou na roupa dele."},
{"v":28,"t":"Porque pensava: Se eu apenas tocar na roupa dele, ficarei curada."},
{"v":29,"t":"Na mesma hora, a hemorragia parou. Ela sentiu no corpo que estava curada."},
{"v":30,"t":"Jesus logo percebeu que um poder tinha saído dele. Virou-se no meio da multidão e perguntou: Quem tocou na minha roupa?"},
{"v":31,"t":"Os discípulos disseram: O senhor vê a multidão apertando, e pergunta quem tocou?"},
{"v":32,"t":"Jesus olhava ao redor para ver quem tinha feito isso."},
{"v":33,"t":"A mulher, tremendo de medo, sabendo o que tinha acontecido, se aproximou, se jogou aos pés dele e contou toda a verdade."},
{"v":34,"t":"Jesus disse: Filha, a sua fé curou você. Vá em paz e fique livre do seu sofrimento."},
{"v":35,"t":"Enquanto ele ainda falava, vieram da casa de Jairo com a notícia: A sua filha morreu. Não precisa mais incomodar o Mestre."},
{"v":36,"t":"Mas Jesus ouviu e disse a Jairo: Não tenha medo. Apenas acredite."},
{"v":37,"t":"Não deixou ninguém acompanhá-lo, a não ser Pedro, Tiago e João, irmão de Tiago."},
{"v":38,"t":"Quando chegaram à casa de Jairo, viram muita agitação, choro e lamento."},
{"v":39,"t":"Jesus entrou e disse: Por que essa agitação e esse choro? A menina não morreu. Está dormindo."},
{"v":40,"t":"Eles riram dele. Mas Jesus mandou todos saírem, pegou o pai e a mãe da menina e os discípulos, e entrou onde a menina estava."},
{"v":41,"t":"Pegou a mão da menina e disse: Talitá cumi! Que quer dizer: Menina, eu ordeno, levante-se!"},
{"v":42,"t":"Na mesma hora, a menina se levantou e começou a andar. Ela tinha doze anos. Todos ficaram completamente espantados."},
{"v":43,"t":"Jesus ordenou que ninguém soubesse daquilo. E disse que dessem comida à menina."},
]})

# Chapter 6
chapters.append({"c":6,"verses":[
{"v":1,"t":"Jesus saiu dali e foi para a cidade onde cresceu. Os discípulos o seguiram."},
{"v":2,"t":"No sábado, começou a ensinar na sinagoga. Muitos que ouviam ficavam admirados e diziam: De onde vem isso? Que sabedoria é essa? E esses milagres que ele faz?"},
{"v":3,"t":"Não é o carpinteiro, o filho de Maria, irmão de Tiago, José, Judas e Simão? As irmãs dele não moram aqui? E ficavam ofendidos com ele."},
{"v":4,"t":"Jesus disse: Um profeta é respeitado em todo lugar, menos na sua cidade, entre seus parentes e na sua casa."},
{"v":5,"t":"Não pôde fazer nenhum milagre ali. Apenas curou alguns doentes, colocando as mãos sobre eles."},
{"v":6,"t":"E ficou admirado com a falta de fé deles. Depois percorreu as vilas ao redor, ensinando."},
{"v":7,"t":"Chamou os doze e começou a enviá-los de dois em dois. Deu a eles poder sobre espíritos maus."},
{"v":8,"t":"Ordenou que não levassem nada para o caminho, a não ser um cajado. Nem pão, nem bolsa, nem dinheiro."},
{"v":9,"t":"Podiam calçar sandálias, mas não vestir roupa extra."},
{"v":10,"t":"Disse: Quando entrarem numa casa, fiquem ali até irem embora."},
{"v":11,"t":"Se em algum lugar não receberem vocês nem ouvirem vocês, saiam de lá e sacudam o pó dos pés. Isso servirá de aviso para eles."},
{"v":12,"t":"Eles saíram e pregaram que as pessoas deviam mudar de vida."},
{"v":13,"t":"Expulsaram muitos demônios, ungiram com óleo muitos doentes e os curaram."},
{"v":14,"t":"O rei Herodes ouviu falar de Jesus, porque o nome dele se tornou conhecido. Alguns diziam: João Batista voltou dos mortos! Por isso faz esses milagres."},
{"v":15,"t":"Outros diziam: É Elias. Outros diziam: É um profeta, como os antigos profetas."},
{"v":16,"t":"Quando Herodes ouviu, disse: É João! Eu mandei cortar a cabeça dele, mas ele voltou dos mortos."},
{"v":17,"t":"Herodes tinha prendido João e o acorrentado na prisão por causa de Herodias, esposa do irmão dele, Filipe. Herodes tinha se casado com ela."},
{"v":18,"t":"João dizia a Herodes: Não é certo você viver com a esposa do seu irmão."},
{"v":19,"t":"Herodias guardava rancor contra João e queria matá-lo, mas não conseguia."},
{"v":20,"t":"Herodes tinha medo de João, porque sabia que era um homem justo e santo. Por isso o protegia. Ficava perturbado quando ouvia João, mas gostava de ouvi-lo."},
{"v":21,"t":"Chegou a oportunidade quando Herodes deu um banquete de aniversário para os seus oficiais, comandantes e líderes da Galileia."},
{"v":22,"t":"A filha de Herodias entrou e dançou. Agradou muito a Herodes e aos convidados. O rei disse à moça: Peça o que quiser, e eu darei."},
{"v":23,"t":"E jurou: O que você pedir, eu dou. Até a metade do meu reino!"},
{"v":24,"t":"Ela saiu e perguntou à mãe: O que devo pedir? A mãe respondeu: A cabeça de João Batista."},
{"v":25,"t":"A moça voltou correndo ao rei e pediu: Quero que me dê agora, num prato, a cabeça de João Batista!"},
{"v":26,"t":"O rei ficou muito triste. Mas por causa do juramento e dos convidados, não quis recusar."},
{"v":27,"t":"Na mesma hora, mandou um soldado buscar a cabeça de João. O soldado foi e cortou a cabeça dele na prisão."},
{"v":28,"t":"Trouxe a cabeça num prato e entregou à moça. Ela deu à mãe."},
{"v":29,"t":"Quando os discípulos de João souberam, vieram, pegaram o corpo e o colocaram num túmulo."},
{"v":30,"t":"Os apóstolos voltaram e contaram a Jesus tudo que tinham feito e ensinado."},
{"v":31,"t":"Jesus disse: Venham comigo para um lugar quieto e descansem um pouco. Porque havia tanta gente indo e vindo que eles não tinham nem tempo de comer."},
{"v":32,"t":"Foram de barco para um lugar deserto, só eles."},
{"v":33,"t":"Mas muitos os viram partir e os reconheceram. De todas as cidades, correram a pé e chegaram lá antes deles."},
{"v":34,"t":"Quando Jesus saiu do barco, viu a grande multidão e teve compaixão, porque eram como ovelhas sem pastor. Começou a ensinar muitas coisas."},
{"v":35,"t":"Quando ficou tarde, os discípulos se aproximaram e disseram: Este lugar é deserto e já está ficando tarde."},
{"v":36,"t":"Mande o povo embora para ir às vilas comprar comida."},
{"v":37,"t":"Jesus respondeu: Deem vocês mesmos de comer a eles. Eles perguntaram: Devemos gastar duzentos salários em pão para dar a eles?"},
{"v":38,"t":"Jesus disse: Quantos pães vocês têm? Vão ver. Depois de verificarem, disseram: Cinco pães e dois peixes."},
{"v":39,"t":"Jesus mandou que todos se sentassem em grupos na grama verde."},
{"v":40,"t":"Sentaram-se em grupos de cem e de cinquenta."},
{"v":41,"t":"Jesus pegou os cinco pães e os dois peixes, olhou para o céu, deu graças a Deus, partiu os pães e deu aos discípulos para distribuírem. Também repartiu os dois peixes entre todos."},
{"v":42,"t":"Todos comeram e ficaram satisfeitos."},
{"v":43,"t":"E ainda recolheram doze cestos cheios de pedaços de pão e peixe."},
{"v":44,"t":"Os que comeram eram cerca de cinco mil homens."},
{"v":45,"t":"Logo depois, Jesus mandou os discípulos entrarem no barco e irem na frente para Betsaida, do outro lado. Enquanto isso, ele despediu a multidão."},
{"v":46,"t":"Depois de despedi-los, subiu ao monte para orar."},
{"v":47,"t":"Quando a noite chegou, o barco estava no meio do mar, e Jesus, sozinho, em terra."},
{"v":48,"t":"Ele viu que os discípulos se esforçavam para remar, porque o vento era contrário. De madrugada, foi até eles, andando sobre o mar. Ia passar por eles."},
{"v":49,"t":"Quando o viram andando sobre o mar, pensaram que era um fantasma e gritaram de medo."},
{"v":50,"t":"Todos o viram e ficaram apavorados. Mas Jesus logo falou: Coragem! Sou eu. Não tenham medo."},
{"v":51,"t":"Entrou no barco, e o vento parou. Eles ficaram completamente espantados."},
{"v":52,"t":"Porque não tinham entendido o milagre dos pães. O coração deles estava duro."},
{"v":53,"t":"Quando terminaram a travessia, chegaram a Genesaré e ancoraram ali."},
{"v":54,"t":"Assim que saíram do barco, as pessoas reconheceram Jesus."},
{"v":55,"t":"Correram por toda a região e começaram a trazer os doentes em macas para onde sabiam que ele estava."},
{"v":56,"t":"Onde Jesus entrava, em vilas, cidades ou no campo, colocavam os doentes nas praças e pediam que pudessem tocar ao menos na barra da roupa dele. Todos os que tocavam ficavam curados."},
]})

# Chapter 7
chapters.append({"c":7,"verses":[
{"v":1,"t":"Os fariseus e alguns mestres da Lei que vieram de Jerusalém se juntaram ao redor de Jesus."},
{"v":2,"t":"Viram que alguns discípulos dele comiam com as mãos impuras, sem lavar."},
{"v":3,"t":"Os fariseus e todos os judeus seguiam a tradição dos antigos e não comiam sem lavar bem as mãos."},
{"v":4,"t":"Quando voltavam do mercado, não comiam sem se purificar. Guardavam muitas outras tradições, como lavar copos, jarras e panelas."},
{"v":5,"t":"Os fariseus e mestres da Lei perguntaram: Por que os seus discípulos não seguem a tradição dos antigos e comem com as mãos sem lavar?"},
{"v":6,"t":"Jesus respondeu: Isaías profetizou bem sobre vocês, hipócritas! Está escrito: Este povo me honra com os lábios, mas o coração está longe de mim."},
{"v":7,"t":"É inútil me adorarem, ensinando regras feitas por seres humanos."},
{"v":8,"t":"Vocês abandonam o mandamento de Deus e seguem tradições humanas."},
{"v":9,"t":"E disse: Vocês são espertos em anular o mandamento de Deus para manter a tradição de vocês!"},
{"v":10,"t":"Moisés disse: Honre seu pai e sua mãe. E: Quem amaldiçoar o pai ou a mãe deve morrer."},
{"v":11,"t":"Mas vocês dizem que se alguém disser ao pai ou à mãe: O que eu poderia usar para ajudá-lo é Corbã, quer dizer, oferta a Deus —"},
{"v":12,"t":"então não precisa mais fazer nada pelo pai ou pela mãe."},
{"v":13,"t":"Assim vocês anulam a palavra de Deus com a tradição de vocês. E fazem muitas coisas parecidas."},
{"v":14,"t":"Jesus chamou a multidão e disse: Ouçam todos e entendam:"},
{"v":15,"t":"Nada que vem de fora pode tornar a pessoa impura ao entrar nela. O que sai da pessoa é que a torna impura."},
{"v":16,"t":"Quem tem ouvidos, ouça!"},
{"v":17,"t":"Quando Jesus deixou a multidão e entrou em casa, os discípulos perguntaram sobre o que ele disse."},
{"v":18,"t":"Ele respondeu: Vocês também não entendem? Não percebem que nada que entra na pessoa vinda de fora pode torná-la impura?"},
{"v":19,"t":"Porque não entra no coração, mas no estômago, e depois é eliminado. Assim ele declarou todos os alimentos puros."},
{"v":20,"t":"E disse: O que sai da pessoa é que a torna impura."},
{"v":21,"t":"Porque de dentro, do coração das pessoas, saem os pensamentos maus: imoralidade, roubo, assassinato,"},
{"v":22,"t":"adultério, ganância, maldade, mentira, falta de vergonha, inveja, ofensa a Deus, orgulho e loucura."},
{"v":23,"t":"Todas essas coisas ruins vêm de dentro e tornam a pessoa impura."},
{"v":24,"t":"Jesus saiu dali e foi para a região de Tiro e Sidom. Entrou numa casa e não queria que ninguém soubesse. Mas não conseguiu ficar escondido."},
{"v":25,"t":"Uma mulher cuja filha tinha um espírito mau ouviu falar dele. Foi e se jogou aos pés de Jesus."},
{"v":26,"t":"A mulher era grega, de origem siro-fenícia. Pediu que expulsasse o demônio da filha dela."},
{"v":27,"t":"Jesus disse: Primeiro os filhos devem comer até ficar satisfeitos. Não é certo pegar o pão dos filhos e jogar para os cachorrinhos."},
{"v":28,"t":"Ela respondeu: Sim, Senhor. Mas até os cachorrinhos debaixo da mesa comem as migalhas das crianças."},
{"v":29,"t":"Jesus disse: Por essa resposta, vá. O demônio já saiu da sua filha."},
{"v":30,"t":"Ela foi para casa e encontrou a filha deitada na cama, livre do demônio."},
{"v":31,"t":"Jesus saiu da região de Tiro, passou por Sidom e foi até o mar da Galileia, pela região de Decápolis."},
{"v":32,"t":"Trouxeram a ele um homem surdo que mal conseguia falar. Pediram que colocasse a mão sobre ele."},
{"v":33,"t":"Jesus o levou para longe da multidão. Colocou os dedos nos ouvidos dele e, com saliva, tocou na língua dele."},
{"v":34,"t":"Olhou para o céu, suspirou e disse: Efatá! Que quer dizer: Abra-se!"},
{"v":35,"t":"Na mesma hora, os ouvidos do homem se abriram, a língua se soltou, e ele começou a falar perfeitamente."},
{"v":36,"t":"Jesus mandou que não contassem a ninguém. Mas quanto mais proibia, mais eles espalhavam."},
{"v":37,"t":"As pessoas ficavam maravilhadas e diziam: Ele faz tudo bem! Faz os surdos ouvirem e os mudos falarem!"},
]})

# Chapter 8
chapters.append({"c":8,"verses":[
{"v":1,"t":"Naqueles dias, outra grande multidão se juntou e não tinham o que comer. Jesus chamou os discípulos e disse:"},
{"v":2,"t":"Tenho compaixão desta multidão. Já faz três dias que estão comigo e não têm comida."},
{"v":3,"t":"Se eu os mandar embora com fome, vão desmaiar no caminho. Alguns vieram de longe."},
{"v":4,"t":"Os discípulos perguntaram: De onde alguém vai conseguir pão aqui no deserto para alimentar toda essa gente?"},
{"v":5,"t":"Jesus perguntou: Quantos pães vocês têm? Responderam: Sete."},
{"v":6,"t":"Jesus mandou a multidão se sentar no chão. Pegou os sete pães, deu graças a Deus, partiu e deu aos discípulos para distribuírem. E eles distribuíram ao povo."},
{"v":7,"t":"Tinham também alguns peixinhos. Jesus deu graças e mandou distribuí-los também."},
{"v":8,"t":"Todos comeram e ficaram satisfeitos. Recolheram sete cestos cheios de pedaços que sobraram."},
{"v":9,"t":"Eram cerca de quatro mil pessoas. Jesus os despediu."},
{"v":10,"t":"Entrou no barco com os discípulos e foi para a região de Dalmanuta."},
{"v":11,"t":"Os fariseus vieram e começaram a discutir com Jesus. Pediram um sinal do céu para testá-lo."},
{"v":12,"t":"Jesus suspirou profundamente e disse: Por que esta geração pede um sinal? Eu digo a verdade: nenhum sinal será dado a esta geração."},
{"v":13,"t":"Deixou-os, entrou de novo no barco e foi para o outro lado."},
{"v":14,"t":"Os discípulos tinham esquecido de levar pão. Só tinham um pão no barco."},
{"v":15,"t":"Jesus os avisou: Cuidado com o fermento dos fariseus e o fermento de Herodes."},
{"v":16,"t":"Eles discutiam entre si: É porque não temos pão."},
{"v":17,"t":"Jesus percebeu e disse: Por que discutem por não terem pão? Ainda não entendem? O coração de vocês ainda está duro?"},
{"v":18,"t":"Vocês têm olhos e não veem? Têm ouvidos e não ouvem? Não se lembram?"},
{"v":19,"t":"Quando parti cinco pães para cinco mil pessoas, quantos cestos de pedaços vocês recolheram? Disseram: Doze."},
{"v":20,"t":"E quando parti sete pães para quatro mil, quantos cestos recolheram? Disseram: Sete."},
{"v":21,"t":"Ele disse: Ainda não entendem?"},
{"v":22,"t":"Chegaram a Betsaida. Trouxeram um cego e pediram que Jesus tocasse nele."},
{"v":23,"t":"Jesus pegou o cego pela mão e o levou para fora da vila. Cuspiu nos olhos dele, colocou as mãos sobre ele e perguntou: Você vê alguma coisa?"},
{"v":24,"t":"O homem olhou e disse: Vejo pessoas, mas parecem árvores andando."},
{"v":25,"t":"Jesus colocou as mãos de novo sobre os olhos dele. O homem olhou fixamente e ficou curado. Passou a ver tudo com clareza."},
{"v":26,"t":"Jesus mandou-o para casa, dizendo: Não entre na vila."},
{"v":27,"t":"Jesus e os discípulos foram para as vilas perto de Cesareia de Filipe. No caminho, perguntou: Quem o povo diz que eu sou?"},
{"v":28,"t":"Responderam: Uns dizem João Batista. Outros, Elias. Outros, um dos profetas."},
{"v":29,"t":"Jesus perguntou: E vocês, quem dizem que eu sou? Pedro respondeu: O senhor é o Cristo."},
{"v":30,"t":"Jesus os avisou para não contarem isso a ninguém."},
{"v":31,"t":"Começou a ensiná-los que o Filho do Homem precisava sofrer muito. Seria rejeitado pelos líderes, pelos chefes dos sacerdotes e mestres da Lei. Seria morto, mas depois de três dias ressuscitaria."},
{"v":32,"t":"Falou isso abertamente. Pedro o chamou de lado e começou a repreendê-lo."},
{"v":33,"t":"Mas Jesus se virou, olhou para os discípulos e repreendeu Pedro: Saia da minha frente, Satanás! Você não pensa nas coisas de Deus, mas nas coisas humanas."},
{"v":34,"t":"Então chamou a multidão com os discípulos e disse: Se alguém quer me seguir, negue a si mesmo, pegue a sua cruz e me siga."},
{"v":35,"t":"Quem quiser salvar a própria vida vai perdê-la. Mas quem perder a vida por minha causa e pela boa notícia vai salvá-la."},
{"v":36,"t":"De que adianta uma pessoa ganhar o mundo inteiro e perder a própria alma?"},
{"v":37,"t":"O que alguém pode dar em troca da sua alma?"},
{"v":38,"t":"Se alguém tiver vergonha de mim e das minhas palavras nesta geração infiel e pecadora, o Filho do Homem também terá vergonha dessa pessoa quando vier na glória do Pai com os anjos santos."},
]})

# Save chapters 1-8
out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'static', 'data', 'bfl', 'marcos_trans.json')
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(chapters, f, ensure_ascii=False, indent=None, separators=(',',':'))

print(f"Mark chapters 1-8 ready: {sum(len(c['verses']) for c in chapters)} verses")
