#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""BFL Translation of Romans (Romanos) - Chapters 9-16"""
import json

chapters = []

# Chapter 9 - God's sovereign choice
chapters.append({"c":9,"verses":[
{"v":1,"t":"Eu digo a verdade em Cristo. Não minto. Minha consciência, guiada pelo Espírito Santo, confirma isso."},
{"v":2,"t":"Tenho uma grande tristeza e uma dor que não para no meu coração."},
{"v":3,"t":"Eu desejaria até ser separado de Cristo em favor dos meus irmãos, meus parentes de sangue."},
{"v":4,"t":"Eles são israelitas. A eles pertencem a adoção como filhos, a glória, as alianças, a lei, o culto no templo e as promessas."},
{"v":5,"t":"Deles são os patriarcas. E deles veio Cristo segundo a natureza humana. Ele é Deus sobre tudo, bendito para sempre. Amém."},
{"v":6,"t":"Não é que a palavra de Deus falhou. Porque nem todos os que descendem de Israel são Israel de verdade."},
{"v":7,"t":"Nem todos os descendentes de Abraão são filhos dele. Mas foi dito: É por meio de Isaque que terá a sua descendência."},
{"v":8,"t":"Isso quer dizer: não são os filhos naturais que são filhos de Deus. São os filhos da promessa que são contados como descendência."},
{"v":9,"t":"Porque a promessa disse: Nesta época eu voltarei e Sara terá um filho."},
{"v":10,"t":"E não é só isso. Rebeca também teve filhos de um só homem, nosso pai Isaque."},
{"v":11,"t":"Antes de os gêmeos nascerem e antes de fazerem qualquer coisa boa ou ruim, para que o propósito de Deus na escolha permanecesse firme, não por causa de obras, mas por causa daquele que chama,"},
{"v":12,"t":"foi dito a ela: O mais velho servirá ao mais novo."},
{"v":13,"t":"Como está escrito: Amei Jacó e rejeitei Esaú."},
{"v":14,"t":"Então o que diremos? Deus é injusto? De jeito nenhum!"},
{"v":15,"t":"Ele disse a Moisés: Terei misericórdia de quem eu quiser ter misericórdia. Terei compaixão de quem eu quiser ter compaixão."},
{"v":16,"t":"Portanto, não depende da vontade nem do esforço humano, mas da misericórdia de Deus."},
{"v":17,"t":"A Escritura diz ao faraó: Eu levantei você exatamente para isso: para mostrar o meu poder em você e para que o meu nome seja anunciado em toda a terra."},
{"v":18,"t":"Portanto, Deus tem misericórdia de quem ele quer e endurece quem ele quer."},
{"v":19,"t":"Você vai me dizer: Então por que Deus ainda nos culpa? Quem pode resistir à vontade dele?"},
{"v":20,"t":"Mas quem é você, ser humano, para discutir com Deus? A coisa moldada vai dizer ao que a moldou: Por que você me fez assim?"},
{"v":21,"t":"O oleiro não tem direito sobre o barro? Ele pode fazer do mesmo barro um vaso para uso nobre e outro para uso comum?"},
{"v":22,"t":"E se Deus, querendo mostrar sua ira e tornar conhecido o seu poder, suportou com muita paciência os vasos da ira, preparados para a destruição?"},
{"v":23,"t":"E se ele fez isso para tornar conhecida a riqueza da sua glória sobre os vasos de misericórdia, que ele preparou de antemão para a glória?"},
{"v":24,"t":"Nós somos esses vasos que ele chamou, não só dentre os judeus, mas também dentre os não judeus."},
{"v":25,"t":"Como ele diz em Oseias: Chamarei de meu povo aqueles que não eram meu povo. Chamarei de amada aquela que não era amada."},
{"v":26,"t":"E no mesmo lugar onde lhes foi dito: Vocês não são meu povo, ali serão chamados filhos do Deus vivo."},
{"v":27,"t":"Isaías também grita a respeito de Israel: Mesmo que o número dos filhos de Israel seja como a areia do mar, apenas um resto será salvo."},
{"v":28,"t":"Porque o Senhor vai executar a sua sentença na terra de forma completa e rápida."},
{"v":29,"t":"Como Isaías disse antes: Se o Senhor dos exércitos não tivesse deixado descendentes para nós, teríamos ficado como Sodoma e nos tornado como Gomorra."},
{"v":30,"t":"Então o que diremos? Que os não judeus, que não buscavam a justiça, a alcançaram. A justiça que vem pela fé."},
{"v":31,"t":"Mas Israel, que buscava uma lei de justiça, não chegou a cumpri-la."},
{"v":32,"t":"Por quê? Porque não buscaram pela fé, mas pelas obras. Tropeçaram na pedra de tropeço."},
{"v":33,"t":"Como está escrito: Eu coloco em Sião uma pedra de tropeço e uma rocha que faz cair. Mas quem crê nele não será envergonhado."},
]})

# Chapter 10 - Salvation for all who believe
chapters.append({"c":10,"verses":[
{"v":1,"t":"Irmãos, o desejo do meu coração e a minha oração a Deus por eles é que sejam salvos."},
{"v":2,"t":"Eu reconheço que eles têm zelo por Deus. Mas esse zelo não é baseado no conhecimento."},
{"v":3,"t":"Não conhecendo a justiça de Deus e tentando estabelecer a sua própria justiça, eles não se submeteram à justiça de Deus."},
{"v":4,"t":"Cristo é o fim da lei para que haja justiça para todo aquele que crê."},
{"v":5,"t":"Moisés escreveu sobre a justiça que vem da lei: A pessoa que fizer essas coisas viverá por elas."},
{"v":6,"t":"Mas a justiça que vem da fé diz: Não diga no seu coração: Quem vai subir ao céu? Isto é, para trazer Cristo para baixo."},
{"v":7,"t":"Ou: Quem vai descer ao abismo? Isto é, para trazer Cristo de volta dos mortos."},
{"v":8,"t":"O que ela diz? A palavra está perto de você, na sua boca e no seu coração. Esta é a palavra da fé que pregamos."},
{"v":9,"t":"Se você confessar com a boca que Jesus é o Senhor e crer no coração que Deus o ressuscitou dos mortos, você será salvo."},
{"v":10,"t":"Porque com o coração se crê para a justiça. E com a boca se confessa para a salvação."},
{"v":11,"t":"A Escritura diz: Todo aquele que crê nele não será envergonhado."},
{"v":12,"t":"Não há diferença entre judeu e não judeu. O mesmo Senhor é Senhor de todos e é generoso com todos os que o invocam."},
{"v":13,"t":"Porque todo aquele que invocar o nome do Senhor será salvo."},
{"v":14,"t":"Mas como invocarão aquele em quem não creram? Como crerão naquele de quem não ouviram falar? Como ouvirão se ninguém pregar?"},
{"v":15,"t":"E como pregarão se não forem enviados? Como está escrito: Como são bonitos os pés dos que anunciam boas notícias!"},
{"v":16,"t":"Mas nem todos aceitaram a boa notícia. Isaías disse: Senhor, quem creu na nossa mensagem?"},
{"v":17,"t":"Portanto, a fé vem por ouvir a mensagem. E a mensagem vem pela palavra de Cristo."},
{"v":18,"t":"Mas eu pergunto: eles não ouviram? Claro que ouviram! A voz deles se espalhou por toda a terra. As suas palavras chegaram aos confins do mundo."},
{"v":19,"t":"Pergunto de novo: Israel não entendeu? Primeiro Moisés diz: Eu vou provocar ciúme em vocês por meio de um povo que não é nação. Vou irritar vocês por meio de uma nação sem entendimento."},
{"v":20,"t":"Isaías diz com ousadia: Fui encontrado por quem não me procurava. Revelei-me a quem não perguntava por mim."},
{"v":21,"t":"Mas sobre Israel ele diz: O dia inteiro estendi as mãos a um povo desobediente e rebelde."},
]})

# Chapter 11 - The remnant of Israel
chapters.append({"c":11,"verses":[
{"v":1,"t":"Então pergunto: Deus rejeitou o seu povo? De jeito nenhum! Eu mesmo sou israelita, descendente de Abraão, da tribo de Benjamim."},
{"v":2,"t":"Deus não rejeitou o povo que conheceu de antemão. Vocês não sabem o que a Escritura diz sobre Elias? Ele reclamou a Deus contra Israel:"},
{"v":3,"t":"Senhor, eles mataram os teus profetas e derrubaram os teus altares. Só sobrei eu, e estão tentando me matar."},
{"v":4,"t":"Mas qual foi a resposta de Deus? Eu reservei para mim sete mil homens que não se ajoelharam diante de Baal."},
{"v":5,"t":"Da mesma forma, no tempo presente existe um resto escolhido pela graça."},
{"v":6,"t":"Se é pela graça, já não é pelas obras. Senão a graça não seria graça."},
{"v":7,"t":"E agora? Israel não conseguiu o que buscava. Mas os escolhidos conseguiram. Os outros foram endurecidos."},
{"v":8,"t":"Como está escrito: Deus lhes deu um espírito de torpor: olhos que não veem e ouvidos que não ouvem, até o dia de hoje."},
{"v":9,"t":"E Davi diz: Que a mesa deles se torne uma armadilha e uma rede, uma pedra de tropeço e uma retribuição para eles."},
{"v":10,"t":"Que os olhos deles fiquem escuros e não vejam. Que suas costas fiquem curvadas para sempre."},
{"v":11,"t":"Então pergunto: eles tropeçaram para cair de vez? De jeito nenhum! Pelo contrário, por causa da transgressão deles, a salvação chegou aos não judeus, para provocar inveja em Israel."},
{"v":12,"t":"Se a transgressão deles trouxe riqueza ao mundo e a derrota deles trouxe riqueza aos não judeus, imagine o que acontecerá quando o número completo deles for alcançado!"},
{"v":13,"t":"Falo a vocês, não judeus. Como apóstolo dos não judeus, dou valor ao meu trabalho."},
{"v":14,"t":"Talvez eu consiga provocar ciúme nos do meu povo e salvar alguns deles."},
{"v":15,"t":"Se a rejeição deles trouxe reconciliação ao mundo, o que será a aceitação deles senão vida dentre os mortos?"},
{"v":16,"t":"Se a primeira porção da massa é santa, toda a massa também é. Se a raiz é santa, os ramos também são."},
{"v":17,"t":"Se alguns dos ramos foram cortados e você, sendo oliveira silvestre, foi enxertado entre eles e passou a participar da raiz e da seiva da oliveira,"},
{"v":18,"t":"não se orgulhe contra os ramos. Se se orgulhar, lembre-se: não é você que sustenta a raiz. É a raiz que sustenta você."},
{"v":19,"t":"Você vai dizer: Os ramos foram cortados para que eu fosse enxertado."},
{"v":20,"t":"Isso é verdade. Eles foram cortados por falta de fé. E você está firme pela fé. Não se orgulhe, mas tenha temor."},
{"v":21,"t":"Se Deus não poupou os ramos naturais, também não vai poupar você."},
{"v":22,"t":"Observe a bondade e a severidade de Deus: severidade para os que caíram, mas bondade para você, se você permanecer na bondade dele. Senão, você também será cortado."},
{"v":23,"t":"E eles, se não persistirem na falta de fé, serão enxertados de volta. Deus tem poder para enxertá-los de novo."},
{"v":24,"t":"Se você foi cortado de uma oliveira silvestre e, contra a natureza, foi enxertado numa oliveira cultivada, quanto mais os ramos naturais serão enxertados de volta na sua própria oliveira!"},
{"v":25,"t":"Irmãos, não quero que vocês fiquem sem saber este mistério, para que não se achem sábios. Israel ficou parcialmente endurecido até que o número completo dos não judeus tenha entrado."},
{"v":26,"t":"E assim todo Israel será salvo. Como está escrito: O libertador virá de Sião. Ele removerá a falta de Deus de Jacó."},
{"v":27,"t":"Esta é a minha aliança com eles quando eu tirar os pecados deles."},
{"v":28,"t":"No que diz respeito à boa notícia, eles são inimigos por causa de vocês. Mas no que diz respeito à escolha, eles são amados por causa dos patriarcas."},
{"v":29,"t":"Porque os dons e o chamado de Deus são irrevogáveis."},
{"v":30,"t":"Assim como vocês um dia desobedeceram a Deus mas agora receberam misericórdia por causa da desobediência deles,"},
{"v":31,"t":"assim também eles agora desobedeceram para que, pela misericórdia que vocês receberam, eles também recebam misericórdia."},
{"v":32,"t":"Deus colocou todos debaixo da desobediência para ter misericórdia de todos."},
{"v":33,"t":"Oh, a profundidade da riqueza, da sabedoria e do conhecimento de Deus! Como são impossíveis de investigar os seus juízos e impossíveis de rastrear os seus caminhos!"},
{"v":34,"t":"Quem conheceu a mente do Senhor? Quem foi conselheiro dele?"},
{"v":35,"t":"Quem deu algo a ele primeiro para que lhe seja devolvido?"},
{"v":36,"t":"Porque dele, por ele e para ele são todas as coisas. A ele seja a glória para sempre! Amém."},
]})

# Chapter 12 - Living sacrifices, love in action
chapters.append({"c":12,"verses":[
{"v":1,"t":"Portanto, irmãos, pela misericórdia de Deus, eu peço que vocês ofereçam o corpo de vocês como sacrifício vivo, santo e agradável a Deus. Este é o culto que faz sentido."},
{"v":2,"t":"Não se adaptem ao padrão deste mundo. Sejam transformados pela renovação da mente de vocês. Assim poderão experimentar e aprovar a boa, agradável e perfeita vontade de Deus."},
{"v":3,"t":"Pela graça que me foi dada, digo a cada um de vocês: não pensem de si mesmos mais do que devem pensar. Pensem de forma equilibrada, conforme a medida de fé que Deus deu a cada um."},
{"v":4,"t":"Assim como num corpo temos muitas partes e nem todas têm a mesma função,"},
{"v":5,"t":"assim também nós, embora muitos, formamos um só corpo em Cristo. Cada um de nós é parte dos outros."},
{"v":6,"t":"Temos dons diferentes conforme a graça que nos foi dada. Se o dom é profecia, que seja conforme a proporção da fé."},
{"v":7,"t":"Se é servir, que sirva. Se é ensinar, que ensine."},
{"v":8,"t":"Se é encorajar, que encoraje. Quem contribui, que seja generoso. Quem lidera, que lidere com dedicação. Quem faz obras de misericórdia, que faça com alegria."},
{"v":9,"t":"O amor deve ser sincero. Odeiem o mal. Apeguem-se ao bem."},
{"v":10,"t":"Sejam carinhosos uns com os outros com amor fraterno. Deem preferência aos outros em honra."},
{"v":11,"t":"Não sejam preguiçosos na dedicação. Sejam fervorosos no espírito. Sirvam ao Senhor."},
{"v":12,"t":"Alegrem-se na esperança. Sejam pacientes no sofrimento. Perseverem na oração."},
{"v":13,"t":"Compartilhem com os santos que estão em necessidade. Pratiquem a hospitalidade."},
{"v":14,"t":"Abençoem os que perseguem vocês. Abençoem, não amaldiçoem."},
{"v":15,"t":"Alegrem-se com os que se alegram. Chorem com os que choram."},
{"v":16,"t":"Tenham a mesma atitude uns com os outros. Não sejam orgulhosos. Associem-se com pessoas humildes. Não se achem sábios."},
{"v":17,"t":"Não paguem o mal com o mal. Esforcem-se para fazer o que é correto aos olhos de todos."},
{"v":18,"t":"Se possível, no que depender de vocês, vivam em paz com todas as pessoas."},
{"v":19,"t":"Amados, não se vinguem. Deixem isso com a ira de Deus. Porque está escrito: A vingança é minha. Eu vou retribuir, diz o Senhor."},
{"v":20,"t":"Pelo contrário: Se o seu inimigo estiver com fome, dê comida a ele. Se estiver com sede, dê água. Fazendo isso, você colocará brasas de fogo sobre a cabeça dele."},
{"v":21,"t":"Não se deixe vencer pelo mal. Vença o mal com o bem."},
]})

# Chapter 13 - Submission to authorities, love fulfills the law
chapters.append({"c":13,"verses":[
{"v":1,"t":"Todas as pessoas devem se submeter às autoridades governamentais. Porque não existe autoridade que não venha de Deus. As que existem foram estabelecidas por Deus."},
{"v":2,"t":"Por isso, quem resiste à autoridade resiste ao que Deus estabeleceu. Os que resistem trazem condenação sobre si mesmos."},
{"v":3,"t":"Os governantes não são motivo de medo para quem faz o bem, mas para quem faz o mal. Você quer viver sem medo da autoridade? Faça o bem e ela vai elogiar você."},
{"v":4,"t":"A autoridade é serva de Deus para o seu bem. Mas se você fizer o mal, tenha medo. Ela não carrega a espada à toa. É serva de Deus para castigar quem faz o mal."},
{"v":5,"t":"Por isso é preciso se submeter, não apenas por causa do castigo, mas também por causa da consciência."},
{"v":6,"t":"Por isso vocês também pagam impostos. As autoridades são servas de Deus dedicadas a essa tarefa."},
{"v":7,"t":"Deem a cada um o que lhe é devido: imposto a quem se deve imposto, taxa a quem se deve taxa, respeito a quem se deve respeito, honra a quem se deve honra."},
{"v":8,"t":"Não devam nada a ninguém, a não ser o amor de uns pelos outros. Quem ama o próximo cumpriu a lei."},
{"v":9,"t":"Os mandamentos: Não cometa adultério, Não mate, Não roube, Não cobiçe, e qualquer outro mandamento, se resumem nesta palavra: Ame o seu próximo como a si mesmo."},
{"v":10,"t":"O amor não faz mal ao próximo. Portanto, o amor é o cumprimento da lei."},
{"v":11,"t":"Façam tudo isso sabendo em que tempo estamos. Já é hora de vocês acordarem do sono. A nossa salvação está mais perto agora do que quando cremos pela primeira vez."},
{"v":12,"t":"A noite está quase acabando. O dia está chegando. Por isso vamos deixar de lado as obras das trevas e vestir as armas da luz."},
{"v":13,"t":"Vamos viver decentemente como quem vive de dia. Nada de festas e bebedeiras, nem de imoralidade e libertinagem, nem de brigas e inveja."},
{"v":14,"t":"Vistam-se do Senhor Jesus Cristo. E não façam planos para satisfazer os desejos da natureza humana."},
]})

# Chapter 14 - The weak and the strong
chapters.append({"c":14,"verses":[
{"v":1,"t":"Aceitem quem é fraco na fé, sem discutir sobre opiniões."},
{"v":2,"t":"Um crê que pode comer de tudo. Outro, que é fraco, come só verduras."},
{"v":3,"t":"Quem come de tudo não deve desprezar quem não come. Quem não come não deve julgar quem come. Porque Deus o aceitou."},
{"v":4,"t":"Quem é você para julgar o servo dos outros? Ele fica de pé ou cai diante do seu próprio senhor. E ficará de pé, porque o Senhor tem poder para mantê-lo firme."},
{"v":5,"t":"Um considera um dia mais importante que outro. Outro considera todos os dias iguais. Cada um esteja convicto na própria mente."},
{"v":6,"t":"Quem observa um dia especial faz isso para o Senhor. Quem come de tudo faz isso para o Senhor, porque dá graças a Deus. Quem não come faz isso para o Senhor e também dá graças a Deus."},
{"v":7,"t":"Nenhum de nós vive para si mesmo. Nenhum de nós morre para si mesmo."},
{"v":8,"t":"Se vivemos, vivemos para o Senhor. Se morremos, morremos para o Senhor. Portanto, vivos ou mortos, pertencemos ao Senhor."},
{"v":9,"t":"Para isso Cristo morreu e ressuscitou: para ser Senhor tanto dos mortos como dos vivos."},
{"v":10,"t":"Você, por que julga o seu irmão? E você, por que despreza o seu irmão? Todos nós vamos comparecer diante do tribunal de Deus."},
{"v":11,"t":"Porque está escrito: Por minha vida, diz o Senhor, todo joelho se dobrará diante de mim e toda língua confessará a Deus."},
{"v":12,"t":"Portanto, cada um de nós prestará contas de si mesmo a Deus."},
{"v":13,"t":"Então vamos parar de julgar uns aos outros. Em vez disso, decidam não colocar pedra de tropeço ou obstáculo no caminho do irmão."},
{"v":14,"t":"Eu sei e estou convencido no Senhor Jesus de que nada é impuro por si mesmo. Mas se alguém considera algo impuro, para essa pessoa é impuro."},
{"v":15,"t":"Se o seu irmão fica triste por causa do que você come, você não está mais agindo com amor. Não destrua com a sua comida aquele por quem Cristo morreu."},
{"v":16,"t":"Não deixem que aquilo que é bom para vocês seja falado mal."},
{"v":17,"t":"Porque o Reino de Deus não é comida nem bebida. É justiça, paz e alegria no Espírito Santo."},
{"v":18,"t":"Quem serve a Cristo assim agrada a Deus e é aprovado pelas pessoas."},
{"v":19,"t":"Portanto, busquemos aquilo que promove a paz e a edificação uns dos outros."},
{"v":20,"t":"Não destrua a obra de Deus por causa de comida. Tudo é puro, mas é errado comer algo que faça o outro tropeçar."},
{"v":21,"t":"É melhor não comer carne, nem beber vinho, nem fazer qualquer coisa que faça o seu irmão tropeçar."},
{"v":22,"t":"A convicção que você tem, guarde-a para si mesmo diante de Deus. Feliz é quem não se condena naquilo que aprova."},
{"v":23,"t":"Mas quem tem dúvida é condenado se comer, porque não come com fé. E tudo o que não vem da fé é pecado."},
]})

# Chapter 15 - Unity, Paul's plans
chapters.append({"c":15,"verses":[
{"v":1,"t":"Nós que somos fortes devemos suportar as fraquezas dos fracos e não agradar a nós mesmos."},
{"v":2,"t":"Cada um de nós deve agradar ao próximo para o bem dele, para edificá-lo."},
{"v":3,"t":"Porque Cristo não agradou a si mesmo. Como está escrito: Os insultos dos que te insultavam caíram sobre mim."},
{"v":4,"t":"Tudo o que foi escrito no passado foi escrito para nos ensinar. As Escrituras nos dão perseverança e encorajamento para que tenhamos esperança."},
{"v":5,"t":"Que o Deus da perseverança e do encorajamento dê a vocês o mesmo modo de pensar uns com os outros, conforme Cristo Jesus."},
{"v":6,"t":"Para que juntos, com uma só voz, vocês glorifiquem ao Deus e Pai do nosso Senhor Jesus Cristo."},
{"v":7,"t":"Portanto, aceitem uns aos outros como Cristo aceitou vocês, para a glória de Deus."},
{"v":8,"t":"Eu digo que Cristo se tornou servo dos judeus por causa da verdade de Deus, para confirmar as promessas feitas aos patriarcas."},
{"v":9,"t":"E para que os não judeus glorifiquem a Deus pela sua misericórdia. Como está escrito: Por isso eu te louvarei entre as nações e cantarei ao teu nome."},
{"v":10,"t":"Também diz: Alegrem-se, nações, com o povo dele."},
{"v":11,"t":"E ainda: Louvem ao Senhor todas as nações. Todos os povos o exaltem."},
{"v":12,"t":"E Isaías diz: A raiz de Jessé brotará. Aquele que se levantará para governar as nações. Nele os não judeus colocarão a sua esperança."},
{"v":13,"t":"Que o Deus da esperança encha vocês de toda alegria e paz por crerem nele. Para que transbordem de esperança pelo poder do Espírito Santo."},
{"v":14,"t":"Irmãos, eu estou convencido de que vocês estão cheios de bondade, cheios de todo conhecimento e capazes de aconselhar uns aos outros."},
{"v":15,"t":"Mesmo assim, escrevi a vocês com certa ousadia em algumas partes, como quem está lembrando. Fiz isso pela graça que Deus me deu"},
{"v":16,"t":"de ser ministro de Cristo Jesus para os não judeus. Tenho o dever sagrado de anunciar a boa notícia de Deus, para que os não judeus sejam uma oferta agradável, santificada pelo Espírito Santo."},
{"v":17,"t":"Portanto, em Cristo Jesus eu tenho motivo para me orgulhar do meu trabalho para Deus."},
{"v":18,"t":"Não vou me atrever a falar de nada além do que Cristo realizou por meu meio para levar os não judeus a obedecer. Isso aconteceu por palavras e ações,"},
{"v":19,"t":"pelo poder de sinais e maravilhas, pelo poder do Espírito de Deus. Assim, desde Jerusalém e arredores até o Ilírico, completei a pregação da boa notícia de Cristo."},
{"v":20,"t":"Minha ambição sempre foi pregar a boa notícia onde Cristo ainda não tinha sido anunciado. Não queria construir sobre o fundamento de outro."},
{"v":21,"t":"Como está escrito: Aqueles a quem não foi anunciado o verão. Aqueles que não ouviram vão entender."},
{"v":22,"t":"É por isso que muitas vezes fui impedido de ir até vocês."},
{"v":23,"t":"Mas agora não tenho mais lugar para trabalhar nestas regiões. E há muitos anos desejo visitá-los."},
{"v":24,"t":"Espero vê-los quando for para a Espanha. De passagem, desejo aproveitar a companhia de vocês por algum tempo, depois que tiver matado um pouco a saudade."},
{"v":25,"t":"Mas agora estou indo a Jerusalém para levar ajuda aos santos."},
{"v":26,"t":"A Macedônia e a Acaia tiveram prazer em fazer uma contribuição para os santos pobres de Jerusalém."},
{"v":27,"t":"Tiveram prazer em fazer isso, e de fato têm essa dívida. Se os não judeus participaram das bênçãos espirituais dos judeus, devem também servi-los com bênçãos materiais."},
{"v":28,"t":"Depois que eu completar essa tarefa e entregar o resultado dessa contribuição, irei para a Espanha passando por vocês."},
{"v":29,"t":"Eu sei que, quando for visitá-los, irei com a plenitude da bênção de Cristo."},
{"v":30,"t":"Irmãos, eu peço a vocês, pelo nosso Senhor Jesus Cristo e pelo amor do Espírito, que lutem comigo em oração a Deus por mim."},
{"v":31,"t":"Orem para que eu seja livrado dos que na Judeia não creem. E para que o meu serviço em Jerusalém seja bem recebido pelos santos."},
{"v":32,"t":"Assim, pela vontade de Deus, eu irei até vocês com alegria e descansarei na companhia de vocês."},
{"v":33,"t":"O Deus da paz esteja com todos vocês. Amém."},
]})

# Chapter 16 - Greetings and final words
chapters.append({"c":16,"verses":[
{"v":1,"t":"Eu recomendo a vocês a nossa irmã Febe, que é serva da igreja em Cencreia."},
{"v":2,"t":"Recebam-na no Senhor como convém aos santos. Ajudem-na no que ela precisar, porque ela tem sido uma grande ajuda para muitos, inclusive para mim."},
{"v":3,"t":"Cumprimentem Priscila e Áquila, meus companheiros de trabalho em Cristo Jesus."},
{"v":4,"t":"Eles arriscaram a própria vida por mim. Não só eu, mas todas as igrejas dos não judeus são gratas a eles."},
{"v":5,"t":"Cumprimentem também a igreja que se reúne na casa deles. Cumprimentem meu querido Epêneto, que foi o primeiro convertido a Cristo na Ásia."},
{"v":6,"t":"Cumprimentem Maria, que trabalhou muito por vocês."},
{"v":7,"t":"Cumprimentem Andrônico e Júnia, meus parentes e companheiros de prisão. Eles são conhecidos entre os apóstolos e estiveram em Cristo antes de mim."},
{"v":8,"t":"Cumprimentem Amplíato, meu amado no Senhor."},
{"v":9,"t":"Cumprimentem Urbano, nosso companheiro de trabalho em Cristo, e meu querido Estáquis."},
{"v":10,"t":"Cumprimentem Apeles, aprovado em Cristo. Cumprimentem os da família de Aristóbulo."},
{"v":11,"t":"Cumprimentem Herodião, meu parente. Cumprimentem os da família de Narciso que estão no Senhor."},
{"v":12,"t":"Cumprimentem Trifena e Trifosa, que trabalham no Senhor. Cumprimentem a querida Pérside, que trabalhou muito no Senhor."},
{"v":13,"t":"Cumprimentem Rufo, escolhido no Senhor, e a mãe dele, que é como mãe para mim também."},
{"v":14,"t":"Cumprimentem Asíncrito, Flegonte, Hermes, Pátrobas, Hermas e os irmãos que estão com eles."},
{"v":15,"t":"Cumprimentem Filólogo, Júlia, Nereu e a irmã dele, Olimpas e todos os santos que estão com eles."},
{"v":16,"t":"Cumprimentem uns aos outros com um beijo santo. Todas as igrejas de Cristo enviam saudações."},
{"v":17,"t":"Irmãos, eu peço que fiquem atentos aos que provocam divisões e escândalos contra o ensino que vocês receberam. Afastem-se deles."},
{"v":18,"t":"Esse tipo de gente não serve ao nosso Senhor Cristo, mas aos seus próprios desejos. Com palavras bonitas e elogios enganam os corações dos ingênuos."},
{"v":19,"t":"A obediência de vocês é conhecida por todos. Por isso eu me alegro por vocês. Quero que vocês sejam sábios para o bem e inocentes para o mal."},
{"v":20,"t":"O Deus da paz em breve esmagará Satanás debaixo dos pés de vocês. A graça do nosso Senhor Jesus esteja com vocês."},
{"v":21,"t":"Timóteo, meu companheiro de trabalho, envia saudações. E também Lúcio, Jasão e Sosípatro, meus parentes."},
{"v":22,"t":"Eu, Tércio, que escrevi esta carta, envio saudações no Senhor."},
{"v":23,"t":"Gaio, que me hospeda e hospeda toda a igreja, envia saudações. Erasto, tesoureiro da cidade, e o irmão Quarto enviam saudações."},
{"v":24,"t":"A graça do nosso Senhor Jesus Cristo esteja com todos vocês. Amém."},
{"v":25,"t":"Glória àquele que tem poder para fortalecer vocês conforme a minha boa notícia e a pregação de Jesus Cristo. Conforme a revelação do mistério guardado em silêncio por tempos eternos,"},
{"v":26,"t":"mas agora revelado e dado a conhecer por meio dos escritos dos profetas. Por ordem do Deus eterno, para que todas as nações creiam e obedeçam."},
{"v":27,"t":"Ao único Deus sábio seja a glória para sempre por meio de Jesus Cristo! Amém."},
]})

# Save chapters 9-16
with open('v:/GitHub/orgs/devzolo/bible/static/data/bfl/romanos_trans_part2.json', 'w', encoding='utf-8') as f:
    json.dump(chapters, f, ensure_ascii=False)
print(f"Saved chapters 9-{chapters[-1]['c']}, total verses: {sum(len(c['verses']) for c in chapters)}")
