#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""BFL Translation of Acts (Atos) - All 28 chapters"""
import json
import os

chapters = []

# Chapter 1 - The Ascension and Matthias
chapters.append({"c":1,"verses":[
{"v":1,"t":"No meu primeiro livro, Teófilo, eu escrevi sobre tudo o que Jesus fez e ensinou desde o começo."},
{"v":2,"t":"Escrevi até o dia em que ele subiu ao céu. Antes disso, pelo Espírito Santo, ele deu instruções aos apóstolos que tinha escolhido."},
{"v":3,"t":"Depois de sofrer e morrer, Jesus se mostrou vivo a eles. Durante quarenta dias, apareceu muitas vezes e deu provas claras de que estava vivo. Ele falou sobre o Reino de Deus."},
{"v":4,"t":"Certa vez, enquanto comia com eles, Jesus ordenou: Não saiam de Jerusalém. Esperem o presente que o Pai prometeu, aquele que eu já mencionei a vocês."},
{"v":5,"t":"João batizou com água, mas dentro de poucos dias vocês serão batizados com o Espírito Santo."},
{"v":6,"t":"Então os que estavam reunidos perguntaram: Senhor, é agora que o senhor vai restaurar o reino de Israel?"},
{"v":7,"t":"Jesus respondeu: Não cabe a vocês saber os tempos ou as datas que o Pai determinou pela sua própria autoridade."},
{"v":8,"t":"Mas vocês receberão poder quando o Espírito Santo descer sobre vocês. E serão minhas testemunhas em Jerusalém, em toda a Judeia, em Samaria e até os lugares mais distantes da terra."},
{"v":9,"t":"Depois de dizer isso, Jesus foi levantado para o alto diante dos olhos deles. Uma nuvem o cobriu e eles não conseguiram mais vê-lo."},
{"v":10,"t":"Enquanto olhavam fixo para o céu, dois homens vestidos de branco apareceram ao lado deles."},
{"v":11,"t":"Eles disseram: Homens da Galileia, por que ficam olhando para o céu? Esse mesmo Jesus que subiu ao céu vai voltar da mesma forma como vocês o viram subir."},
{"v":12,"t":"Então voltaram para Jerusalém. O Monte das Oliveiras, de onde eles estavam, fica perto de Jerusalém, a uma curta caminhada."},
{"v":13,"t":"Quando chegaram, subiram para o andar de cima onde estavam hospedados. Estavam lá Pedro, Tiago, João, André, Filipe, Tomé, Bartolomeu, Mateus, Tiago filho de Alfeu, Simão o Zelote e Judas filho de Tiago."},
{"v":14,"t":"Todos eles se reuniam sempre para orar juntos. As mulheres também estavam lá, junto com Maria, mãe de Jesus, e os irmãos dele."},
{"v":15,"t":"Naqueles dias, Pedro se levantou no meio dos irmãos. Havia ali cerca de cento e vinte pessoas reunidas. Ele disse:"},
{"v":16,"t":"Irmãos, era preciso que se cumprisse o que o Espírito Santo anunciou pela boca de Davi nas Escrituras. Ele falou sobre Judas, que serviu de guia para os que prenderam Jesus."},
{"v":17,"t":"Judas fazia parte do nosso grupo e tinha sua parte neste trabalho."},
{"v":18,"t":"Com o dinheiro que recebeu pelo seu ato mau, Judas comprou um terreno. Lá ele caiu de cabeça e seu corpo se abriu ao meio. Suas entranhas se espalharam pelo chão."},
{"v":19,"t":"Todos em Jerusalém ficaram sabendo disso. Por isso chamaram aquele terreno de Aceldama, que na língua deles quer dizer Campo de Sangue."},
{"v":20,"t":"Porque está escrito no livro dos Salmos: Que a casa dele fique vazia e ninguém more nela. E também: Que outro tome o lugar dele na liderança."},
{"v":21,"t":"Por isso, precisamos escolher alguém que esteve conosco durante todo o tempo em que o Senhor Jesus andou entre nós."},
{"v":22,"t":"Desde o batismo de João até o dia em que Jesus subiu ao céu. Essa pessoa será testemunha da ressurreição dele junto conosco."},
{"v":23,"t":"Então indicaram dois nomes: José, chamado Barsabás, que tinha o apelido de Justo, e Matias."},
{"v":24,"t":"E oraram assim: Senhor, tu conheces o coração de todos. Mostra qual destes dois tu escolheste"},
{"v":25,"t":"para ocupar este lugar de apóstolo, do qual Judas se afastou para ir ao lugar que merecia."},
{"v":26,"t":"Então tiraram a sorte, e a escolha caiu sobre Matias. Ele foi incluído no grupo dos onze apóstolos."},
]})

# Chapter 2 - Pentecost
chapters.append({"c":2,"verses":[
{"v":1,"t":"Quando chegou o dia de Pentecostes, todos estavam reunidos no mesmo lugar."},
{"v":2,"t":"De repente, veio do céu um som parecido com um vento muito forte. O som encheu toda a casa onde estavam sentados."},
{"v":3,"t":"Eles viram algo que parecia línguas de fogo. Essas línguas se separaram e pousaram sobre cada um deles."},
{"v":4,"t":"Todos ficaram cheios do Espírito Santo e começaram a falar em outras línguas. O Espírito Santo é que dava a eles essa capacidade."},
{"v":5,"t":"Naquela época, moravam em Jerusalém judeus devotos de todas as nações do mundo."},
{"v":6,"t":"Quando ouviram aquele som, uma grande multidão se juntou. Ficaram todos confusos porque cada um ouvia os apóstolos falando na sua própria língua."},
{"v":7,"t":"Espantados e admirados, diziam: Esses homens que estão falando não são todos da Galileia?"},
{"v":8,"t":"Como é que cada um de nós os ouve na língua em que nascemos?"},
{"v":9,"t":"Partos, medos, elamitas, gente da Mesopotâmia, da Judeia, da Capadócia, do Ponto e da Ásia,"},
{"v":10,"t":"da Frígia, da Panfília, do Egito e das regiões da Líbia perto de Cirene. Também romanos que moram aqui,"},
{"v":11,"t":"tanto judeus de nascimento como convertidos, cretenses e árabes. Todos nós os ouvimos falar das maravilhas de Deus na nossa própria língua!"},
{"v":12,"t":"Todos ficavam admirados e sem entender. Perguntavam uns aos outros: O que será que isso quer dizer?"},
{"v":13,"t":"Mas outros zombavam e diziam: Eles estão bêbados!"},
{"v":14,"t":"Então Pedro se levantou junto com os outros onze apóstolos. Em voz alta, ele disse: Homens da Judeia e todos que moram em Jerusalém, prestem atenção no que eu vou dizer!"},
{"v":15,"t":"Estes homens não estão bêbados como vocês pensam. São apenas nove horas da manhã!"},
{"v":16,"t":"O que está acontecendo é o que o profeta Joel anunciou:"},
{"v":17,"t":"Deus disse: Nos últimos dias, eu derramarei o meu Espírito sobre todas as pessoas. Os filhos e as filhas de vocês vão profetizar. Os jovens terão visões e os idosos terão sonhos."},
{"v":18,"t":"Naqueles dias, eu derramarei o meu Espírito até sobre os meus servos e servas. E eles profetizarão."},
{"v":19,"t":"Farei coisas impressionantes no céu e sinais na terra: sangue, fogo e nuvens de fumaça."},
{"v":20,"t":"O sol ficará escuro e a lua ficará vermelha como sangue, antes que chegue o grande e glorioso dia do Senhor."},
{"v":21,"t":"E todo aquele que pedir ajuda ao Senhor será salvo."},
{"v":22,"t":"Israelitas, ouçam: Jesus de Nazaré foi aprovado por Deus entre vocês. Deus fez milagres, maravilhas e sinais por meio dele no meio de vocês. Vocês mesmos sabem disso."},
{"v":23,"t":"Jesus foi entregue a vocês pelo plano que Deus já tinha definido. E vocês, com a ajuda de homens maus, o pregaram na cruz e o mataram."},
{"v":24,"t":"Mas Deus o ressuscitou! Ele o libertou das dores da morte porque era impossível que a morte o segurasse."},
{"v":25,"t":"Davi disse sobre ele: Eu sempre via o Senhor diante de mim. Ele está ao meu lado direito para que eu não seja abalado."},
{"v":26,"t":"Por isso meu coração ficou alegre e minha boca cantou de alegria. Meu corpo também vai descansar com esperança."},
{"v":27,"t":"Porque tu não deixarás minha alma no mundo dos mortos. Não permitirás que o teu Santo apodreça no túmulo."},
{"v":28,"t":"Tu me mostraste o caminho da vida. A tua presença me encheu de alegria."},
{"v":29,"t":"Irmãos, posso dizer com toda a franqueza que Davi morreu e foi sepultado. O túmulo dele está entre nós até hoje."},
{"v":30,"t":"Mas Davi era profeta. Ele sabia que Deus tinha prometido com juramento que um dos seus descendentes se sentaria no seu trono."},
{"v":31,"t":"Davi viu o futuro e falou da ressurreição do Cristo. Disse que ele não seria abandonado no mundo dos mortos e que seu corpo não apodreceria."},
{"v":32,"t":"Deus ressuscitou esse Jesus! E todos nós somos testemunhas disso."},
{"v":33,"t":"Jesus foi exaltado ao lugar de honra, ao lado direito de Deus. Ele recebeu do Pai o Espírito Santo prometido e derramou o que vocês estão vendo e ouvindo."},
{"v":34,"t":"Davi não subiu ao céu, mas ele mesmo disse: O Senhor disse ao meu Senhor: Sente-se ao meu lado direito,"},
{"v":35,"t":"até que eu ponha os seus inimigos debaixo dos seus pés."},
{"v":36,"t":"Portanto, que todo o povo de Israel saiba com certeza: Deus fez desse Jesus, que vocês crucificaram, tanto Senhor como Cristo!"},
{"v":37,"t":"Quando ouviram isso, ficaram com o coração partido. Perguntaram a Pedro e aos outros apóstolos: Irmãos, o que devemos fazer?"},
{"v":38,"t":"Pedro respondeu: Arrependam-se e cada um de vocês seja batizado em nome de Jesus Cristo para o perdão dos pecados. Então vocês receberão o presente do Espírito Santo."},
{"v":39,"t":"Porque essa promessa é para vocês, para os filhos de vocês e para todos os que estão longe. É para todos os que o Senhor nosso Deus chamar."},
{"v":40,"t":"Com muitas outras palavras, Pedro insistia e encorajava dizendo: Salvem-se desta geração corrompida!"},
{"v":41,"t":"Os que aceitaram a mensagem foram batizados. Naquele dia, cerca de três mil pessoas se juntaram ao grupo."},
{"v":42,"t":"Eles se dedicavam ao ensino dos apóstolos, à comunhão, ao partir do pão e às orações."},
{"v":43,"t":"Todos ficavam admirados porque os apóstolos faziam muitos milagres e sinais."},
{"v":44,"t":"Todos os que criam ficavam juntos e compartilhavam tudo o que tinham."},
{"v":45,"t":"Vendiam suas propriedades e seus bens. Depois dividiam o dinheiro com todos, conforme a necessidade de cada um."},
{"v":46,"t":"Todos os dias se reuniam no templo com o mesmo propósito. Partiam o pão nas casas e faziam as refeições juntos, com alegria e sinceridade no coração."},
{"v":47,"t":"Louvavam a Deus e todo o povo gostava deles. E todos os dias o Senhor acrescentava ao grupo os que iam sendo salvos."},
]})

# Chapter 3 - Healing at the temple
chapters.append({"c":3,"verses":[
{"v":1,"t":"Um dia, Pedro e João subiram ao templo na hora da oração, às três da tarde."},
{"v":2,"t":"Na porta do templo chamada Formosa, havia um homem que não podia andar desde que nasceu. Todos os dias ele era carregado até ali para pedir esmola."},
{"v":3,"t":"Quando viu Pedro e João entrando no templo, ele pediu uma esmola."},
{"v":4,"t":"Pedro olhou firme para ele, junto com João, e disse: Olhe para nós."},
{"v":5,"t":"O homem olhou para eles esperando receber algum dinheiro."},
{"v":6,"t":"Pedro disse: Eu não tenho prata nem ouro. Mas o que eu tenho, isso eu dou a você. Em nome de Jesus Cristo de Nazaré, levante-se e ande!"},
{"v":7,"t":"Pedro pegou a mão direita dele e o ajudou a levantar. Na mesma hora, os pés e os tornozelos dele ficaram firmes."},
{"v":8,"t":"O homem deu um pulo, ficou de pé e começou a andar! Entrou no templo com eles, andando, pulando e louvando a Deus."},
{"v":9,"t":"Todo o povo o viu andando e louvando a Deus."},
{"v":10,"t":"Reconheceram que era ele mesmo que ficava sentado pedindo esmola na porta Formosa do templo. Ficaram cheios de espanto com o que aconteceu."},
{"v":11,"t":"O homem curado não largava Pedro e João. Todo o povo correu até eles no local chamado Pórtico de Salomão. Estavam todos impressionados."},
{"v":12,"t":"Quando Pedro viu isso, disse ao povo: Israelitas, por que vocês ficam tão espantados? Por que olham para nós como se tivéssemos feito esse homem andar pelo nosso próprio poder ou santidade?"},
{"v":13,"t":"O Deus de Abraão, Isaque e Jacó, o Deus dos nossos antepassados, deu glória ao seu servo Jesus. Vocês o entregaram e o rejeitaram diante de Pilatos, quando ele queria soltá-lo."},
{"v":14,"t":"Vocês rejeitaram o Santo e Justo. Em vez dele, pediram que soltassem um assassino."},
{"v":15,"t":"Vocês mataram aquele que é o Autor da vida! Mas Deus o ressuscitou dos mortos. Nós somos testemunhas disso."},
{"v":16,"t":"É pela fé no nome de Jesus que este homem, que vocês veem e conhecem, ficou forte. A fé que vem por meio de Jesus deu a ele saúde completa, como todos podem ver."},
{"v":17,"t":"Irmãos, eu sei que vocês agiram por ignorância, assim como os líderes de vocês."},
{"v":18,"t":"Mas foi assim que Deus cumpriu o que já tinha anunciado por todos os profetas: que o Cristo haveria de sofrer."},
{"v":19,"t":"Portanto, arrependam-se e voltem para Deus. Assim os pecados de vocês serão apagados e virão tempos de renovação da parte do Senhor."},
{"v":20,"t":"E ele enviará Jesus, o Cristo que já foi designado para vocês."},
{"v":21,"t":"É preciso que o céu o receba até o tempo em que Deus restaurar todas as coisas. Deus falou sobre isso pela boca dos seus santos profetas desde o começo."},
{"v":22,"t":"Moisés disse: O Senhor Deus de vocês vai levantar um profeta como eu dentre o povo de vocês. Obedeçam a tudo o que ele disser."},
{"v":23,"t":"E todo aquele que não ouvir esse profeta será eliminado do meio do povo."},
{"v":24,"t":"De fato, todos os profetas desde Samuel em diante falaram sobre estes dias."},
{"v":25,"t":"Vocês são herdeiros dos profetas e da aliança que Deus fez com nossos antepassados. Deus disse a Abraão: Por meio da sua descendência, todas as famílias da terra serão abençoadas."},
{"v":26,"t":"Deus ressuscitou o seu servo Jesus e o enviou primeiro a vocês. Ele fez isso para abençoar vocês, fazendo cada um se afastar das suas maldades."},
]})

# Chapter 4 - Peter and John before the council
chapters.append({"c":4,"verses":[
{"v":1,"t":"Enquanto Pedro e João falavam ao povo, chegaram os sacerdotes, o capitão do templo e os saduceus."},
{"v":2,"t":"Eles ficaram muito irritados porque Pedro e João ensinavam o povo e anunciavam que Jesus ressuscitou dos mortos."},
{"v":3,"t":"Prenderam os dois e os colocaram na cadeia até o dia seguinte, porque já era tarde."},
{"v":4,"t":"Mas muitos dos que ouviram a mensagem creram. O número de homens que creram chegou a cerca de cinco mil."},
{"v":5,"t":"No dia seguinte, os líderes, os anciãos e os mestres da lei se reuniram em Jerusalém."},
{"v":6,"t":"O sumo sacerdote Anás estava lá, junto com Caifás, João, Alexandre e outros da família do sumo sacerdote."},
{"v":7,"t":"Colocaram Pedro e João diante deles e perguntaram: Com que poder ou em nome de quem vocês fizeram isso?"},
{"v":8,"t":"Então Pedro, cheio do Espírito Santo, respondeu: Líderes do povo e anciãos de Israel,"},
{"v":9,"t":"se hoje estamos sendo interrogados por causa de uma boa ação feita a um homem doente, e querem saber como ele foi curado,"},
{"v":10,"t":"saibam todos vocês e todo o povo de Israel: foi pelo nome de Jesus Cristo de Nazaré que este homem está curado diante de vocês. Vocês crucificaram Jesus, mas Deus o ressuscitou dos mortos."},
{"v":11,"t":"Jesus é a pedra que vocês, os construtores, rejeitaram. Mas ela se tornou a pedra principal da construção."},
{"v":12,"t":"Não existe salvação em nenhum outro. Porque em todo o mundo não há outro nome dado aos seres humanos pelo qual possamos ser salvos."},
{"v":13,"t":"Quando viram a coragem de Pedro e João e descobriram que eram homens simples e sem estudo, ficaram surpresos. Perceberam que eles tinham estado com Jesus."},
{"v":14,"t":"Como viram o homem curado ali de pé com eles, não tinham nada para argumentar contra."},
{"v":15,"t":"Então mandaram que eles saíssem do tribunal e começaram a discutir entre si."},
{"v":16,"t":"Diziam: O que vamos fazer com esses homens? Todos em Jerusalém sabem que eles fizeram um milagre impressionante. Não podemos negar isso."},
{"v":17,"t":"Mas para que isso não se espalhe mais entre o povo, vamos ameaçá-los para que não falem mais em nome de Jesus a ninguém."},
{"v":18,"t":"Chamaram os dois de volta e ordenaram que não falassem nem ensinassem mais em nome de Jesus."},
{"v":19,"t":"Mas Pedro e João responderam: Julguem vocês mesmos se é justo diante de Deus obedecer a vocês em vez de obedecer a Deus."},
{"v":20,"t":"Nós não podemos deixar de falar sobre o que vimos e ouvimos."},
{"v":21,"t":"Depois de mais ameaças, soltaram os dois. Não acharam um jeito de castigá-los porque todo o povo louvava a Deus pelo que aconteceu."},
{"v":22,"t":"O homem que foi curado por esse milagre tinha mais de quarenta anos."},
{"v":23,"t":"Depois de soltos, Pedro e João voltaram para o grupo e contaram tudo o que os líderes dos sacerdotes e os anciãos disseram."},
{"v":24,"t":"Quando ouviram, todos juntos levantaram a voz a Deus e disseram: Senhor, tu criaste o céu, a terra, o mar e tudo o que existe neles."},
{"v":25,"t":"Tu disseste pelo Espírito Santo, por meio do teu servo Davi: Por que as nações se agitaram? Por que os povos fizeram planos inúteis?"},
{"v":26,"t":"Os reis da terra se uniram e os governantes se juntaram contra o Senhor e contra o seu Ungido."},
{"v":27,"t":"De fato, Herodes e Pôncio Pilatos se uniram com os não judeus e o povo de Israel nesta cidade contra o teu santo servo Jesus, a quem tu ungiste."},
{"v":28,"t":"Eles fizeram tudo o que tu, pelo teu poder e pela tua vontade, já tinhas decidido que aconteceria."},
{"v":29,"t":"Agora, Senhor, olha para as ameaças deles. Dá aos teus servos coragem para anunciar a tua palavra com ousadia."},
{"v":30,"t":"Estende a tua mão para curar e para que aconteçam sinais e maravilhas pelo nome do teu santo servo Jesus."},
{"v":31,"t":"Depois que oraram, o lugar onde estavam reunidos tremeu. Todos ficaram cheios do Espírito Santo e anunciavam a palavra de Deus com coragem."},
{"v":32,"t":"Os que creram tinham um só coração e uma só mente. Ninguém dizia que algo do que tinha era só seu. Eles dividiam tudo."},
{"v":33,"t":"Os apóstolos davam testemunho da ressurreição do Senhor Jesus com grande poder. E a graça de Deus estava sobre todos eles."},
{"v":34,"t":"Não havia ninguém passando necessidade entre eles. Quem tinha terras ou casas vendia e trazia o dinheiro."},
{"v":35,"t":"Colocavam o dinheiro aos pés dos apóstolos. Depois era distribuído a cada um conforme a necessidade."},
{"v":36,"t":"José, um levita de Chipre, foi chamado pelos apóstolos de Barnabé, que quer dizer Filho da Consolação."},
{"v":37,"t":"Ele vendeu um terreno que tinha, trouxe o dinheiro e colocou aos pés dos apóstolos."},
]})

# Chapter 5 - Ananias and Sapphira
chapters.append({"c":5,"verses":[
{"v":1,"t":"Um homem chamado Ananias, junto com sua esposa Safira, vendeu uma propriedade."},
{"v":2,"t":"Ele ficou com parte do dinheiro. Sua esposa sabia disso. Depois levou o resto e colocou aos pés dos apóstolos."},
{"v":3,"t":"Pedro disse: Ananias, por que você deixou Satanás encher o seu coração? Você mentiu ao Espírito Santo e ficou com parte do dinheiro da venda do terreno."},
{"v":4,"t":"Antes de vender, o terreno não era seu? E depois de vender, o dinheiro não era seu? Por que você planejou fazer isso? Você não mentiu a pessoas, mas a Deus!"},
{"v":5,"t":"Quando ouviu isso, Ananias caiu no chão e morreu. Um grande medo tomou conta de todos que ouviram."},
{"v":6,"t":"Os jovens se levantaram, cobriram o corpo, levaram para fora e o sepultaram."},
{"v":7,"t":"Cerca de três horas depois, a esposa dele chegou. Ela não sabia o que tinha acontecido."},
{"v":8,"t":"Pedro perguntou: Me diga, vocês venderam o terreno por esse valor? Ela respondeu: Sim, foi por esse valor."},
{"v":9,"t":"Pedro disse a ela: Por que vocês combinaram de testar o Espírito do Senhor? Olhe! Os mesmos jovens que sepultaram o seu marido estão na porta e vão levar você também."},
{"v":10,"t":"Na mesma hora ela caiu aos pés de Pedro e morreu. Os jovens entraram e a encontraram morta. Levaram-na e a sepultaram ao lado do marido."},
{"v":11,"t":"Um grande medo tomou conta de toda a igreja e de todos que ouviram essas coisas."},
{"v":12,"t":"Os apóstolos faziam muitos milagres e sinais no meio do povo. Todos se reuniam no Pórtico de Salomão."},
{"v":13,"t":"Ninguém de fora ousava se juntar a eles. Mas o povo os respeitava muito."},
{"v":14,"t":"Cada vez mais homens e mulheres criam no Senhor e se juntavam ao grupo."},
{"v":15,"t":"As pessoas chegavam a colocar os doentes nas ruas, em camas e esteiras. Faziam isso para que pelo menos a sombra de Pedro caísse sobre algum deles quando passasse."},
{"v":16,"t":"Multidões vinham das cidades vizinhas de Jerusalém. Traziam doentes e pessoas atormentadas por espíritos maus. Todos eram curados."},
{"v":17,"t":"O sumo sacerdote e todos os que estavam com ele, do grupo dos saduceus, ficaram cheios de inveja."},
{"v":18,"t":"Prenderam os apóstolos e os colocaram na cadeia pública."},
{"v":19,"t":"Mas durante a noite, um anjo do Senhor abriu as portas da prisão e os tirou de lá."},
{"v":20,"t":"O anjo disse: Vão ao templo e anunciem ao povo toda esta mensagem de vida."},
{"v":21,"t":"Eles obedeceram e entraram no templo de manhã cedo para ensinar. Quando o sumo sacerdote e seus companheiros chegaram, reuniram o tribunal e todos os líderes de Israel. Mandaram buscar os apóstolos na prisão."},
{"v":22,"t":"Mas quando os guardas chegaram lá, não os encontraram na prisão. Voltaram e informaram:"},
{"v":23,"t":"A prisão estava bem trancada e os guardas estavam na porta. Mas quando abrimos, não encontramos ninguém lá dentro!"},
{"v":24,"t":"O capitão do templo e os chefes dos sacerdotes ficaram sem entender. Não sabiam o que pensar sobre aquilo."},
{"v":25,"t":"Então alguém chegou e avisou: Os homens que vocês prenderam estão no templo ensinando o povo!"},
{"v":26,"t":"O capitão foi com seus guardas e trouxe os apóstolos sem usar violência, porque tinham medo de que o povo os apedrejasse."},
{"v":27,"t":"Levaram os apóstolos diante do tribunal. O sumo sacerdote os interrogou:"},
{"v":28,"t":"Nós demos ordem expressa para que vocês não ensinassem em nome de Jesus! Mas vocês encheram Jerusalém com esse ensino e querem nos culpar pela morte desse homem!"},
{"v":29,"t":"Pedro e os apóstolos responderam: É preciso obedecer a Deus em primeiro lugar, e não a seres humanos."},
{"v":30,"t":"O Deus dos nossos antepassados ressuscitou Jesus, que vocês mataram pregando-o numa cruz."},
{"v":31,"t":"Deus o exaltou ao lugar mais alto como Líder e Salvador. Ele fez isso para dar a Israel a chance de se arrepender e receber o perdão dos pecados."},
{"v":32,"t":"Nós somos testemunhas dessas coisas, e também o Espírito Santo, que Deus deu a todos os que obedecem a ele."},
{"v":33,"t":"Quando ouviram isso, ficaram furiosos e queriam matar os apóstolos."},
{"v":34,"t":"Mas um fariseu chamado Gamaliel se levantou no tribunal. Ele era mestre da lei e respeitado por todo o povo. Pediu que os apóstolos saíssem por um momento."},
{"v":35,"t":"Então disse: Israelitas, tomem cuidado com o que pretendem fazer a esses homens."},
{"v":36,"t":"Algum tempo atrás, apareceu Teudas dizendo que era alguém importante. Cerca de quatrocentos homens se juntaram a ele. Mas ele foi morto e todos os seus seguidores se espalharam. Tudo acabou em nada."},
{"v":37,"t":"Depois dele, apareceu Judas, o galileu, na época do recenseamento. Ele também reuniu muita gente. Mas também morreu e seus seguidores se espalharam."},
{"v":38,"t":"Por isso eu aconselho: não se metam com esses homens. Deixem-nos em paz. Se esse plano ou essa obra é de seres humanos, vai acabar sozinha."},
{"v":39,"t":"Mas se é de Deus, vocês não vão conseguir destruí-la. Cuidado para não acabarem lutando contra o próprio Deus!"},
{"v":40,"t":"Eles concordaram com Gamaliel. Chamaram os apóstolos, mandaram açoitá-los, ordenaram que não falassem mais em nome de Jesus, e os soltaram."},
{"v":41,"t":"Os apóstolos saíram do tribunal cheios de alegria por terem sido considerados dignos de sofrer por causa do nome de Jesus."},
{"v":42,"t":"E todos os dias, no templo e nas casas, não paravam de ensinar e anunciar que Jesus é o Cristo."},
]})

# Chapter 6 - The Seven Chosen
chapters.append({"c":6,"verses":[
{"v":1,"t":"Naqueles dias, o número de seguidores crescia muito. Os judeus de língua grega começaram a reclamar dos judeus de língua hebraica. Diziam que suas viúvas estavam sendo esquecidas na distribuição diária de alimentos."},
{"v":2,"t":"Os doze apóstolos reuniram todo o grupo e disseram: Não é certo que nós deixemos de pregar a palavra de Deus para cuidar da distribuição de alimentos."},
{"v":3,"t":"Irmãos, escolham sete homens entre vocês. Eles devem ter boa reputação, ser cheios do Espírito Santo e de sabedoria. Nós os colocaremos para cuidar dessa tarefa."},
{"v":4,"t":"Assim nós poderemos nos dedicar à oração e ao ensino da palavra de Deus."},
{"v":5,"t":"Todos gostaram da ideia. Então escolheram Estêvão, homem cheio de fé e do Espírito Santo, Filipe, Prócoro, Nicanor, Timão, Pármenas e Nicolau, um convertido de Antioquia."},
{"v":6,"t":"Apresentaram esses homens aos apóstolos. Eles oraram e impuseram as mãos sobre eles."},
{"v":7,"t":"A palavra de Deus se espalhava. O número de seguidores em Jerusalém crescia muito. Até muitos sacerdotes passaram a crer."},
{"v":8,"t":"Estêvão, cheio de graça e de poder, fazia grandes maravilhas e sinais no meio do povo."},
{"v":9,"t":"Então alguns homens da sinagoga chamada dos Libertos, junto com judeus de Cirene, Alexandria, Cilícia e da província da Ásia, começaram a discutir com Estêvão."},
{"v":10,"t":"Mas não conseguiam resistir à sabedoria e ao Espírito com que ele falava."},
{"v":11,"t":"Então subornaram alguns homens para dizer: Nós ouvimos ele falar coisas contra Moisés e contra Deus."},
{"v":12,"t":"Com isso, agitaram o povo, os anciãos e os mestres da lei. Agarraram Estêvão e o levaram ao tribunal."},
{"v":13,"t":"Arranjaram testemunhas falsas que disseram: Este homem não para de falar contra o templo sagrado e contra a lei."},
{"v":14,"t":"Nós o ouvimos dizer que Jesus de Nazaré vai destruir este lugar e mudar os costumes que Moisés nos deixou."},
{"v":15,"t":"Todos os que estavam sentados no tribunal olharam para Estêvão. E viram que o rosto dele parecia o rosto de um anjo."},
]})

# Chapter 7 - Stephen's speech and martyrdom
chapters.append({"c":7,"verses":[
{"v":1,"t":"O sumo sacerdote perguntou: Isso é verdade?"},
{"v":2,"t":"Estêvão respondeu: Irmãos e pais, ouçam. O Deus da glória apareceu ao nosso pai Abraão quando ele ainda morava na Mesopotâmia, antes de ir para Harã."},
{"v":3,"t":"Deus disse a ele: Saia da sua terra e da sua família. Vá para a terra que eu vou mostrar a você."},
{"v":4,"t":"Então Abraão saiu da terra dos caldeus e foi morar em Harã. Depois que o pai dele morreu, Deus o trouxe para esta terra onde vocês vivem agora."},
{"v":5,"t":"Mas Deus não deu a ele nem um pedaço de terra aqui. Porém prometeu que daria esta terra a ele e aos seus descendentes, mesmo que naquele tempo Abraão ainda não tivesse filhos."},
{"v":6,"t":"Deus disse que os descendentes dele morariam como estrangeiros em terra alheia. Seriam escravizados e maltratados por quatrocentos anos."},
{"v":7,"t":"Mas eu vou julgar a nação que os escravizar, disse Deus. Depois disso, eles sairão de lá e me adorarão neste lugar."},
{"v":8,"t":"Deus fez uma aliança com Abraão, marcada pela circuncisão. Assim, quando nasceu Isaque, Abraão o circuncidou no oitavo dia. Isaque fez o mesmo com Jacó, e Jacó com os doze patriarcas."},
{"v":9,"t":"Os patriarcas tiveram inveja de José e o venderam como escravo para o Egito. Mas Deus estava com ele."},
{"v":10,"t":"Deus o livrou de todos os problemas e lhe deu sabedoria. O faraó, rei do Egito, gostou de José e o colocou como governador do Egito e de toda a sua casa."},
{"v":11,"t":"Então veio uma grande fome em todo o Egito e Canaã. O sofrimento era grande. Nossos antepassados não encontravam comida."},
{"v":12,"t":"Quando Jacó ouviu que havia trigo no Egito, enviou nossos antepassados pela primeira vez."},
{"v":13,"t":"Na segunda visita, José se revelou aos irmãos. E o faraó ficou sabendo da família de José."},
{"v":14,"t":"Então José mandou chamar seu pai Jacó e toda a família. Eram setenta e cinco pessoas ao todo."},
{"v":15,"t":"Jacó desceu ao Egito. Lá ele morreu, e também nossos antepassados."},
{"v":16,"t":"Seus corpos foram levados para Siquém e colocados no túmulo que Abraão tinha comprado dos filhos de Hamor."},
{"v":17,"t":"Quando se aproximava o tempo de Deus cumprir a promessa feita a Abraão, o povo cresceu e se multiplicou no Egito."},
{"v":18,"t":"Até que subiu ao poder um novo rei no Egito que não conhecia José."},
{"v":19,"t":"Esse rei agiu com maldade contra nosso povo. Maltratou nossos antepassados e os obrigou a abandonar seus bebês para que morressem."},
{"v":20,"t":"Nessa época nasceu Moisés. Ele era uma criança linda aos olhos de Deus. Foi criado na casa do pai durante três meses."},
{"v":21,"t":"Quando foi abandonado, a filha do faraó o encontrou e o criou como seu próprio filho."},
{"v":22,"t":"Moisés recebeu toda a educação dos egípcios. Tornou-se poderoso em palavras e ações."},
{"v":23,"t":"Quando completou quarenta anos, Moisés decidiu visitar seus irmãos israelitas."},
{"v":24,"t":"Viu um deles sendo maltratado e saiu em sua defesa. Vingou o oprimido matando o egípcio."},
{"v":25,"t":"Moisés pensava que seus irmãos entenderiam que Deus os libertaria por meio dele. Mas eles não entenderam."},
{"v":26,"t":"No dia seguinte, encontrou dois israelitas brigando e tentou fazer as pazes. Disse: Vocês são irmãos! Por que estão se machucando?"},
{"v":27,"t":"Mas o que estava agredindo o outro empurrou Moisés e disse: Quem colocou você como líder e juiz sobre nós?"},
{"v":28,"t":"Você quer me matar como matou o egípcio ontem?"},
{"v":29,"t":"Ao ouvir isso, Moisés fugiu e foi morar na terra de Midiã. Lá teve dois filhos."},
{"v":30,"t":"Quarenta anos depois, um anjo apareceu a Moisés no deserto do Monte Sinai, numa chama de fogo dentro de um arbusto."},
{"v":31,"t":"Moisés ficou impressionado com o que viu. Quando se aproximou para observar melhor, ouviu a voz do Senhor:"},
{"v":32,"t":"Eu sou o Deus dos seus antepassados, o Deus de Abraão, Isaque e Jacó. Moisés tremeu de medo e não teve coragem de olhar."},
{"v":33,"t":"O Senhor disse: Tire as sandálias dos pés, porque o lugar onde você está é terra sagrada."},
{"v":34,"t":"Eu vi o sofrimento do meu povo no Egito. Ouvi os gemidos deles e desci para libertá-los. Agora venha, eu vou enviar você ao Egito."},
{"v":35,"t":"Esse Moisés, que eles tinham rejeitado dizendo 'Quem colocou você como líder e juiz?', foi o mesmo que Deus enviou como líder e libertador, com a ajuda do anjo que apareceu no arbusto."},
{"v":36,"t":"Foi ele que os tirou do Egito, fazendo maravilhas e sinais no Egito, no Mar Vermelho e no deserto durante quarenta anos."},
{"v":37,"t":"É esse Moisés que disse aos israelitas: Deus vai levantar para vocês um profeta como eu, do meio dos seus próprios irmãos."},
{"v":38,"t":"É ele que esteve na assembleia no deserto, junto com o anjo que falou com ele no Monte Sinai e com nossos antepassados. Ele recebeu palavras vivas para transmitir a nós."},
{"v":39,"t":"Mas nossos antepassados não quiseram obedecer a ele. O rejeitaram e em seus corações voltaram para o Egito."},
{"v":40,"t":"Disseram a Arão: Faça deuses para nós que nos guiem. Porque não sabemos o que aconteceu com esse Moisés que nos tirou do Egito."},
{"v":41,"t":"Naqueles dias, fizeram um bezerro de ouro, ofereceram sacrifícios ao ídolo e festejaram aquilo que suas mãos tinham feito."},
{"v":42,"t":"Então Deus se afastou deles e os entregou para adorar os astros do céu. Como está escrito no livro dos profetas: Povo de Israel, foi a mim que vocês ofereceram sacrifícios durante quarenta anos no deserto?"},
{"v":43,"t":"Vocês carregaram a tenda de Moloque e a estrela do deus Renfã, ídolos que vocês fizeram para adorar. Por isso vou mandar vocês para o exílio, para além de Babilônia."},
{"v":44,"t":"No deserto, nossos antepassados tinham a tenda do Testemunho. Deus mandou Moisés fazê-la conforme o modelo que ele tinha visto."},
{"v":45,"t":"Nossos antepassados receberam essa tenda e a trouxeram com Josué quando tomaram as terras das nações que Deus expulsou diante deles. Ela permaneceu até os dias de Davi."},
{"v":46,"t":"Davi encontrou favor diante de Deus e pediu para construir uma morada para o Deus de Jacó."},
{"v":47,"t":"Mas foi Salomão quem construiu a casa para Deus."},
{"v":48,"t":"Porém, o Deus Altíssimo não mora em casas feitas por mãos humanas. Como disse o profeta:"},
{"v":49,"t":"O céu é o meu trono e a terra é o apoio para os meus pés. Que tipo de casa vocês vão construir para mim? Diz o Senhor. Onde é o lugar do meu descanso?"},
{"v":50,"t":"Não foram as minhas mãos que fizeram todas essas coisas?"},
{"v":51,"t":"Vocês são teimosos! Seus corações e ouvidos estão fechados! Vocês sempre resistem ao Espírito Santo, igualzinho aos seus antepassados!"},
{"v":52,"t":"Houve algum profeta que seus antepassados não perseguiram? Eles mataram os que anunciaram a vinda do Justo. E agora vocês o traíram e o mataram."},
{"v":53,"t":"Vocês receberam a lei por meio de anjos, mas não obedeceram!"},
{"v":54,"t":"Quando ouviram isso, ficaram com muita raiva. Rangiam os dentes contra Estêvão."},
{"v":55,"t":"Mas Estêvão, cheio do Espírito Santo, olhou para o céu e viu a glória de Deus. Viu Jesus de pé, ao lado direito de Deus."},
{"v":56,"t":"E disse: Vejam! Eu estou vendo o céu aberto e o Filho do Homem de pé ao lado direito de Deus!"},
{"v":57,"t":"Eles gritaram bem alto, taparam os ouvidos e avançaram juntos contra ele."},
{"v":58,"t":"Arrastaram Estêvão para fora da cidade e começaram a jogar pedras nele. As testemunhas deixaram suas capas aos pés de um jovem chamado Saulo."},
{"v":59,"t":"Enquanto apedrejavam Estêvão, ele orava: Senhor Jesus, receba o meu espírito!"},
{"v":60,"t":"Então caiu de joelhos e gritou em voz alta: Senhor, não os castigue por este pecado! Depois de dizer isso, morreu."},
]})

# Chapter 8 - Persecution and Philip
chapters.append({"c":8,"verses":[
{"v":1,"t":"Saulo concordava com a morte de Estêvão. Naquele dia começou uma grande perseguição contra a igreja em Jerusalém. Todos se espalharam pela Judeia e Samaria, menos os apóstolos."},
{"v":2,"t":"Homens devotos sepultaram Estêvão e fizeram grande luto por ele."},
{"v":3,"t":"Saulo devastava a igreja. Ia de casa em casa, arrastava homens e mulheres e os jogava na prisão."},
{"v":4,"t":"Os que se espalharam iam por toda parte anunciando a mensagem."},
{"v":5,"t":"Filipe desceu à cidade de Samaria e anunciou o Cristo ali."},
{"v":6,"t":"As multidões prestavam atenção ao que Filipe dizia. Ouviam suas palavras e viam os milagres que ele fazia."},
{"v":7,"t":"Espíritos maus saíam de muitas pessoas, gritando em voz alta. Muitos paralíticos e aleijados também foram curados."},
{"v":8,"t":"Por isso havia grande alegria naquela cidade."},
{"v":9,"t":"Na cidade havia um homem chamado Simão. Ele praticava feitiçaria e impressionava o povo de Samaria. Dizia que era alguém importante."},
{"v":10,"t":"Todos, do menor ao maior, davam atenção a ele e diziam: Este homem é o poder de Deus, o chamado Grande Poder."},
{"v":11,"t":"Davam atenção a ele porque há muito tempo os impressionava com suas feitiçarias."},
{"v":12,"t":"Mas quando creram em Filipe, que anunciava a boa notícia do Reino de Deus e do nome de Jesus Cristo, foram batizados, tanto homens como mulheres."},
{"v":13,"t":"O próprio Simão também creu e foi batizado. Ele seguia Filipe por toda parte, impressionado com os grandes sinais e milagres que via."},
{"v":14,"t":"Os apóstolos em Jerusalém ouviram que Samaria tinha recebido a palavra de Deus. Então enviaram Pedro e João até lá."},
{"v":15,"t":"Quando chegaram, oraram pelos novos crentes para que recebessem o Espírito Santo."},
{"v":16,"t":"Porque o Espírito Santo ainda não tinha descido sobre nenhum deles. Eles só tinham sido batizados em nome do Senhor Jesus."},
{"v":17,"t":"Então Pedro e João impuseram as mãos sobre eles, e eles receberam o Espírito Santo."},
{"v":18,"t":"Quando Simão viu que o Espírito era dado pela imposição das mãos dos apóstolos, ofereceu dinheiro a eles."},
{"v":19,"t":"Ele disse: Deem esse poder a mim também, para que todo aquele sobre quem eu impuser as mãos receba o Espírito Santo."},
{"v":20,"t":"Pedro respondeu: Que o seu dinheiro vá com você para a destruição! Você pensou que podia comprar o dom de Deus com dinheiro!"},
{"v":21,"t":"Você não tem parte nem direito neste trabalho, porque o seu coração não é correto diante de Deus."},
{"v":22,"t":"Arrependa-se dessa maldade e peça ao Senhor. Talvez ele perdoe o que você pensou em seu coração."},
{"v":23,"t":"Porque eu vejo que você está cheio de amargura e preso pelo pecado."},
{"v":24,"t":"Simão respondeu: Peçam ao Senhor por mim, para que nada disso que vocês disseram aconteça comigo!"},
{"v":25,"t":"Depois de darem testemunho e pregarem a palavra do Senhor, Pedro e João voltaram para Jerusalém. No caminho, anunciaram a boa notícia em muitas aldeias de Samaria."},
{"v":26,"t":"Um anjo do Senhor disse a Filipe: Levante-se e vá para o sul, pela estrada deserta que vai de Jerusalém a Gaza."},
{"v":27,"t":"Filipe se levantou e foi. No caminho, encontrou um homem da Etiópia. Era um oficial importante, tesoureiro de Candace, rainha da Etiópia. Ele tinha ido a Jerusalém para adorar a Deus."},
{"v":28,"t":"Estava voltando para casa. Sentado em sua carruagem, ia lendo o profeta Isaías."},
{"v":29,"t":"O Espírito disse a Filipe: Vá até aquela carruagem e fique perto dela."},
{"v":30,"t":"Filipe correu até lá e ouviu o homem lendo o profeta Isaías. Perguntou: O senhor entende o que está lendo?"},
{"v":31,"t":"Ele respondeu: Como posso entender se ninguém me explica? E convidou Filipe para subir e sentar ao seu lado."},
{"v":32,"t":"O trecho que ele estava lendo era este: Ele foi levado como ovelha para o matadouro. Como cordeiro mudo diante de quem o tosquia, ele não abriu a boca."},
{"v":33,"t":"Ele foi humilhado e não recebeu justiça. Quem poderá falar dos seus descendentes? Porque a sua vida foi tirada da terra."},
{"v":34,"t":"O oficial perguntou a Filipe: Me diga, de quem o profeta está falando? De si mesmo ou de outra pessoa?"},
{"v":35,"t":"Então Filipe começou a explicar. Partindo daquele trecho, anunciou a boa notícia sobre Jesus."},
{"v":36,"t":"Enquanto seguiam pela estrada, chegaram a um lugar com água. O oficial disse: Olhe, aqui tem água. O que impede que eu seja batizado?"},
{"v":37,"t":"Filipe disse: Se você crê de todo o coração, pode. Ele respondeu: Eu creio que Jesus Cristo é o Filho de Deus."},
{"v":38,"t":"Mandou parar a carruagem. Os dois desceram até a água, e Filipe o batizou."},
{"v":39,"t":"Quando saíram da água, o Espírito do Senhor levou Filipe embora. O oficial não o viu mais, mas seguiu viagem cheio de alegria."},
{"v":40,"t":"Filipe apareceu em Azoto. De lá, foi passando por todas as cidades anunciando a boa notícia, até chegar a Cesareia."},
]})

# Chapter 9 - Saul's conversion
chapters.append({"c":9,"verses":[
{"v":1,"t":"Enquanto isso, Saulo ainda respirava ameaças de morte contra os seguidores do Senhor. Ele foi ao sumo sacerdote"},
{"v":2,"t":"e pediu cartas para as sinagogas de Damasco. Queria autorização para prender qualquer seguidor do Caminho, homens ou mulheres, e levá-los para Jerusalém."},
{"v":3,"t":"Quando estava perto de Damasco, de repente uma luz do céu brilhou ao redor dele."},
{"v":4,"t":"Saulo caiu no chão e ouviu uma voz que dizia: Saulo, Saulo, por que você me persegue?"},
{"v":5,"t":"Ele perguntou: Quem é o senhor? A voz respondeu: Eu sou Jesus, a quem você persegue."},
{"v":6,"t":"Agora levante-se, entre na cidade, e alguém dirá o que você deve fazer."},
{"v":7,"t":"Os homens que viajavam com Saulo ficaram parados sem conseguir falar. Ouviam a voz, mas não viam ninguém."},
{"v":8,"t":"Saulo se levantou do chão. Quando abriu os olhos, não conseguia ver nada. Então o pegaram pela mão e o levaram até Damasco."},
{"v":9,"t":"Durante três dias ele ficou sem enxergar. Não comeu nem bebeu nada."},
{"v":10,"t":"Em Damasco havia um seguidor de Jesus chamado Ananias. O Senhor disse a ele numa visão: Ananias! Ele respondeu: Aqui estou, Senhor."},
{"v":11,"t":"O Senhor disse: Levante-se e vá à rua chamada Reta. Na casa de Judas, procure um homem de Tarso chamado Saulo. Ele está orando."},
{"v":12,"t":"Numa visão, Saulo viu um homem chamado Ananias chegar e colocar as mãos sobre ele para que voltasse a enxergar."},
{"v":13,"t":"Ananias respondeu: Senhor, eu ouvi muita gente falar desse homem e de todo o mal que ele fez aos teus santos em Jerusalém."},
{"v":14,"t":"E ele veio até aqui com autorização dos chefes dos sacerdotes para prender todos os que invocam o teu nome."},
{"v":15,"t":"Mas o Senhor disse: Vá! Eu escolhi esse homem para levar o meu nome aos não judeus, aos reis e ao povo de Israel."},
{"v":16,"t":"Eu vou mostrar a ele o quanto terá que sofrer por causa do meu nome."},
{"v":17,"t":"Ananias foi. Entrou na casa e colocou as mãos sobre Saulo. Disse: Irmão Saulo, o Senhor Jesus, que apareceu a você no caminho, me enviou para que você volte a enxergar e fique cheio do Espírito Santo."},
{"v":18,"t":"Na mesma hora, algo como escamas caiu dos olhos de Saulo. Ele voltou a ver. Levantou-se e foi batizado."},
{"v":19,"t":"Depois de comer, recuperou as forças. Saulo ficou alguns dias com os seguidores de Jesus em Damasco."},
{"v":20,"t":"Logo começou a pregar nas sinagogas que Jesus é o Filho de Deus."},
{"v":21,"t":"Todos que o ouviam ficavam impressionados e diziam: Não é esse o homem que perseguia em Jerusalém os que invocam esse nome? Ele não veio aqui justamente para prendê-los e levá-los aos chefes dos sacerdotes?"},
{"v":22,"t":"Mas Saulo ficava cada vez mais forte. Provava que Jesus é o Cristo e deixava os judeus de Damasco sem argumentos."},
{"v":23,"t":"Depois de muitos dias, os judeus fizeram um plano para matar Saulo."},
{"v":24,"t":"Mas ele ficou sabendo do plano. Dia e noite vigiavam as portas da cidade para matá-lo."},
{"v":25,"t":"Então os seguidores de Jesus pegaram Saulo de noite e o desceram pelo muro da cidade numa cesta."},
{"v":26,"t":"Quando Saulo chegou a Jerusalém, tentou se juntar aos seguidores de Jesus. Mas todos tinham medo dele porque não acreditavam que ele era realmente um seguidor."},
{"v":27,"t":"Então Barnabé o levou aos apóstolos. Contou como Saulo tinha visto o Senhor no caminho e como o Senhor tinha falado com ele. Contou também como Saulo tinha pregado com coragem em Damasco, em nome de Jesus."},
{"v":28,"t":"Saulo ficou com eles em Jerusalém. Andava livremente e pregava com ousadia em nome do Senhor."},
{"v":29,"t":"Falava e discutia com os judeus de língua grega. Mas eles tentavam matá-lo."},
{"v":30,"t":"Quando os irmãos souberam disso, levaram Saulo até Cesareia e de lá o enviaram para Tarso."},
{"v":31,"t":"Então a igreja em toda a Judeia, Galileia e Samaria teve um tempo de paz. Crescia, andava no temor do Senhor e era encorajada pelo Espírito Santo."},
{"v":32,"t":"Pedro viajava por toda parte. Uma vez foi visitar os santos que moravam em Lida."},
{"v":33,"t":"Ali encontrou um homem chamado Eneias, que estava paralítico e acamado havia oito anos."},
{"v":34,"t":"Pedro disse a ele: Eneias, Jesus Cristo cura você. Levante-se e arrume a sua cama. Na mesma hora Eneias se levantou."},
{"v":35,"t":"Todos os que moravam em Lida e na planície de Sarona viram Eneias curado e se voltaram para o Senhor."},
{"v":36,"t":"Em Jope, havia uma seguidora de Jesus chamada Tabita, que em grego se chama Dorcas. Ela vivia fazendo o bem e ajudando os pobres."},
{"v":37,"t":"Naqueles dias, ela ficou doente e morreu. Lavaram o corpo e o colocaram num quarto no andar de cima."},
{"v":38,"t":"Como Lida ficava perto de Jope, os seguidores ouviram que Pedro estava lá. Enviaram dois homens para pedir: Por favor, venha rápido!"},
{"v":39,"t":"Pedro foi com eles. Quando chegou, o levaram ao quarto de cima. Todas as viúvas estavam ali chorando e mostrando as roupas e os vestidos que Dorcas tinha feito enquanto ainda estava com elas."},
{"v":40,"t":"Pedro mandou todos saírem. Ajoelhou-se e orou. Depois se virou para o corpo e disse: Tabita, levante-se! Ela abriu os olhos, viu Pedro e se sentou."},
{"v":41,"t":"Pedro estendeu a mão e a ajudou a levantar. Depois chamou os santos e as viúvas e a apresentou viva."},
{"v":42,"t":"A notícia se espalhou por toda Jope, e muitos creram no Senhor."},
{"v":43,"t":"Pedro ficou muitos dias em Jope, na casa de um curtidor chamado Simão."},
]})

# Chapter 10 - Cornelius and Peter
chapters.append({"c":10,"verses":[
{"v":1,"t":"Em Cesareia havia um homem chamado Cornélio. Era centurião do batalhão chamado Italiano."},
{"v":2,"t":"Ele era um homem religioso que respeitava a Deus, junto com toda a sua família. Ajudava muito os pobres e orava a Deus sempre."},
{"v":3,"t":"Certa tarde, por volta das três horas, ele teve uma visão. Viu claramente um anjo de Deus que chegou até ele e disse: Cornélio!"},
{"v":4,"t":"Cornélio olhou para o anjo com medo e disse: O que é, Senhor? O anjo respondeu: As suas orações e a sua ajuda aos pobres subiram até Deus como uma oferta agradável."},
{"v":5,"t":"Agora mande homens a Jope para trazer um homem chamado Simão Pedro."},
{"v":6,"t":"Ele está hospedado na casa de Simão, o curtidor, que fica perto do mar."},
{"v":7,"t":"Quando o anjo foi embora, Cornélio chamou dois dos seus empregados e um soldado fiel que o servia."},
{"v":8,"t":"Contou tudo a eles e os enviou a Jope."},
{"v":9,"t":"No dia seguinte, enquanto eles viajavam e já estavam perto da cidade, Pedro subiu ao terraço para orar, por volta do meio-dia."},
{"v":10,"t":"Ele ficou com fome e quis comer. Enquanto preparavam a comida, Pedro teve uma visão."},
{"v":11,"t":"Viu o céu aberto e algo parecido com um grande lençol descendo, segurado pelas quatro pontas."},
{"v":12,"t":"Dentro dele havia todo tipo de animal: quadrúpedes, répteis e aves."},
{"v":13,"t":"Uma voz disse: Pedro, levante-se! Mate e coma."},
{"v":14,"t":"Pedro respondeu: De jeito nenhum, Senhor! Eu nunca comi nada impuro ou proibido."},
{"v":15,"t":"A voz falou de novo: O que Deus declarou puro, não chame de impuro."},
{"v":16,"t":"Isso aconteceu três vezes, e logo depois o lençol foi recolhido de volta ao céu."},
{"v":17,"t":"Pedro ainda estava tentando entender a visão quando os homens enviados por Cornélio chegaram à porta da casa de Simão. Tinham perguntado pelo caminho."},
{"v":18,"t":"Chamaram e perguntaram se Simão Pedro estava hospedado ali."},
{"v":19,"t":"Enquanto Pedro pensava na visão, o Espírito disse: Três homens estão procurando você."},
{"v":20,"t":"Desça e vá com eles sem hesitar. Fui eu que os enviei."},
{"v":21,"t":"Pedro desceu e disse aos homens: Sou eu que vocês estão procurando. Qual é o motivo da visita?"},
{"v":22,"t":"Eles responderam: O centurião Cornélio é um homem justo que respeita a Deus. Todo o povo judeu fala bem dele. Um anjo santo disse a ele que chamasse o senhor à casa dele para ouvir o que tem a dizer."},
{"v":23,"t":"Pedro os convidou a entrar e os hospedou. No dia seguinte, Pedro saiu com eles. Alguns irmãos de Jope foram junto."},
{"v":24,"t":"No outro dia chegaram a Cesareia. Cornélio os esperava. Tinha reunido seus parentes e amigos próximos."},
{"v":25,"t":"Quando Pedro entrou, Cornélio foi até ele e se ajoelhou aos seus pés."},
{"v":26,"t":"Mas Pedro o levantou e disse: Fique de pé. Eu também sou apenas um ser humano."},
{"v":27,"t":"Enquanto conversava com Cornélio, Pedro entrou e encontrou muitas pessoas reunidas."},
{"v":28,"t":"Ele disse: Vocês sabem que um judeu não tem permissão para se associar a não judeus ou visitar a casa deles. Mas Deus me mostrou que eu não devo chamar ninguém de impuro ou indigno."},
{"v":29,"t":"Por isso vim sem reclamar quando me chamaram. Agora pergunto: por que vocês mandaram me chamar?"},
{"v":30,"t":"Cornélio respondeu: Quatro dias atrás, nesta mesma hora, às três da tarde, eu estava orando em casa. De repente apareceu diante de mim um homem com roupas brilhantes."},
{"v":31,"t":"Ele disse: Cornélio, Deus ouviu a sua oração e se lembrou da sua ajuda aos pobres."},
{"v":32,"t":"Mande alguém a Jope para chamar Simão Pedro. Ele está na casa de Simão, o curtidor, perto do mar."},
{"v":33,"t":"Eu mandei chamar o senhor imediatamente. E o senhor fez bem em vir. Agora estamos todos aqui diante de Deus para ouvir tudo o que o Senhor mandou o senhor nos dizer."},
{"v":34,"t":"Então Pedro começou a falar: Agora eu entendo de verdade que Deus não faz diferença entre as pessoas."},
{"v":35,"t":"Em qualquer nação, quem respeita a Deus e faz o que é certo é aceito por ele."},
{"v":36,"t":"Deus enviou a sua mensagem ao povo de Israel, anunciando a boa notícia de paz por meio de Jesus Cristo. Ele é o Senhor de todos."},
{"v":37,"t":"Vocês sabem o que aconteceu em toda a Judeia, começando pela Galileia, depois que João pregou o batismo."},
{"v":38,"t":"Deus ungiu Jesus de Nazaré com o Espírito Santo e com poder. Ele andou por toda parte fazendo o bem e curando todos os que eram dominados pelo diabo, porque Deus estava com ele."},
{"v":39,"t":"Nós somos testemunhas de tudo o que ele fez na terra dos judeus e em Jerusalém. Eles o mataram pregando-o numa cruz."},
{"v":40,"t":"Mas Deus o ressuscitou no terceiro dia e permitiu que ele fosse visto."},
{"v":41,"t":"Não por todo o povo, mas pelas testemunhas que Deus já tinha escolhido. Nós comemos e bebemos com ele depois que ressuscitou dos mortos."},
{"v":42,"t":"Ele nos mandou pregar ao povo e testemunhar que ele é quem Deus designou como juiz dos vivos e dos mortos."},
{"v":43,"t":"Todos os profetas dão testemunho dele. Todo aquele que crê nele recebe o perdão dos pecados por meio do seu nome."},
{"v":44,"t":"Enquanto Pedro ainda falava, o Espírito Santo desceu sobre todos os que ouviam a mensagem."},
{"v":45,"t":"Os judeus que tinham vindo com Pedro ficaram espantados porque o dom do Espírito Santo foi derramado também sobre os não judeus."},
{"v":46,"t":"Eles os ouviam falando em línguas e louvando a Deus. Então Pedro disse:"},
{"v":47,"t":"Alguém pode impedir que essas pessoas sejam batizadas com água? Eles receberam o Espírito Santo assim como nós!"},
{"v":48,"t":"E mandou que fossem batizados em nome de Jesus Cristo. Depois pediram que Pedro ficasse com eles por alguns dias."},
]})

# Chapter 11 - Peter explains, Antioch church
chapters.append({"c":11,"verses":[
{"v":1,"t":"Os apóstolos e os irmãos da Judeia ouviram que os não judeus também tinham recebido a palavra de Deus."},
{"v":2,"t":"Quando Pedro voltou a Jerusalém, os judeus que defendiam a circuncisão o criticaram."},
{"v":3,"t":"Disseram: Você entrou na casa de gente que não é circuncidada e comeu com eles!"},
{"v":4,"t":"Então Pedro começou a explicar tudo desde o início:"},
{"v":5,"t":"Eu estava na cidade de Jope orando quando tive uma visão. Vi algo parecido com um grande lençol descendo do céu, segurado pelas quatro pontas. Ele desceu até mim."},
{"v":6,"t":"Olhei bem para dentro e vi animais quadrúpedes, feras, répteis e aves."},
{"v":7,"t":"Então ouvi uma voz que disse: Pedro, levante-se! Mate e coma."},
{"v":8,"t":"Eu respondi: De jeito nenhum, Senhor! Nunca comi nada impuro ou proibido."},
{"v":9,"t":"A voz do céu falou de novo: O que Deus declarou puro, não chame de impuro."},
{"v":10,"t":"Isso aconteceu três vezes, e depois tudo foi recolhido de volta ao céu."},
{"v":11,"t":"Naquele mesmo momento, três homens enviados de Cesareia chegaram à casa onde eu estava."},
{"v":12,"t":"O Espírito me disse para ir com eles sem hesitar. Esses seis irmãos foram comigo. Nós entramos na casa daquele homem."},
{"v":13,"t":"Ele nos contou como tinha visto um anjo na sua casa que disse: Mande buscar Simão Pedro em Jope."},
{"v":14,"t":"Ele vai dizer a você as palavras pelas quais você e toda a sua família serão salvos."},
{"v":15,"t":"Quando comecei a falar, o Espírito Santo desceu sobre eles da mesma forma como desceu sobre nós no começo."},
{"v":16,"t":"Então me lembrei do que o Senhor disse: João batizou com água, mas vocês serão batizados com o Espírito Santo."},
{"v":17,"t":"Se Deus deu a eles o mesmo presente que deu a nós quando cremos no Senhor Jesus Cristo, quem era eu para me opor a Deus?"},
{"v":18,"t":"Quando ouviram isso, pararam de criticar e louvaram a Deus dizendo: Então Deus também deu aos não judeus a oportunidade de se arrepender e ter vida!"},
{"v":19,"t":"Os que tinham se espalhado por causa da perseguição após a morte de Estêvão foram até a Fenícia, Chipre e Antioquia. Mas só anunciavam a mensagem aos judeus."},
{"v":20,"t":"Porém, alguns deles, homens de Chipre e Cirene, chegaram a Antioquia e começaram a falar também aos gregos, anunciando a boa notícia do Senhor Jesus."},
{"v":21,"t":"A mão do Senhor estava com eles. Um grande número de pessoas creu e se voltou para o Senhor."},
{"v":22,"t":"A notícia chegou à igreja de Jerusalém. Então enviaram Barnabé a Antioquia."},
{"v":23,"t":"Quando Barnabé chegou e viu a graça de Deus, ficou muito feliz. Encorajou todos a permanecerem fiéis ao Senhor de todo o coração."},
{"v":24,"t":"Barnabé era um homem bom, cheio do Espírito Santo e de fé. E muitas pessoas foram acrescentadas ao Senhor."},
{"v":25,"t":"Depois Barnabé foi a Tarso procurar Saulo."},
{"v":26,"t":"Quando o encontrou, trouxe-o para Antioquia. Durante um ano inteiro, os dois se reuniram com a igreja e ensinaram muita gente. Foi em Antioquia que os seguidores de Jesus foram chamados de cristãos pela primeira vez."},
{"v":27,"t":"Naqueles dias, alguns profetas desceram de Jerusalém a Antioquia."},
{"v":28,"t":"Um deles, chamado Ágabo, ficou de pé e pelo Espírito anunciou que haveria uma grande fome em todo o mundo. Isso aconteceu no tempo do imperador Cláudio."},
{"v":29,"t":"Os seguidores decidiram que cada um ajudaria conforme pudesse. Enviariam ajuda aos irmãos que moravam na Judeia."},
{"v":30,"t":"E assim fizeram. Enviaram a ajuda aos líderes da igreja pela mão de Barnabé e Saulo."},
]})

# Save chapters 1-11
with open('v:/GitHub/orgs/devzolo/bible/static/data/bfl/atos_trans_part1.json', 'w', encoding='utf-8') as f:
    json.dump(chapters, f, ensure_ascii=False)
print(f"Saved chapters 1-{chapters[-1]['c']}, total verses: {sum(len(c['verses']) for c in chapters)}")
