# -*- coding: utf-8 -*-
"""BFL Translation - Marcos (Mark) - Chapters 9-16"""
import json, sys, os

chapters = []

# Chapter 9
chapters.append({"c":9,"verses":[
{"v":1,"t":"E disse: Eu digo a verdade: alguns dos que estão aqui não morrerão antes de verem o Reino de Deus chegar com poder."},
{"v":2,"t":"Seis dias depois, Jesus levou Pedro, Tiago e João a um monte alto, só eles. Ali Jesus se transformou diante deles."},
{"v":3,"t":"As roupas dele ficaram brilhantes, de um branco muito intenso, como nenhum lavador no mundo poderia branquear."},
{"v":4,"t":"Apareceram Elias e Moisés, conversando com Jesus."},
{"v":5,"t":"Pedro disse: Mestre, é bom estarmos aqui! Vamos fazer três barracas: uma para o senhor, uma para Moisés e uma para Elias."},
{"v":6,"t":"Ele não sabia o que dizer, porque estavam assustados."},
{"v":7,"t":"Uma nuvem os cobriu, e da nuvem veio uma voz: Este é o meu Filho amado. Ouçam o que ele diz!"},
{"v":8,"t":"De repente, quando olharam ao redor, só viram Jesus com eles."},
{"v":9,"t":"Enquanto desciam do monte, Jesus ordenou que não contassem a ninguém o que viram até que o Filho do Homem ressuscitasse dos mortos."},
{"v":10,"t":"Eles guardaram o assunto entre si, mas perguntavam o que significava ressuscitar dos mortos."},
{"v":11,"t":"Perguntaram: Por que os mestres da Lei dizem que Elias precisa vir primeiro?"},
{"v":12,"t":"Jesus respondeu: Elias vem primeiro e restaura todas as coisas. Mas está escrito que o Filho do Homem vai sofrer muito e ser desprezado."},
{"v":13,"t":"Eu digo que Elias já veio. E fizeram com ele o que quiseram, como está escrito."},
{"v":14,"t":"Quando chegaram onde estavam os outros discípulos, viram uma grande multidão ao redor deles e mestres da Lei discutindo com eles."},
{"v":15,"t":"Assim que a multidão viu Jesus, ficou surpresa e correu para cumprimentá-lo."},
{"v":16,"t":"Jesus perguntou: Sobre o que vocês estão discutindo?"},
{"v":17,"t":"Um homem da multidão respondeu: Mestre, eu trouxe o meu filho. Ele tem um espírito que o deixa mudo."},
{"v":18,"t":"Onde quer que o espírito o ataque, joga-o no chão. O menino espuma, range os dentes e fica duro. Pedi aos seus discípulos para expulsá-lo, mas não conseguiram."},
{"v":19,"t":"Jesus disse: Geração sem fé! Até quando vou ficar com vocês? Até quando vou aguentar vocês? Tragam o menino."},
{"v":20,"t":"Trouxeram o menino. Quando o espírito viu Jesus, sacudiu o menino com violência. Ele caiu no chão e rolava, espumando."},
{"v":21,"t":"Jesus perguntou ao pai: Desde quando isso acontece com ele? Ele respondeu: Desde criança."},
{"v":22,"t":"Muitas vezes o joga no fogo ou na água para matá-lo. Se o senhor puder fazer alguma coisa, tenha compaixão de nós e nos ajude!"},
{"v":23,"t":"Jesus disse: Se puder? Tudo é possível para quem acredita!"},
{"v":24,"t":"Na mesma hora, o pai gritou com lágrimas: Eu acredito! Ajude a minha falta de fé!"},
{"v":25,"t":"Jesus viu que a multidão se aglomerava. Repreendeu o espírito mau: Espírito mudo e surdo, eu ordeno: saia dele e nunca mais entre nele!"},
{"v":26,"t":"O espírito gritou, sacudiu o menino com violência e saiu. O menino ficou como morto, e muitos disseram que tinha morrido."},
{"v":27,"t":"Mas Jesus pegou a mão dele e o levantou. E ele ficou de pé."},
{"v":28,"t":"Quando Jesus entrou em casa, os discípulos perguntaram em particular: Por que nós não conseguimos expulsá-lo?"},
{"v":29,"t":"Jesus respondeu: Esse tipo só sai com oração e jejum."},
{"v":30,"t":"Saíram dali e passaram pela Galileia. Jesus não queria que ninguém soubesse,"},
{"v":31,"t":"porque estava ensinando os discípulos. Dizia: O Filho do Homem será entregue nas mãos de homens. Vão matá-lo, mas três dias depois ele vai ressuscitar."},
{"v":32,"t":"Mas eles não entendiam e tinham medo de perguntar."},
{"v":33,"t":"Chegaram a Cafarnaum. Dentro de casa, Jesus perguntou: Sobre o que vocês discutiam no caminho?"},
{"v":34,"t":"Ficaram calados, porque no caminho tinham discutido sobre quem era o maior."},
{"v":35,"t":"Jesus se sentou, chamou os doze e disse: Se alguém quer ser o primeiro, seja o último de todos e sirva a todos."},
{"v":36,"t":"Pegou uma criança, colocou no meio deles, abraçou-a e disse:"},
{"v":37,"t":"Quem receber uma criança como esta em meu nome está me recebendo. E quem me recebe, não está recebendo a mim, mas aquele que me enviou."},
{"v":38,"t":"João disse: Mestre, vimos um homem expulsando demônios em seu nome. Tentamos impedir, porque ele não é um de nós."},
{"v":39,"t":"Jesus disse: Não impeçam! Ninguém que faça um milagre em meu nome pode falar mal de mim logo depois."},
{"v":40,"t":"Quem não é contra nós está a nosso favor."},
{"v":41,"t":"Eu digo a verdade: quem der a vocês um copo de água por serem de Cristo não ficará sem recompensa."},
{"v":42,"t":"Se alguém fizer um destes pequeninos que creem em mim pecar, seria melhor que amarrassem uma pedra grande no pescoço dele e o jogassem no mar."},
{"v":43,"t":"Se a sua mão faz você pecar, corte-a. É melhor entrar na vida sem uma mão do que ter as duas mãos e ir para o inferno, para o fogo que não se apaga."},
{"v":44,"t":"Onde o verme não morre e o fogo não se apaga."},
{"v":45,"t":"Se o seu pé faz você pecar, corte-o. É melhor entrar na vida sem um pé do que ter os dois pés e ser jogado no inferno."},
{"v":46,"t":"Onde o verme não morre e o fogo não se apaga."},
{"v":47,"t":"Se o seu olho faz você pecar, arranque-o. É melhor entrar no Reino de Deus com um olho só do que ter dois olhos e ser jogado no inferno."},
{"v":48,"t":"Onde o verme não morre e o fogo não se apaga."},
{"v":49,"t":"Porque todos serão temperados com fogo."},
{"v":50,"t":"O sal é bom. Mas se perder o sabor, como vai ficar salgado de novo? Tenham sal em vocês mesmos e vivam em paz uns com os outros."},
]})

# Chapter 10
chapters.append({"c":10,"verses":[
{"v":1,"t":"Jesus saiu dali e foi para a região da Judeia, além do Jordão. Outra vez as multidões se juntaram, e ele as ensinava como sempre fazia."},
{"v":2,"t":"Alguns fariseus se aproximaram e perguntaram para testá-lo: É permitido um homem se divorciar da esposa?"},
{"v":3,"t":"Jesus respondeu: O que Moisés mandou vocês fazerem?"},
{"v":4,"t":"Disseram: Moisés permitiu escrever um documento de divórcio e se separar."},
{"v":5,"t":"Jesus disse: Moisés escreveu essa regra por causa da dureza do coração de vocês."},
{"v":6,"t":"Mas desde o começo da criação, Deus os fez homem e mulher."},
{"v":7,"t":"Por isso o homem deixará o pai e a mãe e se unirá à esposa."},
{"v":8,"t":"E os dois serão um só. Eles não são mais dois, mas um só."},
{"v":9,"t":"Portanto, o que Deus uniu, o ser humano não deve separar."},
{"v":10,"t":"Em casa, os discípulos perguntaram de novo sobre isso."},
{"v":11,"t":"Jesus disse: Quem se divorciar da esposa e casar com outra comete adultério contra ela."},
{"v":12,"t":"E se a mulher se divorciar do marido e casar com outro, comete adultério."},
{"v":13,"t":"Traziam crianças a Jesus para que ele tocasse nelas. Mas os discípulos repreendiam quem as trazia."},
{"v":14,"t":"Jesus ficou indignado e disse: Deixem as crianças virem a mim! Não as impeçam! Porque o Reino de Deus pertence a pessoas como elas."},
{"v":15,"t":"Eu digo a verdade: quem não receber o Reino de Deus como uma criança, não entrará nele."},
{"v":16,"t":"Então abraçou as crianças, colocou as mãos sobre elas e as abençoou."},
{"v":17,"t":"Quando Jesus saiu para a estrada, um homem correu até ele, se ajoelhou e perguntou: Bom Mestre, o que devo fazer para ter a vida eterna?"},
{"v":18,"t":"Jesus disse: Por que me chama de bom? Ninguém é bom, a não ser Deus."},
{"v":19,"t":"Você conhece os mandamentos: não mate, não cometa adultério, não roube, não dê falso testemunho, não engane ninguém, honre seu pai e sua mãe."},
{"v":20,"t":"O homem disse: Mestre, eu obedeço tudo isso desde novo."},
{"v":21,"t":"Jesus olhou para ele com amor e disse: Uma coisa falta: vá, venda tudo que tem e dê aos pobres. Você terá um tesouro no céu. Depois, venha e me siga."},
{"v":22,"t":"Quando ouviu isso, o homem ficou triste e foi embora, porque tinha muitas riquezas."},
{"v":23,"t":"Jesus olhou ao redor e disse aos discípulos: Como é difícil para os ricos entrar no Reino de Deus!"},
{"v":24,"t":"Os discípulos ficaram espantados. Jesus disse de novo: Filhos, como é difícil entrar no Reino de Deus!"},
{"v":25,"t":"É mais fácil um camelo passar pelo buraco de uma agulha do que um rico entrar no Reino de Deus."},
{"v":26,"t":"Eles ficaram ainda mais espantados e diziam uns aos outros: Quem pode então se salvar?"},
{"v":27,"t":"Jesus olhou para eles e disse: Para os seres humanos é impossível. Mas para Deus não. Porque para Deus tudo é possível."},
{"v":28,"t":"Pedro disse: Nós deixamos tudo e seguimos o senhor."},
{"v":29,"t":"Jesus respondeu: Eu digo a verdade: todo aquele que deixou casa, irmãos, irmãs, mãe, pai, filhos ou terras por minha causa e pela boa notícia"},
{"v":30,"t":"receberá cem vezes mais nesta vida — casas, irmãos, irmãs, mães, filhos e terras, junto com perseguição — e na vida que vem, a vida eterna."},
{"v":31,"t":"Muitos que são os primeiros serão os últimos. E muitos que são os últimos serão os primeiros."},
{"v":32,"t":"Estavam no caminho, subindo para Jerusalém. Jesus ia à frente. Os discípulos estavam espantados, e os que vinham atrás tinham medo. Ele chamou os doze à parte e começou a contar o que ia acontecer:"},
{"v":33,"t":"Nós estamos subindo para Jerusalém. O Filho do Homem será entregue aos chefes dos sacerdotes e aos mestres da Lei. Eles o condenarão à morte e o entregarão aos romanos."},
{"v":34,"t":"Vão zombar dele, cuspir nele, açoitá-lo e matá-lo. Mas depois de três dias ele vai ressuscitar."},
{"v":35,"t":"Tiago e João, filhos de Zebedeu, se aproximaram e disseram: Mestre, queremos que faça o que vamos pedir."},
{"v":36,"t":"Jesus perguntou: O que vocês querem?"},
{"v":37,"t":"Disseram: Conceda que na sua glória nos sentemos um à sua direita e outro à sua esquerda."},
{"v":38,"t":"Jesus disse: Vocês não sabem o que estão pedindo. Vocês podem beber o cálice que eu vou beber e ser batizados com o batismo que eu vou receber?"},
{"v":39,"t":"Disseram: Podemos. Jesus disse: Vocês vão beber o cálice que eu beber e receber o batismo que eu receber."},
{"v":40,"t":"Mas sentar à minha direita ou esquerda não depende de mim. Esses lugares são para quem foram preparados."},
{"v":41,"t":"Quando os outros dez ouviram, ficaram irritados com Tiago e João."},
{"v":42,"t":"Jesus chamou todos e disse: Vocês sabem que os governantes das nações dominam sobre elas, e os poderosos abusam do poder."},
{"v":43,"t":"Entre vocês não deve ser assim. Quem quiser ser grande, sirva os outros."},
{"v":44,"t":"Quem quiser ser o primeiro, seja servo de todos."},
{"v":45,"t":"Porque o Filho do Homem não veio para ser servido, mas para servir e dar a sua vida para salvar muitas pessoas."},
{"v":46,"t":"Chegaram a Jericó. Quando Jesus saiu da cidade com os discípulos e uma grande multidão, um mendigo cego chamado Bartimeu, filho de Timeu, estava sentado à beira do caminho."},
{"v":47,"t":"Quando ouviu que era Jesus de Nazaré, começou a gritar: Jesus, Filho de Davi, tenha compaixão de mim!"},
{"v":48,"t":"Muitos mandavam que se calasse. Mas ele gritava ainda mais: Filho de Davi, tenha compaixão de mim!"},
{"v":49,"t":"Jesus parou e disse: Chamem-no. Chamaram o cego e disseram: Coragem! Levante-se, ele está chamando você."},
{"v":50,"t":"O cego jogou a capa, levantou de um salto e foi até Jesus."},
{"v":51,"t":"Jesus perguntou: O que você quer que eu faça? O cego disse: Mestre, eu quero enxergar!"},
{"v":52,"t":"Jesus disse: Vá, a sua fé curou você. Na mesma hora, ele passou a enxergar e seguiu Jesus pelo caminho."},
]})

# Chapter 11
chapters.append({"c":11,"verses":[
{"v":1,"t":"Quando se aproximaram de Jerusalém, perto de Betfagé e Betânia, junto do Monte das Oliveiras, Jesus enviou dois discípulos."},
{"v":2,"t":"Disse: Vão à vila ali na frente. Assim que entrarem, vão encontrar um jumentinho amarrado, que ninguém nunca montou. Soltem-no e tragam."},
{"v":3,"t":"Se alguém perguntar por que estão fazendo isso, digam: O Senhor precisa dele. E logo o deixarão ir."},
{"v":4,"t":"Foram e encontraram o jumentinho amarrado na porta de uma casa, na rua. Soltaram-no."},
{"v":5,"t":"Algumas pessoas que estavam ali perguntaram: O que estão fazendo, soltando o jumentinho?"},
{"v":6,"t":"Responderam como Jesus mandou, e as deixaram ir."},
{"v":7,"t":"Trouxeram o jumentinho a Jesus, colocaram as capas sobre ele, e Jesus montou."},
{"v":8,"t":"Muitos estendiam as capas pelo caminho. Outros espalhavam galhos que cortavam dos campos."},
{"v":9,"t":"Os que iam na frente e os que vinham atrás gritavam: Hosana! Bendito o que vem em nome do Senhor!"},
{"v":10,"t":"Bendito o Reino do nosso pai Davi que está chegando! Hosana nas alturas!"},
{"v":11,"t":"Jesus entrou em Jerusalém e foi ao templo. Olhou tudo ao redor. Como já era tarde, saiu para Betânia com os doze."},
{"v":12,"t":"No dia seguinte, quando saíam de Betânia, Jesus sentiu fome."},
{"v":13,"t":"Viu de longe uma figueira com folhas. Chegou perto para ver se tinha frutos, mas só encontrou folhas, pois não era tempo de figos."},
{"v":14,"t":"Jesus disse à árvore: Nunca mais ninguém coma fruto de você! E os discípulos ouviram."},
{"v":15,"t":"Chegaram a Jerusalém. Jesus entrou no templo e começou a expulsar os que compravam e vendiam ali. Virou as mesas dos que trocavam dinheiro e as cadeiras dos que vendiam pombas."},
{"v":16,"t":"Não permitia que ninguém carregasse coisas pelo templo."},
{"v":17,"t":"E ensinava: Não está escrito: A minha casa será chamada casa de oração para todos os povos? Mas vocês a transformaram num esconderijo de ladrões!"},
{"v":18,"t":"Os chefes dos sacerdotes e os mestres da Lei ouviram e procuravam um jeito de matar Jesus. Tinham medo dele, porque toda a multidão ficava admirada com o ensino dele."},
{"v":19,"t":"Quando a tarde chegou, Jesus saiu da cidade."},
{"v":20,"t":"De manhã, passando pela figueira, viram que tinha secado desde a raiz."},
{"v":21,"t":"Pedro lembrou e disse: Mestre, veja! A figueira que o senhor amaldiçoou secou!"},
{"v":22,"t":"Jesus respondeu: Tenham fé em Deus."},
{"v":23,"t":"Eu digo a verdade: se alguém disser a este monte: Levante-se e jogue-se no mar, e não duvidar no coração, mas acreditar que vai acontecer, será feito."},
{"v":24,"t":"Por isso eu digo: tudo o que vocês pedirem em oração, acreditem que já receberam, e será de vocês."},
{"v":25,"t":"E quando estiverem orando, perdoem se tiverem algo contra alguém. Assim o Pai de vocês que está no céu perdoará as falhas de vocês."},
{"v":26,"t":"Mas se não perdoarem, o Pai de vocês que está no céu também não perdoará as falhas de vocês."},
{"v":27,"t":"Voltaram a Jerusalém. Enquanto Jesus andava pelo templo, os chefes dos sacerdotes, os mestres da Lei e os líderes se aproximaram."},
{"v":28,"t":"Perguntaram: Com que autoridade você faz essas coisas? Quem deu essa autoridade a você?"},
{"v":29,"t":"Jesus disse: Eu vou fazer uma pergunta. Respondam, e eu digo com que autoridade faço essas coisas."},
{"v":30,"t":"O batismo de João era de Deus ou dos homens? Respondam."},
{"v":31,"t":"Eles discutiam entre si: Se dissermos que era de Deus, ele vai perguntar por que não acreditamos."},
{"v":32,"t":"Se dissermos que era dos homens... Tinham medo do povo, porque todos achavam que João era um profeta de verdade."},
{"v":33,"t":"Responderam: Não sabemos. Jesus disse: Então eu também não digo com que autoridade faço essas coisas."},
]})

# Chapter 12
chapters.append({"c":12,"verses":[
{"v":1,"t":"Jesus começou a falar por histórias: Um homem plantou uma vinha, cercou com um muro, fez um tanque para pisar as uvas e construiu uma torre. Alugou para uns agricultores e viajou."},
{"v":2,"t":"Na época da colheita, mandou um empregado para receber a parte dele."},
{"v":3,"t":"Mas eles agarraram o empregado, bateram nele e o mandaram embora sem nada."},
{"v":4,"t":"Mandou outro empregado. Eles bateram na cabeça dele e o humilharam."},
{"v":5,"t":"Mandou outro, e o mataram. E muitos outros: alguns foram espancados, outros mortos."},
{"v":6,"t":"Tinha ainda um: o filho amado. Por último, mandou o filho, pensando: Vão respeitar o meu filho."},
{"v":7,"t":"Mas os agricultores disseram: Este é o herdeiro! Vamos matá-lo, e a herança será nossa!"},
{"v":8,"t":"Agarraram-no, mataram e jogaram para fora da vinha."},
{"v":9,"t":"O que o dono da vinha vai fazer? Vai destruir esses agricultores e dar a vinha a outros."},
{"v":10,"t":"Vocês não leram nas Escrituras: A pedra que os construtores rejeitaram se tornou a pedra principal."},
{"v":11,"t":"Isso veio do Senhor, e é maravilhoso para nós?"},
{"v":12,"t":"Queriam prendê-lo, pois entenderam que a história era contra eles. Mas tinham medo da multidão. Então o deixaram e foram embora."},
{"v":13,"t":"Mandaram alguns fariseus e partidários de Herodes para pegá-lo em alguma palavra."},
{"v":14,"t":"Eles disseram: Mestre, sabemos que o senhor é sincero e ensina o caminho de Deus com verdade. O senhor não se importa com a opinião de ninguém. É certo pagar impostos ao imperador romano ou não?"},
{"v":15,"t":"Jesus, percebendo a hipocrisia deles, disse: Por que estão me testando? Tragam uma moeda para eu ver."},
{"v":16,"t":"Trouxeram. Jesus perguntou: De quem é o rosto e o nome nesta moeda? Responderam: Do imperador."},
{"v":17,"t":"Jesus disse: Deem ao imperador o que é do imperador, e a Deus o que é de Deus. E ficaram admirados."},
{"v":18,"t":"Então os saduceus, que dizem que não existe ressurreição, vieram a Jesus com uma pergunta:"},
{"v":19,"t":"Mestre, Moisés escreveu que se um homem morrer sem filhos, o irmão deve se casar com a viúva para dar descendência ao irmão."},
{"v":20,"t":"Havia sete irmãos. O primeiro se casou e morreu sem filhos."},
{"v":21,"t":"O segundo se casou com ela e também morreu sem filhos. O mesmo com o terceiro."},
{"v":22,"t":"Os sete se casaram com ela e nenhum deixou filhos. Por último, a mulher também morreu."},
{"v":23,"t":"Na ressurreição, de qual deles ela será esposa, já que os sete se casaram com ela?"},
{"v":24,"t":"Jesus respondeu: Vocês estão errados porque não conhecem as Escrituras nem o poder de Deus."},
{"v":25,"t":"Quando ressuscitarem, não vão se casar. Serão como os anjos no céu."},
{"v":26,"t":"Sobre os mortos que ressuscitam, vocês não leram no livro de Moisés o que Deus disse na sarça: Eu sou o Deus de Abraão, o Deus de Isaque e o Deus de Jacó?"},
{"v":27,"t":"Ele não é Deus de mortos, mas de vivos. Vocês estão muito errados."},
{"v":28,"t":"Um mestre da Lei que ouviu a discussão e viu que Jesus respondeu bem perguntou: Qual é o mandamento mais importante de todos?"},
{"v":29,"t":"Jesus respondeu: O mais importante é: Ouça, Israel! O Senhor nosso Deus é o único Senhor."},
{"v":30,"t":"Ame o Senhor seu Deus de todo o coração, de toda a alma, de todo o pensamento e com todas as forças. Este é o primeiro mandamento."},
{"v":31,"t":"O segundo é: Ame o próximo como a si mesmo. Não há mandamento maior do que esses."},
{"v":32,"t":"O mestre da Lei disse: Muito bem, Mestre! O senhor disse a verdade: existe um só Deus e não há outro além dele."},
{"v":33,"t":"Amá-lo de todo o coração, pensamento, alma e forças, e amar o próximo como a si mesmo é mais importante que todos os sacrifícios e ofertas."},
{"v":34,"t":"Jesus viu que ele respondeu com sabedoria e disse: Você não está longe do Reino de Deus. Depois disso, ninguém mais ousou perguntar nada."},
{"v":35,"t":"Enquanto ensinava no templo, Jesus perguntou: Como os mestres da Lei dizem que o Cristo é filho de Davi?"},
{"v":36,"t":"O próprio Davi, inspirado pelo Espírito Santo, disse: O Senhor disse ao meu Senhor: Sente-se à minha direita até que eu ponha os seus inimigos debaixo dos seus pés."},
{"v":37,"t":"Se Davi o chama de Senhor, como pode ser filho dele? A grande multidão ouvia Jesus com prazer."},
{"v":38,"t":"Jesus ensinava: Cuidado com os mestres da Lei! Eles gostam de andar com roupas compridas e de ser cumprimentados nas praças."},
{"v":39,"t":"Gostam dos melhores assentos nas sinagogas e dos lugares de honra nos banquetes."},
{"v":40,"t":"Tomam as casas das viúvas e fazem orações longas para disfarçar. Receberão um castigo ainda maior."},
{"v":41,"t":"Jesus se sentou de frente para a caixa de ofertas e observava as pessoas colocando dinheiro. Muitos ricos colocavam bastante."},
{"v":42,"t":"Então veio uma viúva pobre e colocou duas moedinhas de pouco valor."},
{"v":43,"t":"Jesus chamou os discípulos e disse: Eu digo a verdade: esta viúva pobre colocou mais do que todos."},
{"v":44,"t":"Porque todos deram do que sobrava. Mas ela, da sua pobreza, deu tudo que tinha para viver."},
]})

# Chapter 13
chapters.append({"c":13,"verses":[
{"v":1,"t":"Quando Jesus saía do templo, um dos discípulos disse: Mestre, veja que pedras e que construções enormes!"},
{"v":2,"t":"Jesus respondeu: Você está vendo essas grandes construções? Não ficará pedra sobre pedra. Tudo será derrubado."},
{"v":3,"t":"Jesus se sentou no Monte das Oliveiras, de frente para o templo. Pedro, Tiago, João e André perguntaram em particular:"},
{"v":4,"t":"Quando isso vai acontecer? E qual será o sinal de que tudo isso está para se cumprir?"},
{"v":5,"t":"Jesus respondeu: Cuidado para ninguém enganar vocês."},
{"v":6,"t":"Muitos virão usando o meu nome e dizendo: Eu sou o Cristo. E vão enganar muitas pessoas."},
{"v":7,"t":"Quando ouvirem falar de guerras, não fiquem com medo. Essas coisas precisam acontecer, mas ainda não é o fim."},
{"v":8,"t":"Nação lutará contra nação. Haverá terremotos em muitos lugares, fome e sofrimento. Isso é apenas o começo das dores."},
{"v":9,"t":"Cuidem de vocês mesmos! Vocês serão entregues aos tribunais e açoitados nas sinagogas. Serão levados diante de governadores e reis por minha causa, como testemunho para eles."},
{"v":10,"t":"Primeiro, a boa notícia precisa ser pregada a todos os povos."},
{"v":11,"t":"Quando levarem vocês para serem julgados, não se preocupem com o que dizer. Digam o que lhes for dado naquela hora, porque não são vocês que falam, mas o Espírito Santo."},
{"v":12,"t":"O irmão entregará o irmão para morrer. O pai entregará o filho. Os filhos se levantarão contra os pais e os matarão."},
{"v":13,"t":"Todos vão odiar vocês por minha causa. Mas quem aguentar até o fim será salvo."},
{"v":14,"t":"Quando virem a coisa terrível e destruidora no lugar onde não devia estar — quem lê, entenda — os que estiverem na Judeia devem fugir para os montes."},
{"v":15,"t":"Quem estiver no terraço não desça nem entre em casa para pegar nada."},
{"v":16,"t":"Quem estiver no campo não volte para pegar a roupa."},
{"v":17,"t":"Ai das grávidas e das que estiverem amamentando naqueles dias!"},
{"v":18,"t":"Orem para que isso não aconteça no inverno."},
{"v":19,"t":"Porque haverá um sofrimento tão grande como nunca houve desde que Deus criou o mundo, e nunca mais haverá."},
{"v":20,"t":"Se o Senhor não reduzisse aqueles dias, ninguém sobreviveria. Mas por causa dos escolhidos, ele vai reduzir aqueles dias."},
{"v":21,"t":"Se alguém disser: Olha, o Cristo está aqui! Ou: Está ali! Não acreditem."},
{"v":22,"t":"Surgirão falsos cristos e falsos profetas. Farão sinais e milagres para enganar, se fosse possível, até os escolhidos."},
{"v":23,"t":"Fiquem atentos! Eu avisei vocês com antecedência."},
{"v":24,"t":"Naqueles dias, depois daquele sofrimento, o sol vai escurecer e a lua não vai brilhar."},
{"v":25,"t":"As estrelas vão cair do céu e os poderes do céu serão abalados."},
{"v":26,"t":"Então verão o Filho do Homem vindo nas nuvens com grande poder e glória."},
{"v":27,"t":"Ele enviará os anjos e reunirá os escolhidos dos quatro cantos, de uma ponta da terra à outra ponta do céu."},
{"v":28,"t":"Aprendam com a figueira: quando os galhos ficam verdes e as folhas brotam, vocês sabem que o verão está perto."},
{"v":29,"t":"Da mesma forma, quando virem essas coisas acontecendo, saibam que ele está perto, às portas."},
{"v":30,"t":"Eu digo a verdade: esta geração não passará sem que tudo isso aconteça."},
{"v":31,"t":"O céu e a terra vão passar, mas as minhas palavras nunca passarão."},
{"v":32,"t":"Ninguém sabe o dia nem a hora. Nem os anjos no céu, nem o Filho. Só o Pai sabe."},
{"v":33,"t":"Fiquem atentos! Vigiem e orem, porque vocês não sabem quando será o momento."},
{"v":34,"t":"É como um homem que viajou. Deixou a casa aos cuidados dos empregados, deu uma tarefa a cada um e mandou o porteiro ficar vigiando."},
{"v":35,"t":"Vigiem, porque vocês não sabem quando o dono da casa volta: se à tarde, à meia-noite, de madrugada ou ao amanhecer."},
{"v":36,"t":"Não deixem que ele chegue de surpresa e encontre vocês dormindo."},
{"v":37,"t":"O que eu digo a vocês, digo a todos: vigiem!"},
]})

# Chapter 14
chapters.append({"c":14,"verses":[
{"v":1,"t":"Faltavam dois dias para a Páscoa e a festa dos Pães sem Fermento. Os chefes dos sacerdotes e os mestres da Lei procuravam um jeito de prender Jesus com uma armadilha e matá-lo."},
{"v":2,"t":"Diziam: Não durante a festa, para não causar tumulto no povo."},
{"v":3,"t":"Jesus estava em Betânia, na casa de Simão, o leproso, sentado à mesa. Uma mulher chegou com um frasco de perfume de nardo puro, muito caro. Quebrou o frasco e derramou na cabeça de Jesus."},
{"v":4,"t":"Alguns ficaram indignados e disseram: Que desperdício de perfume!"},
{"v":5,"t":"Podia ser vendido por mais de trezentos salários e dado aos pobres. E a criticavam."},
{"v":6,"t":"Mas Jesus disse: Deixem-na. Por que a incomodam? Ela fez uma coisa bonita por mim."},
{"v":7,"t":"Os pobres vocês sempre terão e podem ajudá-los quando quiserem. Mas a mim vocês não terão sempre."},
{"v":8,"t":"Ela fez o que pôde. Preparou o meu corpo para o sepultamento antes da hora."},
{"v":9,"t":"Eu digo a verdade: em todo lugar do mundo onde a boa notícia for pregada, o que ela fez será contado em memória dela."},
{"v":10,"t":"Judas Iscariotes, um dos doze, foi aos chefes dos sacerdotes para entregar Jesus."},
{"v":11,"t":"Quando ouviram, ficaram contentes e prometeram pagar. Judas começou a procurar uma boa oportunidade."},
{"v":12,"t":"No primeiro dia da festa dos Pães sem Fermento, quando se preparava a Páscoa, os discípulos perguntaram: Onde o senhor quer que preparemos a ceia da Páscoa?"},
{"v":13,"t":"Jesus enviou dois discípulos e disse: Vão à cidade. Um homem carregando um jarro de água vai encontrar vocês. Sigam-no."},
{"v":14,"t":"Onde ele entrar, digam ao dono da casa: O Mestre pergunta: Onde está a sala em que vou comer a Páscoa com os meus discípulos?"},
{"v":15,"t":"Ele vai mostrar um salão grande no andar de cima, todo preparado. Preparem a ceia ali."},
{"v":16,"t":"Os discípulos saíram, foram à cidade, encontraram tudo como Jesus disse e prepararam a Páscoa."},
{"v":17,"t":"Quando a noite chegou, Jesus veio com os doze."},
{"v":18,"t":"Enquanto estavam à mesa comendo, Jesus disse: Eu digo a verdade: um de vocês, que está comendo comigo, vai me trair."},
{"v":19,"t":"Eles ficaram tristes. Um por um perguntou: Sou eu?"},
{"v":20,"t":"Jesus respondeu: É um dos doze, que está colocando a mão no prato comigo."},
{"v":21,"t":"O Filho do Homem vai, como está escrito. Mas ai daquele que trai o Filho do Homem! Seria melhor para ele não ter nascido."},
{"v":22,"t":"Enquanto comiam, Jesus pegou o pão, deu graças, partiu e deu a eles, dizendo: Peguem. Isto é o meu corpo."},
{"v":23,"t":"Pegou o cálice, deu graças e deu a eles. Todos beberam."},
{"v":24,"t":"Disse: Isto é o meu sangue, o sangue da nova aliança, derramado por muitos."},
{"v":25,"t":"Eu digo a verdade: não beberei mais deste vinho até o dia em que beber o vinho novo no Reino de Deus."},
{"v":26,"t":"Cantaram um hino e saíram para o Monte das Oliveiras."},
{"v":27,"t":"Jesus disse: Todos vocês vão me abandonar esta noite. Porque está escrito: Vou ferir o pastor, e as ovelhas se espalharão."},
{"v":28,"t":"Mas depois que eu ressuscitar, irei na frente de vocês para a Galileia."},
{"v":29,"t":"Pedro disse: Mesmo que todos o abandonem, eu não vou!"},
{"v":30,"t":"Jesus disse: Eu digo a verdade: hoje, esta noite, antes do galo cantar duas vezes, você vai me negar três vezes."},
{"v":31,"t":"Pedro insistiu: Mesmo que eu tenha que morrer com o senhor, nunca vou negá-lo! Todos disseram o mesmo."},
{"v":32,"t":"Foram a um lugar chamado Getsêmani. Jesus disse aos discípulos: Sentem-se aqui enquanto eu oro."},
{"v":33,"t":"Levou Pedro, Tiago e João. Começou a sentir pavor e angústia."},
{"v":34,"t":"Disse: A minha alma está cheia de tristeza, a ponto de morrer. Fiquem aqui e vigiem."},
{"v":35,"t":"Foi um pouco mais adiante, caiu no chão e orou para que, se possível, aquela hora passasse dele."},
{"v":36,"t":"Disse: Aba, Pai, tudo é possível para o senhor. Afaste de mim este cálice. Mas não seja o que eu quero, e sim o que o senhor quer."},
{"v":37,"t":"Voltou e encontrou os três dormindo. Disse a Pedro: Simão, você está dormindo? Não conseguiu vigiar nem uma hora?"},
{"v":38,"t":"Vigiem e orem para não caírem em tentação. O espírito quer fazer o certo, mas o corpo é fraco."},
{"v":39,"t":"Foi de novo e orou as mesmas palavras."},
{"v":40,"t":"Voltou e os encontrou dormindo outra vez. Os olhos deles estavam pesados. Não sabiam o que dizer."},
{"v":41,"t":"Voltou pela terceira vez e disse: Ainda dormindo e descansando? Chega. A hora chegou. O Filho do Homem está sendo entregue nas mãos dos pecadores."},
{"v":42,"t":"Levantem-se, vamos! O traidor está chegando."},
{"v":43,"t":"Naquele instante, chegou Judas, um dos doze, com uma grande multidão armada com espadas e paus, enviada pelos chefes dos sacerdotes, mestres da Lei e líderes."},
{"v":44,"t":"O traidor tinha combinado um sinal: Aquele que eu beijar é ele. Prendam-no e levem-no com segurança."},
{"v":45,"t":"Assim que chegou, se aproximou de Jesus e disse: Mestre! E o beijou."},
{"v":46,"t":"Eles agarraram Jesus e o prenderam."},
{"v":47,"t":"Um dos que estavam ali puxou a espada e atingiu o empregado do sumo sacerdote, cortando a orelha dele."},
{"v":48,"t":"Jesus disse: Vocês vieram me prender com espadas e paus, como se eu fosse um criminoso?"},
{"v":49,"t":"Todos os dias eu estava com vocês ensinando no templo, e vocês não me prenderam. Mas as Escrituras precisam se cumprir."},
{"v":50,"t":"Então todos o abandonaram e fugiram."},
{"v":51,"t":"Um jovem seguia Jesus, usando apenas um lençol sobre o corpo. Tentaram agarrá-lo."},
{"v":52,"t":"Mas ele largou o lençol e fugiu nu."},
{"v":53,"t":"Levaram Jesus ao sumo sacerdote. Todos os chefes dos sacerdotes, líderes e mestres da Lei se reuniram."},
{"v":54,"t":"Pedro o seguiu de longe até dentro do pátio do sumo sacerdote. Sentou-se com os guardas e se esquentava junto ao fogo."},
{"v":55,"t":"Os chefes dos sacerdotes e todo o conselho procuravam um testemunho contra Jesus para condená-lo à morte, mas não encontravam."},
{"v":56,"t":"Muitos davam falso testemunho, mas as histórias não batiam."},
{"v":57,"t":"Alguns se levantaram e mentiram:"},
{"v":58,"t":"Nós ouvimos ele dizer: Eu vou destruir este templo feito por mãos humanas e em três dias construir outro, sem mãos humanas."},
{"v":59,"t":"Mas nem assim as histórias combinavam."},
{"v":60,"t":"O sumo sacerdote se levantou e perguntou a Jesus: Não vai responder nada? O que essas pessoas dizem contra você?"},
{"v":61,"t":"Jesus ficou em silêncio e não respondeu. O sumo sacerdote perguntou de novo: Você é o Cristo, o Filho do Deus Bendito?"},
{"v":62,"t":"Jesus disse: Eu sou. E vocês verão o Filho do Homem sentado à direita do Poder e vindo nas nuvens do céu."},
{"v":63,"t":"O sumo sacerdote rasgou as roupas e disse: Não precisamos de mais testemunhas!"},
{"v":64,"t":"Vocês ouviram a ofensa a Deus. O que vocês acham? Todos o condenaram como digno de morte."},
{"v":65,"t":"Alguns começaram a cuspir nele, cobrir o rosto dele e dar socos, dizendo: Profetize! E os guardas davam tapas nele."},
{"v":66,"t":"Enquanto Pedro estava no pátio, uma das empregadas do sumo sacerdote se aproximou."},
{"v":67,"t":"Viu Pedro se esquentando e disse: Você também estava com Jesus, o Nazareno."},
{"v":68,"t":"Pedro negou: Não sei do que você está falando. Saiu para a entrada, e o galo cantou."},
{"v":69,"t":"A empregada o viu de novo e disse aos que estavam ali: Esse é um deles."},
{"v":70,"t":"Pedro negou outra vez. Pouco depois, os que estavam ali disseram: Com certeza você é um deles! Você também é galileu, e o sotaque entrega."},
{"v":71,"t":"Pedro começou a amaldiçoar e jurar: Eu não conheço esse homem de quem vocês falam!"},
{"v":72,"t":"Na mesma hora, o galo cantou pela segunda vez. Pedro lembrou das palavras de Jesus: Antes do galo cantar duas vezes, você vai me negar três vezes. E caiu no choro."},
]})

# Chapter 15
chapters.append({"c":15,"verses":[
{"v":1,"t":"Logo de manhã cedo, os chefes dos sacerdotes com os líderes, mestres da Lei e todo o conselho fizeram uma reunião. Amarraram Jesus, levaram e entregaram a Pilatos."},
{"v":2,"t":"Pilatos perguntou: Você é o Rei dos Judeus? Jesus respondeu: Você mesmo está dizendo."},
{"v":3,"t":"Os chefes dos sacerdotes o acusavam de muitas coisas."},
{"v":4,"t":"Pilatos perguntou de novo: Não vai responder nada? Veja quantas acusações fazem contra você!"},
{"v":5,"t":"Mas Jesus não respondeu mais nada. Pilatos ficou surpreso."},
{"v":6,"t":"Na festa, Pilatos costumava soltar um preso que o povo pedisse."},
{"v":7,"t":"Havia um preso chamado Barrabás, que junto com outros rebeldes tinha cometido um assassinato."},
{"v":8,"t":"A multidão se aproximou e começou a pedir que Pilatos fizesse como de costume."},
{"v":9,"t":"Pilatos perguntou: Vocês querem que eu solte o Rei dos Judeus?"},
{"v":10,"t":"Porque sabia que os chefes dos sacerdotes tinham entregado Jesus por inveja."},
{"v":11,"t":"Mas os chefes dos sacerdotes incitaram a multidão a pedir que soltasse Barrabás."},
{"v":12,"t":"Pilatos perguntou de novo: Então o que faço com aquele que vocês chamam de Rei dos Judeus?"},
{"v":13,"t":"Gritaram: Crucifique!"},
{"v":14,"t":"Pilatos disse: Mas que mal ele fez? Eles gritaram ainda mais: Crucifique!"},
{"v":15,"t":"Querendo agradar a multidão, Pilatos soltou Barrabás. Mandou açoitar Jesus e o entregou para ser crucificado."},
{"v":16,"t":"Os soldados levaram Jesus para dentro do palácio e reuniram toda a tropa."},
{"v":17,"t":"Colocaram nele um manto roxo e fizeram uma coroa de espinhos, que puseram na cabeça dele."},
{"v":18,"t":"Começaram a saudá-lo: Salve, Rei dos Judeus!"},
{"v":19,"t":"Batiam na cabeça dele com uma vara, cuspiam nele e se ajoelhavam, fingindo adorá-lo."},
{"v":20,"t":"Depois de zombar, tiraram o manto, colocaram as roupas dele de volta e o levaram para crucificar."},
{"v":21,"t":"Obrigaram um homem que passava, Simão de Cirene, pai de Alexandre e Rufo, que vinha do campo, a carregar a cruz de Jesus."},
{"v":22,"t":"Levaram Jesus ao lugar chamado Gólgota, que quer dizer Lugar da Caveira."},
{"v":23,"t":"Ofereceram vinho misturado com mirra, mas ele não aceitou."},
{"v":24,"t":"Crucificaram-no e dividiram as roupas dele entre si, tirando sortes."},
{"v":25,"t":"Eram nove horas da manhã quando o crucificaram."},
{"v":26,"t":"A acusação escrita dizia: O REI DOS JUDEUS."},
{"v":27,"t":"Crucificaram dois criminosos com ele, um à direita e outro à esquerda."},
{"v":28,"t":"Assim se cumpriu a Escritura que diz: Ele foi contado entre os criminosos."},
{"v":29,"t":"Os que passavam insultavam Jesus, balançando a cabeça e dizendo: Você que destrói o templo e reconstrói em três dias,"},
{"v":30,"t":"salve a si mesmo e desça da cruz!"},
{"v":31,"t":"Os chefes dos sacerdotes e os mestres da Lei também zombavam entre si: Salvou outros, mas não pode salvar a si mesmo!"},
{"v":32,"t":"Que o Cristo, o Rei de Israel, desça agora da cruz para que vejamos e acreditemos! Até os criminosos crucificados com ele o insultavam."},
{"v":33,"t":"Do meio-dia às três da tarde, uma escuridão cobriu toda a terra."},
{"v":34,"t":"Às três da tarde, Jesus gritou com voz forte: Eloí, Eloí, lamá sabactâni? Que quer dizer: Deus meu, Deus meu, por que me abandonou?"},
{"v":35,"t":"Alguns que estavam ali ouviram e disseram: Olha, ele está chamando Elias!"},
{"v":36,"t":"Um deles correu, encheu uma esponja de vinagre, colocou numa vara e deu a Jesus para beber, dizendo: Esperem! Vamos ver se Elias vem tirá-lo."},
{"v":37,"t":"Jesus deu um grito forte e morreu."},
{"v":38,"t":"A cortina do templo se rasgou em duas partes, de cima a baixo."},
{"v":39,"t":"O oficial romano que estava de frente para Jesus viu como ele morreu e disse: Este homem era mesmo o Filho de Deus!"},
{"v":40,"t":"Algumas mulheres observavam de longe. Entre elas estavam Maria Madalena, Maria, mãe de Tiago, o menor, e de José, e Salomé."},
{"v":41,"t":"Elas tinham seguido e servido Jesus na Galileia. Muitas outras mulheres que tinham subido com ele a Jerusalém também estavam ali."},
{"v":42,"t":"Quando a tarde chegou, como era dia de Preparação, véspera do sábado,"},
{"v":43,"t":"veio José de Arimateia, um membro respeitado do conselho, que também esperava o Reino de Deus. Ele tomou coragem, foi a Pilatos e pediu o corpo de Jesus."},
{"v":44,"t":"Pilatos se surpreendeu que Jesus já tivesse morrido. Chamou o oficial e perguntou se fazia tempo."},
{"v":45,"t":"Confirmado pelo oficial, entregou o corpo a José."},
{"v":46,"t":"José comprou um tecido de linho, tirou o corpo da cruz, envolveu no tecido e o colocou num túmulo cavado na rocha. Rolou uma pedra na entrada do túmulo."},
{"v":47,"t":"Maria Madalena e Maria, mãe de José, viram onde ele foi colocado."},
]})

# Chapter 16
chapters.append({"c":16,"verses":[
{"v":1,"t":"Quando o sábado terminou, Maria Madalena, Maria, mãe de Tiago, e Salomé compraram perfumes para ungir o corpo de Jesus."},
{"v":2,"t":"No primeiro dia da semana, bem cedo, ao nascer do sol, foram ao túmulo."},
{"v":3,"t":"Perguntavam umas às outras: Quem vai rolar a pedra da entrada do túmulo para nós?"},
{"v":4,"t":"Quando olharam, viram que a pedra já tinha sido rolada. E era muito grande."},
{"v":5,"t":"Entraram no túmulo e viram um jovem vestido de branco sentado à direita. Ficaram assustadas."},
{"v":6,"t":"Ele disse: Não fiquem assustadas. Vocês estão procurando Jesus de Nazaré, o crucificado. Ele ressuscitou! Não está aqui. Vejam o lugar onde o colocaram."},
{"v":7,"t":"Vão e digam aos discípulos e a Pedro que ele vai na frente de vocês para a Galileia. Lá vocês vão vê-lo, como ele disse."},
{"v":8,"t":"Elas saíram correndo do túmulo, tremendo e assustadas. Não contaram nada a ninguém, porque estavam com medo."},
{"v":9,"t":"Depois de ressuscitar na manhã do primeiro dia da semana, Jesus apareceu primeiro a Maria Madalena, da qual tinha expulsado sete demônios."},
{"v":10,"t":"Ela foi contar aos que tinham estado com Jesus, que estavam tristes e chorando."},
{"v":11,"t":"Quando ouviram que ele estava vivo e que ela o tinha visto, não acreditaram."},
{"v":12,"t":"Depois disso, Jesus apareceu com outra aparência a dois deles que iam caminhando para o campo."},
{"v":13,"t":"Eles voltaram e contaram aos outros, mas também não acreditaram."},
{"v":14,"t":"Por fim, apareceu aos onze enquanto estavam comendo. Criticou a falta de fé e a teimosia deles por não terem acreditado nos que o viram ressuscitado."},
{"v":15,"t":"E disse: Vão pelo mundo inteiro e anunciem a boa notícia a toda pessoa."},
{"v":16,"t":"Quem crer e for batizado será salvo. Mas quem não crer será condenado."},
{"v":17,"t":"Estes sinais vão acompanhar os que crerem: em meu nome expulsarão demônios e falarão novas línguas."},
{"v":18,"t":"Pegarão em cobras. Se beberem algo venenoso, não fará mal. Colocarão as mãos sobre os doentes, e eles ficarão curados."},
{"v":19,"t":"Depois de falar com eles, o Senhor Jesus foi elevado ao céu e se sentou à direita de Deus."},
{"v":20,"t":"Os discípulos saíram e pregaram por toda parte. O Senhor trabalhava com eles e confirmava a palavra com os sinais que a acompanhavam. Amém."},
]})

# Save chapters 9-16
out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'static', 'data', 'bfl', 'marcos_trans_p2.json')
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(chapters, f, ensure_ascii=False, indent=None, separators=(',',':'))

print(f"Mark chapters 9-16 ready: {sum(len(c['verses']) for c in chapters)} verses")
