#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""BFL Translation of Romans (Romanos) - Chapters 1-8"""
import json

chapters = []

# Chapter 1 - Introduction, God's wrath
chapters.append({"c":1,"verses":[
{"v":1,"t":"Paulo, servo de Cristo Jesus, chamado para ser apóstolo, separado para a boa notícia de Deus."},
{"v":2,"t":"Deus já tinha prometido essa boa notícia por meio dos seus profetas nas Escrituras Sagradas."},
{"v":3,"t":"Ela é sobre o seu Filho. Na sua natureza humana, ele nasceu da família de Davi."},
{"v":4,"t":"Pela sua natureza santa, ele foi declarado Filho de Deus com poder pela ressurreição dos mortos. Ele é Jesus Cristo, nosso Senhor."},
{"v":5,"t":"Por meio dele recebemos a graça e a missão de apóstolo. A missão é levar pessoas de todas as nações a crer e a obedecer, para a honra do seu nome."},
{"v":6,"t":"Vocês também estão entre os chamados para pertencer a Jesus Cristo."},
{"v":7,"t":"A todos em Roma que são amados por Deus e chamados para ser santos: graça e paz da parte de Deus nosso Pai e do Senhor Jesus Cristo."},
{"v":8,"t":"Antes de tudo, eu agradeço ao meu Deus por meio de Jesus Cristo por todos vocês. A fé de vocês é comentada no mundo inteiro."},
{"v":9,"t":"Deus, a quem sirvo de todo o coração anunciando a boa notícia do seu Filho, é minha testemunha de que eu lembro de vocês sempre nas minhas orações."},
{"v":10,"t":"Peço que, se for da vontade de Deus, eu possa finalmente ir visitá-los."},
{"v":11,"t":"Eu desejo muito ver vocês para compartilhar algum dom espiritual que os fortaleça."},
{"v":12,"t":"Quero dizer, para que nos encorajemos mutuamente pela fé que temos, vocês e eu."},
{"v":13,"t":"Irmãos, quero que saibam que muitas vezes planejei ir até vocês, mas fui impedido até agora. Quero ter algum fruto entre vocês, assim como entre os outros não judeus."},
{"v":14,"t":"Tenho obrigação tanto com os gregos como com os não gregos, tanto com os sábios como com os simples."},
{"v":15,"t":"Por isso estou ansioso para anunciar a boa notícia também a vocês que estão em Roma."},
{"v":16,"t":"Eu não tenho vergonha da boa notícia. Ela é o poder de Deus para salvar todo aquele que crê. Primeiro para o judeu, depois para o não judeu."},
{"v":17,"t":"Nela se revela a justiça de Deus. Essa justiça vem pela fé e leva à fé, como está escrito: O justo viverá pela fé."},
{"v":18,"t":"A ira de Deus se revela do céu contra toda a falta de respeito a Deus e toda a injustiça das pessoas. Elas usam a injustiça para sufocar a verdade."},
{"v":19,"t":"Aquilo que se pode conhecer sobre Deus é visível para elas. O próprio Deus tornou isso claro."},
{"v":20,"t":"Desde a criação do mundo, as qualidades invisíveis de Deus podem ser vistas claramente nas coisas que ele criou: o seu poder eterno e a sua natureza divina. Por isso ninguém tem desculpa."},
{"v":21,"t":"Mesmo conhecendo Deus, não o honraram como Deus nem agradeceram a ele. Seus pensamentos se tornaram inúteis e seus corações insensatos ficaram no escuro."},
{"v":22,"t":"Dizendo que eram sábios, tornaram-se tolos."},
{"v":23,"t":"Trocaram a glória do Deus imortal por imagens de seres humanos mortais, aves, animais e répteis."},
{"v":24,"t":"Por isso Deus os entregou aos desejos dos seus corações, à impureza, para desonrarem seus próprios corpos entre si."},
{"v":25,"t":"Trocaram a verdade de Deus pela mentira. Adoraram e serviram as coisas criadas em vez do Criador, que é bendito para sempre. Amém."},
{"v":26,"t":"Por isso Deus os entregou a paixões vergonhosas. As mulheres trocaram as relações naturais por relações que vão contra a natureza."},
{"v":27,"t":"Da mesma forma, os homens abandonaram as relações naturais com as mulheres e se inflamaram de paixão uns pelos outros. Homens cometeram atos vergonhosos com homens e receberam em si mesmos o castigo que mereciam."},
{"v":28,"t":"Como não acharam importante conhecer a Deus, ele os entregou a uma mente corrompida para fazerem o que não deviam."},
{"v":29,"t":"Ficaram cheios de todo tipo de injustiça, maldade, ganância e ruindade. Cheios de inveja, assassinato, brigas, engano e maldade."},
{"v":30,"t":"São fofoqueiros, caluniadores, inimigos de Deus, arrogantes, orgulhosos, presunçosos, inventores de maldades e desobedientes aos pais."},
{"v":31,"t":"São sem entendimento, sem fidelidade, sem amor e sem misericórdia."},
{"v":32,"t":"Embora conheçam a lei de Deus que diz que quem pratica essas coisas merece a morte, não apenas continuam fazendo, mas também aplaudem os que fazem."},
]})

# Chapter 2 - God's righteous judgment
chapters.append({"c":2,"verses":[
{"v":1,"t":"Portanto, você não tem desculpa, quem quer que seja, quando julga o outro. Porque ao julgar, você se condena. Você que julga pratica as mesmas coisas."},
{"v":2,"t":"Sabemos que Deus julga com verdade os que praticam essas coisas."},
{"v":3,"t":"Você que julga os outros mas faz a mesma coisa, acha que vai escapar do juízo de Deus?"},
{"v":4,"t":"Ou será que você não dá valor à riqueza da bondade, da paciência e da tolerância de Deus? Não sabe que a bondade de Deus quer levar você ao arrependimento?"},
{"v":5,"t":"Mas com o seu coração teimoso e sem arrependimento, você está juntando ira para si mesmo no dia da ira. Nesse dia Deus mostrará o seu juízo justo."},
{"v":6,"t":"Deus vai dar a cada pessoa conforme o que ela fez."},
{"v":7,"t":"Vida eterna para os que perseveram em fazer o bem e buscam glória, honra e imortalidade."},
{"v":8,"t":"Mas ira e fúria para os que são egoístas, rejeitam a verdade e seguem a injustiça."},
{"v":9,"t":"Sofrimento e angústia para todo ser humano que pratica o mal. Primeiro para o judeu, depois para o não judeu."},
{"v":10,"t":"Mas glória, honra e paz para todo aquele que pratica o bem. Primeiro para o judeu, depois para o não judeu."},
{"v":11,"t":"Porque Deus não faz diferença entre as pessoas."},
{"v":12,"t":"Todos os que pecaram sem conhecer a lei vão morrer sem a lei. E todos os que pecaram conhecendo a lei serão julgados pela lei."},
{"v":13,"t":"Porque não são os que apenas ouvem a lei que são justos diante de Deus. Os que praticam a lei é que serão declarados justos."},
{"v":14,"t":"Quando os não judeus, que não têm a lei, fazem por natureza o que a lei manda, eles são lei para si mesmos, mesmo sem ter a lei."},
{"v":15,"t":"Eles mostram que o que a lei exige está escrito no coração deles. A consciência deles confirma isso. Seus pensamentos ora os acusam, ora os defendem."},
{"v":16,"t":"Isso vai acontecer no dia em que Deus, por meio de Jesus Cristo, julgar os segredos das pessoas. Como diz a boa notícia que eu prego."},
{"v":17,"t":"Mas se você se chama de judeu e confia na lei e se orgulha de Deus,"},
{"v":18,"t":"e conhece a vontade dele e sabe o que é melhor porque foi instruído na lei,"},
{"v":19,"t":"e tem certeza de que é guia de cegos, luz para os que estão no escuro,"},
{"v":20,"t":"educador dos ignorantes e mestre de crianças, porque tem na lei a base do conhecimento e da verdade:"},
{"v":21,"t":"Então, você que ensina os outros não ensina a si mesmo? Você que prega contra o roubo, rouba?"},
{"v":22,"t":"Você que diz para não cometer adultério, comete? Você que detesta ídolos, rouba templos?"},
{"v":23,"t":"Você que se orgulha da lei, desonra a Deus quando desobedece à lei?"},
{"v":24,"t":"Porque, como está escrito: O nome de Deus é falado mal entre as nações por causa de vocês."},
{"v":25,"t":"A circuncisão tem valor se você obedece à lei. Mas se você desobedece à lei, é como se não fosse circuncidado."},
{"v":26,"t":"Se quem não é circuncidado obedece ao que a lei exige, Deus não vai tratá-lo como se fosse circuncidado?"},
{"v":27,"t":"E quem não é circuncidado fisicamente, mas obedece à lei, vai condenar você. Porque você tem a lei escrita e a circuncisão, mas desobedece à lei."},
{"v":28,"t":"Ser judeu de verdade não é algo que se vê por fora. E a verdadeira circuncisão não é a que aparece no corpo."},
{"v":29,"t":"Judeu de verdade é quem é judeu por dentro. A verdadeira circuncisão é a do coração, feita pelo Espírito, não pela letra da lei. Quem é assim recebe o louvor de Deus, não das pessoas."},
]})

# Chapter 3 - No one is righteous; justification by faith
chapters.append({"c":3,"verses":[
{"v":1,"t":"Então, qual é a vantagem de ser judeu? Qual é o valor da circuncisão?"},
{"v":2,"t":"Muito, em todos os sentidos! Antes de tudo, foi aos judeus que Deus confiou a sua palavra."},
{"v":3,"t":"E se alguns não creram? A falta de fé deles vai anular a fidelidade de Deus?"},
{"v":4,"t":"De jeito nenhum! Deus é verdadeiro, mesmo que todo ser humano seja mentiroso. Como está escrito: Para que sejas reconhecido como justo nas tuas palavras e vencedor quando fores julgado."},
{"v":5,"t":"Mas se a nossa injustiça faz brilhar a justiça de Deus, o que diremos? Que Deus é injusto quando nos castiga? Falo em termos humanos."},
{"v":6,"t":"De jeito nenhum! Se fosse assim, como Deus poderia julgar o mundo?"},
{"v":7,"t":"Mas se a minha mentira faz a verdade de Deus brilhar ainda mais para a glória dele, por que ainda sou julgado como pecador?"},
{"v":8,"t":"E por que não dizer, como alguns nos acusam falsamente de ensinar: Vamos fazer o mal para que venha o bem? A condenação dessas pessoas é justa."},
{"v":9,"t":"Então, nós judeus somos melhores? De jeito nenhum! Já mostramos que todos, judeus e não judeus, estão debaixo do pecado."},
{"v":10,"t":"Como está escrito: Não há ninguém justo, nem um sequer."},
{"v":11,"t":"Não há ninguém que entenda. Não há ninguém que busque a Deus."},
{"v":12,"t":"Todos se desviaram. Juntos se tornaram inúteis. Não há quem faça o bem, nem um sequer."},
{"v":13,"t":"A garganta deles é um túmulo aberto. Com a língua enganam. Veneno de cobra está nos seus lábios."},
{"v":14,"t":"A boca deles está cheia de maldição e amargura."},
{"v":15,"t":"Os pés deles são rápidos para derramar sangue."},
{"v":16,"t":"Destruição e miséria marcam os seus caminhos."},
{"v":17,"t":"Eles não conhecem o caminho da paz."},
{"v":18,"t":"Não existe temor de Deus diante dos olhos deles."},
{"v":19,"t":"Sabemos que tudo o que a lei diz, diz para os que estão debaixo da lei. Para que toda boca se cale e o mundo inteiro esteja sujeito ao juízo de Deus."},
{"v":20,"t":"Por isso ninguém será declarado justo diante de Deus por obedecer a lei. A lei serve para nos mostrar o pecado."},
{"v":21,"t":"Mas agora, sem depender da lei, Deus revelou a sua justiça. A Lei e os Profetas já testemunhavam sobre isso."},
{"v":22,"t":"A justiça de Deus vem pela fé em Jesus Cristo para todos os que creem. Não há diferença,"},
{"v":23,"t":"porque todos pecaram e estão longe da glória de Deus."},
{"v":24,"t":"Mas são declarados justos de graça, pela sua bondade, por meio da redenção que há em Cristo Jesus."},
{"v":25,"t":"Deus ofereceu Jesus como sacrifício que traz o perdão por meio da fé no seu sangue. Fez isso para mostrar a sua justiça, porque em sua paciência tinha deixado os pecados do passado sem castigo."},
{"v":26,"t":"Fez isso para mostrar a sua justiça no tempo presente. Assim ele é justo e ao mesmo tempo declara justo aquele que tem fé em Jesus."},
{"v":27,"t":"Então, onde fica o motivo de orgulho? Não existe! Com base em que lei? Na lei das obras? Não! Com base na lei da fé."},
{"v":28,"t":"Porque nós afirmamos que a pessoa é declarada justa por Deus pela fé, sem depender de obedecer a lei."},
{"v":29,"t":"Deus é Deus só dos judeus? Não é também dos não judeus? Sim, dos não judeus também!"},
{"v":30,"t":"Já que há um só Deus, ele vai declarar justos tanto os circuncidados como os não circuncidados pela fé."},
{"v":31,"t":"Então a fé anula a lei? De jeito nenhum! Pelo contrário, a fé confirma a lei."},
]})

# Chapter 4 - Abraham justified by faith
chapters.append({"c":4,"verses":[
{"v":1,"t":"Então, o que diremos que Abraão, nosso antepassado, descobriu?"},
{"v":2,"t":"Se Abraão foi declarado justo por Deus pelas obras, ele teria motivo para se orgulhar. Mas não diante de Deus."},
{"v":3,"t":"O que diz a Escritura? Abraão creu em Deus, e isso lhe foi contado como justiça."},
{"v":4,"t":"Quem trabalha não recebe o salário como presente, mas como algo que lhe é devido."},
{"v":5,"t":"Porém, quem não trabalha mas crê naquele que declara justo o pecador, a sua fé é contada como justiça."},
{"v":6,"t":"Davi diz a mesma coisa quando fala da felicidade da pessoa a quem Deus declara justa sem depender de obras:"},
{"v":7,"t":"Felizes aqueles cujas maldades foram perdoadas e cujos pecados foram cobertos."},
{"v":8,"t":"Feliz o homem cujo pecado o Senhor não leva em conta."},
{"v":9,"t":"Essa felicidade é só para os circuncidados ou também para os não circuncidados? Dissemos que a fé de Abraão foi contada como justiça."},
{"v":10,"t":"Quando isso aconteceu? Depois ou antes de ele ser circuncidado? Não foi depois, mas antes!"},
{"v":11,"t":"Abraão recebeu a circuncisão como sinal, como selo da justiça que ele já tinha recebido pela fé antes de ser circuncidado. Isso para que ele fosse o pai de todos os que creem sem ser circuncidados, para que a justiça também fosse contada a eles."},
{"v":12,"t":"E também para ser pai dos circuncidados que não são apenas circuncidados, mas que também seguem o exemplo de fé que nosso pai Abraão teve antes de ser circuncidado."},
{"v":13,"t":"A promessa de que Abraão e seus descendentes seriam herdeiros do mundo não veio pela lei. Veio pela justiça que vem da fé."},
{"v":14,"t":"Se os herdeiros são os que dependem da lei, então a fé não serve para nada e a promessa fica sem valor."},
{"v":15,"t":"Porque a lei produz ira. Onde não há lei, também não há transgressão."},
{"v":16,"t":"Por isso a promessa vem pela fé, para que seja pela graça. Assim a promessa é garantida a todos os descendentes de Abraão. Não só aos que têm a lei, mas também aos que têm a fé de Abraão. Ele é o pai de todos nós."},
{"v":17,"t":"Como está escrito: Eu fiz de você pai de muitas nações. Ele é nosso pai diante de Deus, em quem creu. O Deus que dá vida aos mortos e chama as coisas que não existem como se existissem."},
{"v":18,"t":"Contra toda esperança, Abraão creu com esperança. Assim se tornou pai de muitas nações, conforme lhe foi dito: Assim será a sua descendência."},
{"v":19,"t":"Sua fé não enfraqueceu quando pensou no seu próprio corpo, já quase morto (tinha cerca de cem anos), e no ventre sem vida de Sara."},
{"v":20,"t":"Diante da promessa de Deus, ele não duvidou por falta de fé. Pelo contrário, ficou forte na fé e deu glória a Deus."},
{"v":21,"t":"Estava totalmente convencido de que Deus tinha poder para cumprir o que havia prometido."},
{"v":22,"t":"Por isso a fé dele foi contada como justiça."},
{"v":23,"t":"Mas as palavras foi contada a ele não foram escritas só para Abraão."},
{"v":24,"t":"Foram escritas também para nós. A justiça será contada a nós que cremos naquele que ressuscitou Jesus nosso Senhor dos mortos."},
{"v":25,"t":"Jesus foi entregue à morte por causa dos nossos pecados e ressuscitou para que fôssemos declarados justos por Deus."},
]})

# Chapter 5 - Peace with God, Adam and Christ
chapters.append({"c":5,"verses":[
{"v":1,"t":"Portanto, já que fomos declarados justos por Deus pela fé, temos paz com Deus por meio do nosso Senhor Jesus Cristo."},
{"v":2,"t":"Por meio dele temos acesso pela fé a esta graça na qual estamos firmes. E nos alegramos na esperança de participar da glória de Deus."},
{"v":3,"t":"Não apenas isso, mas também nos alegramos nos sofrimentos. Porque sabemos que o sofrimento produz perseverança."},
{"v":4,"t":"A perseverança produz caráter aprovado. E o caráter aprovado produz esperança."},
{"v":5,"t":"E a esperança não nos decepciona, porque o amor de Deus foi derramado em nossos corações pelo Espírito Santo que nos foi dado."},
{"v":6,"t":"Quando ainda éramos fracos, no tempo certo, Cristo morreu pelos que não tinham Deus."},
{"v":7,"t":"Dificilmente alguém morreria por uma pessoa justa. Talvez alguém tivesse coragem de morrer por uma pessoa boa."},
{"v":8,"t":"Mas Deus prova o seu amor por nós: Cristo morreu por nós quando ainda éramos pecadores."},
{"v":9,"t":"Já que fomos declarados justos pelo sangue dele, com muito mais razão seremos salvos da ira de Deus por meio dele."},
{"v":10,"t":"Se quando éramos inimigos de Deus fomos reconciliados com ele pela morte do seu Filho, muito mais agora, reconciliados, seremos salvos pela vida dele."},
{"v":11,"t":"E não só isso. Também nos alegramos em Deus por meio do nosso Senhor Jesus Cristo, por quem recebemos a reconciliação."},
{"v":12,"t":"O pecado entrou no mundo por meio de um só homem. E pelo pecado veio a morte. Assim a morte passou a todos os seres humanos, porque todos pecaram."},
{"v":13,"t":"Antes de existir a lei, já havia pecado no mundo. Mas o pecado não é contado quando não existe lei."},
{"v":14,"t":"Mesmo assim, a morte reinou desde Adão até Moisés. Até sobre aqueles que não pecaram da mesma forma que Adão, que é uma figura daquele que viria."},
{"v":15,"t":"Mas o presente de Deus não é como a transgressão. Se pela transgressão de um só morreram muitos, muito mais a graça de Deus e o presente pela graça de um só homem, Jesus Cristo, transbordou para muitos."},
{"v":16,"t":"O resultado do presente de Deus é diferente do resultado do pecado de um só homem. O juízo veio por causa de uma transgressão e trouxe condenação. Mas o presente de Deus veio depois de muitas transgressões e trouxe o veredicto de justo."},
{"v":17,"t":"Se pela transgressão de um só a morte reinou por meio desse um, muito mais os que recebem a abundância da graça e do presente da justiça reinarão em vida por meio de um só: Jesus Cristo."},
{"v":18,"t":"Portanto, assim como uma só transgressão trouxe condenação a todos, assim também um só ato de justiça trouxe a todos a possibilidade de serem declarados justos e ter vida."},
{"v":19,"t":"Como pela desobediência de um só homem muitos se tornaram pecadores, assim pela obediência de um só muitos serão declarados justos."},
{"v":20,"t":"A lei entrou para que a transgressão aumentasse. Mas onde o pecado aumentou, a graça aumentou muito mais."},
{"v":21,"t":"Assim como o pecado reinou trazendo a morte, a graça reina pela justiça para trazer vida eterna por meio de Jesus Cristo nosso Senhor."},
]})

# Chapter 6 - Dead to sin, alive in Christ
chapters.append({"c":6,"verses":[
{"v":1,"t":"Então, o que diremos? Vamos continuar pecando para que a graça aumente?"},
{"v":2,"t":"De jeito nenhum! Nós que morremos para o pecado, como vamos continuar vivendo nele?"},
{"v":3,"t":"Vocês não sabem que todos nós que fomos batizados em Cristo Jesus fomos batizados na morte dele?"},
{"v":4,"t":"Fomos sepultados com ele pelo batismo na morte. Assim como Cristo foi ressuscitado dos mortos pela glória do Pai, nós também devemos viver uma vida nova."},
{"v":5,"t":"Se fomos unidos com ele na semelhança da sua morte, também seremos na semelhança da sua ressurreição."},
{"v":6,"t":"Sabemos que o nosso velho eu foi crucificado com Cristo. O corpo dominado pelo pecado foi desativado, para que não sejamos mais escravos do pecado."},
{"v":7,"t":"Porque quem morreu foi libertado do pecado."},
{"v":8,"t":"Se morremos com Cristo, cremos que também viveremos com ele."},
{"v":9,"t":"Sabemos que Cristo, depois de ressuscitar dos mortos, não morre mais. A morte não tem mais poder sobre ele."},
{"v":10,"t":"Quando morreu, morreu para o pecado uma vez por todas. Agora que vive, vive para Deus."},
{"v":11,"t":"Da mesma forma, vocês também devem se considerar mortos para o pecado e vivos para Deus em Cristo Jesus."},
{"v":12,"t":"Portanto, não deixem o pecado reinar no corpo mortal de vocês para obedecer aos desejos dele."},
{"v":13,"t":"Não ofereçam partes do corpo de vocês ao pecado como instrumentos de injustiça. Em vez disso, ofereçam-se a Deus como pessoas que voltaram da morte para a vida. E ofereçam as partes do corpo de vocês a Deus como instrumentos de justiça."},
{"v":14,"t":"O pecado não terá domínio sobre vocês, porque vocês não estão debaixo da lei, mas debaixo da graça."},
{"v":15,"t":"Então? Vamos pecar porque não estamos debaixo da lei, mas debaixo da graça? De jeito nenhum!"},
{"v":16,"t":"Vocês não sabem que quando se oferecem a alguém para obedecer, vocês são escravos daquele a quem obedecem? Ou do pecado, que leva à morte, ou da obediência, que leva à justiça."},
{"v":17,"t":"Mas graças a Deus! Vocês eram escravos do pecado, mas obedeceram de coração à forma de ensino que receberam."},
{"v":18,"t":"Libertados do pecado, vocês se tornaram servos da justiça."},
{"v":19,"t":"Falo em termos simples por causa da fraqueza humana de vocês. Assim como vocês ofereceram partes do corpo como escravas da impureza e da maldade, agora ofereçam como escravas da justiça para a santidade."},
{"v":20,"t":"Quando eram escravos do pecado, vocês estavam livres da justiça."},
{"v":21,"t":"Que fruto vocês colheram daquelas coisas de que agora têm vergonha? O resultado delas é a morte."},
{"v":22,"t":"Mas agora, libertados do pecado e servos de Deus, o fruto que vocês colhem leva à santidade. E o resultado é a vida eterna."},
{"v":23,"t":"Porque o salário do pecado é a morte. Mas o presente de Deus é a vida eterna em Cristo Jesus nosso Senhor."},
]})

# Chapter 7 - Released from the law; the struggle with sin
chapters.append({"c":7,"verses":[
{"v":1,"t":"Irmãos, eu falo a vocês que conhecem a lei. Vocês não sabem que a lei tem autoridade sobre a pessoa apenas enquanto ela vive?"},
{"v":2,"t":"Por exemplo, a mulher casada está ligada ao marido pela lei enquanto ele vive. Mas se o marido morrer, ela fica livre da lei do casamento."},
{"v":3,"t":"Se ela se juntar a outro homem enquanto o marido vive, será chamada de adúltera. Mas se o marido morrer, ela está livre dessa lei e não é adúltera se se casar com outro."},
{"v":4,"t":"Da mesma forma, irmãos, vocês morreram para a lei por meio do corpo de Cristo. Agora pertencem a outro: àquele que ressuscitou dos mortos, para que possamos dar fruto para Deus."},
{"v":5,"t":"Quando vivíamos controlados pela nossa natureza pecadora, os desejos pecaminosos despertados pela lei agiam no nosso corpo e davam fruto para a morte."},
{"v":6,"t":"Mas agora estamos livres da lei. Morremos para aquilo que nos prendia. Assim servimos de uma forma nova, pelo Espírito, e não da forma velha, pela letra da lei."},
{"v":7,"t":"Então a lei é pecado? De jeito nenhum! Mas eu não teria conhecido o pecado se não fosse pela lei. Eu não saberia o que é cobiça se a lei não dissesse: Não cobiçarás."},
{"v":8,"t":"O pecado usou o mandamento como oportunidade e produziu em mim todo tipo de cobiça. Porque sem a lei o pecado está morto."},
{"v":9,"t":"Houve um tempo em que eu vivia sem a lei. Mas quando o mandamento veio, o pecado ganhou vida e eu morri."},
{"v":10,"t":"O mandamento que deveria trazer vida trouxe morte para mim."},
{"v":11,"t":"Porque o pecado usou o mandamento como oportunidade. Me enganou e por meio do mandamento me matou."},
{"v":12,"t":"Portanto, a lei é santa. O mandamento é santo, justo e bom."},
{"v":13,"t":"Então o que é bom se tornou morte para mim? De jeito nenhum! Foi o pecado que produziu morte em mim por meio do que é bom. Assim o pecado se mostrou como realmente é: extremamente pecaminoso, por meio do mandamento."},
{"v":14,"t":"Sabemos que a lei é espiritual. Mas eu sou humano, vendido como escravo do pecado."},
{"v":15,"t":"Eu não entendo o que faço. Não faço o que quero. Faço o que detesto."},
{"v":16,"t":"Se faço o que não quero, concordo que a lei é boa."},
{"v":17,"t":"Nesse caso, já não sou eu que faço isso. É o pecado que mora em mim."},
{"v":18,"t":"Eu sei que em mim, na minha natureza humana, não mora nada de bom. Tenho vontade de fazer o bem, mas não consigo realizá-lo."},
{"v":19,"t":"Não faço o bem que quero. Faço o mal que não quero."},
{"v":20,"t":"Se faço o que não quero, já não sou eu que faço. É o pecado que mora em mim."},
{"v":21,"t":"Então descubro esta lei em mim: quando quero fazer o bem, o mal está presente."},
{"v":22,"t":"No meu interior, tenho prazer na lei de Deus."},
{"v":23,"t":"Mas vejo outra lei agindo no meu corpo. Ela luta contra a lei da minha mente e me faz prisioneiro da lei do pecado que age no meu corpo."},
{"v":24,"t":"Que pessoa infeliz eu sou! Quem vai me livrar deste corpo de morte?"},
{"v":25,"t":"Graças a Deus, por meio de Jesus Cristo nosso Senhor! Portanto, eu mesmo com a mente sirvo à lei de Deus, mas com a natureza humana sirvo à lei do pecado."},
]})

# Chapter 8 - Life in the Spirit
chapters.append({"c":8,"verses":[
{"v":1,"t":"Portanto, agora não existe mais condenação para os que estão em Cristo Jesus."},
{"v":2,"t":"Porque a lei do Espírito da vida em Cristo Jesus me libertou da lei do pecado e da morte."},
{"v":3,"t":"O que a lei não conseguiu fazer, porque era enfraquecida pela natureza humana, Deus fez. Enviou o seu próprio Filho em corpo semelhante ao nosso corpo pecador. E como oferta pelo pecado, Deus condenou o pecado na natureza humana."},
{"v":4,"t":"Fez isso para que a exigência justa da lei fosse cumprida em nós, que não vivemos conforme a natureza humana, mas conforme o Espírito."},
{"v":5,"t":"Quem vive conforme a natureza humana pensa nas coisas da natureza humana. Quem vive conforme o Espírito pensa nas coisas do Espírito."},
{"v":6,"t":"A mentalidade da natureza humana é morte. Mas a mentalidade do Espírito é vida e paz."},
{"v":7,"t":"A mentalidade da natureza humana é inimiga de Deus. Não obedece à lei de Deus, nem pode obedecer."},
{"v":8,"t":"Quem é controlado pela natureza humana não pode agradar a Deus."},
{"v":9,"t":"Mas vocês não são controlados pela natureza humana, e sim pelo Espírito, se de fato o Espírito de Deus mora em vocês. Se alguém não tem o Espírito de Cristo, não pertence a ele."},
{"v":10,"t":"Mas se Cristo está em vocês, o corpo está morto por causa do pecado. Porém o espírito tem vida por causa da justiça."},
{"v":11,"t":"Se o Espírito daquele que ressuscitou Jesus dos mortos mora em vocês, aquele que ressuscitou Cristo dos mortos também dará vida aos corpos mortais de vocês pelo seu Espírito que mora em vocês."},
{"v":12,"t":"Portanto, irmãos, não devemos nada à natureza humana para vivermos conforme ela."},
{"v":13,"t":"Se vocês vivem conforme a natureza humana, vão morrer. Mas se pelo Espírito matam as ações do corpo, viverão."},
{"v":14,"t":"Todos os que são guiados pelo Espírito de Deus são filhos de Deus."},
{"v":15,"t":"Vocês não receberam um espírito de escravidão para viver com medo de novo. Receberam o Espírito de adoção. Por ele clamamos: Aba, Pai!"},
{"v":16,"t":"O próprio Espírito confirma junto com o nosso espírito que somos filhos de Deus."},
{"v":17,"t":"Se somos filhos, somos também herdeiros. Herdeiros de Deus e co-herdeiros com Cristo, se de fato sofremos com ele para também sermos glorificados com ele."},
{"v":18,"t":"Eu considero que os sofrimentos do tempo presente não se comparam com a glória que será revelada em nós."},
{"v":19,"t":"Toda a criação espera com ansiedade a revelação dos filhos de Deus."},
{"v":20,"t":"A criação foi submetida à frustração, não por sua própria escolha, mas por causa daquele que a submeteu. Porém há esperança."},
{"v":21,"t":"A própria criação será libertada da escravidão da corrupção e vai participar da liberdade gloriosa dos filhos de Deus."},
{"v":22,"t":"Sabemos que toda a criação geme e sofre dores de parto até agora."},
{"v":23,"t":"E não só a criação. Nós mesmos, que temos as primícias do Espírito, também gememos por dentro. Esperamos ansiosamente a adoção como filhos, a redenção do nosso corpo."},
{"v":24,"t":"Nessa esperança fomos salvos. Mas esperança que se vê não é esperança. Quem espera pelo que já vê?"},
{"v":25,"t":"Mas se esperamos o que não vemos, esperamos com paciência."},
{"v":26,"t":"Da mesma forma, o Espírito nos ajuda na nossa fraqueza. Não sabemos orar como devemos. Mas o próprio Espírito intercede por nós com gemidos que não podem ser expressos em palavras."},
{"v":27,"t":"E Deus, que examina os corações, conhece a intenção do Espírito. Porque o Espírito intercede pelos santos conforme a vontade de Deus."},
{"v":28,"t":"Sabemos que Deus faz todas as coisas cooperarem para o bem daqueles que o amam, dos que foram chamados conforme o seu propósito."},
{"v":29,"t":"Porque aqueles que Deus conheceu de antemão, também os predestinou para serem parecidos com o seu Filho. Assim o Filho seria o primeiro entre muitos irmãos."},
{"v":30,"t":"E os que predestinou, também chamou. Os que chamou, também declarou justos. Os que declarou justos, também glorificou."},
{"v":31,"t":"O que diremos diante disso? Se Deus é por nós, quem será contra nós?"},
{"v":32,"t":"Aquele que não poupou o seu próprio Filho, mas o entregou por todos nós, como não nos dará também todas as coisas junto com ele?"},
{"v":33,"t":"Quem vai acusar os escolhidos de Deus? Deus é quem os declara justos."},
{"v":34,"t":"Quem vai condenar? Cristo Jesus morreu. Mais que isso: ressuscitou! Está à direita de Deus e intercede por nós."},
{"v":35,"t":"Quem vai nos separar do amor de Cristo? O sofrimento, a angústia, a perseguição, a fome, a nudez, o perigo ou a espada?"},
{"v":36,"t":"Como está escrito: Por tua causa somos entregues à morte o dia inteiro. Somos tratados como ovelhas para o matadouro."},
{"v":37,"t":"Mas em todas essas coisas somos mais que vencedores por meio daquele que nos amou."},
{"v":38,"t":"Porque estou convencido de que nem a morte, nem a vida, nem anjos, nem poderes, nem o presente, nem o futuro,"},
{"v":39,"t":"nem altura, nem profundidade, nem qualquer outra coisa na criação vai conseguir nos separar do amor de Deus que está em Cristo Jesus nosso Senhor."},
]})

# Save chapters 1-8
with open('v:/GitHub/orgs/devzolo/bible/static/data/bfl/romanos_trans_part1.json', 'w', encoding='utf-8') as f:
    json.dump(chapters, f, ensure_ascii=False)
print(f"Saved chapters 1-{chapters[-1]['c']}, total verses: {sum(len(c['verses']) for c in chapters)}")
