#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""BFL Translation of Acts (Atos) - Chapters 12-20"""
import json

chapters = []

# Chapter 12 - Peter's imprisonment and escape
chapters.append({"c":12,"verses":[
{"v":1,"t":"Naquela época, o rei Herodes começou a perseguir alguns membros da igreja."},
{"v":2,"t":"Mandou matar Tiago, irmão de João, com espada."},
{"v":3,"t":"Quando viu que isso agradou os judeus, prendeu Pedro também. Era o período da festa dos Pães sem Fermento."},
{"v":4,"t":"Depois de prender Pedro, colocou-o na cadeia com quatro grupos de quatro soldados para vigiá-lo. Herodes planejava apresentá-lo ao povo depois da Páscoa."},
{"v":5,"t":"Pedro ficou na prisão. Mas a igreja orava a Deus por ele sem parar."},
{"v":6,"t":"Na noite antes de Herodes apresentá-lo ao povo, Pedro dormia entre dois soldados, preso com duas correntes. Guardas vigiavam a porta da prisão."},
{"v":7,"t":"De repente, um anjo do Senhor apareceu e uma luz brilhou na cela. O anjo tocou Pedro no lado e o acordou dizendo: Levante-se rápido! As correntes caíram das mãos dele."},
{"v":8,"t":"O anjo disse: Vista-se e calce as sandálias. Pedro obedeceu. Depois o anjo disse: Coloque a capa e venha comigo."},
{"v":9,"t":"Pedro seguiu o anjo para fora. Não sabia se aquilo era real. Achava que estava tendo uma visão."},
{"v":10,"t":"Passaram pela primeira guarda, depois pela segunda. Chegaram ao portão de ferro que dava para a cidade. O portão se abriu sozinho para eles. Saíram e andaram por uma rua. De repente, o anjo desapareceu."},
{"v":11,"t":"Então Pedro caiu em si e disse: Agora eu sei que isso é real! O Senhor enviou o seu anjo e me livrou de Herodes e de tudo o que o povo judeu esperava."},
{"v":12,"t":"Quando entendeu o que tinha acontecido, Pedro foi até a casa de Maria, mãe de João Marcos. Muitas pessoas estavam reunidas ali orando."},
{"v":13,"t":"Pedro bateu no portão de entrada. Uma empregada chamada Rode foi atender."},
{"v":14,"t":"Quando reconheceu a voz de Pedro, ficou tão feliz que esqueceu de abrir o portão. Correu para dentro e disse: Pedro está na porta!"},
{"v":15,"t":"Eles disseram: Você está louca! Mas ela insistia que era verdade. Então disseram: Deve ser o anjo dele."},
{"v":16,"t":"Pedro continuava batendo. Quando finalmente abriram, viram que era ele mesmo e ficaram espantados."},
{"v":17,"t":"Pedro fez sinal com a mão para que ficassem em silêncio. Contou como o Senhor o tinha tirado da prisão e disse: Contem isso a Tiago e aos irmãos. Depois saiu e foi para outro lugar."},
{"v":18,"t":"Quando amanheceu, houve uma grande confusão entre os soldados. Ninguém sabia o que tinha acontecido com Pedro."},
{"v":19,"t":"Herodes mandou procurá-lo, mas não o encontraram. Interrogou os guardas e mandou executá-los. Depois Herodes saiu da Judeia e foi para Cesareia, onde ficou."},
{"v":20,"t":"Herodes estava com muita raiva do povo de Tiro e Sidom. Eles se uniram e foram falar com ele. Primeiro ganharam o apoio de Blasto, assistente pessoal do rei. Depois pediram paz porque dependiam das terras do rei para se alimentar."},
{"v":21,"t":"No dia marcado, Herodes vestiu suas roupas reais, sentou-se no trono e fez um discurso ao povo."},
{"v":22,"t":"O povo gritava: Esta é a voz de um deus, não de um ser humano!"},
{"v":23,"t":"Na mesma hora, um anjo do Senhor o feriu, porque ele não deu a glória a Deus. Herodes foi comido por vermes e morreu."},
{"v":24,"t":"Mas a palavra de Deus continuava crescendo e se espalhando."},
{"v":25,"t":"Barnabé e Saulo completaram sua missão e voltaram de Jerusalém. Levaram com eles João Marcos."},
]})

# Chapter 13 - First missionary journey
chapters.append({"c":13,"verses":[
{"v":1,"t":"Na igreja de Antioquia havia profetas e mestres: Barnabé, Simeão chamado Níger, Lúcio de Cirene, Manaém que foi criado com Herodes o governador, e Saulo."},
{"v":2,"t":"Enquanto adoravam ao Senhor e jejuavam, o Espírito Santo disse: Separem Barnabé e Saulo para a obra que eu os chamei para fazer."},
{"v":3,"t":"Depois de jejuar e orar, impuseram as mãos sobre eles e os enviaram."},
{"v":4,"t":"Enviados pelo Espírito Santo, Barnabé e Saulo desceram a Selêucia. De lá navegaram para a ilha de Chipre."},
{"v":5,"t":"Quando chegaram a Salamina, anunciaram a palavra de Deus nas sinagogas dos judeus. João Marcos os acompanhava como auxiliar."},
{"v":6,"t":"Percorreram toda a ilha até Pafos. Ali encontraram um feiticeiro judeu e falso profeta chamado Barjesus."},
{"v":7,"t":"Ele era companheiro do governador Sérgio Paulo, homem inteligente. O governador chamou Barnabé e Saulo porque queria ouvir a palavra de Deus."},
{"v":8,"t":"Mas Elimas, o feiticeiro (pois esse é o significado do nome dele), se opôs a eles e tentava afastar o governador da fé."},
{"v":9,"t":"Então Saulo, também chamado Paulo, cheio do Espírito Santo, olhou firme para Elimas e disse:"},
{"v":10,"t":"Você é filho do diabo! Inimigo de tudo o que é justo! Você é cheio de todo tipo de engano e maldade! Quando vai parar de torcer os caminhos retos do Senhor?"},
{"v":11,"t":"Agora a mão do Senhor está contra você. Você ficará cego e por algum tempo não verá a luz do sol. Na mesma hora, escuridão e trevas caíram sobre ele. Andava às cegas procurando alguém que o guiasse pela mão."},
{"v":12,"t":"Quando o governador viu o que aconteceu, creu. Ficou impressionado com o ensino do Senhor."},
{"v":13,"t":"Paulo e seus companheiros navegaram de Pafos e chegaram a Perge, na Panfília. Mas João Marcos se separou deles e voltou a Jerusalém."},
{"v":14,"t":"De Perge, seguiram viagem até Antioquia da Pisídia. No sábado, entraram na sinagoga e se sentaram."},
{"v":15,"t":"Depois da leitura da Lei e dos Profetas, os líderes da sinagoga mandaram dizer a eles: Irmãos, se vocês têm alguma palavra de encorajamento para o povo, falem."},
{"v":16,"t":"Paulo se levantou, fez sinal com a mão e disse: Israelitas e vocês que temem a Deus, ouçam!"},
{"v":17,"t":"O Deus deste povo de Israel escolheu nossos antepassados. Fez o povo crescer enquanto moravam como estrangeiros no Egito. Com grande poder, tirou-os de lá."},
{"v":18,"t":"Por cerca de quarenta anos suportou o comportamento deles no deserto."},
{"v":19,"t":"Destruiu sete nações na terra de Canaã e deu a terra ao seu povo como herança."},
{"v":20,"t":"Tudo isso levou cerca de quatrocentos e cinquenta anos. Depois disso, Deus lhes deu juízes até o tempo do profeta Samuel."},
{"v":21,"t":"Então o povo pediu um rei. Deus lhes deu Saul, filho de Quis, da tribo de Benjamim, que reinou por quarenta anos."},
{"v":22,"t":"Depois de tirar Saul, Deus colocou Davi como rei. Deus disse sobre ele: Encontrei em Davi, filho de Jessé, um homem que agrada o meu coração. Ele fará tudo o que eu quero."},
{"v":23,"t":"Dos descendentes de Davi, conforme prometeu, Deus trouxe a Israel o Salvador Jesus."},
{"v":24,"t":"Antes de Jesus começar, João pregou a todo o povo de Israel o batismo de arrependimento."},
{"v":25,"t":"Quando João estava terminando sua missão, ele disse: Quem vocês pensam que eu sou? Eu não sou aquele que vocês esperam. Mas depois de mim vem alguém cujas sandálias eu não sou digno de desamarrar."},
{"v":26,"t":"Irmãos, descendentes de Abraão, e vocês que temem a Deus: esta mensagem de salvação foi enviada a nós!"},
{"v":27,"t":"O povo de Jerusalém e seus líderes não reconheceram Jesus. Ao condená-lo, cumpriram as palavras dos profetas que são lidas todo sábado."},
{"v":28,"t":"Mesmo sem encontrar motivo para condená-lo à morte, pediram a Pilatos que o matasse."},
{"v":29,"t":"Depois de cumprirem tudo o que estava escrito sobre ele, tiraram-no da cruz e o colocaram num túmulo."},
{"v":30,"t":"Mas Deus o ressuscitou dos mortos."},
{"v":31,"t":"Durante muitos dias, ele apareceu àqueles que tinham ido com ele da Galileia a Jerusalém. Eles agora são testemunhas dele para o povo."},
{"v":32,"t":"Nós estamos trazendo a vocês a boa notícia: a promessa que Deus fez aos nossos antepassados"},
{"v":33,"t":"ele cumpriu para nós, os filhos deles, ressuscitando Jesus. Como está escrito no Salmo segundo: Tu és o meu Filho. Hoje eu gerei você."},
{"v":34,"t":"Sobre o fato de Deus tê-lo ressuscitado para nunca mais morrer, ele disse assim: Eu darei a vocês as bênçãos santas e fiéis prometidas a Davi."},
{"v":35,"t":"Por isso também diz em outro Salmo: Não permitirás que o teu Santo apodreça."},
{"v":36,"t":"Davi serviu à vontade de Deus na sua própria geração. Depois morreu, foi sepultado com seus antepassados e seu corpo apodreceu."},
{"v":37,"t":"Mas aquele que Deus ressuscitou não apodreceu."},
{"v":38,"t":"Portanto, irmãos, saibam que é por meio de Jesus que o perdão dos pecados é anunciado a vocês."},
{"v":39,"t":"Por meio dele, todo aquele que crê é declarado justo por Deus. Algo que a lei de Moisés não podia fazer."},
{"v":40,"t":"Tomem cuidado para que não aconteça o que os profetas disseram:"},
{"v":41,"t":"Olhem, zombadores! Fiquem espantados e desapareçam! Porque eu vou fazer algo nos dias de vocês que vocês não vão acreditar, mesmo que alguém conte."},
{"v":42,"t":"Quando Paulo e Barnabé saíram da sinagoga, o povo pediu que falassem sobre essas coisas no sábado seguinte."},
{"v":43,"t":"Depois que a reunião terminou, muitos judeus e convertidos devotos seguiram Paulo e Barnabé. Eles conversavam com eles e os encorajavam a continuar na graça de Deus."},
{"v":44,"t":"No sábado seguinte, quase toda a cidade se reuniu para ouvir a palavra do Senhor."},
{"v":45,"t":"Quando os judeus viram a multidão, ficaram cheios de inveja e começaram a falar contra o que Paulo dizia, insultando-o."},
{"v":46,"t":"Então Paulo e Barnabé falaram com coragem: Era preciso que a palavra de Deus fosse anunciada primeiro a vocês. Mas já que vocês a rejeitam e não se consideram dignos da vida eterna, nós vamos nos dirigir aos não judeus."},
{"v":47,"t":"Porque assim o Senhor nos ordenou: Eu coloquei você como luz para as nações, para que leve a salvação até os confins da terra."},
{"v":48,"t":"Quando os não judeus ouviram isso, ficaram alegres e louvaram a palavra do Senhor. E todos os que estavam destinados à vida eterna creram."},
{"v":49,"t":"A palavra do Senhor se espalhou por toda aquela região."},
{"v":50,"t":"Mas os judeus incitaram mulheres devotas e de posição social e os líderes da cidade. Provocaram perseguição contra Paulo e Barnabé e os expulsaram do território."},
{"v":51,"t":"Paulo e Barnabé sacudiram a poeira dos pés contra eles e foram para Icônio."},
{"v":52,"t":"Os seguidores ficaram cheios de alegria e do Espírito Santo."},
]})

# Chapter 14 - Iconium, Lystra, Derbe
chapters.append({"c":14,"verses":[
{"v":1,"t":"Em Icônio, Paulo e Barnabé entraram na sinagoga dos judeus como sempre. Falaram de tal forma que muitos judeus e gregos creram."},
{"v":2,"t":"Mas os judeus que não creram provocaram os não judeus contra os irmãos e envenenaram suas mentes."},
{"v":3,"t":"Mesmo assim, Paulo e Barnabé ficaram ali por muito tempo. Falavam com ousadia sobre o Senhor. Ele confirmava a mensagem da sua graça fazendo sinais e maravilhas por meio deles."},
{"v":4,"t":"O povo da cidade ficou dividido. Uns estavam do lado dos judeus e outros do lado dos apóstolos."},
{"v":5,"t":"Quando judeus e não judeus, junto com seus líderes, planejaram maltratá-los e apedrejá-los,"},
{"v":6,"t":"Paulo e Barnabé ficaram sabendo e fugiram para as cidades de Listra e Derbe, na Licaônia, e para a região ao redor."},
{"v":7,"t":"Ali continuaram anunciando a boa notícia."},
{"v":8,"t":"Em Listra havia um homem aleijado dos pés. Ele era paralítico desde que nasceu e nunca tinha andado."},
{"v":9,"t":"Esse homem ouvia Paulo falar. Paulo olhou firme para ele e viu que ele tinha fé para ser curado."},
{"v":10,"t":"Então disse em voz alta: Levante-se e fique de pé! O homem deu um pulo e começou a andar."},
{"v":11,"t":"Quando a multidão viu o que Paulo tinha feito, gritaram na língua da Licaônia: Os deuses desceram até nós em forma humana!"},
{"v":12,"t":"Chamaram Barnabé de Zeus e Paulo de Hermes, porque era ele quem falava."},
{"v":13,"t":"O sacerdote do templo de Zeus, que ficava na entrada da cidade, trouxe touros e flores até os portões. Ele e o povo queriam oferecer sacrifícios a eles."},
{"v":14,"t":"Quando Barnabé e Paulo ouviram isso, rasgaram suas roupas e correram para o meio da multidão gritando:"},
{"v":15,"t":"Homens, por que estão fazendo isso? Nós somos seres humanos iguais a vocês! Estamos aqui para trazer a boa notícia: deixem essas coisas inúteis e se voltem para o Deus vivo, que fez o céu, a terra, o mar e tudo o que existe neles."},
{"v":16,"t":"No passado, Deus permitiu que todas as nações seguissem seus próprios caminhos."},
{"v":17,"t":"Mas ele não deixou de dar provas de si mesmo fazendo o bem: dando chuvas do céu e colheitas no tempo certo, alimentando vocês e enchendo seus corações de alegria."},
{"v":18,"t":"Mesmo com essas palavras, mal conseguiram impedir que a multidão oferecesse sacrifícios a eles."},
{"v":19,"t":"Então chegaram judeus de Antioquia e Icônio. Eles convenceram a multidão contra Paulo, o apedrejaram e o arrastaram para fora da cidade pensando que estava morto."},
{"v":20,"t":"Mas quando os seguidores se reuniram ao redor dele, Paulo se levantou e voltou para a cidade. No dia seguinte, ele e Barnabé partiram para Derbe."},
{"v":21,"t":"Anunciaram a boa notícia naquela cidade e fizeram muitos seguidores. Depois voltaram a Listra, Icônio e Antioquia da Pisídia."},
{"v":22,"t":"Fortaleciam os seguidores e os encorajavam a permanecer firmes na fé. Diziam: É preciso passar por muitas dificuldades para entrar no Reino de Deus."},
{"v":23,"t":"Em cada igreja, Paulo e Barnabé escolheram líderes. Oraram e jejuaram, e os entregaram ao Senhor em quem tinham crido."},
{"v":24,"t":"Passaram pela Pisídia e chegaram à Panfília."},
{"v":25,"t":"Depois de pregar a palavra em Perge, desceram para Atália."},
{"v":26,"t":"De lá navegaram de volta para Antioquia. Era de lá que tinham sido enviados pela graça de Deus para a obra que agora tinham completado."},
{"v":27,"t":"Quando chegaram, reuniram a igreja e contaram tudo o que Deus tinha feito por meio deles. Contaram como Deus tinha aberto a porta da fé para os não judeus."},
{"v":28,"t":"E ficaram ali bastante tempo com os seguidores."},
]})

# Chapter 15 - Council at Jerusalem
chapters.append({"c":15,"verses":[
{"v":1,"t":"Alguns homens desceram da Judeia e ensinavam os irmãos: Se vocês não forem circuncidados conforme o costume de Moisés, não podem ser salvos."},
{"v":2,"t":"Paulo e Barnabé discordaram fortemente deles. Depois de muita discussão, decidiram que Paulo, Barnabé e alguns outros iriam a Jerusalém tratar dessa questão com os apóstolos e líderes."},
{"v":3,"t":"A igreja os enviou. No caminho, passaram pela Fenícia e Samaria contando como os não judeus tinham se convertido. Todos ficaram muito alegres com a notícia."},
{"v":4,"t":"Quando chegaram a Jerusalém, foram recebidos pela igreja, pelos apóstolos e pelos líderes. Contaram tudo o que Deus tinha feito por meio deles."},
{"v":5,"t":"Mas alguns do grupo dos fariseus que tinham crido se levantaram e disseram: É preciso circuncidá-los e mandá-los obedecer a lei de Moisés."},
{"v":6,"t":"Os apóstolos e os líderes se reuniram para tratar do assunto."},
{"v":7,"t":"Depois de muita discussão, Pedro se levantou e disse: Irmãos, vocês sabem que há muito tempo Deus me escolheu entre vocês para que os não judeus ouvissem a mensagem da boa notícia e cressem."},
{"v":8,"t":"Deus, que conhece o coração, mostrou que os aceitou dando a eles o Espírito Santo, assim como deu a nós."},
{"v":9,"t":"Ele não fez diferença entre nós e eles. Purificou o coração deles pela fé."},
{"v":10,"t":"Então por que vocês querem testar Deus colocando sobre os seguidores um peso que nem nós nem nossos antepassados conseguimos carregar?"},
{"v":11,"t":"Nós cremos que somos salvos pela graça do Senhor Jesus, da mesma forma que eles."},
{"v":12,"t":"Toda a assembleia ficou em silêncio. Ouviram Barnabé e Paulo contarem todos os sinais e maravilhas que Deus tinha feito entre os não judeus por meio deles."},
{"v":13,"t":"Quando terminaram de falar, Tiago disse: Irmãos, ouçam."},
{"v":14,"t":"Simão contou como Deus pela primeira vez visitou os não judeus para escolher entre eles um povo para o seu nome."},
{"v":15,"t":"Isso está de acordo com o que os profetas disseram, como está escrito:"},
{"v":16,"t":"Depois disso voltarei e reconstruirei a tenda caída de Davi. Vou restaurar suas ruínas e levantá-la de novo."},
{"v":17,"t":"Para que o restante das pessoas procure o Senhor, todos os não judeus sobre quem o meu nome é invocado. Diz o Senhor que faz essas coisas"},
{"v":18,"t":"conhecidas desde os tempos antigos."},
{"v":19,"t":"Por isso, a minha opinião é que não devemos dificultar a vida dos não judeus que estão se voltando para Deus."},
{"v":20,"t":"Em vez disso, devemos escrever a eles que se afastem da comida oferecida a ídolos, da imoralidade sexual, da carne de animais estrangulados e do sangue."},
{"v":21,"t":"Porque desde os tempos antigos Moisés tem quem o pregue em todas as cidades. A lei dele é lida nas sinagogas todo sábado."},
{"v":22,"t":"Então os apóstolos, os líderes e toda a igreja decidiram escolher alguns homens e enviá-los a Antioquia com Paulo e Barnabé. Escolheram Judas, chamado Barsabás, e Silas, que eram líderes entre os irmãos."},
{"v":23,"t":"Enviaram com eles esta carta: Os apóstolos e os líderes, seus irmãos, aos irmãos não judeus em Antioquia, Síria e Cilícia. Saudações!"},
{"v":24,"t":"Ficamos sabendo que alguns dos nossos foram até vocês e os perturbaram com palavras que confundiram suas mentes. Nós não os autorizamos."},
{"v":25,"t":"Por isso decidimos, de comum acordo, escolher alguns homens e enviá-los a vocês com nossos queridos Barnabé e Paulo,"},
{"v":26,"t":"homens que arriscaram a vida pelo nome do nosso Senhor Jesus Cristo."},
{"v":27,"t":"Estamos enviando Judas e Silas, que dirão as mesmas coisas pessoalmente."},
{"v":28,"t":"Pareceu bem ao Espírito Santo e a nós não impor a vocês nada além destas coisas essenciais:"},
{"v":29,"t":"que se afastem de comida oferecida a ídolos, de sangue, de carne de animais estrangulados e de imoralidade sexual. Se vocês evitarem essas coisas, farão bem. Fiquem bem!"},
{"v":30,"t":"Os enviados foram para Antioquia. Reuniram a comunidade e entregaram a carta."},
{"v":31,"t":"Quando leram, ficaram alegres com a mensagem de encorajamento."},
{"v":32,"t":"Judas e Silas, que também eram profetas, encorajaram e fortaleceram os irmãos com muitas palavras."},
{"v":33,"t":"Depois de algum tempo, os irmãos os despediram em paz para que voltassem aos que os tinham enviado."},
{"v":34,"t":"Mas Silas decidiu ficar ali."},
{"v":35,"t":"Paulo e Barnabé ficaram em Antioquia. Junto com muitos outros, ensinavam e anunciavam a palavra do Senhor."},
{"v":36,"t":"Algum tempo depois, Paulo disse a Barnabé: Vamos voltar e visitar os irmãos em todas as cidades onde anunciamos a palavra do Senhor. Vamos ver como eles estão."},
{"v":37,"t":"Barnabé queria levar João Marcos com eles."},
{"v":38,"t":"Mas Paulo achava melhor não levar alguém que os tinha abandonado na Panfília e não continuou com eles no trabalho."},
{"v":39,"t":"A discussão ficou tão séria que eles se separaram. Barnabé levou Marcos e navegou para Chipre."},
{"v":40,"t":"Paulo escolheu Silas e partiu. Os irmãos o entregaram à graça do Senhor."},
{"v":41,"t":"Ele passou pela Síria e Cilícia, fortalecendo as igrejas."},
]})

# Chapter 16 - Timothy, Philippi, jail
chapters.append({"c":16,"verses":[
{"v":1,"t":"Paulo chegou a Derbe e depois a Listra. Ali havia um seguidor chamado Timóteo. Sua mãe era judia e crente, mas o pai era grego."},
{"v":2,"t":"Os irmãos de Listra e Icônio falavam muito bem dele."},
{"v":3,"t":"Paulo quis levá-lo na viagem. Por causa dos judeus daquela região, circuncidou Timóteo, porque todos sabiam que o pai dele era grego."},
{"v":4,"t":"Nas cidades por onde passavam, entregavam as decisões tomadas pelos apóstolos e líderes em Jerusalém para que fossem obedecidas."},
{"v":5,"t":"Assim as igrejas ficavam mais fortes na fé e cresciam em número a cada dia."},
{"v":6,"t":"Paulo e seus companheiros viajaram pela região da Frígia e da Galácia. O Espírito Santo os impediu de pregar a palavra na província da Ásia."},
{"v":7,"t":"Quando chegaram perto da Mísia, tentaram ir para a Bitínia. Mas o Espírito de Jesus não permitiu."},
{"v":8,"t":"Então passaram pela Mísia e desceram até Trôade."},
{"v":9,"t":"Durante a noite, Paulo teve uma visão. Um homem da Macedônia estava de pé e pedia: Venha para a Macedônia e nos ajude!"},
{"v":10,"t":"Depois que Paulo teve essa visão, nos preparamos imediatamente para ir à Macedônia. Entendemos que Deus nos chamava para anunciar a boa notícia a eles."},
{"v":11,"t":"Partimos de Trôade e navegamos direto para Samotrácia. No dia seguinte fomos para Neápolis."},
{"v":12,"t":"De lá fomos para Filipos, que é uma importante cidade da Macedônia e uma colônia romana. Ficamos ali alguns dias."},
{"v":13,"t":"No sábado, saímos da cidade e fomos até a beira do rio. Achamos que ali haveria um lugar de oração. Sentamos e começamos a conversar com as mulheres que estavam reunidas."},
{"v":14,"t":"Uma delas se chamava Lídia. Era vendedora de tecidos de púrpura, da cidade de Tiatira, e adorava a Deus. O Senhor abriu o coração dela para que prestasse atenção ao que Paulo dizia."},
{"v":15,"t":"Ela e toda a sua família foram batizadas. Depois nos convidou: Se vocês me consideram fiel ao Senhor, venham ficar na minha casa. E nos convenceu."},
{"v":16,"t":"Certo dia, quando íamos ao lugar de oração, encontramos uma escrava que tinha um espírito que previa o futuro. Ela dava muito lucro aos seus donos com as suas previsões."},
{"v":17,"t":"Ela seguia Paulo e a nós gritando: Estes homens são servos do Deus Altíssimo! Eles anunciam a vocês o caminho da salvação!"},
{"v":18,"t":"Ela fez isso durante muitos dias. Paulo ficou irritado, virou-se e disse ao espírito: Em nome de Jesus Cristo, eu ordeno que você saia dela! Na mesma hora o espírito saiu."},
{"v":19,"t":"Quando os donos da escrava viram que tinham perdido sua fonte de lucro, agarraram Paulo e Silas e os arrastaram até a praça diante das autoridades."},
{"v":20,"t":"Levaram-nos aos magistrados e disseram: Estes homens são judeus e estão causando confusão na nossa cidade."},
{"v":21,"t":"Eles ensinam costumes que nós, romanos, não podemos aceitar nem praticar."},
{"v":22,"t":"A multidão se juntou contra eles. Os magistrados mandaram rasgar as roupas deles e açoitá-los com varas."},
{"v":23,"t":"Depois de muitos açoites, jogaram-nos na prisão e ordenaram ao carcereiro que os vigiasse bem."},
{"v":24,"t":"Ao receber essa ordem, o carcereiro os colocou na cela mais interna e prendeu os pés deles no tronco."},
{"v":25,"t":"Por volta da meia-noite, Paulo e Silas oravam e cantavam hinos a Deus. Os outros presos ouviam."},
{"v":26,"t":"De repente, veio um terremoto tão forte que os alicerces da prisão tremeram. Na mesma hora, todas as portas se abriram e as correntes de todos os presos se soltaram."},
{"v":27,"t":"O carcereiro acordou. Quando viu as portas da prisão abertas, puxou a espada e ia se matar, pensando que os presos tinham fugido."},
{"v":28,"t":"Mas Paulo gritou bem alto: Não faça mal a si mesmo! Estamos todos aqui!"},
{"v":29,"t":"O carcereiro pediu uma tocha, correu para dentro e se jogou tremendo aos pés de Paulo e Silas."},
{"v":30,"t":"Depois os levou para fora e perguntou: Senhores, o que devo fazer para ser salvo?"},
{"v":31,"t":"Eles responderam: Creia no Senhor Jesus e você será salvo, você e a sua família."},
{"v":32,"t":"Então falaram a palavra do Senhor a ele e a todos na sua casa."},
{"v":33,"t":"Naquela mesma hora da noite, o carcereiro lavou os ferimentos deles. Em seguida, ele e toda a sua família foram batizados."},
{"v":34,"t":"Levou-os para a sua casa e serviu comida. Ele e toda a sua família ficaram cheios de alegria por terem crido em Deus."},
{"v":35,"t":"Quando amanheceu, os magistrados enviaram guardas com a ordem: Soltem aqueles homens."},
{"v":36,"t":"O carcereiro disse a Paulo: Os magistrados mandaram soltá-los. Agora saiam e vão em paz."},
{"v":37,"t":"Mas Paulo disse: Eles nos açoitaram em público sem julgamento, sendo nós cidadãos romanos. Nos jogaram na prisão. E agora querem nos mandar embora escondido? De jeito nenhum! Que eles mesmos venham nos tirar daqui!"},
{"v":38,"t":"Os guardas contaram isso aos magistrados. Quando ouviram que eram cidadãos romanos, ficaram com medo."},
{"v":39,"t":"Vieram e pediram desculpas. Tiraram-nos da prisão e pediram que fossem embora da cidade."},
{"v":40,"t":"Depois de saírem da prisão, Paulo e Silas foram à casa de Lídia. Ali se encontraram com os irmãos, os encorajaram e partiram."},
]})

# Chapter 17 - Thessalonica, Berea, Athens
chapters.append({"c":17,"verses":[
{"v":1,"t":"Paulo e Silas passaram por Anfípolis e Apolônia e chegaram a Tessalônica. Havia ali uma sinagoga dos judeus."},
{"v":2,"t":"Como era seu costume, Paulo foi à sinagoga. Durante três sábados discutiu com eles usando as Escrituras."},
{"v":3,"t":"Explicava e provava que o Cristo tinha que sofrer e ressuscitar dos mortos. Dizia: Esse Jesus que eu anuncio a vocês é o Cristo."},
{"v":4,"t":"Alguns judeus foram convencidos e se juntaram a Paulo e Silas. Um grande número de gregos devotos e muitas mulheres importantes também creram."},
{"v":5,"t":"Mas os judeus ficaram com inveja. Juntaram gente ruim da rua, formaram uma turba e causaram tumulto na cidade. Atacaram a casa de Jasão procurando Paulo e Silas para levá-los ao povo."},
{"v":6,"t":"Não os encontraram. Então arrastaram Jasão e alguns irmãos diante das autoridades da cidade e gritaram: Esses homens que causam confusão no mundo inteiro chegaram aqui também!"},
{"v":7,"t":"Jasão os recebeu! Todos eles agem contra as leis do imperador dizendo que existe outro rei chamado Jesus."},
{"v":8,"t":"O povo e as autoridades ficaram agitados quando ouviram isso."},
{"v":9,"t":"Exigiram uma fiança de Jasão e dos outros e depois os soltaram."},
{"v":10,"t":"Naquela mesma noite, os irmãos enviaram Paulo e Silas para Bereia. Quando chegaram, foram à sinagoga dos judeus."},
{"v":11,"t":"Os judeus de Bereia tinham a mente mais aberta que os de Tessalônica. Receberam a mensagem com muita vontade de aprender. Todos os dias examinavam as Escrituras para ver se o que Paulo dizia era verdade."},
{"v":12,"t":"Muitos deles creram. Também muitas mulheres gregas importantes e muitos homens gregos creram."},
{"v":13,"t":"Quando os judeus de Tessalônica souberam que Paulo pregava a palavra de Deus em Bereia, foram até lá agitar e perturbar o povo."},
{"v":14,"t":"Então os irmãos mandaram Paulo embora rapidamente em direção ao mar. Mas Silas e Timóteo ficaram em Bereia."},
{"v":15,"t":"Os que acompanhavam Paulo o levaram até Atenas. Voltaram com a instrução de que Silas e Timóteo deviam ir ao encontro dele o mais rápido possível."},
{"v":16,"t":"Enquanto esperava em Atenas, Paulo ficou profundamente incomodado ao ver a cidade cheia de ídolos."},
{"v":17,"t":"Por isso discutia na sinagoga com os judeus e com os gregos devotos. Na praça, todos os dias conversava com quem aparecesse."},
{"v":18,"t":"Alguns filósofos epicureus e estoicos debatiam com ele. Uns diziam: O que esse tagarela quer dizer? Outros diziam: Parece que ele prega deuses estrangeiros. Diziam isso porque Paulo anunciava Jesus e a ressurreição."},
{"v":19,"t":"Então levaram Paulo ao Areópago e disseram: Podemos saber que novo ensino é esse que você está pregando?"},
{"v":20,"t":"Você está nos dizendo coisas estranhas. Queremos saber o que isso significa."},
{"v":21,"t":"Todos os atenienses e estrangeiros que moravam ali não faziam outra coisa senão falar ou ouvir as últimas novidades."},
{"v":22,"t":"Paulo ficou de pé no meio do Areópago e disse: Atenienses, vejo que vocês são muito religiosos em todos os sentidos."},
{"v":23,"t":"Andando pela cidade e observando os lugares de adoração, encontrei até um altar com a inscrição: Ao Deus Desconhecido. Pois é esse Deus que vocês adoram sem conhecer que eu anuncio a vocês."},
{"v":24,"t":"O Deus que fez o mundo e tudo o que nele existe é o Senhor do céu e da terra. Ele não mora em templos feitos por mãos humanas."},
{"v":25,"t":"Ele não precisa que ninguém cuide dele, como se precisasse de algo. Ele mesmo é quem dá a todos a vida, a respiração e todas as coisas."},
{"v":26,"t":"De um só homem ele fez todas as nações para que habitassem toda a terra. Ele determinou os tempos certos e os limites de onde cada povo viveria."},
{"v":27,"t":"Fez isso para que as pessoas o buscassem e talvez pudessem encontrá-lo, mesmo tateando. Na verdade, ele não está longe de nenhum de nós."},
{"v":28,"t":"Porque nele vivemos, nos movemos e existimos. Como disseram alguns dos poetas de vocês: Somos também descendentes dele."},
{"v":29,"t":"Sendo descendentes de Deus, não devemos pensar que ele se parece com ouro, prata ou pedra, moldados pela arte e imaginação humana."},
{"v":30,"t":"No passado Deus não levou em conta a ignorância. Mas agora ele ordena que todas as pessoas, em todos os lugares, se arrependam."},
{"v":31,"t":"Porque ele marcou um dia em que vai julgar o mundo com justiça por meio do homem que designou. Ele deu prova disso a todos, ressuscitando-o dos mortos."},
{"v":32,"t":"Quando ouviram sobre a ressurreição dos mortos, alguns zombaram. Outros disseram: Queremos ouvir mais sobre isso depois."},
{"v":33,"t":"Com isso, Paulo saiu do meio deles."},
{"v":34,"t":"Mas alguns se juntaram a ele e creram. Entre eles estava Dionísio, membro do Areópago, uma mulher chamada Dâmaris e outros mais."},
]})

# Chapter 18 - Corinth, return
chapters.append({"c":18,"verses":[
{"v":1,"t":"Depois disso, Paulo saiu de Atenas e foi para Corinto."},
{"v":2,"t":"Ali encontrou um judeu chamado Áquila, natural do Ponto, que tinha chegado recentemente da Itália com sua esposa Priscila. O imperador Cláudio tinha ordenado que todos os judeus saíssem de Roma. Paulo foi visitá-los."},
{"v":3,"t":"Como trabalhavam no mesmo ofício, ficou morando e trabalhando com eles. Eles faziam tendas."},
{"v":4,"t":"Todo sábado, Paulo discutia na sinagoga tentando convencer judeus e gregos."},
{"v":5,"t":"Quando Silas e Timóteo chegaram da Macedônia, Paulo se dedicou totalmente à pregação. Testemunhava aos judeus que Jesus é o Cristo."},
{"v":6,"t":"Mas eles se opuseram e o insultaram. Paulo sacudiu as roupas e disse: O sangue de vocês caia sobre a cabeça de vocês! Estou limpo! De agora em diante vou para os não judeus."},
{"v":7,"t":"Saiu dali e foi para a casa de um homem chamado Tício Justo, que adorava a Deus. A casa dele ficava ao lado da sinagoga."},
{"v":8,"t":"Crispo, o líder da sinagoga, creu no Senhor junto com toda a sua família. Muitos coríntios que ouviam a mensagem criam e eram batizados."},
{"v":9,"t":"Certa noite, o Senhor disse a Paulo numa visão: Não tenha medo. Continue falando e não fique em silêncio."},
{"v":10,"t":"Porque eu estou com você. Ninguém vai atacar ou machucar você, porque eu tenho muita gente nesta cidade."},
{"v":11,"t":"Paulo ficou ali um ano e meio, ensinando a palavra de Deus entre eles."},
{"v":12,"t":"Quando Gálio era governador da região da Acaia, os judeus se uniram contra Paulo e o levaram ao tribunal."},
{"v":13,"t":"Disseram: Este homem convence as pessoas a adorar a Deus de um jeito contrário à lei."},
{"v":14,"t":"Quando Paulo ia falar, Gálio disse aos judeus: Se fosse uma questão de crime ou de maldade, eu teria motivo para ouvi-los."},
{"v":15,"t":"Mas já que é questão de palavras, nomes e da lei de vocês, resolvam vocês mesmos. Eu não quero ser juiz dessas coisas."},
{"v":16,"t":"E os mandou embora do tribunal."},
{"v":17,"t":"Então todos agarraram Sóstenes, o líder da sinagoga, e o espancaram diante do tribunal. Mas Gálio não se importou com nada disso."},
{"v":18,"t":"Paulo ficou em Corinto ainda muitos dias. Depois se despediu dos irmãos e navegou para a Síria, junto com Priscila e Áquila. Em Cencreia, raspou a cabeça por causa de um voto que tinha feito."},
{"v":19,"t":"Chegaram a Éfeso. Ali Paulo deixou Priscila e Áquila. Ele mesmo entrou na sinagoga e discutiu com os judeus."},
{"v":20,"t":"Eles pediram que ficasse mais tempo, mas ele não aceitou."},
{"v":21,"t":"Despediu-se dizendo: Se Deus quiser, eu volto. E partiu de Éfeso."},
{"v":22,"t":"Desembarcou em Cesareia, subiu e cumprimentou a igreja. Depois desceu para Antioquia."},
{"v":23,"t":"Depois de passar algum tempo ali, partiu. Percorreu a região da Galácia e da Frígia, fortalecendo todos os seguidores."},
{"v":24,"t":"Um judeu chamado Apolo, natural de Alexandria, chegou a Éfeso. Era um homem culto e conhecia bem as Escrituras."},
{"v":25,"t":"Ele tinha sido instruído no caminho do Senhor. Falava com entusiasmo e ensinava corretamente sobre Jesus, embora conhecesse apenas o batismo de João."},
{"v":26,"t":"Começou a falar com ousadia na sinagoga. Quando Priscila e Áquila o ouviram, o levaram à parte e explicaram a ele o caminho de Deus de forma mais completa."},
{"v":27,"t":"Quando Apolo quis ir para a Acaia, os irmãos o encorajaram e escreveram aos seguidores de lá para que o recebessem bem. Quando chegou, ajudou muito os que tinham crido pela graça de Deus."},
{"v":28,"t":"Ele refutava os judeus com firmeza em público, provando pelas Escrituras que Jesus é o Cristo."},
]})

# Chapter 19 - Paul in Ephesus
chapters.append({"c":19,"verses":[
{"v":1,"t":"Enquanto Apolo estava em Corinto, Paulo viajou pelo interior e chegou a Éfeso. Ali encontrou alguns seguidores."},
{"v":2,"t":"Perguntou a eles: Vocês receberam o Espírito Santo quando creram? Responderam: Nem sabíamos que existe um Espírito Santo."},
{"v":3,"t":"Paulo perguntou: Então com que batismo vocês foram batizados? Responderam: Com o batismo de João."},
{"v":4,"t":"Paulo explicou: João batizou com um batismo de arrependimento. Ele dizia ao povo que cressem naquele que viria depois dele, isto é, em Jesus."},
{"v":5,"t":"Quando ouviram isso, foram batizados em nome do Senhor Jesus."},
{"v":6,"t":"Paulo impôs as mãos sobre eles e o Espírito Santo veio sobre eles. Começaram a falar em línguas e a profetizar."},
{"v":7,"t":"Eram cerca de doze homens ao todo."},
{"v":8,"t":"Paulo entrou na sinagoga e durante três meses falou com ousadia. Discutia e procurava convencê-los sobre o Reino de Deus."},
{"v":9,"t":"Mas alguns endureceram e não creram. Falavam mal do Caminho diante de todos. Então Paulo se afastou deles. Separou os seguidores e passou a ensinar todos os dias na escola de Tirano."},
{"v":10,"t":"Isso continuou por dois anos. Assim todos os que moravam na província da Ásia, tanto judeus como gregos, ouviram a palavra do Senhor."},
{"v":11,"t":"Deus fazia milagres extraordinários por meio de Paulo."},
{"v":12,"t":"Até lenços e aventais que tinham tocado o corpo de Paulo eram levados aos doentes. As doenças os deixavam e os espíritos maus saíam."},
{"v":13,"t":"Alguns judeus que andavam expulsando espíritos maus tentaram usar o nome do Senhor Jesus. Diziam: Eu ordeno em nome do Jesus que Paulo prega!"},
{"v":14,"t":"Os que faziam isso eram os sete filhos de Ceva, um sumo sacerdote judeu."},
{"v":15,"t":"Um dia, o espírito mau respondeu: Eu conheço Jesus. Sei quem é Paulo. Mas vocês, quem são?"},
{"v":16,"t":"O homem que tinha o espírito mau saltou sobre eles. Dominou todos eles com tanta violência que fugiram da casa nus e feridos."},
{"v":17,"t":"Quando todos os judeus e gregos de Éfeso souberam disso, ficaram com medo. E o nome do Senhor Jesus era cada vez mais honrado."},
{"v":18,"t":"Muitos dos que tinham crido vinham confessar publicamente o que tinham feito."},
{"v":19,"t":"Vários que praticavam feitiçaria juntaram seus livros e os queimaram diante de todos. Calcularam o valor dos livros: cinquenta mil moedas de prata."},
{"v":20,"t":"Assim a palavra do Senhor crescia e se tornava cada vez mais poderosa."},
{"v":21,"t":"Depois desses acontecimentos, Paulo decidiu no Espírito passar pela Macedônia e Acaia e ir a Jerusalém. Disse: Depois que eu for lá, preciso visitar Roma também."},
{"v":22,"t":"Enviou à Macedônia dois dos seus ajudantes, Timóteo e Erasto. Ele ficou mais um tempo na província da Ásia."},
{"v":23,"t":"Naquela época aconteceu uma grande confusão por causa do Caminho."},
{"v":24,"t":"Um ourives chamado Demétrio fabricava miniaturas de prata do templo de Ártemis. Isso dava muito lucro aos artesãos."},
{"v":25,"t":"Reuniu os artesãos e outros do mesmo ramo e disse: Companheiros, vocês sabem que nossa riqueza vem deste trabalho."},
{"v":26,"t":"E vocês veem e ouvem que esse Paulo convenceu e desviou muita gente, não só em Éfeso, mas em quase toda a província da Ásia. Ele diz que deuses feitos por mãos humanas não são deuses."},
{"v":27,"t":"Há o perigo de nosso ofício cair em descrédito. Além disso, o templo da grande deusa Ártemis pode perder sua importância. E ela mesma, que é adorada em toda a Ásia e no mundo inteiro, pode perder sua grandeza."},
{"v":28,"t":"Quando ouviram isso, ficaram furiosos e começaram a gritar: Grande é a Ártemis dos efésios!"},
{"v":29,"t":"A cidade inteira ficou em tumulto. O povo agarrou Gaio e Aristarco, companheiros de viagem de Paulo, vindos da Macedônia. Todos correram juntos para o teatro."},
{"v":30,"t":"Paulo queria ir falar ao povo, mas os seguidores não deixaram."},
{"v":31,"t":"Até alguns funcionários do governo da Ásia, que eram amigos de Paulo, mandaram um recado pedindo que ele não se arriscasse indo ao teatro."},
{"v":32,"t":"A assembleia estava em total confusão. Uns gritavam uma coisa, outros outra. A maioria nem sabia por que estava ali."},
{"v":33,"t":"Os judeus empurraram Alexandre para frente. Ele fez sinal com a mão querendo falar ao povo."},
{"v":34,"t":"Mas quando perceberam que era judeu, todos gritaram juntos por quase duas horas: Grande é a Ártemis dos efésios!"},
{"v":35,"t":"Finalmente, o secretário da cidade acalmou a multidão e disse: Efésios, quem no mundo não sabe que a cidade de Éfeso é guardiã do templo da grande Ártemis e da imagem que caiu do céu?"},
{"v":36,"t":"Já que esses fatos não podem ser negados, vocês devem se acalmar e não fazer nada por impulso."},
{"v":37,"t":"Vocês trouxeram estes homens aqui, mas eles não roubaram o templo nem falaram mal da nossa deusa."},
{"v":38,"t":"Se Demétrio e seus companheiros têm queixa contra alguém, existem tribunais e governadores para isso. Que apresentem suas acusações lá."},
{"v":39,"t":"Se vocês querem mais alguma coisa, será resolvido numa assembleia regular."},
{"v":40,"t":"Porque corremos o risco de sermos acusados de desordem por causa do que aconteceu hoje. Não há motivo que justifique essa confusão."},
{"v":41,"t":"Depois de dizer isso, dispensou a assembleia."},
]})

# Chapter 20 - Troas, Miletus farewell
chapters.append({"c":20,"verses":[
{"v":1,"t":"Depois que a confusão acabou, Paulo chamou os seguidores, os encorajou e se despediu. Partiu em viagem para a Macedônia."},
{"v":2,"t":"Viajou por aquela região e encorajou muito os irmãos com suas palavras. Depois foi para a Grécia."},
{"v":3,"t":"Ficou ali três meses. Quando estava pronto para embarcar para a Síria, os judeus fizeram um plano contra ele. Então decidiu voltar pela Macedônia."},
{"v":4,"t":"O acompanharam Sópatro de Bereia, Aristarco e Segundo de Tessalônica, Gaio de Derbe, Timóteo, e Tíquico e Trófimo da província da Ásia."},
{"v":5,"t":"Eles foram na frente e nos esperaram em Trôade."},
{"v":6,"t":"Depois da festa dos Pães sem Fermento, embarcamos de Filipos e cinco dias depois nos encontramos com eles em Trôade. Ficamos ali sete dias."},
{"v":7,"t":"No primeiro dia da semana, nos reunimos para partir o pão. Paulo falou ao grupo. Como ia partir no dia seguinte, continuou falando até a meia-noite."},
{"v":8,"t":"Havia muitas lâmpadas no andar de cima onde estávamos reunidos."},
{"v":9,"t":"Um jovem chamado Êutico estava sentado na janela. Ele foi ficando com muito sono enquanto Paulo falava sem parar. Vencido pelo sono, caiu do terceiro andar e foi recolhido morto."},
{"v":10,"t":"Paulo desceu, abraçou o jovem e disse: Não se preocupem! Ele está vivo!"},
{"v":11,"t":"Depois subiu de volta, partiu o pão e comeu. Continuou conversando até o amanhecer. Então partiu."},
{"v":12,"t":"O jovem foi levado para casa vivo. Todos ficaram muito consolados."},
{"v":13,"t":"Nós fomos na frente para o navio e navegamos até Assôs, onde íamos pegar Paulo. Ele mesmo tinha combinado assim porque queria ir a pé."},
{"v":14,"t":"Quando nos encontrou em Assôs, ele embarcou conosco e fomos para Mitilene."},
{"v":15,"t":"No dia seguinte navegamos de lá e chegamos em frente a Quios. No outro dia aportamos em Samos. No dia seguinte chegamos a Mileto."},
{"v":16,"t":"Paulo tinha decidido não parar em Éfeso para não se atrasar na província da Ásia. Estava com pressa para chegar a Jerusalém, se possível, no dia de Pentecostes."},
{"v":17,"t":"De Mileto, Paulo mandou chamar os líderes da igreja de Éfeso."},
{"v":18,"t":"Quando chegaram, ele disse: Vocês sabem como eu vivi entre vocês durante todo o tempo desde o primeiro dia que cheguei à província da Ásia."},
{"v":19,"t":"Servi ao Senhor com toda a humildade, com lágrimas e em meio às provações que os planos dos judeus me causaram."},
{"v":20,"t":"Vocês sabem que não deixei de anunciar nada que fosse útil a vocês. Ensinei em público e de casa em casa."},
{"v":21,"t":"Tanto a judeus como a gregos eu testemunhei sobre o arrependimento diante de Deus e a fé no nosso Senhor Jesus."},
{"v":22,"t":"Agora estou indo a Jerusalém, levado pelo Espírito, sem saber o que vai acontecer comigo lá."},
{"v":23,"t":"Só sei que em todas as cidades o Espírito Santo me avisa que prisão e sofrimento me esperam."},
{"v":24,"t":"Mas eu não dou valor à minha própria vida. O que importa é completar a tarefa que recebi do Senhor Jesus: dar testemunho da boa notícia da graça de Deus."},
{"v":25,"t":"Agora eu sei que nenhum de vocês, entre quem eu andei pregando o Reino, verá meu rosto de novo."},
{"v":26,"t":"Por isso eu declaro hoje: estou livre da responsabilidade pelo destino de todos vocês."},
{"v":27,"t":"Porque não deixei de anunciar a vocês toda a vontade de Deus."},
{"v":28,"t":"Cuidem de si mesmos e de todo o rebanho sobre o qual o Espírito Santo colocou vocês como líderes. Pastoreiem a igreja de Deus, que ele comprou com o seu próprio sangue."},
{"v":29,"t":"Eu sei que depois que eu for embora, lobos ferozes entrarão no meio de vocês e não pouparão o rebanho."},
{"v":30,"t":"Do meio de vocês mesmos se levantarão homens que vão distorcer a verdade para atrair seguidores."},
{"v":31,"t":"Fiquem atentos! Lembrem-se de que durante três anos, dia e noite, eu não parei de aconselhar cada um de vocês com lágrimas."},
{"v":32,"t":"Agora eu entrego vocês a Deus e à palavra da sua graça. Ela tem poder para fortalecer vocês e dar a vocês a herança entre todos os que foram santificados."},
{"v":33,"t":"Eu não cobicei a prata, o ouro nem as roupas de ninguém."},
{"v":34,"t":"Vocês mesmos sabem que estas mãos trabalharam para suprir as minhas necessidades e as dos meus companheiros."},
{"v":35,"t":"Em tudo mostrei a vocês que devemos trabalhar para ajudar os fracos. Lembrem-se das palavras do Senhor Jesus: Há mais felicidade em dar do que em receber."},
{"v":36,"t":"Depois de dizer isso, Paulo se ajoelhou com todos eles e orou."},
{"v":37,"t":"Todos choraram muito. Abraçaram e beijaram Paulo."},
{"v":38,"t":"O que mais os entristeceu foi quando ele disse que não veriam mais o rosto dele. Então o acompanharam até o navio."},
]})

# Save chapters 12-20
with open('v:/GitHub/orgs/devzolo/bible/static/data/bfl/atos_trans_part2.json', 'w', encoding='utf-8') as f:
    json.dump(chapters, f, ensure_ascii=False)
print(f"Saved chapters 12-{chapters[-1]['c']}, total verses: {sum(len(c['verses']) for c in chapters)}")
