# -*- coding: utf-8 -*-
"""BFL Translation - Mateus (Matthew) - Chapters 21-28"""
import json, sys, os

chapters = []

# Chapter 21
chapters.append({"c":21,"verses":[
{"v":1,"t":"Quando se aproximaram de Jerusalém e chegaram a Betfagé, no Monte das Oliveiras, Jesus enviou dois discípulos."},
{"v":2,"t":"Disse: Vão até a vila que está ali na frente. Logo vão encontrar uma jumenta amarrada e um jumentinho. Soltem-nos e tragam a mim."},
{"v":3,"t":"Se alguém perguntar alguma coisa, digam: O Senhor precisa deles. E logo os deixarão ir."},
{"v":4,"t":"Isso aconteceu para se cumprir o que o profeta disse:"},
{"v":5,"t":"Digam à cidade de Sião: O seu Rei vem até você. Ele é manso e vem montado num jumentinho."},
{"v":6,"t":"Os discípulos foram e fizeram como Jesus mandou."},
{"v":7,"t":"Trouxeram a jumenta e o jumentinho. Colocaram as capas sobre eles, e Jesus montou."},
{"v":8,"t":"Uma grande multidão estendia as capas pelo caminho. Outros cortavam galhos de árvores e espalhavam na estrada."},
{"v":9,"t":"A multidão que ia à frente e a que vinha atrás gritava: Hosana ao Filho de Davi! Bendito o que vem em nome do Senhor! Hosana nas alturas!"},
{"v":10,"t":"Quando Jesus entrou em Jerusalém, a cidade inteira ficou agitada. Perguntavam: Quem é esse?"},
{"v":11,"t":"A multidão respondia: Este é o profeta Jesus, de Nazaré da Galileia."},
{"v":12,"t":"Jesus entrou no templo e expulsou todos que compravam e vendiam ali. Virou as mesas dos que trocavam dinheiro e as cadeiras dos que vendiam pombas."},
{"v":13,"t":"Disse: Está escrito: A minha casa será chamada casa de oração. Mas vocês a transformaram num esconderijo de ladrões!"},
{"v":14,"t":"Cegos e pessoas que não andavam vieram a ele no templo, e ele os curou."},
{"v":15,"t":"Os chefes dos sacerdotes e os mestres da Lei viram os milagres e as crianças gritando no templo: Hosana ao Filho de Davi! E ficaram furiosos."},
{"v":16,"t":"Disseram a Jesus: Você está ouvindo o que eles dizem? Jesus respondeu: Sim. Vocês nunca leram: Da boca das crianças tiraste o louvor perfeito?"},
{"v":17,"t":"Então os deixou e saiu da cidade para Betânia, onde passou a noite."},
{"v":18,"t":"De manhã cedo, voltando à cidade, Jesus sentiu fome."},
{"v":19,"t":"Viu uma figueira à beira do caminho. Chegou perto, mas só encontrou folhas. Disse à árvore: Nunca mais dê frutos! E na mesma hora a figueira secou."},
{"v":20,"t":"Os discípulos ficaram espantados: Como a figueira secou tão rápido?"},
{"v":21,"t":"Jesus respondeu: Eu digo a verdade: se vocês tiverem fé e não duvidarem, farão não só o que aconteceu com a figueira, mas até se disserem a este monte: Levante-se e jogue-se no mar, vai acontecer."},
{"v":22,"t":"Tudo o que vocês pedirem em oração, crendo, receberão."},
{"v":23,"t":"Quando Jesus entrou no templo e começou a ensinar, os chefes dos sacerdotes e os líderes do povo se aproximaram e perguntaram: Com que autoridade você faz essas coisas? Quem deu essa autoridade a você?"},
{"v":24,"t":"Jesus respondeu: Eu também vou fazer uma pergunta. Se responderem, eu digo com que autoridade faço essas coisas."},
{"v":25,"t":"O batismo de João era de Deus ou dos homens? Eles discutiam: Se dissermos que era de Deus, ele vai perguntar por que não acreditamos."},
{"v":26,"t":"Se dissermos que era dos homens, temos medo do povo, porque todos consideram João um profeta."},
{"v":27,"t":"Responderam: Não sabemos. Jesus disse: Então eu também não digo com que autoridade faço essas coisas."},
{"v":28,"t":"O que vocês acham? Um homem tinha dois filhos. Foi ao primeiro e disse: Filho, vá trabalhar hoje na plantação."},
{"v":29,"t":"Ele respondeu: Não quero! Mas depois mudou de ideia e foi."},
{"v":30,"t":"O pai foi ao segundo filho e disse a mesma coisa. Ele respondeu: Vou sim, senhor! Mas não foi."},
{"v":31,"t":"Qual dos dois fez a vontade do pai? Responderam: O primeiro. Jesus disse: Eu digo a verdade: os cobradores de impostos e as prostitutas entrarão no Reino de Deus antes de vocês."},
{"v":32,"t":"Porque João veio mostrando o caminho certo, e vocês não acreditaram nele. Mas os cobradores de impostos e as prostitutas acreditaram. Vocês viram e mesmo assim não mudaram de ideia."},
{"v":33,"t":"Ouçam outra história: Um homem plantou uma vinha, cercou-a com um muro, fez um tanque para pisar as uvas e construiu uma torre. Depois alugou a vinha para uns agricultores e viajou."},
{"v":34,"t":"Quando chegou o tempo da colheita, enviou empregados para receber a parte dele."},
{"v":35,"t":"Mas os agricultores pegaram os empregados: bateram num, mataram outro e apedrejaram outro."},
{"v":36,"t":"O dono enviou mais empregados, em número maior. Mas eles fizeram a mesma coisa."},
{"v":37,"t":"Por último, enviou o próprio filho, pensando: Vão respeitar o meu filho."},
{"v":38,"t":"Mas os agricultores viram o filho e disseram: Este é o herdeiro! Vamos matá-lo e ficar com a herança dele!"},
{"v":39,"t":"Agarraram-no, arrastaram para fora da vinha e o mataram."},
{"v":40,"t":"Quando o dono da vinha voltar, o que fará com esses agricultores?"},
{"v":41,"t":"Responderam: Vai destruir esses maus de forma terrível e alugar a vinha para outros que entreguem a colheita na hora certa."},
{"v":42,"t":"Jesus disse: Vocês nunca leram nas Escrituras: A pedra que os construtores rejeitaram se tornou a pedra principal. Isso veio do Senhor, e é maravilhoso para nós?"},
{"v":43,"t":"Por isso eu digo: o Reino de Deus será tirado de vocês e dado a um povo que dê os frutos dele."},
{"v":44,"t":"Quem cair sobre esta pedra será despedaçado. E sobre quem ela cair, será esmagado."},
{"v":45,"t":"Os chefes dos sacerdotes e os fariseus ouviram e perceberam que Jesus falava deles."},
{"v":46,"t":"Queriam prendê-lo, mas tinham medo da multidão, que o considerava profeta."},
]})

# Chapter 22
chapters.append({"c":22,"verses":[
{"v":1,"t":"Jesus continuou falando por meio de histórias:"},
{"v":2,"t":"O Reino dos Céus é como um rei que preparou a festa de casamento do filho."},
{"v":3,"t":"Mandou empregados chamar os convidados, mas eles não quiseram vir."},
{"v":4,"t":"Mandou outros empregados com a mensagem: O banquete está pronto. Os bois e animais gordos foram preparados. Venham para a festa!"},
{"v":5,"t":"Mas os convidados não deram importância. Um foi para a fazenda, outro para o negócio."},
{"v":6,"t":"Os outros pegaram os empregados, maltrataram e mataram."},
{"v":7,"t":"O rei ficou furioso. Mandou o exército destruir os assassinos e queimar a cidade deles."},
{"v":8,"t":"Então disse aos empregados: A festa está pronta, mas os convidados não mereciam."},
{"v":9,"t":"Vão às esquinas das ruas e convidem todos que encontrarem."},
{"v":10,"t":"Os empregados saíram pelas ruas e trouxeram todos que encontraram, bons e maus. E a festa ficou cheia."},
{"v":11,"t":"Quando o rei entrou para ver os convidados, encontrou um homem que não usava roupa de festa."},
{"v":12,"t":"Disse: Amigo, como você entrou aqui sem roupa de festa? O homem não teve resposta."},
{"v":13,"t":"Então o rei ordenou: Amarrem as mãos e os pés dele e joguem na escuridão lá fora. Ali haverá choro e ranger de dentes."},
{"v":14,"t":"Porque muitos são convidados, mas poucos são escolhidos."},
{"v":15,"t":"Os fariseus foram embora e combinaram como pegar Jesus em alguma palavra."},
{"v":16,"t":"Mandaram discípulos deles junto com partidários de Herodes dizer: Mestre, sabemos que o senhor é sincero e ensina o caminho de Deus com verdade. O senhor não se importa com a opinião de ninguém."},
{"v":17,"t":"Diga-nos: é certo pagar impostos ao imperador romano ou não?"},
{"v":18,"t":"Jesus percebeu a maldade deles e disse: Hipócritas! Por que estão me testando?"},
{"v":19,"t":"Mostrem a moeda do imposto. Trouxeram uma moeda."},
{"v":20,"t":"Jesus perguntou: De quem é o rosto e o nome nesta moeda?"},
{"v":21,"t":"Responderam: Do imperador. Jesus disse: Então deem ao imperador o que é do imperador, e a Deus o que é de Deus."},
{"v":22,"t":"Quando ouviram isso, ficaram espantados. Foram embora e o deixaram."},
{"v":23,"t":"No mesmo dia, os saduceus, que dizem que não existe ressurreição, vieram a Jesus com uma pergunta:"},
{"v":24,"t":"Mestre, Moisés disse que se um homem morrer sem filhos, o irmão deve se casar com a viúva para dar descendência ao irmão."},
{"v":25,"t":"Entre nós havia sete irmãos. O primeiro se casou e morreu sem filhos. Deixou a esposa para o irmão."},
{"v":26,"t":"O mesmo aconteceu com o segundo, o terceiro e assim por diante até o sétimo."},
{"v":27,"t":"Por último, a mulher também morreu."},
{"v":28,"t":"Na ressurreição, de qual dos sete ela será esposa, já que todos se casaram com ela?"},
{"v":29,"t":"Jesus respondeu: Vocês estão errados porque não conhecem as Escrituras nem o poder de Deus."},
{"v":30,"t":"Na ressurreição, as pessoas não se casam. São como os anjos no céu."},
{"v":31,"t":"Sobre a ressurreição dos mortos, vocês não leram o que Deus disse:"},
{"v":32,"t":"Eu sou o Deus de Abraão, o Deus de Isaque e o Deus de Jacó? Deus não é Deus de mortos, mas de vivos."},
{"v":33,"t":"A multidão ouviu e ficou admirada com o ensino dele."},
{"v":34,"t":"Os fariseus souberam que Jesus tinha feito os saduceus ficarem sem resposta e se reuniram."},
{"v":35,"t":"Um deles, especialista na Lei, fez uma pergunta para testá-lo:"},
{"v":36,"t":"Mestre, qual é o mandamento mais importante da Lei?"},
{"v":37,"t":"Jesus respondeu: Ame o Senhor seu Deus de todo o coração, de toda a alma e de todo o pensamento."},
{"v":38,"t":"Este é o primeiro e mais importante mandamento."},
{"v":39,"t":"O segundo é parecido: Ame o próximo como a si mesmo."},
{"v":40,"t":"Toda a Lei e os Profetas dependem desses dois mandamentos."},
{"v":41,"t":"Enquanto os fariseus estavam reunidos, Jesus perguntou:"},
{"v":42,"t":"O que vocês pensam sobre o Cristo? De quem ele é filho? Responderam: De Davi."},
{"v":43,"t":"Jesus disse: Então como Davi, inspirado pelo Espírito, o chama de Senhor, dizendo:"},
{"v":44,"t":"O Senhor disse ao meu Senhor: Sente-se à minha direita até que eu ponha os seus inimigos debaixo dos seus pés?"},
{"v":45,"t":"Se Davi o chama de Senhor, como pode ser filho dele?"},
{"v":46,"t":"Ninguém conseguiu responder. E daquele dia em diante, ninguém mais ousou fazer perguntas a Jesus."},
]})

# Chapter 23
chapters.append({"c":23,"verses":[
{"v":1,"t":"Então Jesus disse à multidão e aos discípulos:"},
{"v":2,"t":"Os mestres da Lei e os fariseus têm a autoridade de ensinar a Lei de Moisés."},
{"v":3,"t":"Obedeçam tudo que eles dizem. Mas não façam o que eles fazem, porque falam e não praticam."},
{"v":4,"t":"Eles amarram cargas pesadas e difíceis de carregar e colocam nos ombros das pessoas. Mas eles mesmos não levantam nem um dedo para ajudar."},
{"v":5,"t":"Tudo o que fazem é para serem vistos. Usam enfeites religiosos enormes e roupas com franjas grandes."},
{"v":6,"t":"Adoram os melhores lugares nos banquetes e os assentos de honra nas sinagogas."},
{"v":7,"t":"Gostam de ser cumprimentados nas praças e de serem chamados de Mestre."},
{"v":8,"t":"Mas vocês não devem ser chamados de Mestre, porque só um é o Mestre de vocês, e todos vocês são irmãos."},
{"v":9,"t":"Não chamem ninguém na terra de Pai, porque vocês têm um só Pai, que está no céu."},
{"v":10,"t":"Não se deixem chamar de líderes, porque vocês têm um só líder: o Cristo."},
{"v":11,"t":"O maior entre vocês será aquele que serve."},
{"v":12,"t":"Quem se exaltar será humilhado. E quem se humilhar será exaltado."},
{"v":13,"t":"Ai de vocês, mestres da Lei e fariseus, hipócritas! Vocês trancam o Reino dos Céus. Nem vocês entram nem deixam entrar quem quer entrar."},
{"v":14,"t":"Ai de vocês, mestres da Lei e fariseus, hipócritas! Vocês tomam as casas das viúvas e fazem orações longas para disfarçar. Por isso receberão um castigo ainda maior."},
{"v":15,"t":"Ai de vocês, mestres da Lei e fariseus, hipócritas! Vocês cruzam mares e terras para ganhar um seguidor. E quando conseguem, fazem dele alguém duas vezes pior que vocês."},
{"v":16,"t":"Ai de vocês, guias cegos! Vocês dizem: Se alguém jurar pelo templo, não vale nada. Mas se jurar pelo ouro do templo, está preso ao juramento."},
{"v":17,"t":"Tolos e cegos! O que é mais importante: o ouro ou o templo que torna o ouro sagrado?"},
{"v":18,"t":"Vocês também dizem: Se alguém jurar pelo altar, não vale. Mas se jurar pela oferta que está sobre o altar, está preso ao juramento."},
{"v":19,"t":"Cegos! O que é mais importante: a oferta ou o altar que torna a oferta sagrada?"},
{"v":20,"t":"Quem jura pelo altar, jura por ele e por tudo que está sobre ele."},
{"v":21,"t":"Quem jura pelo templo, jura por ele e por Deus que mora nele."},
{"v":22,"t":"Quem jura pelo céu, jura pelo trono de Deus e por quem está sentado nele."},
{"v":23,"t":"Ai de vocês, mestres da Lei e fariseus, hipócritas! Vocês dão o dízimo de temperos como hortelã, endro e cominho. Mas deixam de lado o mais importante da Lei: a justiça, a compaixão e a fé. Vocês deviam praticar essas coisas sem esquecer as outras."},
{"v":24,"t":"Guias cegos! Vocês coam um mosquito e engolem um camelo!"},
{"v":25,"t":"Ai de vocês, mestres da Lei e fariseus, hipócritas! Vocês limpam o lado de fora do copo e do prato, mas por dentro estão cheios de ganância e falta de controle."},
{"v":26,"t":"Fariseu cego! Limpe primeiro o interior do copo, e o exterior também ficará limpo."},
{"v":27,"t":"Ai de vocês, mestres da Lei e fariseus, hipócritas! Vocês são como túmulos pintados de branco: bonitos por fora, mas cheios de ossos de mortos e podridão por dentro."},
{"v":28,"t":"Assim são vocês: por fora parecem justos, mas por dentro estão cheios de hipocrisia e maldade."},
{"v":29,"t":"Ai de vocês, mestres da Lei e fariseus, hipócritas! Vocês constroem túmulos para os profetas e enfeitam os monumentos dos justos."},
{"v":30,"t":"E dizem: Se tivéssemos vivido no tempo dos nossos antepassados, não teríamos participado da morte dos profetas."},
{"v":31,"t":"Com isso, vocês mesmos admitem que são filhos dos que mataram os profetas."},
{"v":32,"t":"Então completem o que os seus antepassados começaram!"},
{"v":33,"t":"Cobras! Raça de víboras! Como vocês vão escapar da condenação do inferno?"},
{"v":34,"t":"Por isso, eu envio a vocês profetas, sábios e mestres. Vocês vão matar e crucificar alguns. Vão açoitar outros nas sinagogas e persegui-los de cidade em cidade."},
{"v":35,"t":"Assim cairá sobre vocês todo o sangue inocente derramado na terra, desde o sangue de Abel até o sangue de Zacarias, filho de Baraquias, que vocês mataram entre o templo e o altar."},
{"v":36,"t":"Eu digo a verdade: tudo isso virá sobre esta geração."},
{"v":37,"t":"Jerusalém, Jerusalém! Você que mata os profetas e apedreja os que são enviados a você! Quantas vezes eu quis reunir os seus filhos, como a galinha reúne os pintinhos debaixo das asas. Mas você não quis!"},
{"v":38,"t":"A casa de vocês vai ficar abandonada."},
{"v":39,"t":"Eu digo: vocês não vão me ver de novo até que digam: Bendito o que vem em nome do Senhor!"},
]})

# Chapter 24
chapters.append({"c":24,"verses":[
{"v":1,"t":"Jesus saiu do templo e ia embora. Os discípulos se aproximaram para mostrar as construções do templo."},
{"v":2,"t":"Jesus disse: Vocês estão vendo tudo isso? Eu digo a verdade: não ficará pedra sobre pedra. Tudo será derrubado."},
{"v":3,"t":"Sentado no Monte das Oliveiras, os discípulos perguntaram em particular: Quando isso vai acontecer? E qual será o sinal da sua vinda e do fim dos tempos?"},
{"v":4,"t":"Jesus respondeu: Cuidado para ninguém enganar vocês."},
{"v":5,"t":"Muitos virão usando o meu nome e dizendo: Eu sou o Cristo. E vão enganar muitas pessoas."},
{"v":6,"t":"Vocês vão ouvir falar de guerras. Não fiquem com medo. Essas coisas precisam acontecer, mas ainda não é o fim."},
{"v":7,"t":"Nação lutará contra nação. Haverá fome, epidemias e terremotos em muitos lugares."},
{"v":8,"t":"Tudo isso é apenas o começo das dores."},
{"v":9,"t":"Vocês serão perseguidos e mortos. Todas as nações vão odiar vocês por minha causa."},
{"v":10,"t":"Muitos vão abandonar a fé, trair e odiar uns aos outros."},
{"v":11,"t":"Aparecerão muitos falsos profetas e enganarão muita gente."},
{"v":12,"t":"Por causa do aumento da maldade, o amor de muitos vai esfriar."},
{"v":13,"t":"Mas quem aguentar até o fim será salvo."},
{"v":14,"t":"Esta boa notícia do Reino será pregada no mundo inteiro, como testemunho a todos os povos. Então virá o fim."},
{"v":15,"t":"Quando vocês virem a coisa terrível e destruidora, de que falou o profeta Daniel, no lugar sagrado — quem lê, entenda —"},
{"v":16,"t":"os que estiverem na Judeia devem fugir para os montes."},
{"v":17,"t":"Quem estiver no terraço não desça para pegar nada em casa."},
{"v":18,"t":"Quem estiver no campo não volte para pegar a roupa."},
{"v":19,"t":"Ai das grávidas e das que estiverem amamentando naqueles dias!"},
{"v":20,"t":"Orem para que a fuga de vocês não seja no inverno nem no sábado."},
{"v":21,"t":"Porque haverá um sofrimento tão grande como nunca houve desde o começo do mundo até agora, e nunca mais haverá."},
{"v":22,"t":"Se aqueles dias não fossem reduzidos, ninguém sobreviveria. Mas por causa dos escolhidos, aqueles dias serão reduzidos."},
{"v":23,"t":"Se alguém disser: Olha, o Cristo está aqui! Ou: Está ali! Não acreditem."},
{"v":24,"t":"Porque surgirão falsos cristos e falsos profetas. Farão sinais e milagres tão grandes que, se fosse possível, enganariam até os escolhidos."},
{"v":25,"t":"Eu estou avisando vocês com antecedência."},
{"v":26,"t":"Se disserem: Ele está no deserto! Não vão lá. Se disserem: Ele está escondido ali dentro! Não acreditem."},
{"v":27,"t":"Porque a vinda do Filho do Homem será como o relâmpago que sai do leste e brilha até o oeste."},
{"v":28,"t":"Onde houver um corpo morto, ali se juntarão os urubus."},
{"v":29,"t":"Logo depois do sofrimento daqueles dias, o sol vai escurecer, a lua não vai brilhar, as estrelas vão cair do céu e os poderes do céu serão abalados."},
{"v":30,"t":"Então o sinal do Filho do Homem aparecerá no céu. Todos os povos da terra vão chorar e verão o Filho do Homem vindo nas nuvens com poder e grande glória."},
{"v":31,"t":"Ele enviará os anjos com um toque forte de trombeta. Eles reunirão os escolhidos dos quatro cantos da terra, de uma ponta do céu à outra."},
{"v":32,"t":"Aprendam com a figueira: quando os galhos ficam verdes e as folhas brotam, vocês sabem que o verão está perto."},
{"v":33,"t":"Da mesma forma, quando virem todas essas coisas, saibam que ele está perto, às portas."},
{"v":34,"t":"Eu digo a verdade: esta geração não vai passar sem que tudo isso aconteça."},
{"v":35,"t":"O céu e a terra vão passar, mas as minhas palavras nunca passarão."},
{"v":36,"t":"Ninguém sabe o dia nem a hora. Nem os anjos do céu. Só o Pai sabe."},
{"v":37,"t":"A vinda do Filho do Homem será como nos dias de Noé."},
{"v":38,"t":"Nos dias antes do dilúvio, as pessoas comiam, bebiam, casavam e eram dadas em casamento, até o dia em que Noé entrou na arca."},
{"v":39,"t":"Eles não perceberam nada, até que o dilúvio veio e levou todos. Assim será a vinda do Filho do Homem."},
{"v":40,"t":"Dois homens estarão trabalhando no campo: um será levado e o outro ficará."},
{"v":41,"t":"Duas mulheres estarão trabalhando no moinho: uma será levada e a outra ficará."},
{"v":42,"t":"Fiquem alertas, porque vocês não sabem em que dia o Senhor de vocês vai voltar."},
{"v":43,"t":"Pensem nisso: se o dono da casa soubesse a que hora o ladrão viria, ficaria acordado e não deixaria a casa ser arrombada."},
{"v":44,"t":"Por isso, estejam preparados, porque o Filho do Homem virá na hora que vocês menos esperam."},
{"v":45,"t":"Quem é o empregado fiel e sábio que o patrão colocou para cuidar dos outros e dar comida na hora certa?"},
{"v":46,"t":"Feliz o empregado que estiver fazendo isso quando o patrão voltar."},
{"v":47,"t":"Eu digo a verdade: o patrão vai colocá-lo para cuidar de tudo que tem."},
{"v":48,"t":"Mas se esse empregado for mau e pensar: Meu patrão vai demorar,"},
{"v":49,"t":"e começar a bater nos companheiros e a comer e beber com bêbados,"},
{"v":50,"t":"o patrão dele vai chegar num dia que ele não espera e numa hora que ele não sabe."},
{"v":51,"t":"Vai castigá-lo severamente e dar a ele o destino dos hipócritas. Ali haverá choro e ranger de dentes."},
]})

# Chapter 25
chapters.append({"c":25,"verses":[
{"v":1,"t":"O Reino dos Céus será como dez moças que pegaram suas lâmpadas e saíram para encontrar o noivo."},
{"v":2,"t":"Cinco eram sensatas e cinco eram tolas."},
{"v":3,"t":"As tolas levaram as lâmpadas, mas não levaram óleo extra."},
{"v":4,"t":"As sensatas levaram óleo em vasilhas, junto com as lâmpadas."},
{"v":5,"t":"Como o noivo demorou, todas ficaram com sono e dormiram."},
{"v":6,"t":"À meia-noite ouviu-se um grito: O noivo está chegando! Saiam para encontrá-lo!"},
{"v":7,"t":"Todas as moças acordaram e arrumaram as lâmpadas."},
{"v":8,"t":"As tolas disseram às sensatas: Deem um pouco do óleo de vocês, porque as nossas lâmpadas estão apagando."},
{"v":9,"t":"As sensatas responderam: Não, senão não vai ter suficiente para nós e para vocês. Vão comprar nos vendedores."},
{"v":10,"t":"Enquanto foram comprar, o noivo chegou. As que estavam preparadas entraram com ele para a festa, e a porta se fechou."},
{"v":11,"t":"Depois chegaram as outras moças e disseram: Senhor, senhor, abra para nós!"},
{"v":12,"t":"Mas ele respondeu: Eu digo a verdade: eu não conheço vocês."},
{"v":13,"t":"Fiquem alertas, porque vocês não sabem nem o dia nem a hora."},
{"v":14,"t":"Também é como um homem que ia viajar. Chamou os empregados e entregou os bens dele a eles."},
{"v":15,"t":"A um deu cinco sacas de ouro, a outro duas, e a outro uma. A cada um de acordo com a capacidade. Depois viajou."},
{"v":16,"t":"O que recebeu cinco sacas foi trabalhar com elas e ganhou mais cinco."},
{"v":17,"t":"O que recebeu duas também ganhou mais duas."},
{"v":18,"t":"Mas o que recebeu uma foi, cavou um buraco na terra e escondeu o dinheiro do patrão."},
{"v":19,"t":"Muito tempo depois, o patrão voltou e acertou as contas com eles."},
{"v":20,"t":"O que recebeu cinco sacas trouxe mais cinco e disse: Senhor, o senhor me entregou cinco sacas. Veja, eu ganhei mais cinco!"},
{"v":21,"t":"O patrão disse: Muito bem, empregado bom e fiel! Você foi fiel no pouco. Eu vou colocá-lo para cuidar de muito. Venha compartilhar da minha alegria!"},
{"v":22,"t":"O que recebeu duas sacas disse: Senhor, o senhor me entregou duas sacas. Veja, eu ganhei mais duas!"},
{"v":23,"t":"O patrão disse: Muito bem, empregado bom e fiel! Você foi fiel no pouco. Eu vou colocá-lo para cuidar de muito. Venha compartilhar da minha alegria!"},
{"v":24,"t":"Então veio o que recebeu uma saca e disse: Senhor, eu sei que o senhor é um homem duro. Colhe onde não plantou e junta onde não semeou."},
{"v":25,"t":"Fiquei com medo e escondi o seu dinheiro na terra. Aqui está o que é seu."},
{"v":26,"t":"O patrão respondeu: Empregado mau e preguiçoso! Você sabia que eu colho onde não plantei e junto onde não semeei?"},
{"v":27,"t":"Então devia ter colocado meu dinheiro no banco. Quando eu voltasse, receberia de volta com juros."},
{"v":28,"t":"Tirem a saca de ouro dele e deem ao que tem dez."},
{"v":29,"t":"Porque a quem tem, mais será dado, e terá em abundância. Mas de quem não tem, até o que tem será tirado."},
{"v":30,"t":"Joguem esse empregado inútil na escuridão lá fora. Ali haverá choro e ranger de dentes."},
{"v":31,"t":"Quando o Filho do Homem vier em sua glória, com todos os anjos, ele se sentará no seu trono glorioso."},
{"v":32,"t":"Todos os povos serão reunidos diante dele. Ele vai separar as pessoas umas das outras, como o pastor separa as ovelhas dos bodes."},
{"v":33,"t":"Colocará as ovelhas à direita e os bodes à esquerda."},
{"v":34,"t":"Então o Rei dirá aos que estiverem à direita: Venham, abençoados do meu Pai! Recebam o Reino que foi preparado para vocês desde a criação do mundo."},
{"v":35,"t":"Porque eu tive fome, e vocês me deram de comer. Tive sede, e vocês me deram de beber. Eu era estranho, e vocês me acolheram."},
{"v":36,"t":"Estava sem roupa, e vocês me vestiram. Fiquei doente, e vocês me visitaram. Estava na prisão, e vocês foram me ver."},
{"v":37,"t":"Os justos vão perguntar: Senhor, quando foi que vimos o senhor com fome e demos de comer? Com sede e demos de beber?"},
{"v":38,"t":"Quando vimos o senhor como estranho e acolhemos? Sem roupa e vestimos?"},
{"v":39,"t":"Quando vimos o senhor doente ou na prisão e fomos visitá-lo?"},
{"v":40,"t":"O Rei vai responder: Eu digo a verdade: tudo o que vocês fizeram a um destes meus irmãos mais pequenos, foi a mim que fizeram."},
{"v":41,"t":"Então dirá aos da esquerda: Afastem-se de mim, malditos! Vão para o fogo eterno, preparado para o diabo e os anjos dele."},
{"v":42,"t":"Porque eu tive fome, e vocês não me deram de comer. Tive sede, e vocês não me deram de beber."},
{"v":43,"t":"Eu era estranho, e vocês não me acolheram. Estava sem roupa, e vocês não me vestiram. Doente e na prisão, e vocês não me visitaram."},
{"v":44,"t":"Eles vão perguntar: Senhor, quando vimos o senhor com fome, sede, como estranho, sem roupa, doente ou na prisão, e não o ajudamos?"},
{"v":45,"t":"O Rei vai responder: Eu digo a verdade: tudo o que vocês deixaram de fazer a um destes mais pequenos, foi a mim que deixaram de fazer."},
{"v":46,"t":"Estes irão para o castigo eterno. Mas os justos irão para a vida eterna."},
]})

# Chapter 26
chapters.append({"c":26,"verses":[
{"v":1,"t":"Quando Jesus terminou tudo o que tinha para dizer, disse aos discípulos:"},
{"v":2,"t":"Vocês sabem que daqui a dois dias é a Páscoa. E o Filho do Homem será entregue para ser crucificado."},
{"v":3,"t":"Nessa mesma hora, os chefes dos sacerdotes, os mestres da Lei e os líderes do povo se reuniram no palácio do sumo sacerdote, chamado Caifás."},
{"v":4,"t":"E combinaram prender Jesus com uma armadilha para matá-lo."},
{"v":5,"t":"Mas diziam: Não durante a festa, para não causar tumulto no povo."},
{"v":6,"t":"Jesus estava em Betânia, na casa de Simão, o leproso."},
{"v":7,"t":"Uma mulher se aproximou com um frasco de perfume muito caro e derramou na cabeça de Jesus, enquanto ele estava à mesa."},
{"v":8,"t":"Os discípulos ficaram irritados e disseram: Que desperdício!"},
{"v":9,"t":"Esse perfume podia ser vendido por muito dinheiro e dado aos pobres."},
{"v":10,"t":"Mas Jesus percebeu e disse: Por que incomodam essa mulher? Ela fez uma coisa bonita por mim."},
{"v":11,"t":"Os pobres vocês sempre terão. Mas a mim vocês não terão sempre."},
{"v":12,"t":"Ao derramar este perfume, ela preparou o meu corpo para o sepultamento."},
{"v":13,"t":"Eu digo a verdade: em todo lugar do mundo onde esta boa notícia for anunciada, o que ela fez será contado em memória dela."},
{"v":14,"t":"Então Judas Iscariotes, um dos doze, foi aos chefes dos sacerdotes"},
{"v":15,"t":"e perguntou: Quanto vocês me pagam para eu entregar Jesus? Eles combinaram trinta moedas de prata."},
{"v":16,"t":"A partir daquele momento, Judas procurava uma oportunidade para entregar Jesus."},
{"v":17,"t":"No primeiro dia da festa dos Pães sem Fermento, os discípulos perguntaram: Onde o senhor quer que preparemos a ceia da Páscoa?"},
{"v":18,"t":"Jesus respondeu: Vão à cidade, a certa pessoa, e digam: O Mestre diz: O meu tempo está perto. Vou celebrar a Páscoa na sua casa com os meus discípulos."},
{"v":19,"t":"Os discípulos fizeram como Jesus mandou e prepararam a Páscoa."},
{"v":20,"t":"Quando a noite chegou, Jesus estava à mesa com os doze."},
{"v":21,"t":"Enquanto comiam, disse: Eu digo a verdade: um de vocês vai me trair."},
{"v":22,"t":"Eles ficaram muito tristes. Cada um perguntava: Sou eu, Senhor?"},
{"v":23,"t":"Jesus respondeu: Aquele que colocou a mão no prato comigo é quem vai me trair."},
{"v":24,"t":"O Filho do Homem vai, como está escrito sobre ele. Mas ai daquele que trai o Filho do Homem! Seria melhor para ele não ter nascido."},
{"v":25,"t":"Judas, o traidor, perguntou: Sou eu, Mestre? Jesus respondeu: Você mesmo disse."},
{"v":26,"t":"Enquanto comiam, Jesus pegou o pão, deu graças, partiu e deu aos discípulos, dizendo: Peguem e comam. Isto é o meu corpo."},
{"v":27,"t":"Pegou o cálice, deu graças e deu a eles, dizendo: Bebam dele todos."},
{"v":28,"t":"Porque isto é o meu sangue, o sangue da nova aliança, derramado por muitos para o perdão dos pecados."},
{"v":29,"t":"Eu digo: não beberei mais deste vinho até o dia em que beber com vocês o vinho novo no Reino do meu Pai."},
{"v":30,"t":"Depois de cantarem um hino, saíram para o Monte das Oliveiras."},
{"v":31,"t":"Jesus disse: Esta noite, todos vocês vão me abandonar. Porque está escrito: Vou ferir o pastor, e as ovelhas se espalharão."},
{"v":32,"t":"Mas depois que eu ressuscitar, irei na frente de vocês para a Galileia."},
{"v":33,"t":"Pedro disse: Mesmo que todos o abandonem, eu nunca vou abandonar o senhor!"},
{"v":34,"t":"Jesus disse: Eu digo a verdade: esta noite, antes do galo cantar, você vai me negar três vezes."},
{"v":35,"t":"Pedro disse: Mesmo que eu tenha que morrer com o senhor, eu não vou negá-lo! E todos os discípulos disseram o mesmo."},
{"v":36,"t":"Jesus foi com eles a um lugar chamado Getsêmani. Disse aos discípulos: Sentem-se aqui enquanto eu vou ali orar."},
{"v":37,"t":"Levou Pedro e os dois filhos de Zebedeu. Começou a sentir uma tristeza e angústia muito grande."},
{"v":38,"t":"Disse a eles: A minha alma está cheia de tristeza, a ponto de morrer. Fiquem aqui e vigiem comigo."},
{"v":39,"t":"Foi um pouco mais adiante, caiu com o rosto no chão e orou: Meu Pai, se for possível, afaste de mim este cálice de sofrimento. Mas não seja o que eu quero, e sim o que o senhor quer."},
{"v":40,"t":"Voltou e encontrou os discípulos dormindo. Disse a Pedro: Vocês não conseguiram vigiar comigo nem uma hora?"},
{"v":41,"t":"Vigiem e orem para não caírem em tentação. O espírito quer fazer o certo, mas o corpo é fraco."},
{"v":42,"t":"Foi orar pela segunda vez: Meu Pai, se este cálice não pode ser afastado sem que eu o beba, que a sua vontade seja feita."},
{"v":43,"t":"Voltou e os encontrou dormindo de novo, porque os olhos deles estavam pesados."},
{"v":44,"t":"Deixou-os e foi orar pela terceira vez, dizendo as mesmas palavras."},
{"v":45,"t":"Voltou aos discípulos e disse: Ainda estão dormindo e descansando? A hora chegou! O Filho do Homem está sendo entregue nas mãos dos pecadores."},
{"v":46,"t":"Levantem-se! Vamos! O traidor já está chegando."},
{"v":47,"t":"Enquanto Jesus ainda falava, chegou Judas, um dos doze. Com ele vinha uma grande multidão com espadas e paus, enviada pelos chefes dos sacerdotes e líderes do povo."},
{"v":48,"t":"O traidor tinha combinado um sinal: Aquele que eu beijar é ele. Prendam-no."},
{"v":49,"t":"Judas se aproximou de Jesus e disse: Saudações, Mestre! E o beijou."},
{"v":50,"t":"Jesus disse: Amigo, faça o que veio fazer. Então eles se aproximaram, agarraram Jesus e o prenderam."},
{"v":51,"t":"Um dos que estavam com Jesus puxou a espada, atacou o empregado do sumo sacerdote e cortou a orelha dele."},
{"v":52,"t":"Jesus disse: Guarde a espada! Porque todos os que usarem espada pela espada morrerão."},
{"v":53,"t":"Você acha que eu não posso pedir ao meu Pai e ele me mandaria agora mesmo mais de doze legiões de anjos?"},
{"v":54,"t":"Mas como as Escrituras se cumpririam, que dizem que tem que ser assim?"},
{"v":55,"t":"Naquele momento, Jesus disse à multidão: Vocês vieram me prender com espadas e paus, como se eu fosse um criminoso? Todos os dias eu estava no templo ensinando, e vocês não me prenderam."},
{"v":56,"t":"Mas tudo isso aconteceu para que se cumprissem as Escrituras dos profetas. Então todos os discípulos o abandonaram e fugiram."},
{"v":57,"t":"Os que prenderam Jesus o levaram à casa do sumo sacerdote Caifás, onde os mestres da Lei e os líderes estavam reunidos."},
{"v":58,"t":"Pedro seguiu de longe até o pátio do sumo sacerdote. Entrou e sentou com os guardas para ver o que ia acontecer."},
{"v":59,"t":"Os chefes dos sacerdotes e todo o conselho procuravam um falso testemunho contra Jesus para condená-lo à morte."},
{"v":60,"t":"Mas não encontraram, apesar de virem muitas testemunhas falsas. Por fim, vieram duas"},
{"v":61,"t":"que disseram: Este homem disse: Eu posso destruir o templo de Deus e reconstruí-lo em três dias."},
{"v":62,"t":"O sumo sacerdote se levantou e disse a Jesus: Não vai responder nada ao que eles dizem contra você?"},
{"v":63,"t":"Jesus ficou em silêncio. O sumo sacerdote insistiu: Eu ordeno pelo Deus vivo que nos diga se você é o Cristo, o Filho de Deus!"},
{"v":64,"t":"Jesus respondeu: Você mesmo disse. E eu digo: vocês verão o Filho do Homem sentado à direita do Poder e vindo nas nuvens do céu."},
{"v":65,"t":"Então o sumo sacerdote rasgou as roupas e disse: Ele ofendeu a Deus! Não precisamos de mais testemunhas! Vocês ouviram a ofensa."},
{"v":66,"t":"O que vocês acham? Responderam: Merece a morte!"},
{"v":67,"t":"Cuspiram no rosto dele e deram socos. Outros bateram"},
{"v":68,"t":"e disseram: Profetize, Cristo! Quem bateu em você?"},
{"v":69,"t":"Pedro estava sentado no pátio. Uma empregada se aproximou e disse: Você também estava com Jesus, o galileu."},
{"v":70,"t":"Pedro negou diante de todos: Eu não sei do que você está falando."},
{"v":71,"t":"Saindo para a porta, outra empregada o viu e disse: Este homem estava com Jesus de Nazaré."},
{"v":72,"t":"Pedro negou de novo, jurando: Eu não conheço esse homem!"},
{"v":73,"t":"Pouco depois, os que estavam ali se aproximaram de Pedro: Com certeza você é um deles! O seu sotaque entrega você."},
{"v":74,"t":"Então Pedro começou a amaldiçoar e jurar: Eu não conheço esse homem! Na mesma hora, o galo cantou."},
{"v":75,"t":"Pedro lembrou das palavras de Jesus: Antes do galo cantar, você vai me negar três vezes. Saiu dali e chorou muito."},
]})

# Chapter 27
chapters.append({"c":27,"verses":[
{"v":1,"t":"De manhã cedo, todos os chefes dos sacerdotes e líderes do povo se reuniram contra Jesus e decidiram matá-lo."},
{"v":2,"t":"Amarraram-no, levaram e entregaram a Pilatos, o governador romano."},
{"v":3,"t":"Quando Judas, o traidor, viu que Jesus foi condenado, se arrependeu. Devolveu as trinta moedas de prata aos chefes dos sacerdotes e líderes."},
{"v":4,"t":"Disse: Eu pequei! Entreguei um homem inocente! Eles responderam: O problema é seu."},
{"v":5,"t":"Judas jogou as moedas no templo, saiu e se enforcou."},
{"v":6,"t":"Os chefes dos sacerdotes pegaram as moedas e disseram: Não podemos colocar isso no cofre do templo, porque é dinheiro de sangue."},
{"v":7,"t":"Então usaram o dinheiro para comprar o campo de um oleiro, como cemitério para estrangeiros."},
{"v":8,"t":"Por isso, aquele campo é chamado até hoje de Campo de Sangue."},
{"v":9,"t":"Assim se cumpriu o que o profeta Jeremias disse: Pegaram as trinta moedas de prata, o preço que o povo de Israel colocou nele,"},
{"v":10,"t":"e as usaram para comprar o campo do oleiro, como o Senhor me ordenou."},
{"v":11,"t":"Jesus foi levado diante do governador. Pilatos perguntou: Você é o Rei dos Judeus? Jesus respondeu: Você mesmo está dizendo."},
{"v":12,"t":"Quando os chefes dos sacerdotes e líderes o acusaram, Jesus não respondeu nada."},
{"v":13,"t":"Pilatos disse: Não ouve quantas acusações fazem contra você?"},
{"v":14,"t":"Mas Jesus não respondeu nem uma palavra. O governador ficou muito surpreso."},
{"v":15,"t":"Na festa, o governador costumava soltar um preso que o povo escolhesse."},
{"v":16,"t":"Naquela época havia um preso famoso chamado Barrabás."},
{"v":17,"t":"Pilatos perguntou à multidão reunida: Quem vocês querem que eu solte? Barrabás ou Jesus, chamado Cristo?"},
{"v":18,"t":"Porque sabia que tinham entregado Jesus por inveja."},
{"v":19,"t":"Enquanto Pilatos estava sentado no tribunal, a esposa dele mandou um recado: Não se meta com esse homem justo. Eu sofri muito num sonho por causa dele."},
{"v":20,"t":"Mas os chefes dos sacerdotes e os líderes convenceram a multidão a pedir a soltura de Barrabás e a morte de Jesus."},
{"v":21,"t":"O governador perguntou: Qual dos dois vocês querem que eu solte? Gritaram: Barrabás!"},
{"v":22,"t":"Pilatos perguntou: Então o que faço com Jesus, chamado Cristo? Todos gritaram: Crucifique!"},
{"v":23,"t":"Pilatos disse: Mas que mal ele fez? Eles gritaram ainda mais: Crucifique!"},
{"v":24,"t":"Pilatos viu que não adiantava nada e que o tumulto aumentava. Pegou água, lavou as mãos diante do povo e disse: Eu não tenho culpa pela morte deste homem. O problema é de vocês."},
{"v":25,"t":"Todo o povo respondeu: Que o sangue dele caia sobre nós e sobre os nossos filhos!"},
{"v":26,"t":"Então Pilatos soltou Barrabás. Mandou açoitar Jesus e o entregou para ser crucificado."},
{"v":27,"t":"Os soldados do governador levaram Jesus para dentro do palácio e reuniram toda a tropa ao redor dele."},
{"v":28,"t":"Tiraram a roupa dele e colocaram um manto vermelho."},
{"v":29,"t":"Fizeram uma coroa de espinhos e puseram na cabeça dele. Colocaram uma vara na mão direita. Ajoelhavam diante dele e zombavam: Salve, Rei dos Judeus!"},
{"v":30,"t":"Cuspiam nele, pegavam a vara e batiam na cabeça dele."},
{"v":31,"t":"Depois de zombar, tiraram o manto, colocaram as roupas dele de volta e o levaram para crucificar."},
{"v":32,"t":"No caminho, encontraram um homem de Cirene chamado Simão. Obrigaram-no a carregar a cruz de Jesus."},
{"v":33,"t":"Chegaram ao lugar chamado Gólgota, que quer dizer Lugar da Caveira."},
{"v":34,"t":"Ofereceram a Jesus vinho misturado com substância amarga. Ele provou, mas não quis beber."},
{"v":35,"t":"Depois de crucificá-lo, dividiram as roupas dele entre si, tirando sortes."},
{"v":36,"t":"E ficaram ali sentados, vigiando."},
{"v":37,"t":"Acima da cabeça dele colocaram a acusação escrita: ESTE É JESUS, O REI DOS JUDEUS."},
{"v":38,"t":"Junto com ele, crucificaram dois criminosos, um à direita e outro à esquerda."},
{"v":39,"t":"Os que passavam insultavam Jesus, balançando a cabeça"},
{"v":40,"t":"e dizendo: Você que destrói o templo e reconstrói em três dias, salve a si mesmo! Se é o Filho de Deus, desça da cruz!"},
{"v":41,"t":"Os chefes dos sacerdotes, mestres da Lei e líderes também zombavam:"},
{"v":42,"t":"Salvou outros, mas não pode salvar a si mesmo! Se é o Rei de Israel, que desça da cruz agora, e nós vamos crer nele."},
{"v":43,"t":"Confiou em Deus. Que Deus o salve agora, se o quer! Pois disse: Sou Filho de Deus."},
{"v":44,"t":"Até os criminosos crucificados com ele o insultavam."},
{"v":45,"t":"Do meio-dia às três da tarde, uma escuridão cobriu toda a terra."},
{"v":46,"t":"Por volta das três da tarde, Jesus gritou com voz forte: Eli, Eli, lamá sabactâni? Que quer dizer: Deus meu, Deus meu, por que me abandonou?"},
{"v":47,"t":"Alguns dos que estavam ali ouviram e disseram: Ele está chamando Elias."},
{"v":48,"t":"Logo, um deles correu, pegou uma esponja, encheu de vinagre, colocou numa vara e deu a Jesus para beber."},
{"v":49,"t":"Os outros diziam: Deixem! Vamos ver se Elias vem salvá-lo."},
{"v":50,"t":"Jesus gritou de novo com voz forte e morreu."},
{"v":51,"t":"Naquele momento, a cortina do templo se rasgou em duas partes, de cima a baixo. A terra tremeu e as rochas se partiram."},
{"v":52,"t":"Os túmulos se abriram, e muitos que tinham morrido voltaram à vida."},
{"v":53,"t":"Depois que Jesus ressuscitou, eles saíram dos túmulos, entraram na cidade santa e apareceram a muitas pessoas."},
{"v":54,"t":"O oficial romano e os soldados que vigiavam Jesus viram o terremoto e tudo que aconteceu. Ficaram apavorados e disseram: Este homem era mesmo o Filho de Deus!"},
{"v":55,"t":"Muitas mulheres que tinham seguido Jesus desde a Galileia, servindo-o, estavam ali, olhando de longe."},
{"v":56,"t":"Entre elas estavam Maria Madalena, Maria, mãe de Tiago e José, e a mãe dos filhos de Zebedeu."},
{"v":57,"t":"Quando a tarde chegou, veio um homem rico de Arimateia, chamado José, que também era discípulo de Jesus."},
{"v":58,"t":"Foi a Pilatos e pediu o corpo de Jesus. Pilatos mandou entregar."},
{"v":59,"t":"José pegou o corpo, envolveu num tecido limpo de linho"},
{"v":60,"t":"e o colocou no seu túmulo novo, que tinha sido cavado na rocha. Rolou uma pedra grande na entrada do túmulo e foi embora."},
{"v":61,"t":"Maria Madalena e a outra Maria estavam ali, sentadas em frente ao túmulo."},
{"v":62,"t":"No dia seguinte, que era depois da Preparação, os chefes dos sacerdotes e os fariseus foram juntos a Pilatos."},
{"v":63,"t":"Disseram: Senhor, lembramos que aquele enganador disse quando era vivo: Depois de três dias vou ressuscitar."},
{"v":64,"t":"Mande guardar o túmulo até o terceiro dia. Senão os discípulos podem roubar o corpo e dizer ao povo que ele ressuscitou. E a última mentira seria pior que a primeira."},
{"v":65,"t":"Pilatos disse: Vocês têm guardas. Vão e protejam como acharem melhor."},
{"v":66,"t":"Eles foram, lacraram a pedra e colocaram guardas no túmulo."},
]})

# Chapter 28
chapters.append({"c":28,"verses":[
{"v":1,"t":"Depois do sábado, ao amanhecer do primeiro dia da semana, Maria Madalena e a outra Maria foram ver o túmulo."},
{"v":2,"t":"De repente, houve um grande terremoto. Um anjo do Senhor desceu do céu, rolou a pedra e se sentou sobre ela."},
{"v":3,"t":"A aparência do anjo era como um relâmpago, e as roupas eram brancas como neve."},
{"v":4,"t":"Os guardas tremeram de medo e ficaram como mortos."},
{"v":5,"t":"O anjo disse às mulheres: Não tenham medo! Eu sei que vocês estão procurando Jesus, que foi crucificado."},
{"v":6,"t":"Ele não está aqui. Ressuscitou, como tinha dito! Venham ver o lugar onde ele estava."},
{"v":7,"t":"Vão depressa e digam aos discípulos: Ele ressuscitou dos mortos e vai na frente de vocês para a Galileia. Lá vocês vão vê-lo. Eu já avisei vocês."},
{"v":8,"t":"As mulheres saíram depressa do túmulo, com medo e grande alegria, e correram para contar aos discípulos."},
{"v":9,"t":"De repente, Jesus apareceu e disse: Saudações! Elas se aproximaram, abraçaram os pés dele e o adoraram."},
{"v":10,"t":"Jesus disse: Não tenham medo. Vão dizer aos meus irmãos que sigam para a Galileia. Lá eles vão me ver."},
{"v":11,"t":"Enquanto as mulheres iam, alguns guardas foram à cidade e contaram aos chefes dos sacerdotes tudo que tinha acontecido."},
{"v":12,"t":"Os chefes se reuniram com os líderes. Deram muito dinheiro aos soldados"},
{"v":13,"t":"e disseram: Digam que os discípulos dele vieram à noite e roubaram o corpo enquanto vocês dormiam."},
{"v":14,"t":"Se o governador souber disso, nós o convenceremos e protegeremos vocês."},
{"v":15,"t":"Os soldados pegaram o dinheiro e fizeram como foram instruídos. Essa história se espalhou entre os judeus até hoje."},
{"v":16,"t":"Os onze discípulos foram para a Galileia, ao monte que Jesus tinha indicado."},
{"v":17,"t":"Quando o viram, o adoraram, mas alguns duvidaram."},
{"v":18,"t":"Jesus se aproximou e disse: Todo poder no céu e na terra foi dado a mim."},
{"v":19,"t":"Portanto, vão e façam discípulos em todos os povos, batizando-os em nome do Pai, do Filho e do Espírito Santo."},
{"v":20,"t":"Ensinem a obedecer tudo o que eu mandei. E eu estarei com vocês todos os dias, até o fim dos tempos. Amém."},
]})

# Save chapters 21-28
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'static', 'data', 'bfl', 'mateus_trans_p3.json'), 'w', encoding='utf-8') as f:
    json.dump(chapters, f, ensure_ascii=False, indent=None, separators=(',',':'))

print(f"Matthew chapters 21-28 ready: {sum(len(c['verses']) for c in chapters)} verses")
