# -*- coding: utf-8 -*-
"""BFL Translation - Mateus (Matthew) - All 28 chapters"""
import json, sys, os

chapters = []

# Chapter 1 - Genealogy and Birth of Jesus
chapters.append({"c":1,"verses":[
{"v":1,"t":"Este é o registro dos antepassados de Jesus Cristo, descendente de Davi e de Abraão."},
{"v":2,"t":"Abraão foi pai de Isaque. Isaque foi pai de Jacó. Jacó foi pai de Judá e de seus irmãos."},
{"v":3,"t":"Judá foi pai de Perez e Zerá. A mãe deles foi Tamar. Perez foi pai de Esrom. Esrom foi pai de Arão."},
{"v":4,"t":"Arão foi pai de Aminadabe. Aminadabe foi pai de Naassom. Naassom foi pai de Salmom."},
{"v":5,"t":"Salmom foi pai de Boaz, e a mãe de Boaz foi Raabe. Boaz foi pai de Obede, e a mãe de Obede foi Rute. Obede foi pai de Jessé."},
{"v":6,"t":"Jessé foi pai do rei Davi. Davi foi pai de Salomão. A mãe de Salomão tinha sido esposa de Urias."},
{"v":7,"t":"Salomão foi pai de Roboão. Roboão foi pai de Abias. Abias foi pai de Asa."},
{"v":8,"t":"Asa foi pai de Josafá. Josafá foi pai de Jorão. Jorão foi pai de Uzias."},
{"v":9,"t":"Uzias foi pai de Jotão. Jotão foi pai de Acaz. Acaz foi pai de Ezequias."},
{"v":10,"t":"Ezequias foi pai de Manassés. Manassés foi pai de Amom. Amom foi pai de Josias."},
{"v":11,"t":"Josias foi pai de Jeconias e de seus irmãos. Isso foi na época em que o povo foi levado para a Babilônia."},
{"v":12,"t":"Depois que o povo foi levado para a Babilônia, Jeconias foi pai de Salatiel. Salatiel foi pai de Zorobabel."},
{"v":13,"t":"Zorobabel foi pai de Abiúde. Abiúde foi pai de Eliaquim. Eliaquim foi pai de Azor."},
{"v":14,"t":"Azor foi pai de Sadoque. Sadoque foi pai de Aquim. Aquim foi pai de Eliúde."},
{"v":15,"t":"Eliúde foi pai de Eleazar. Eleazar foi pai de Matã. Matã foi pai de Jacó."},
{"v":16,"t":"Jacó foi pai de José, o marido de Maria. E Maria foi a mãe de Jesus, que é chamado de Cristo."},
{"v":17,"t":"Assim, de Abraão até Davi foram catorze gerações. De Davi até o exílio na Babilônia, mais catorze. E do exílio até Cristo, outras catorze gerações."},
{"v":18,"t":"O nascimento de Jesus aconteceu assim: Maria, a mãe dele, estava prometida em casamento a José. Antes de se casarem, ela ficou grávida pelo poder do Espírito Santo."},
{"v":19,"t":"José, o noivo dela, era um homem justo. Ele não queria humilhar Maria em público. Por isso, decidiu cancelar o casamento em segredo."},
{"v":20,"t":"Enquanto José pensava nisso, um anjo do Senhor apareceu a ele em sonho e disse: José, descendente de Davi, não tenha medo de se casar com Maria. O filho que ela espera vem do Espírito Santo."},
{"v":21,"t":"Ela terá um filho, e você vai dar a ele o nome de Jesus. Esse nome significa que ele vai salvar o seu povo dos pecados deles."},
{"v":22,"t":"Tudo isso aconteceu para se cumprir o que o Senhor disse pelo profeta:"},
{"v":23,"t":"A virgem ficará grávida e terá um filho. Ele será chamado Emanuel, que quer dizer: Deus está conosco."},
{"v":24,"t":"Quando José acordou, fez o que o anjo do Senhor mandou. Ele se casou com Maria."},
{"v":25,"t":"Mas não teve relações com ela até o filho nascer. E deu a ele o nome de Jesus."},
]})

# Chapter 2 - Wise Men and Flight to Egypt
chapters.append({"c":2,"verses":[
{"v":1,"t":"Jesus nasceu em Belém da Judeia, no tempo do rei Herodes. Nessa época, alguns sábios do Oriente chegaram a Jerusalém"},
{"v":2,"t":"e perguntaram: Onde está o rei dos judeus que acabou de nascer? Nós vimos a estrela dele no Oriente e viemos adorá-lo."},
{"v":3,"t":"Quando o rei Herodes ouviu isso, ficou muito preocupado. E toda Jerusalém também."},
{"v":4,"t":"Herodes reuniu todos os chefes dos sacerdotes e os mestres da Lei e perguntou onde o Cristo deveria nascer."},
{"v":5,"t":"Eles responderam: Em Belém da Judeia. O profeta escreveu assim:"},
{"v":6,"t":"E você, Belém, terra de Judá, não é de modo nenhum a menor entre as principais cidades de Judá. Porque de você sairá o líder que vai cuidar do meu povo Israel."},
{"v":7,"t":"Então Herodes chamou os sábios em segredo e perguntou exatamente quando a estrela tinha aparecido."},
{"v":8,"t":"Depois os enviou a Belém e disse: Vão e procurem bem o menino. Quando o encontrarem, me avisem para que eu também vá adorá-lo."},
{"v":9,"t":"Depois de ouvirem o rei, eles partiram. E a estrela que tinham visto no Oriente ia à frente deles, até parar sobre o lugar onde o menino estava."},
{"v":10,"t":"Quando viram a estrela, ficaram muito felizes."},
{"v":11,"t":"Entraram na casa e viram o menino com Maria, a mãe dele. Ajoelharam-se e o adoraram. Depois abriram seus tesouros e deram presentes: ouro, incenso e mirra."},
{"v":12,"t":"Deus os avisou em sonho para não voltarem a Herodes. Então voltaram para a terra deles por outro caminho."},
{"v":13,"t":"Depois que os sábios foram embora, um anjo do Senhor apareceu a José em sonho e disse: Levante-se! Pegue o menino e a mãe dele e fuja para o Egito. Fique lá até eu avisar. Porque Herodes vai procurar o menino para matá-lo."},
{"v":14,"t":"José se levantou, pegou o menino e a mãe dele durante a noite, e foi para o Egito."},
{"v":15,"t":"E ficou lá até a morte de Herodes. Assim se cumpriu o que o Senhor disse pelo profeta: Do Egito chamei o meu Filho."},
{"v":16,"t":"Quando Herodes percebeu que os sábios tinham enganado ele, ficou furioso. Mandou matar todos os meninos de Belém e região com dois anos ou menos. Ele se baseou na data que os sábios tinham informado."},
{"v":17,"t":"Então se cumpriu o que o profeta Jeremias disse:"},
{"v":18,"t":"Em Ramá se ouviu uma voz, choro e grande sofrimento. Raquel chorava pelos seus filhos e não queria ser consolada, porque eles já não existem."},
{"v":19,"t":"Depois que Herodes morreu, um anjo do Senhor apareceu a José em sonho, no Egito."},
{"v":20,"t":"O anjo disse: Levante-se! Pegue o menino e a mãe dele e volte para Israel. Porque os que queriam matar o menino já morreram."},
{"v":21,"t":"José se levantou, pegou o menino e a mãe dele, e voltou para Israel."},
{"v":22,"t":"Mas quando soube que Arquelau governava a Judeia no lugar de Herodes, teve medo de ir para lá. Avisado por Deus em sonho, foi para a região da Galileia."},
{"v":23,"t":"Chegou e foi morar numa cidade chamada Nazaré. Assim se cumpriu o que os profetas disseram: Ele será chamado Nazareno."},
]})

# Chapter 3 - John the Baptist and Jesus' Baptism
chapters.append({"c":3,"verses":[
{"v":1,"t":"Naquela época, João Batista apareceu pregando no deserto da Judeia."},
{"v":2,"t":"Ele dizia: Mudem de vida, porque o Reino dos Céus está perto!"},
{"v":3,"t":"João é aquele de quem o profeta Isaías falou: Uma voz grita no deserto: Preparem o caminho do Senhor! Endireitem as estradas para ele!"},
{"v":4,"t":"João usava roupas feitas de pelo de camelo e um cinto de couro. Ele comia gafanhotos e mel silvestre."},
{"v":5,"t":"As pessoas de Jerusalém, de toda a Judeia e de toda a região do Jordão iam até ele."},
{"v":6,"t":"Confessavam os seus pecados e eram batizadas por ele no rio Jordão."},
{"v":7,"t":"Quando João viu muitos fariseus e saduceus chegando para serem batizados, disse: Raça de cobras! Quem avisou vocês para fugirem do castigo que vem?"},
{"v":8,"t":"Provem com ações que vocês realmente mudaram de vida!"},
{"v":9,"t":"E não fiquem pensando: Nós somos descendentes de Abraão. Eu digo que Deus pode fazer destas pedras descendentes de Abraão."},
{"v":10,"t":"O machado já está na raiz das árvores. Toda árvore que não dá bom fruto será cortada e jogada no fogo."},
{"v":11,"t":"Eu batizo vocês com água, para que mudem de vida. Mas depois de mim vem alguém mais poderoso do que eu. Eu não sou digno nem de carregar as sandálias dele. Ele vai batizar vocês com o Espírito Santo e com fogo."},
{"v":12,"t":"Ele traz a pá na mão para separar o trigo da palha. Vai guardar o trigo no depósito e queimar a palha com fogo que nunca se apaga."},
{"v":13,"t":"Então Jesus veio da Galileia até o rio Jordão para ser batizado por João."},
{"v":14,"t":"Mas João tentou impedir, dizendo: Eu é que preciso ser batizado por você, e você vem a mim?"},
{"v":15,"t":"Jesus respondeu: Deixe assim por agora. É certo que façamos isso para cumprir toda a vontade de Deus. Então João concordou."},
{"v":16,"t":"Assim que Jesus foi batizado, saiu da água. Nesse momento, o céu se abriu e ele viu o Espírito de Deus descendo como uma pomba e pousando sobre ele."},
{"v":17,"t":"E uma voz do céu disse: Este é o meu Filho amado. Nele tenho grande alegria!"},
]})

# Chapter 4 - Temptation and Beginning of Ministry
chapters.append({"c":4,"verses":[
{"v":1,"t":"Então o Espírito levou Jesus ao deserto para ser tentado pelo diabo."},
{"v":2,"t":"Jesus ficou sem comer por quarenta dias e quarenta noites. Depois, sentiu fome."},
{"v":3,"t":"O tentador se aproximou e disse: Se você é o Filho de Deus, mande estas pedras virarem pão."},
{"v":4,"t":"Jesus respondeu: Está escrito: O ser humano não vive só de pão, mas de toda palavra que Deus fala."},
{"v":5,"t":"Então o diabo levou Jesus até a cidade santa e o colocou no ponto mais alto do templo."},
{"v":6,"t":"E disse: Se você é o Filho de Deus, pule daqui! Porque está escrito: Deus vai mandar os anjos dele cuidarem de você. Eles vão segurá-lo nas mãos para que você não machuque o pé em nenhuma pedra."},
{"v":7,"t":"Jesus respondeu: Também está escrito: Não ponha o Senhor seu Deus à prova."},
{"v":8,"t":"Depois o diabo levou Jesus a um monte muito alto. Mostrou a ele todos os reinos do mundo e toda a riqueza deles."},
{"v":9,"t":"E disse: Eu dou tudo isso a você, se você se ajoelhar e me adorar."},
{"v":10,"t":"Então Jesus disse: Vá embora, Satanás! Porque está escrito: Adore o Senhor seu Deus e sirva somente a ele."},
{"v":11,"t":"Então o diabo foi embora. E anjos vieram e cuidaram de Jesus."},
{"v":12,"t":"Quando Jesus soube que João tinha sido preso, voltou para a Galileia."},
{"v":13,"t":"Saiu de Nazaré e foi morar em Cafarnaum, que fica perto do mar, na região de Zebulom e Naftali."},
{"v":14,"t":"Isso aconteceu para se cumprir o que o profeta Isaías disse:"},
{"v":15,"t":"Terra de Zebulom e terra de Naftali, junto ao mar, além do Jordão, Galileia dos povos!"},
{"v":16,"t":"O povo que vivia na escuridão viu uma luz muito grande. Para os que viviam na sombra da morte, uma luz brilhou."},
{"v":17,"t":"A partir desse momento, Jesus começou a pregar e a dizer: Mudem de vida, porque o Reino dos Céus está perto!"},
{"v":18,"t":"Andando perto do mar da Galileia, Jesus viu dois irmãos: Simão, chamado Pedro, e André. Eles estavam jogando redes no mar, porque eram pescadores."},
{"v":19,"t":"Jesus disse a eles: Sigam-me, e eu vou fazer de vocês pescadores de pessoas."},
{"v":20,"t":"Na mesma hora, eles largaram as redes e seguiram Jesus."},
{"v":21,"t":"Andando um pouco mais, viu outros dois irmãos: Tiago e João, filhos de Zebedeu. Eles estavam no barco com o pai, consertando as redes."},
{"v":22,"t":"Jesus os chamou. Eles deixaram o barco e o pai, e seguiram Jesus."},
{"v":23,"t":"Jesus percorria toda a Galileia. Ensinava nas sinagogas, anunciava a boa notícia do Reino e curava todo tipo de doença entre o povo."},
{"v":24,"t":"A fama dele se espalhou por toda a Síria. Traziam a ele todos os doentes, com vários tipos de doenças e sofrimentos: os que tinham demônios, os epiléticos e os paralíticos. E ele curava todos."},
{"v":25,"t":"Grandes multidões o seguiam, vindas da Galileia, de Decápolis, de Jerusalém, da Judeia e de além do Jordão."},
]})

# Chapter 5 - Sermon on the Mount (Beatitudes)
chapters.append({"c":5,"verses":[
{"v":1,"t":"Jesus viu a multidão e subiu a um monte. Sentou-se, e os discípulos dele se aproximaram."},
{"v":2,"t":"Então ele começou a ensinar:"},
{"v":3,"t":"Felizes os que são humildes de espírito, porque deles é o Reino dos Céus."},
{"v":4,"t":"Felizes os que choram, porque serão consolados."},
{"v":5,"t":"Felizes os que são mansos, porque receberão a terra como herança."},
{"v":6,"t":"Felizes os que têm fome e sede de justiça, porque serão satisfeitos."},
{"v":7,"t":"Felizes os que têm compaixão, porque receberão compaixão."},
{"v":8,"t":"Felizes os que têm o coração puro, porque verão a Deus."},
{"v":9,"t":"Felizes os que promovem a paz, porque serão chamados filhos de Deus."},
{"v":10,"t":"Felizes os que são perseguidos por fazerem o que é certo, porque deles é o Reino dos Céus."},
{"v":11,"t":"Felizes são vocês quando os insultarem, perseguirem e mentirem todo tipo de coisa ruim contra vocês por minha causa."},
{"v":12,"t":"Fiquem felizes e comemorem! Porque a recompensa de vocês no céu é grande. Assim também perseguiram os profetas que viveram antes de vocês."},
{"v":13,"t":"Vocês são o sal da terra. Mas se o sal perder o sabor, como vai ficar salgado de novo? Não serve mais para nada. É jogado fora e pisado pelas pessoas."},
{"v":14,"t":"Vocês são a luz do mundo. Uma cidade no alto de um monte não pode ficar escondida."},
{"v":15,"t":"Ninguém acende uma lâmpada e a coloca debaixo de um balde. Ela é colocada no lugar certo para iluminar todos na casa."},
{"v":16,"t":"Assim, deixem que a luz de vocês brilhe diante das pessoas. Para que elas vejam as boas coisas que vocês fazem e louvem o Pai de vocês que está no céu."},
{"v":17,"t":"Não pensem que eu vim acabar com a Lei ou com os Profetas. Eu não vim acabar, mas cumprir."},
{"v":18,"t":"Eu digo a verdade: enquanto o céu e a terra existirem, nem a menor letra da Lei será tirada, até que tudo se cumpra."},
{"v":19,"t":"Quem desobedecer o menor mandamento e ensinar outros a fazer o mesmo será chamado o menor no Reino dos Céus. Mas quem obedecer e ensinar será chamado grande no Reino dos Céus."},
{"v":20,"t":"Eu digo a vocês: se vocês não forem mais justos que os mestres da Lei e os fariseus, não entrarão no Reino dos Céus."},
{"v":21,"t":"Vocês ouviram que foi dito aos antigos: Não mate. Quem matar será julgado."},
{"v":22,"t":"Mas eu digo: quem ficar com raiva do irmão sem motivo será julgado. Quem chamar o irmão de inútil terá que responder ao tribunal. E quem chamar o irmão de idiota merece o fogo do inferno."},
{"v":23,"t":"Por isso, se você estiver levando sua oferta ao altar e lembrar que seu irmão tem algo contra você,"},
{"v":24,"t":"deixe a oferta ali. Primeiro, vá fazer as pazes com o seu irmão. Depois, volte e apresente sua oferta."},
{"v":25,"t":"Resolva logo o problema com quem quer levá-lo ao tribunal. Faça isso enquanto estiver a caminho, para que essa pessoa não o entregue ao juiz, o juiz ao oficial, e você acabe na prisão."},
{"v":26,"t":"Eu digo a verdade: você não vai sair de lá até pagar o último centavo."},
{"v":27,"t":"Vocês ouviram que foi dito: Não cometa adultério."},
{"v":28,"t":"Mas eu digo: quem olhar para uma mulher com desejo já cometeu adultério no coração."},
{"v":29,"t":"Se o seu olho direito faz você pecar, arranque-o e jogue fora. É melhor perder uma parte do corpo do que o corpo inteiro ser jogado no inferno."},
{"v":30,"t":"Se a sua mão direita faz você pecar, corte-a e jogue fora. É melhor perder uma parte do corpo do que o corpo inteiro ir para o inferno."},
{"v":31,"t":"Também foi dito: Quem se divorciar da esposa deve dar a ela um documento de divórcio."},
{"v":32,"t":"Mas eu digo: quem se divorcia da esposa, a não ser por infidelidade, faz com que ela cometa adultério. E quem casa com uma mulher divorciada também comete adultério."},
{"v":33,"t":"Vocês também ouviram que foi dito: Não quebre seus juramentos, mas cumpra o que prometeu ao Senhor."},
{"v":34,"t":"Mas eu digo: não jurem de jeito nenhum. Não jurem pelo céu, porque é o trono de Deus."},
{"v":35,"t":"Nem pela terra, porque é onde Deus apoia os pés. Nem por Jerusalém, porque é a cidade do grande Rei."},
{"v":36,"t":"Não jure nem pela sua cabeça, porque você não pode fazer um cabelo ficar branco ou preto."},
{"v":37,"t":"Digam apenas sim ou não. O que passar disso vem do mal."},
{"v":38,"t":"Vocês ouviram que foi dito: Olho por olho e dente por dente."},
{"v":39,"t":"Mas eu digo: não revidem o mal. Se alguém bater no seu rosto direito, ofereça também o outro lado."},
{"v":40,"t":"Se alguém quiser processá-lo para ficar com a sua camisa, dê também o casaco."},
{"v":41,"t":"Se alguém obrigar você a andar um quilômetro, vá dois."},
{"v":42,"t":"Dê a quem pedir, e não recuse quem quiser um empréstimo."},
{"v":43,"t":"Vocês ouviram que foi dito: Ame o seu próximo e odeie o seu inimigo."},
{"v":44,"t":"Mas eu digo: amem os seus inimigos e orem por quem persegue vocês. Assim, vocês serão filhos do Pai que está no céu."},
{"v":45,"t":"Porque ele faz o sol nascer sobre maus e bons. E faz chover sobre justos e injustos."},
{"v":46,"t":"Se vocês amam só quem ama vocês, que recompensa terão? Os cobradores de impostos não fazem a mesma coisa?"},
{"v":47,"t":"Se vocês cumprimentam só os seus irmãos, o que há de especial nisso? Os que não conhecem a Deus não fazem igual?"},
{"v":48,"t":"Sejam perfeitos, assim como o Pai de vocês que está no céu é perfeito."},
]})

# Chapter 6 - Prayer, Fasting, and Treasure
chapters.append({"c":6,"verses":[
{"v":1,"t":"Cuidado para não fazer o bem só para serem vistos pelos outros. Se fizerem assim, não receberão recompensa do Pai de vocês que está no céu."},
{"v":2,"t":"Quando você ajudar alguém, não fique anunciando como fazem os hipócritas nas sinagogas e nas ruas, para serem elogiados. Eu digo a verdade: eles já receberam a recompensa deles."},
{"v":3,"t":"Quando você ajudar alguém, que a sua mão esquerda não saiba o que a direita faz."},
{"v":4,"t":"Assim, a sua ajuda ficará em segredo. E o seu Pai, que vê o que é feito em segredo, vai recompensar você."},
{"v":5,"t":"Quando vocês orarem, não sejam como os hipócritas. Eles gostam de orar em pé nas sinagogas e nas esquinas para serem vistos. Eu digo a verdade: eles já receberam a recompensa deles."},
{"v":6,"t":"Quando você orar, entre no seu quarto e feche a porta. Ore ao seu Pai, que está no secreto. E o seu Pai, que vê no secreto, vai recompensar você."},
{"v":7,"t":"Quando orarem, não fiquem repetindo palavras sem parar, como fazem os que não conhecem a Deus. Eles pensam que serão ouvidos por falarem muito."},
{"v":8,"t":"Não sejam como eles. O Pai de vocês sabe do que vocês precisam antes mesmo de pedirem."},
{"v":9,"t":"Orem assim: Pai nosso, que estás no céu, que o teu nome seja honrado."},
{"v":10,"t":"Que o teu Reino venha. Que a tua vontade seja feita aqui na terra como é feita no céu."},
{"v":11,"t":"Dá-nos hoje o pão que precisamos."},
{"v":12,"t":"Perdoa as nossas falhas, assim como nós perdoamos os que erram contra nós."},
{"v":13,"t":"Não nos deixe cair em tentação, mas livra-nos do mal. Porque teu é o Reino, o poder e a glória para sempre. Amém."},
{"v":14,"t":"Se vocês perdoarem as pessoas que erram contra vocês, o Pai de vocês que está no céu também vai perdoar vocês."},
{"v":15,"t":"Mas se vocês não perdoarem os outros, o Pai de vocês também não vai perdoar vocês."},
{"v":16,"t":"Quando vocês jejuarem, não fiquem com cara triste como os hipócritas. Eles mudam a aparência para mostrar que estão jejuando. Eu digo a verdade: eles já receberam a recompensa deles."},
{"v":17,"t":"Quando você jejuar, lave o rosto e arrume o cabelo."},
{"v":18,"t":"Assim, as pessoas não vão perceber que você está jejuando. Só o seu Pai, que está no secreto, vai saber. E o seu Pai, que vê no secreto, vai recompensar você."},
{"v":19,"t":"Não juntem tesouros aqui na terra, onde a traça e a ferrugem destroem, e onde os ladrões roubam."},
{"v":20,"t":"Juntem tesouros no céu, onde a traça e a ferrugem não destroem, e os ladrões não roubam."},
{"v":21,"t":"Porque onde estiver o seu tesouro, ali estará o seu coração."},
{"v":22,"t":"Os olhos são a luz do corpo. Se os seus olhos forem bons, todo o seu corpo terá luz."},
{"v":23,"t":"Mas se os seus olhos forem maus, o seu corpo ficará na escuridão. Se a luz que existe em você é escuridão, como será grande essa escuridão!"},
{"v":24,"t":"Ninguém pode servir a dois patrões. Vai odiar um e amar o outro, ou se dedicar a um e desprezar o outro. Vocês não podem servir a Deus e ao dinheiro."},
{"v":25,"t":"Por isso eu digo: não fiquem preocupados com a vida, com o que vão comer ou beber, nem com o corpo, com o que vão vestir. A vida não é mais que a comida? E o corpo não é mais que a roupa?"},
{"v":26,"t":"Olhem para os pássaros do céu: eles não plantam, não colhem, não guardam em depósitos. E o Pai de vocês que está no céu os alimenta. Vocês não valem muito mais do que eles?"},
{"v":27,"t":"Quem de vocês, por mais que se preocupe, pode acrescentar uma hora à sua vida?"},
{"v":28,"t":"E por que vocês se preocupam com roupa? Olhem como crescem os lírios do campo. Eles não trabalham nem costuram."},
{"v":29,"t":"Mas eu digo que nem Salomão, com toda a sua riqueza, se vestiu tão bem como um deles."},
{"v":30,"t":"Se Deus veste assim a grama do campo, que hoje existe e amanhã é queimada, ele não cuidará muito mais de vocês, gente de pouca fé?"},
{"v":31,"t":"Então não fiquem preocupados, dizendo: O que vamos comer? O que vamos beber? O que vamos vestir?"},
{"v":32,"t":"Os que não conhecem a Deus é que correm atrás dessas coisas. O Pai de vocês que está no céu sabe que vocês precisam de tudo isso."},
{"v":33,"t":"Busquem primeiro o Reino de Deus e o que é certo diante dele. E tudo o mais será dado a vocês."},
{"v":34,"t":"Não se preocupem com o dia de amanhã. O dia de amanhã trará as suas próprias preocupações. Cada dia já tem problemas suficientes."},
]})

# Chapter 7 - Judging, Asking, Two Paths
chapters.append({"c":7,"verses":[
{"v":1,"t":"Não julguem os outros, para que vocês não sejam julgados."},
{"v":2,"t":"Porque da mesma forma que vocês julgarem, serão julgados. E a mesma medida que usarem será usada para medir vocês."},
{"v":3,"t":"Por que você repara no cisco que está no olho do seu irmão, mas não nota a viga que está no seu próprio olho?"},
{"v":4,"t":"Como você pode dizer ao seu irmão: Deixe eu tirar o cisco do seu olho, se existe uma viga no seu?"},
{"v":5,"t":"Hipócrita! Tire primeiro a viga do seu olho. Depois você vai enxergar bem para tirar o cisco do olho do seu irmão."},
{"v":6,"t":"Não deem o que é sagrado aos cães. Não joguem as suas pérolas aos porcos. Eles vão pisar nelas e depois atacar vocês."},
{"v":7,"t":"Peçam, e será dado a vocês. Busquem, e encontrarão. Batam, e a porta será aberta."},
{"v":8,"t":"Porque todo aquele que pede, recebe. Quem busca, encontra. E para quem bate, a porta se abre."},
{"v":9,"t":"Qual de vocês, se o filho pedir pão, vai dar uma pedra?"},
{"v":10,"t":"Ou, se pedir peixe, vai dar uma cobra?"},
{"v":11,"t":"Se vocês, mesmo sendo imperfeitos, sabem dar coisas boas aos filhos, imaginem o Pai de vocês que está no céu! Ele dará coisas muito melhores a quem pedir."},
{"v":12,"t":"Então, tudo o que vocês querem que as pessoas façam por vocês, façam por elas. Isso resume a Lei e os Profetas."},
{"v":13,"t":"Entrem pela porta estreita. Porque a porta larga e o caminho fácil levam à destruição. E muitos entram por ela."},
{"v":14,"t":"Mas a porta estreita e o caminho difícil levam à vida. E poucos encontram esse caminho."},
{"v":15,"t":"Cuidado com os falsos profetas. Eles chegam disfarçados de ovelhas, mas por dentro são lobos ferozes."},
{"v":16,"t":"Vocês vão reconhecê-los pelos frutos deles. Alguém colhe uvas de espinheiros ou figos de plantas com espinhos?"},
{"v":17,"t":"Toda árvore boa dá bons frutos. E toda árvore ruim dá frutos ruins."},
{"v":18,"t":"Uma árvore boa não pode dar frutos ruins. E uma árvore ruim não pode dar bons frutos."},
{"v":19,"t":"Toda árvore que não dá bom fruto é cortada e jogada no fogo."},
{"v":20,"t":"Portanto, é pelos frutos deles que vocês vão reconhecê-los."},
{"v":21,"t":"Nem todo mundo que me chama de Senhor vai entrar no Reino dos Céus. Só quem faz a vontade do meu Pai que está no céu."},
{"v":22,"t":"Muitos vão me dizer naquele dia: Senhor, Senhor, nós não profetizamos em seu nome? Não expulsamos demônios? Não fizemos muitos milagres?"},
{"v":23,"t":"E eu vou dizer claramente: Eu nunca conheci vocês. Afastem-se de mim, vocês que praticam o mal!"},
{"v":24,"t":"Todo aquele que ouve estas minhas palavras e as pratica é como um homem sábio que construiu a casa dele sobre a rocha."},
{"v":25,"t":"Caiu a chuva, vieram as enchentes, sopraram os ventos e bateram contra a casa. Mas ela não caiu, porque estava construída sobre a rocha."},
{"v":26,"t":"Mas todo aquele que ouve estas minhas palavras e não as pratica é como um homem tolo que construiu a casa dele sobre a areia."},
{"v":27,"t":"Caiu a chuva, vieram as enchentes, sopraram os ventos e bateram contra a casa. Ela caiu, e a queda foi terrível!"},
{"v":28,"t":"Quando Jesus terminou de falar, a multidão estava impressionada com o ensino dele."},
{"v":29,"t":"Porque ele ensinava com autoridade, e não como os mestres da Lei."},
]})

# Chapter 8 - Healings and Miracles
chapters.append({"c":8,"verses":[
{"v":1,"t":"Quando Jesus desceu do monte, uma grande multidão o seguiu."},
{"v":2,"t":"Um homem com lepra se aproximou, se ajoelhou diante dele e disse: Senhor, se o senhor quiser, pode me curar."},
{"v":3,"t":"Jesus estendeu a mão, tocou nele e disse: Eu quero. Seja curado! Na mesma hora, a lepra desapareceu."},
{"v":4,"t":"Jesus disse a ele: Não conte a ninguém. Vá, mostre-se ao sacerdote e leve a oferta que Moisés ordenou. Assim todos terão prova da cura."},
{"v":5,"t":"Quando Jesus entrou em Cafarnaum, um oficial romano se aproximou dele pedindo ajuda."},
{"v":6,"t":"Ele disse: Senhor, o meu empregado está em casa, paralítico, sofrendo muito."},
{"v":7,"t":"Jesus respondeu: Eu vou lá curá-lo."},
{"v":8,"t":"O oficial disse: Senhor, eu não mereço que o senhor entre na minha casa. Basta dizer uma palavra, e o meu empregado será curado."},
{"v":9,"t":"Eu também sou um homem que obedece ordens e tenho soldados sob o meu comando. Digo a um: Vá, e ele vai. A outro: Venha, e ele vem. E ao meu empregado: Faça isso, e ele faz."},
{"v":10,"t":"Jesus ficou admirado ao ouvir isso. Disse aos que o seguiam: Eu digo a verdade: não encontrei fé tão grande como esta nem em Israel!"},
{"v":11,"t":"Eu digo que muitos virão do leste e do oeste e se sentarão à mesa com Abraão, Isaque e Jacó no Reino dos Céus."},
{"v":12,"t":"Mas os que deveriam estar no Reino serão jogados na escuridão de fora. Ali haverá choro e ranger de dentes."},
{"v":13,"t":"Então Jesus disse ao oficial: Vá. Que aconteça como você acreditou. E naquela mesma hora o empregado foi curado."},
{"v":14,"t":"Jesus foi à casa de Pedro e viu a sogra dele de cama, com febre."},
{"v":15,"t":"Tocou na mão dela, e a febre foi embora. Ela se levantou e começou a servir Jesus."},
{"v":16,"t":"Quando chegou a noite, trouxeram a Jesus muitas pessoas dominadas por demônios. Ele expulsou os espíritos com uma palavra e curou todos os doentes."},
{"v":17,"t":"Assim se cumpriu o que o profeta Isaías disse: Ele tomou sobre si as nossas fraquezas e carregou as nossas doenças."},
{"v":18,"t":"Quando Jesus viu a multidão ao redor dele, mandou que fossem para o outro lado do lago."},
{"v":19,"t":"Um mestre da Lei se aproximou e disse: Mestre, eu vou seguir o senhor para onde o senhor for."},
{"v":20,"t":"Jesus respondeu: As raposas têm tocas e os pássaros têm ninhos. Mas o Filho do Homem não tem onde descansar a cabeça."},
{"v":21,"t":"Outro discípulo disse: Senhor, deixe eu ir primeiro enterrar o meu pai."},
{"v":22,"t":"Mas Jesus respondeu: Siga-me. Deixe que os mortos enterrem os seus mortos."},
{"v":23,"t":"Jesus entrou no barco e os discípulos o seguiram."},
{"v":24,"t":"De repente, uma tempestade violenta atingiu o lago. As ondas cobriam o barco. Mas Jesus estava dormindo."},
{"v":25,"t":"Os discípulos foram acordá-lo: Senhor, nos salve! Nós vamos morrer!"},
{"v":26,"t":"Jesus disse: Por que vocês estão com medo, gente de pouca fé? Então se levantou e deu uma ordem ao vento e ao mar. E tudo ficou calmo."},
{"v":27,"t":"Os homens ficaram espantados e disseram: Quem é este, que até o vento e o mar obedecem a ele?"},
{"v":28,"t":"Quando chegaram ao outro lado do lago, na região dos gadarenos, dois homens dominados por demônios saíram dos túmulos. Eles eram tão violentos que ninguém podia passar por aquele caminho."},
{"v":29,"t":"Eles gritaram: O que você quer conosco, Jesus, Filho de Deus? Você veio nos atormentar antes do tempo?"},
{"v":30,"t":"Perto dali, uma grande manada de porcos estava comendo."},
{"v":31,"t":"Os demônios imploraram: Se nos expulsar, nos mande para a manada de porcos."},
{"v":32,"t":"Jesus disse: Vão! Eles saíram e entraram nos porcos. Toda a manada correu despenhadeiro abaixo e se afogou no mar."},
{"v":33,"t":"Os que cuidavam dos porcos fugiram para a cidade e contaram tudo o que aconteceu."},
{"v":34,"t":"Então toda a cidade saiu ao encontro de Jesus. Quando o viram, pediram que ele fosse embora da região deles."},
]})

# Chapter 9 - More Healings, Calling of Matthew
chapters.append({"c":9,"verses":[
{"v":1,"t":"Jesus entrou no barco, atravessou o lago e chegou à sua cidade. Trouxeram a ele um paralítico, deitado numa maca."},
{"v":2,"t":"Vendo a fé deles, Jesus disse ao paralítico: Tenha coragem, filho! Os seus pecados estão perdoados."},
{"v":3,"t":"Alguns mestres da Lei pensaram: Isso é uma ofensa a Deus!"},
{"v":4,"t":"Jesus, sabendo o que eles pensavam, disse: Por que vocês pensam coisas ruins no coração?"},
{"v":5,"t":"O que é mais fácil: dizer 'Os seus pecados estão perdoados' ou dizer 'Levante-se e ande'?"},
{"v":6,"t":"Mas para que vocês saibam que o Filho do Homem tem poder na terra para perdoar pecados — disse ao paralítico: Levante-se, pegue a sua maca e vá para casa."},
{"v":7,"t":"O homem se levantou e foi para casa."},
{"v":8,"t":"A multidão viu aquilo, ficou admirada e louvou a Deus por dar esse poder aos seres humanos."},
{"v":9,"t":"Saindo dali, Jesus viu um homem chamado Mateus sentado no posto de cobrança de impostos. Disse a ele: Siga-me. Mateus se levantou e o seguiu."},
{"v":10,"t":"Enquanto Jesus estava em casa, à mesa, vieram muitos cobradores de impostos e pecadores. Eles se sentaram com Jesus e os discípulos."},
{"v":11,"t":"Os fariseus viram e perguntaram aos discípulos: Por que o mestre de vocês come com cobradores de impostos e pecadores?"},
{"v":12,"t":"Jesus ouviu e respondeu: Não são os saudáveis que precisam de médico, mas os doentes."},
{"v":13,"t":"Vão e aprendam o que significa: Eu quero compaixão, não sacrifício. Porque eu não vim chamar os justos, mas os pecadores para que mudem de vida."},
{"v":14,"t":"Então os discípulos de João vieram perguntar: Por que nós e os fariseus jejuamos, mas os seus discípulos não?"},
{"v":15,"t":"Jesus respondeu: Os convidados de um casamento podem ficar tristes enquanto o noivo está com eles? Mas virão dias em que o noivo será tirado deles. Aí sim eles vão jejuar."},
{"v":16,"t":"Ninguém coloca um remendo de pano novo em roupa velha. O remendo encolhe, rasga a roupa, e o buraco fica ainda maior."},
{"v":17,"t":"Também ninguém coloca vinho novo em vasilhas velhas de couro. Senão, as vasilhas estouram, o vinho derrama e as vasilhas se perdem. Vinho novo deve ser colocado em vasilhas novas. Assim, os dois se conservam."},
{"v":18,"t":"Enquanto Jesus dizia isso, um líder da sinagoga se ajoelhou diante dele e disse: A minha filha acabou de morrer. Mas venha e coloque a mão sobre ela, e ela viverá."},
{"v":19,"t":"Jesus se levantou e o seguiu, junto com os discípulos."},
{"v":20,"t":"Nesse momento, uma mulher que sofria de hemorragia havia doze anos se aproximou por trás e tocou na barra da roupa de Jesus."},
{"v":21,"t":"Ela pensava: Se eu apenas tocar na roupa dele, ficarei curada."},
{"v":22,"t":"Jesus se virou, viu a mulher e disse: Coragem, filha! A sua fé curou você. E naquela mesma hora a mulher ficou curada."},
{"v":23,"t":"Quando Jesus chegou à casa do líder, viu os músicos tocando e a multidão fazendo barulho."},
{"v":24,"t":"Ele disse: Saiam daqui! A menina não morreu. Ela está dormindo. E riam dele."},
{"v":25,"t":"Depois que o povo saiu, Jesus entrou, pegou a mão da menina, e ela se levantou."},
{"v":26,"t":"A notícia se espalhou por toda aquela região."},
{"v":27,"t":"Quando Jesus saiu dali, dois cegos o seguiam, gritando: Filho de Davi, tenha compaixão de nós!"},
{"v":28,"t":"Quando Jesus entrou na casa, os cegos se aproximaram. Ele perguntou: Vocês acreditam que eu posso fazer isso? Responderam: Sim, Senhor!"},
{"v":29,"t":"Então tocou nos olhos deles e disse: Que aconteça de acordo com a fé de vocês."},
{"v":30,"t":"E os olhos deles se abriram. Jesus os avisou: Não contem isso a ninguém."},
{"v":31,"t":"Mas eles saíram e espalharam a notícia por toda a região."},
{"v":32,"t":"Logo depois, trouxeram a Jesus um homem mudo, que estava dominado por um demônio."},
{"v":33,"t":"Quando o demônio foi expulso, o mudo começou a falar. A multidão ficou admirada e disse: Nunca se viu nada assim em Israel!"},
{"v":34,"t":"Mas os fariseus diziam: É pelo chefe dos demônios que ele expulsa os demônios."},
{"v":35,"t":"Jesus percorria todas as cidades e vilarejos. Ensinava nas sinagogas, anunciava a boa notícia do Reino e curava toda doença e todo sofrimento."},
{"v":36,"t":"Quando viu as multidões, teve muita compaixão delas, porque estavam cansadas e perdidas, como ovelhas sem pastor."},
{"v":37,"t":"Então disse aos discípulos: A colheita é grande, mas os trabalhadores são poucos."},
{"v":38,"t":"Peçam ao dono da colheita que mande trabalhadores para a colheita dele."},
]})

# Chapter 10 - Sending the Twelve
chapters.append({"c":10,"verses":[
{"v":1,"t":"Jesus chamou os doze discípulos e deu a eles poder para expulsar espíritos maus e curar toda doença e sofrimento."},
{"v":2,"t":"Os nomes dos doze apóstolos são: primeiro, Simão, chamado Pedro, e André, irmão dele; Tiago, filho de Zebedeu, e João, irmão dele;"},
{"v":3,"t":"Filipe e Bartolomeu; Tomé e Mateus, o cobrador de impostos; Tiago, filho de Alfeu, e Tadeu;"},
{"v":4,"t":"Simão, o zelote, e Judas Iscariotes, aquele que traiu Jesus."},
{"v":5,"t":"Jesus enviou esses doze com estas instruções: Não vão a terras de outros povos nem entrem em cidades samaritanas."},
{"v":6,"t":"Vão antes às ovelhas perdidas do povo de Israel."},
{"v":7,"t":"Enquanto andam, preguem assim: O Reino dos Céus está perto!"},
{"v":8,"t":"Curem os doentes, ressuscitem os mortos, purifiquem os leprosos, expulsem os demônios. Vocês receberam de graça; deem de graça."},
{"v":9,"t":"Não levem ouro, prata ou moedas no bolso."},
{"v":10,"t":"Nem bolsa de viagem, nem roupa extra, nem sandálias, nem cajado. Porque o trabalhador merece o seu sustento."},
{"v":11,"t":"Quando entrarem numa cidade ou vilarejo, procurem alguém que mereça hospedá-los. Fiquem ali até irem embora."},
{"v":12,"t":"Ao entrar numa casa, cumprimentem os moradores."},
{"v":13,"t":"Se a casa merecer, que a paz de vocês fique nela. Se não merecer, que a paz de vocês volte para vocês."},
{"v":14,"t":"Se alguém não receber vocês nem ouvir as palavras de vocês, saiam da casa ou da cidade e sacudam o pó dos pés."},
{"v":15,"t":"Eu digo a verdade: no dia do julgamento, Sodoma e Gomorra serão tratadas com menos rigor do que aquela cidade."},
{"v":16,"t":"Eu envio vocês como ovelhas no meio de lobos. Sejam espertos como cobras e simples como pombas."},
{"v":17,"t":"Cuidado com as pessoas! Elas vão entregar vocês aos tribunais e vão açoitar vocês nas sinagogas."},
{"v":18,"t":"Vocês serão levados diante de governadores e reis por minha causa. Isso será um testemunho para eles e para os outros povos."},
{"v":19,"t":"Quando entregarem vocês, não se preocupem com o que dizer. Na hora certa, as palavras certas serão dadas a vocês."},
{"v":20,"t":"Porque não são vocês que estarão falando, mas o Espírito do Pai de vocês falará por meio de vocês."},
{"v":21,"t":"O irmão vai entregar o irmão para morrer. O pai vai entregar o filho. Os filhos vão se levantar contra os pais e mandá-los matar."},
{"v":22,"t":"Todos vão odiar vocês por minha causa. Mas quem aguentar até o fim será salvo."},
{"v":23,"t":"Quando perseguirem vocês numa cidade, fujam para outra. Eu digo a verdade: vocês não vão terminar de percorrer as cidades de Israel antes que o Filho do Homem venha."},
{"v":24,"t":"O aluno não é maior que o professor. O empregado não é maior que o patrão."},
{"v":25,"t":"Basta que o aluno seja como o professor e o empregado como o patrão. Se chamaram o dono da casa de Belzebu, imaginem os da família dele!"},
{"v":26,"t":"Não tenham medo deles. Porque nada que está escondido vai ficar assim. Tudo que está em segredo será descoberto."},
{"v":27,"t":"O que eu digo a vocês na escuridão, digam na luz. O que eu falo ao ouvido de vocês, anunciem do alto dos telhados."},
{"v":28,"t":"Não tenham medo dos que matam o corpo, mas não podem matar a alma. Tenham medo daquele que pode destruir a alma e o corpo no inferno."},
{"v":29,"t":"Dois pardais não são vendidos por uma moedinha? Mesmo assim, nenhum deles cai no chão sem que o Pai de vocês saiba."},
{"v":30,"t":"Até os cabelos da cabeça de vocês estão todos contados."},
{"v":31,"t":"Não tenham medo. Vocês valem muito mais do que muitos pardais."},
{"v":32,"t":"Quem me reconhece diante das pessoas, eu também vou reconhecer diante do meu Pai que está no céu."},
{"v":33,"t":"Mas quem me nega diante das pessoas, eu também vou negar diante do meu Pai que está no céu."},
{"v":34,"t":"Não pensem que eu vim trazer paz à terra. Eu não vim trazer paz, mas divisão."},
{"v":35,"t":"Eu vim colocar o filho contra o pai, a filha contra a mãe, e a nora contra a sogra."},
{"v":36,"t":"Os inimigos de uma pessoa serão os da própria família."},
{"v":37,"t":"Quem ama o pai ou a mãe mais do que a mim não é digno de mim. Quem ama o filho ou a filha mais do que a mim não é digno de mim."},
{"v":38,"t":"Quem não pega a sua cruz e me segue não é digno de mim."},
{"v":39,"t":"Quem tenta salvar a própria vida vai perdê-la. E quem perde a vida por minha causa vai encontrá-la."},
{"v":40,"t":"Quem recebe vocês está me recebendo. E quem me recebe está recebendo aquele que me enviou."},
{"v":41,"t":"Quem recebe um profeta por ser profeta terá a recompensa de profeta. Quem recebe um justo por ser justo terá a recompensa de justo."},
{"v":42,"t":"E quem der apenas um copo de água fresca a um destes pequeninos, por ser meu discípulo, eu digo a verdade: essa pessoa não ficará sem recompensa."},
]})

print(f"Matthew chapters 1-10 ready: {sum(len(c['verses']) for c in chapters)} verses")

# Will continue in next part...
# Save partial for reference
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'static', 'data', 'bfl', 'mateus_trans.json'), 'w', encoding='utf-8') as f:
    json.dump(chapters, f, ensure_ascii=False, indent=None, separators=(',',':'))

print("Saved chapters 1-10 to mateus_trans.json")
