#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""BFL Translation of Acts (Atos) - Chapters 21-28"""
import json

chapters = []

# Chapter 21 - Paul goes to Jerusalem
chapters.append({"c":21,"verses":[
{"v":1,"t":"Depois de nos separarmos deles, embarcamos e navegamos direto para Cós. No dia seguinte fomos para Rodes e dali para Pátara."},
{"v":2,"t":"Encontramos um navio indo para a Fenícia. Embarcamos e partimos."},
{"v":3,"t":"Avistamos Chipre e passamos ao sul da ilha. Navegamos para a Síria e desembarcamos em Tiro, onde o navio ia descarregar."},
{"v":4,"t":"Encontramos os seguidores de Jesus e ficamos ali sete dias. Pelo Espírito, eles diziam a Paulo que não fosse a Jerusalém."},
{"v":5,"t":"Quando nosso tempo ali acabou, partimos. Todos nos acompanharam com suas mulheres e filhos até fora da cidade. Na praia, nos ajoelhamos e oramos."},
{"v":6,"t":"Nos despedimos uns dos outros. Nós embarcamos no navio e eles voltaram para casa."},
{"v":7,"t":"Continuamos a viagem de Tiro e chegamos a Ptolemaida. Cumprimentamos os irmãos e ficamos um dia com eles."},
{"v":8,"t":"No dia seguinte partimos e chegamos a Cesareia. Fomos à casa de Filipe, o evangelista, que era um dos sete. Ficamos com ele."},
{"v":9,"t":"Ele tinha quatro filhas solteiras que profetizavam."},
{"v":10,"t":"Depois de vários dias, desceu da Judeia um profeta chamado Ágabo."},
{"v":11,"t":"Ele veio até nós, pegou o cinto de Paulo, amarrou os próprios pés e mãos e disse: O Espírito Santo diz: É assim que os judeus de Jerusalém vão amarrar o dono deste cinto. E vão entregá-lo nas mãos dos não judeus."},
{"v":12,"t":"Quando ouvimos isso, nós e as pessoas dali pedimos a Paulo que não fosse a Jerusalém."},
{"v":13,"t":"Paulo respondeu: Por que vocês choram e partem o meu coração? Eu estou pronto não apenas para ser preso, mas também para morrer em Jerusalém pelo nome do Senhor Jesus."},
{"v":14,"t":"Como não conseguimos convencê-lo, paramos de insistir e dissemos: Que a vontade do Senhor seja feita."},
{"v":15,"t":"Depois daqueles dias, nos preparamos e subimos para Jerusalém."},
{"v":16,"t":"Alguns seguidores de Cesareia foram conosco. Levaram-nos à casa de Mnasom, um cipriota, seguidor antigo de Jesus. Íamos ficar hospedados com ele."},
{"v":17,"t":"Quando chegamos a Jerusalém, os irmãos nos receberam com alegria."},
{"v":18,"t":"No dia seguinte, Paulo foi conosco visitar Tiago. Todos os líderes estavam lá."},
{"v":19,"t":"Paulo os cumprimentou e contou em detalhe tudo o que Deus tinha feito entre os não judeus por meio do seu trabalho."},
{"v":20,"t":"Quando ouviram, louvaram a Deus. Depois disseram a Paulo: Irmão, você vê quantas milhares de judeus creram. Todos são zelosos pela lei."},
{"v":21,"t":"Eles ouviram dizer que você ensina todos os judeus que vivem entre os não judeus a abandonar Moisés. Dizem que você manda não circuncidar os filhos nem seguir os costumes."},
{"v":22,"t":"O que vamos fazer? Eles certamente vão saber que você chegou."},
{"v":23,"t":"Faça o que vamos sugerir. Temos aqui quatro homens que fizeram um voto."},
{"v":24,"t":"Leve-os com você, participe da purificação com eles e pague as despesas para que raspem a cabeça. Assim todos saberão que o que disseram sobre você não é verdade. Verão que você mesmo segue a lei."},
{"v":25,"t":"Quanto aos não judeus que creram, já enviamos uma carta com nossas decisões: que se afastem de comida oferecida a ídolos, de sangue, de carne de animais estrangulados e de imoralidade sexual."},
{"v":26,"t":"No dia seguinte Paulo levou os homens, purificou-se com eles e entrou no templo. Anunciou a data em que o período de purificação terminaria, quando a oferta seria apresentada por cada um deles."},
{"v":27,"t":"Quando os sete dias estavam quase terminando, alguns judeus da província da Ásia viram Paulo no templo. Agitaram a multidão e o agarraram."},
{"v":28,"t":"Gritavam: Israelitas, ajudem! Este é o homem que ensina a todos, em toda parte, contra o nosso povo, contra a lei e contra este lugar sagrado. Além disso, trouxe gregos para dentro do templo e profanou este lugar santo!"},
{"v":29,"t":"Diziam isso porque tinham visto Trófimo, de Éfeso, com Paulo na cidade. Achavam que Paulo o tinha levado ao templo."},
{"v":30,"t":"A cidade inteira ficou agitada. O povo veio correndo, agarrou Paulo e o arrastou para fora do templo. As portas foram fechadas na hora."},
{"v":31,"t":"Enquanto tentavam matar Paulo, chegou a notícia ao comandante do batalhão romano de que Jerusalém inteira estava em tumulto."},
{"v":32,"t":"Ele imediatamente reuniu soldados e oficiais e correu até lá. Quando a multidão viu o comandante e os soldados, pararam de bater em Paulo."},
{"v":33,"t":"O comandante se aproximou, prendeu Paulo e mandou amarrá-lo com duas correntes. Perguntou quem ele era e o que tinha feito."},
{"v":34,"t":"Na multidão, uns gritavam uma coisa e outros gritavam outra. Como não conseguia descobrir a verdade por causa da confusão, mandou levar Paulo para a fortaleza."},
{"v":35,"t":"Quando chegou às escadas, os soldados tiveram que carregar Paulo por causa da violência da multidão."},
{"v":36,"t":"O povo vinha atrás gritando: Matem-no!"},
{"v":37,"t":"Quando estavam prestes a entrar na fortaleza, Paulo disse ao comandante: Posso falar com o senhor? O comandante disse: Você fala grego?"},
{"v":38,"t":"Então não é você o egípcio que há algum tempo provocou uma revolta e levou quatro mil assassinos para o deserto?"},
{"v":39,"t":"Paulo respondeu: Eu sou judeu, cidadão de Tarso na Cilícia, uma cidade importante. Peço que me deixe falar ao povo."},
{"v":40,"t":"O comandante permitiu. Paulo ficou de pé nas escadas e fez sinal com a mão. Quando ficaram em silêncio, ele começou a falar em hebraico:"},
]})

# Chapter 22 - Paul's defense
chapters.append({"c":22,"verses":[
{"v":1,"t":"Irmãos e pais, ouçam a minha defesa."},
{"v":2,"t":"Quando ouviram que ele falava em hebraico, fizeram ainda mais silêncio. Paulo continuou:"},
{"v":3,"t":"Eu sou judeu, nascido em Tarso da Cilícia, mas criado nesta cidade. Fui educado aos pés de Gamaliel, treinado na lei dos nossos antepassados. Eu era zeloso por Deus, assim como todos vocês são hoje."},
{"v":4,"t":"Persegui os seguidores deste Caminho até a morte. Prendi homens e mulheres e os joguei na cadeia."},
{"v":5,"t":"O sumo sacerdote e todo o conselho podem confirmar isso. Eles me deram cartas para os judeus de Damasco. Eu ia para lá prender os seguidores e trazê-los a Jerusalém para serem castigados."},
{"v":6,"t":"Por volta do meio-dia, quando eu estava perto de Damasco, de repente uma luz forte do céu brilhou ao meu redor."},
{"v":7,"t":"Caí no chão e ouvi uma voz dizendo: Saulo, Saulo, por que você me persegue?"},
{"v":8,"t":"Perguntei: Quem é o senhor? Ele respondeu: Eu sou Jesus de Nazaré, a quem você persegue."},
{"v":9,"t":"Os que estavam comigo viram a luz, mas não entenderam a voz que falava comigo."},
{"v":10,"t":"Perguntei: O que devo fazer, Senhor? O Senhor me disse: Levante-se, vá a Damasco, e lá vão dizer a você tudo o que foi designado para fazer."},
{"v":11,"t":"Como eu não conseguia enxergar por causa do brilho daquela luz, meus companheiros me levaram pela mão até Damasco."},
{"v":12,"t":"Ali um homem chamado Ananias veio me visitar. Ele era devoto e obediente à lei, respeitado por todos os judeus de lá."},
{"v":13,"t":"Parou diante de mim e disse: Irmão Saulo, recupere a visão! Naquela mesma hora voltei a enxergar e o vi."},
{"v":14,"t":"Ele disse: O Deus dos nossos antepassados escolheu você para conhecer a vontade dele, para ver o Justo e ouvir a voz dele."},
{"v":15,"t":"Porque você será testemunha dele para todas as pessoas, contando o que viu e ouviu."},
{"v":16,"t":"Agora, por que você está esperando? Levante-se, seja batizado e lave os seus pecados, invocando o nome dele."},
{"v":17,"t":"Quando voltei a Jerusalém, enquanto orava no templo, tive uma visão."},
{"v":18,"t":"Vi o Senhor dizendo: Saia rápido de Jerusalém, porque eles não vão aceitar o seu testemunho sobre mim."},
{"v":19,"t":"Eu disse: Senhor, eles sabem muito bem que eu ia de sinagoga em sinagoga prendendo e açoitando os que criam no senhor."},
{"v":20,"t":"Quando o sangue de Estêvão, sua testemunha, foi derramado, eu estava lá aprovando. Eu tomava conta das roupas dos que o matavam."},
{"v":21,"t":"Mas o Senhor me disse: Vá! Eu vou enviar você para longe, para os não judeus."},
{"v":22,"t":"O povo ouviu Paulo até esse ponto. Depois começaram a gritar: Tire esse homem da terra! Ele não merece viver!"},
{"v":23,"t":"Enquanto gritavam, jogavam as capas e levantavam poeira no ar."},
{"v":24,"t":"O comandante mandou levar Paulo para dentro da fortaleza. Ordenou que o interrogassem com açoites para descobrir por que o povo gritava contra ele."},
{"v":25,"t":"Quando estavam amarrando Paulo para açoitá-lo, ele disse ao oficial que estava ali: É permitido açoitar um cidadão romano sem julgamento?"},
{"v":26,"t":"Quando o oficial ouviu isso, foi ao comandante e disse: O que o senhor vai fazer? Esse homem é cidadão romano!"},
{"v":27,"t":"O comandante foi até Paulo e perguntou: Me diga, você é cidadão romano? Paulo respondeu: Sim, eu sou."},
{"v":28,"t":"O comandante disse: Eu paguei muito caro para ter essa cidadania. Paulo disse: Mas eu já nasci com ela."},
{"v":29,"t":"Na mesma hora, os que iam interrogá-lo se afastaram. O comandante também ficou com medo quando soube que tinha acorrentado um cidadão romano."},
{"v":30,"t":"No dia seguinte, querendo saber exatamente do que Paulo estava sendo acusado pelos judeus, o comandante mandou soltá-lo. Ordenou que os chefes dos sacerdotes e todo o tribunal se reunissem. Trouxe Paulo e o colocou diante deles."},
]})

# Chapter 23 - Paul before the Sanhedrin
chapters.append({"c":23,"verses":[
{"v":1,"t":"Paulo olhou firme para o tribunal e disse: Irmãos, eu tenho vivido diante de Deus com a consciência limpa até hoje."},
{"v":2,"t":"O sumo sacerdote Ananias ordenou que os que estavam perto de Paulo batessem na boca dele."},
{"v":3,"t":"Paulo disse a ele: Deus vai bater em você, parede caiada! Você está aí sentado para me julgar conforme a lei, e manda me bater contra a lei?"},
{"v":4,"t":"Os que estavam perto disseram: Você insulta o sumo sacerdote de Deus?"},
{"v":5,"t":"Paulo respondeu: Irmãos, eu não sabia que ele era o sumo sacerdote. Porque está escrito: Não fale mal do líder do seu povo."},
{"v":6,"t":"Paulo sabia que uma parte do tribunal era de saduceus e outra de fariseus. Então gritou no tribunal: Irmãos, eu sou fariseu, filho de fariseu! Estou sendo julgado por causa da esperança na ressurreição dos mortos!"},
{"v":7,"t":"Quando disse isso, começou uma briga entre os fariseus e os saduceus. O grupo ficou dividido."},
{"v":8,"t":"Os saduceus dizem que não existe ressurreição, nem anjos, nem espíritos. Mas os fariseus acreditam em tudo isso."},
{"v":9,"t":"Houve um grande tumulto. Alguns mestres da lei do grupo dos fariseus se levantaram e argumentaram: Não encontramos nada de errado neste homem. E se um espírito ou um anjo falou com ele?"},
{"v":10,"t":"A briga ficou tão violenta que o comandante teve medo de que Paulo fosse despedaçado. Mandou os soldados descerem e o tirarem do meio deles à força. Levaram-no de volta para a fortaleza."},
{"v":11,"t":"Na noite seguinte, o Senhor apareceu a Paulo e disse: Coragem! Assim como você testemunhou sobre mim em Jerusalém, é preciso que testemunhe também em Roma."},
{"v":12,"t":"Quando amanheceu, os judeus fizeram um plano. Fizeram um juramento de que não comeriam nem beberiam até matar Paulo."},
{"v":13,"t":"Mais de quarenta homens participaram desse plano."},
{"v":14,"t":"Foram aos chefes dos sacerdotes e aos anciãos e disseram: Fizemos um juramento solene de não comer nada até matarmos Paulo."},
{"v":15,"t":"Agora, vocês e o tribunal peçam ao comandante que traga Paulo até vocês. Finjam que querem examinar o caso dele com mais cuidado. Nós estaremos prontos para matá-lo no caminho."},
{"v":16,"t":"Mas o filho da irmã de Paulo ouviu sobre a emboscada. Ele foi à fortaleza e contou a Paulo."},
{"v":17,"t":"Paulo chamou um dos oficiais e disse: Leve este jovem ao comandante. Ele tem algo para contar."},
{"v":18,"t":"O oficial o levou ao comandante e disse: O prisioneiro Paulo me pediu para trazer este jovem até o senhor. Ele tem algo para dizer."},
{"v":19,"t":"O comandante pegou o jovem pela mão, levou-o a um lugar reservado e perguntou: O que você tem para me dizer?"},
{"v":20,"t":"Ele disse: Os judeus combinaram de pedir que o senhor leve Paulo ao tribunal amanhã, como se quisessem investigar o caso dele com mais cuidado."},
{"v":21,"t":"Não aceite! Porque mais de quarenta homens estão preparando uma emboscada contra ele. Fizeram um juramento de não comer nem beber até matá-lo. Já estão prontos, esperando apenas a sua ordem."},
{"v":22,"t":"O comandante mandou o jovem embora e ordenou: Não conte a ninguém que me disse isso."},
{"v":23,"t":"Chamou dois oficiais e disse: Preparem duzentos soldados, setenta cavaleiros e duzentos lanceiros para ir a Cesareia às nove horas da noite."},
{"v":24,"t":"Providenciem cavalos para Paulo montar e o levem em segurança ao governador Félix."},
{"v":25,"t":"Escreveu uma carta com estas palavras:"},
{"v":26,"t":"Cláudio Lísias ao excelentíssimo governador Félix. Saudações!"},
{"v":27,"t":"Este homem foi preso pelos judeus. Estavam prestes a matá-lo quando eu cheguei com meus soldados e o resgatei. Soube que ele é cidadão romano."},
{"v":28,"t":"Querendo saber do que o acusavam, levei-o ao tribunal deles."},
{"v":29,"t":"Descobri que a acusação era sobre questões da lei deles. Não havia nenhuma acusação que merecesse morte ou prisão."},
{"v":30,"t":"Quando fui informado de um plano contra este homem, eu o enviei ao senhor imediatamente. Também mandei que os acusadores apresentem suas queixas diante do senhor."},
{"v":31,"t":"Os soldados obedeceram. Pegaram Paulo durante a noite e o levaram até Antipátride."},
{"v":32,"t":"No dia seguinte, deixaram os cavaleiros continuarem com ele e voltaram para a fortaleza."},
{"v":33,"t":"Quando chegaram a Cesareia, entregaram a carta ao governador e apresentaram Paulo a ele."},
{"v":34,"t":"O governador leu a carta e perguntou de que província Paulo era. Soube que era da Cilícia."},
{"v":35,"t":"Disse: Eu vou ouvir o seu caso quando seus acusadores chegarem. E mandou guardá-lo no palácio de Herodes."},
]})

# Chapter 24 - Paul before Felix
chapters.append({"c":24,"verses":[
{"v":1,"t":"Cinco dias depois, o sumo sacerdote Ananias desceu a Cesareia com alguns anciãos e um advogado chamado Tértulo. Apresentaram as acusações contra Paulo ao governador."},
{"v":2,"t":"Paulo foi chamado. Tértulo começou a acusá-lo: Excelentíssimo Félix, graças ao senhor temos vivido em grande paz. Muitas melhorias foram feitas para esta nação pelo seu governo."},
{"v":3,"t":"Em tudo e em todo lugar reconhecemos isso com muita gratidão."},
{"v":4,"t":"Mas para não tomar muito do seu tempo, peço que nos ouça com a sua costumeira gentileza."},
{"v":5,"t":"Descobrimos que este homem é um problema. Ele provoca confusão entre os judeus pelo mundo inteiro. É líder da seita dos nazarenos."},
{"v":6,"t":"Ele até tentou profanar o templo. Por isso o prendemos."},
{"v":7,"t":"Mas o comandante Lísias veio e o tirou das nossas mãos com grande violência."},
{"v":8,"t":"Mandou que os acusadores viessem ao senhor. O senhor mesmo pode interrogá-lo e descobrir a verdade sobre tudo isso."},
{"v":9,"t":"Os judeus também concordaram, dizendo que tudo era verdade."},
{"v":10,"t":"O governador fez sinal para Paulo falar. Paulo disse: Sei que o senhor é juiz desta nação há muitos anos. Por isso faço minha defesa com confiança."},
{"v":11,"t":"O senhor pode verificar que não faz mais de doze dias que subi a Jerusalém para adorar."},
{"v":12,"t":"Ninguém me encontrou discutindo com alguém no templo, nem agitando a multidão nas sinagogas ou em qualquer lugar da cidade."},
{"v":13,"t":"Eles não podem provar as acusações que fazem contra mim."},
{"v":14,"t":"Mas eu confesso isto: eu sirvo ao Deus dos nossos antepassados seguindo o Caminho que eles chamam de seita. Eu creio em tudo o que está escrito na Lei e nos Profetas."},
{"v":15,"t":"Tenho a mesma esperança em Deus que eles também têm: que haverá uma ressurreição tanto dos justos como dos injustos."},
{"v":16,"t":"Por isso me esforço sempre para ter a consciência limpa diante de Deus e das pessoas."},
{"v":17,"t":"Depois de vários anos, voltei a Jerusalém para trazer doações ao meu povo e para apresentar ofertas."},
{"v":18,"t":"Estavam me encontrando no templo purificado, sem multidão e sem tumulto."},
{"v":19,"t":"Mas alguns judeus da província da Ásia deveriam estar aqui diante do senhor para me acusar, se tivessem algo contra mim."},
{"v":20,"t":"Ou então que estes mesmos aqui digam que crime encontraram em mim quando estive diante do tribunal."},
{"v":21,"t":"A não ser por esta única frase que gritei quando estava no meio deles: Estou sendo julgado diante de vocês hoje por causa da ressurreição dos mortos!"},
{"v":22,"t":"Félix, que conhecia bem o Caminho, adiou o julgamento dizendo: Quando o comandante Lísias descer, eu decidirei o caso de vocês."},
{"v":23,"t":"Ordenou ao oficial que mantivesse Paulo preso, mas com alguma liberdade. Que não impedissem seus amigos de cuidar dele."},
{"v":24,"t":"Alguns dias depois, Félix veio com sua esposa Drusila, que era judia. Mandou chamar Paulo e o ouviu falar sobre a fé em Cristo Jesus."},
{"v":25,"t":"Quando Paulo falou sobre justiça, autocontrole e o juízo futuro, Félix ficou com medo e disse: Pode ir agora. Quando eu tiver oportunidade, vou chamá-lo de novo."},
{"v":26,"t":"Ao mesmo tempo, Félix esperava que Paulo lhe oferecesse dinheiro. Por isso mandava chamá-lo com frequência para conversar."},
{"v":27,"t":"Dois anos se passaram. Félix foi substituído por Pórcio Festo. Para agradar aos judeus, Félix deixou Paulo preso."},
]})

# Chapter 25 - Paul appeals to Caesar
chapters.append({"c":25,"verses":[
{"v":1,"t":"Três dias depois de chegar à província, Festo subiu de Cesareia a Jerusalém."},
{"v":2,"t":"Os chefes dos sacerdotes e os principais judeus apresentaram as acusações contra Paulo."},
{"v":3,"t":"Pediram um favor a Festo: que transferisse Paulo para Jerusalém. Planejavam uma emboscada para matá-lo no caminho."},
{"v":4,"t":"Festo respondeu que Paulo ficaria preso em Cesareia e que ele mesmo voltaria para lá em breve."},
{"v":5,"t":"Disse: Que os líderes de vocês desçam comigo. Se esse homem fez algo errado, que o acusem lá."},
{"v":6,"t":"Festo ficou em Jerusalém não mais que oito ou dez dias. Depois desceu a Cesareia. No dia seguinte abriu o tribunal e mandou trazer Paulo."},
{"v":7,"t":"Quando Paulo chegou, os judeus que tinham descido de Jerusalém ficaram ao redor dele. Fizeram muitas acusações graves que não conseguiam provar."},
{"v":8,"t":"Paulo se defendeu: Eu não cometi nenhum crime contra a lei dos judeus, nem contra o templo, nem contra o imperador."},
{"v":9,"t":"Festo, querendo agradar aos judeus, perguntou a Paulo: Você quer subir a Jerusalém e ser julgado lá diante de mim sobre essas acusações?"},
{"v":10,"t":"Paulo respondeu: Estou diante do tribunal do imperador, onde devo ser julgado. Não fiz nada de errado contra os judeus, como o senhor sabe muito bem."},
{"v":11,"t":"Se eu cometi algum crime que mereça a morte, não me recuso a morrer. Mas se as acusações deles não são verdadeiras, ninguém pode me entregar a eles. Eu apelo para o imperador!"},
{"v":12,"t":"Festo conversou com seus conselheiros e respondeu: Você apelou para o imperador. Ao imperador irá!"},
{"v":13,"t":"Alguns dias depois, o rei Agripa e Berenice chegaram a Cesareia para cumprimentar Festo."},
{"v":14,"t":"Como ficaram ali vários dias, Festo apresentou o caso de Paulo ao rei. Disse: Félix deixou aqui um prisioneiro."},
{"v":15,"t":"Quando estive em Jerusalém, os chefes dos sacerdotes e os anciãos dos judeus apresentaram acusações contra ele e pediram que eu o condenasse."},
{"v":16,"t":"Eu disse a eles que não é costume dos romanos entregar alguém sem que o acusado tenha a chance de se defender diante dos acusadores."},
{"v":17,"t":"Quando eles vieram aqui, não perdi tempo. No dia seguinte abri o tribunal e mandei trazer o homem."},
{"v":18,"t":"Os acusadores se levantaram, mas não fizeram nenhuma das acusações graves que eu esperava."},
{"v":19,"t":"A discussão era sobre questões da religião deles e sobre um homem chamado Jesus, que morreu, mas que Paulo afirma estar vivo."},
{"v":20,"t":"Eu não sabia como investigar essas questões. Por isso perguntei se ele queria ir a Jerusalém para ser julgado lá."},
{"v":21,"t":"Mas Paulo apelou para que seu caso fosse guardado para a decisão do imperador. Então ordenei que ficasse preso até que eu o enviasse ao imperador."},
{"v":22,"t":"Agripa disse a Festo: Eu gostaria de ouvir esse homem pessoalmente. Festo respondeu: Amanhã o senhor o ouvirá."},
{"v":23,"t":"No dia seguinte, Agripa e Berenice chegaram com grande pompa. Entraram no salão de audiências junto com os comandantes militares e os homens importantes da cidade. Festo mandou trazer Paulo."},
{"v":24,"t":"Festo disse: Rei Agripa e todos os presentes, vocês estão vendo este homem. Toda a comunidade judaica veio a mim, tanto em Jerusalém como aqui, gritando que ele não deve mais viver."},
{"v":25,"t":"Mas eu não encontrei nada que mereça a morte. Como ele apelou para o imperador, decidi enviá-lo."},
{"v":26,"t":"Porém não tenho nada definitivo para escrever ao imperador sobre ele. Por isso o trouxe diante de vocês, especialmente diante do senhor, rei Agripa. Assim, depois deste interrogatório, eu terei algo para escrever."},
{"v":27,"t":"Porque me parece sem sentido enviar um prisioneiro sem indicar as acusações contra ele."},
]})

# Chapter 26 - Paul before Agrippa
chapters.append({"c":26,"verses":[
{"v":1,"t":"Agripa disse a Paulo: Você tem permissão para falar em sua defesa. Paulo estendeu a mão e começou a se defender:"},
{"v":2,"t":"Rei Agripa, eu me considero feliz por poder me defender hoje diante do senhor de todas as acusações dos judeus."},
{"v":3,"t":"Principalmente porque o senhor conhece bem todos os costumes e as questões dos judeus. Por isso peço que me ouça com paciência."},
{"v":4,"t":"Todos os judeus conhecem a minha vida desde a juventude. Desde o começo eu vivi no meio do meu povo e em Jerusalém."},
{"v":5,"t":"Eles me conhecem há muito tempo e podem confirmar que eu vivi como fariseu, o grupo mais rigoroso da nossa religião."},
{"v":6,"t":"Agora estou sendo julgado por causa da esperança na promessa que Deus fez aos nossos antepassados."},
{"v":7,"t":"Esta é a promessa que nossas doze tribos esperam alcançar, servindo a Deus dia e noite com dedicação. É por causa desta esperança, ó rei, que os judeus me acusam."},
{"v":8,"t":"Por que vocês acham impossível que Deus ressuscite os mortos?"},
{"v":9,"t":"Eu mesmo achava que devia fazer tudo para combater o nome de Jesus de Nazaré."},
{"v":10,"t":"E foi o que fiz em Jerusalém. Com autorização dos chefes dos sacerdotes, prendi muitos dos santos. Quando eles eram condenados à morte, eu votava a favor."},
{"v":11,"t":"Muitas vezes fui de sinagoga em sinagoga para castigá-los e forçá-los a falar contra Jesus. Minha raiva era tanta que os perseguia até em cidades estrangeiras."},
{"v":12,"t":"Foi nessa missão que eu ia para Damasco, com autorização e ordem dos chefes dos sacerdotes."},
{"v":13,"t":"Ao meio-dia, ó rei, enquanto eu estava na estrada, vi uma luz do céu mais brilhante que o sol. Ela brilhou ao redor de mim e dos que viajavam comigo."},
{"v":14,"t":"Todos nós caímos no chão. Ouvi uma voz em hebraico dizendo: Saulo, Saulo, por que você me persegue? É difícil para você resistir ao que eu quero."},
{"v":15,"t":"Perguntei: Quem é o senhor? O Senhor respondeu: Eu sou Jesus, a quem você persegue."},
{"v":16,"t":"Levante-se e fique de pé. Eu apareci a você para designá-lo como meu servo e testemunha. Você vai contar o que viu hoje e o que eu ainda vou mostrar a você."},
{"v":17,"t":"Eu vou livrá-lo do seu próprio povo e dos não judeus, para quem eu estou enviando você."},
{"v":18,"t":"Você vai abrir os olhos deles para que saiam da escuridão para a luz e do poder de Satanás para Deus. Assim receberão o perdão dos pecados e um lugar entre os que são santificados pela fé em mim."},
{"v":19,"t":"Portanto, rei Agripa, não desobedeci à visão que veio do céu."},
{"v":20,"t":"Primeiro aos que estavam em Damasco, depois em Jerusalém e em toda a Judeia, e também aos não judeus, eu preguei que se arrependessem e se voltassem para Deus, provando o arrependimento pelas suas ações."},
{"v":21,"t":"É por isso que os judeus me agarraram no templo e tentaram me matar."},
{"v":22,"t":"Mas Deus me ajudou até hoje. Por isso estou aqui testemunhando a pequenos e grandes. Não digo nada além do que os profetas e Moisés disseram que aconteceria:"},
{"v":23,"t":"que o Cristo sofreria e seria o primeiro a ressuscitar dos mortos. E que anunciaria luz ao seu povo e aos não judeus."},
{"v":24,"t":"Enquanto Paulo se defendia assim, Festo gritou: Paulo, você está louco! Tanto estudo deixou você maluco!"},
{"v":25,"t":"Paulo respondeu: Não estou louco, excelentíssimo Festo! O que digo é verdade e faz sentido."},
{"v":26,"t":"O rei conhece essas coisas. Falo com liberdade diante dele. Tenho certeza de que nada disso lhe é desconhecido, porque não aconteceu em segredo."},
{"v":27,"t":"Rei Agripa, o senhor crê nos profetas? Eu sei que crê!"},
{"v":28,"t":"Agripa disse a Paulo: Em tão pouco tempo você quer me convencer a ser cristão?"},
{"v":29,"t":"Paulo respondeu: Em pouco ou em muito tempo, eu peço a Deus que não só o senhor, mas todos que me ouvem hoje, se tornem como eu sou. Menos estas correntes, é claro!"},
{"v":30,"t":"O rei se levantou, junto com o governador, Berenice e todos os que estavam sentados com eles."},
{"v":31,"t":"Ao saírem, comentavam entre si: Este homem não fez nada que mereça morte ou prisão."},
{"v":32,"t":"Agripa disse a Festo: Esse homem poderia ser solto se não tivesse apelado para o imperador."},
]})

# Chapter 27 - Voyage to Rome, shipwreck
chapters.append({"c":27,"verses":[
{"v":1,"t":"Quando foi decidido que navegaríamos para a Itália, Paulo e alguns outros prisioneiros foram entregues a um centurião chamado Júlio, do batalhão Imperial."},
{"v":2,"t":"Embarcamos num navio de Adramítio que ia viajar pela costa da província da Ásia. Aristarco, da Macedônia, de Tessalônica, estava conosco."},
{"v":3,"t":"No dia seguinte aportamos em Sidom. Júlio tratou Paulo com gentileza e permitiu que visitasse os amigos e recebesse cuidados."},
{"v":4,"t":"De lá navegamos protegidos por Chipre porque os ventos eram contrários."},
{"v":5,"t":"Atravessamos o mar aberto ao longo da Cilícia e Panfília e chegamos a Mirra, na Lícia."},
{"v":6,"t":"Ali o centurião encontrou um navio de Alexandria que ia para a Itália. Embarcou-nos nele."},
{"v":7,"t":"Navegamos devagar por muitos dias. Com dificuldade chegamos perto de Cnido. O vento não nos deixava seguir em frente. Então navegamos protegidos por Creta, passando pelo cabo Salmone."},
{"v":8,"t":"Com muita dificuldade, seguimos pela costa e chegamos a um lugar chamado Bons Portos, perto da cidade de Laseia."},
{"v":9,"t":"Já tinha passado muito tempo e a navegação ficou perigosa. O jejum do Dia do Perdão já tinha passado. Paulo os avisou:"},
{"v":10,"t":"Homens, eu vejo que esta viagem vai causar muitos problemas e grandes perdas, não só da carga e do navio, mas também das nossas vidas."},
{"v":11,"t":"Mas o centurião confiou mais no piloto e no dono do navio do que no que Paulo disse."},
{"v":12,"t":"Como o porto não era bom para passar o inverno, a maioria decidiu continuar. Queriam chegar a Fênix, um porto de Creta que dava para o sudoeste e noroeste. Ali passariam o inverno."},
{"v":13,"t":"Quando um vento suave do sul começou a soprar, acharam que tinham conseguido o que queriam. Levantaram âncora e navegaram perto da costa de Creta."},
{"v":14,"t":"Mas logo um vento forte, chamado Euroaquilão, desceu da ilha."},
{"v":15,"t":"O navio foi arrastado e não conseguia enfrentar o vento. Então nos deixamos levar."},
{"v":16,"t":"Passamos protegidos por uma pequena ilha chamada Clauda. Com muita dificuldade conseguimos segurar o bote salva-vidas."},
{"v":17,"t":"Depois de içá-lo, usaram cordas para amarrar o navio por baixo. Com medo de encalhar nos bancos de areia de Sirte, baixaram a vela e ficaram à deriva."},
{"v":18,"t":"A tempestade continuava muito forte. No dia seguinte começaram a jogar a carga fora."},
{"v":19,"t":"No terceiro dia, com as próprias mãos jogaram fora os equipamentos do navio."},
{"v":20,"t":"Durante muitos dias não vimos nem o sol nem as estrelas. A tempestade continuava forte. Perdemos toda a esperança de sobreviver."},
{"v":21,"t":"Já fazia muito tempo que ninguém comia. Paulo se levantou no meio deles e disse: Homens, vocês deviam ter me ouvido e não saído de Creta. Teriam evitado esses problemas e essas perdas."},
{"v":22,"t":"Mas agora eu peço que tenham coragem! Nenhum de vocês vai morrer. Só o navio será perdido."},
{"v":23,"t":"Porque na noite passada um anjo do Deus a quem pertenço e a quem sirvo apareceu a mim."},
{"v":24,"t":"Ele disse: Não tenha medo, Paulo! Você precisa comparecer diante do imperador. E Deus, por graça, salvou todos os que navegam com você."},
{"v":25,"t":"Portanto, coragem, homens! Eu confio em Deus que vai acontecer exatamente como me foi dito."},
{"v":26,"t":"Mas nós vamos dar numa ilha."},
{"v":27,"t":"Na décima quarta noite, enquanto éramos levados pelo mar Adriático, por volta da meia-noite os marinheiros sentiram que estávamos chegando perto de terra."},
{"v":28,"t":"Mediram a profundidade: vinte braças. Um pouco mais adiante mediram de novo: quinze braças."},
{"v":29,"t":"Com medo de bater em rochas, jogaram quatro âncoras pela popa e desejaram que amanhecesse."},
{"v":30,"t":"Os marinheiros tentaram fugir do navio. Desceram o bote no mar fingindo que iam jogar âncoras pela proa."},
{"v":31,"t":"Paulo disse ao centurião e aos soldados: Se esses homens não ficarem no navio, vocês não poderão se salvar."},
{"v":32,"t":"Então os soldados cortaram as cordas do bote e o deixaram cair."},
{"v":33,"t":"Antes do dia clarear, Paulo insistiu que todos comessem. Disse: Já faz catorze dias que vocês ficam sem comer, esperando."},
{"v":34,"t":"Por isso eu peço que comam. Vocês precisam disso para sobreviver. Nenhum de vocês vai perder nem um fio de cabelo."},
{"v":35,"t":"Depois de dizer isso, Paulo pegou pão, agradeceu a Deus diante de todos, partiu e começou a comer."},
{"v":36,"t":"Todos ficaram encorajados e também comeram."},
{"v":37,"t":"Éramos duzentos e setenta e seis pessoas no navio."},
{"v":38,"t":"Depois que comeram o suficiente, aliviaram o navio jogando o trigo no mar."},
{"v":39,"t":"Quando amanheceu, não reconheceram a terra. Mas viram uma baía com uma praia. Decidiram tentar encalhar o navio ali, se possível."},
{"v":40,"t":"Cortaram as âncoras e as deixaram no mar. Ao mesmo tempo soltaram as amarras dos lemes, levantaram a vela da frente ao vento e se dirigiram para a praia."},
{"v":41,"t":"Mas o navio bateu num banco de areia e encalhou. A proa ficou presa e não se movia. A popa começou a se despedaçar com a força das ondas."},
{"v":42,"t":"Os soldados queriam matar os prisioneiros para que nenhum escapasse nadando."},
{"v":43,"t":"Mas o centurião queria salvar Paulo e impediu o plano. Mandou que os que sabiam nadar pulassem primeiro e fossem para terra."},
{"v":44,"t":"Os outros seguiram em tábuas ou em pedaços do navio. Assim todos chegaram à terra em segurança."},
]})

# Chapter 28 - Malta, arrival in Rome
chapters.append({"c":28,"verses":[
{"v":1,"t":"Depois de todos se salvarem, ficamos sabendo que a ilha se chamava Malta."},
{"v":2,"t":"Os moradores da ilha nos trataram com muita gentileza. Acenderam uma fogueira e nos receberam bem, porque estava chovendo e fazia frio."},
{"v":3,"t":"Paulo juntou um monte de gravetos e os colocou no fogo. Uma cobra venenosa saiu por causa do calor e mordeu a mão dele."},
{"v":4,"t":"Quando os moradores viram a cobra pendurada na mão dele, disseram uns aos outros: Com certeza esse homem é um assassino. Escapou do mar, mas a justiça divina não o deixou viver."},
{"v":5,"t":"Mas Paulo sacudiu a cobra no fogo e não sofreu nenhum mal."},
{"v":6,"t":"Eles esperavam que ele fosse inchar ou cair morto de repente. Depois de esperar muito tempo e ver que nada de mal acontecia, mudaram de ideia e disseram que ele era um deus."},
{"v":7,"t":"Perto dali havia terras do homem principal da ilha, chamado Públio. Ele nos recebeu e nos hospedou com gentileza durante três dias."},
{"v":8,"t":"O pai de Públio estava de cama com febre e diarreia. Paulo foi visitá-lo, orou, colocou as mãos sobre ele e o curou."},
{"v":9,"t":"Quando isso aconteceu, os outros doentes da ilha também vieram e foram curados."},
{"v":10,"t":"Eles nos honraram de muitas formas. Quando partimos, nos deram tudo de que precisávamos."},
{"v":11,"t":"Três meses depois, embarcamos num navio de Alexandria que tinha passado o inverno na ilha. O navio tinha como símbolo os Gêmeos."},
{"v":12,"t":"Aportamos em Siracusa e ficamos três dias."},
{"v":13,"t":"De lá navegamos e chegamos a Régio. No dia seguinte soprou o vento sul e em dois dias chegamos a Putéoli."},
{"v":14,"t":"Ali encontramos alguns irmãos que nos convidaram para ficar uma semana com eles. E assim chegamos a Roma."},
{"v":15,"t":"Os irmãos de Roma ouviram que estávamos chegando e vieram nos encontrar na Praça de Ápio e nas Três Tabernas. Quando Paulo os viu, agradeceu a Deus e ficou encorajado."},
{"v":16,"t":"Quando chegamos a Roma, Paulo recebeu permissão para morar sozinho com um soldado que o vigiava."},
{"v":17,"t":"Três dias depois, Paulo reuniu os líderes judeus dali. Quando se reuniram, disse: Irmãos, embora eu não tenha feito nada contra o nosso povo nem contra os costumes dos nossos antepassados, fui preso em Jerusalém e entregue aos romanos."},
{"v":18,"t":"Os romanos me interrogaram e queriam me soltar porque não encontraram em mim nenhum motivo para a pena de morte."},
{"v":19,"t":"Mas os judeus se opuseram. Então fui obrigado a apelar para o imperador, sem ter nenhuma acusação para fazer contra o meu povo."},
{"v":20,"t":"Foi por isso que pedi para ver e falar com vocês. Estou preso com esta corrente por causa da esperança de Israel."},
{"v":21,"t":"Eles responderam: Nós não recebemos nenhuma carta da Judeia sobre você. Nenhum dos irmãos que veio de lá disse ou relatou algo ruim sobre você."},
{"v":22,"t":"Mas queremos ouvir o que você pensa. Porque sabemos que em todo lugar falam contra essa seita."},
{"v":23,"t":"Marcaram um dia e muitos foram ao lugar onde Paulo estava hospedado. Desde a manhã até a noite, ele explicou e testemunhou sobre o Reino de Deus. Tentava convencê-los sobre Jesus usando a Lei de Moisés e os Profetas."},
{"v":24,"t":"Alguns foram convencidos pelo que ele dizia. Outros não creram."},
{"v":25,"t":"Como não concordavam entre si, começaram a ir embora. Paulo disse uma última coisa: O Espírito Santo falou bem aos seus antepassados por meio do profeta Isaías:"},
{"v":26,"t":"Vá a esse povo e diga: Vocês vão ouvir, mas não vão entender. Vão olhar, mas não vão ver."},
{"v":27,"t":"Porque o coração deste povo ficou insensível. Eles taparam os ouvidos e fecharam os olhos. Senão veriam com os olhos, ouviriam com os ouvidos, entenderiam com o coração, se voltariam para mim, e eu os curaria."},
{"v":28,"t":"Portanto, saibam que esta salvação de Deus foi enviada aos não judeus. Eles vão ouvir!"},
{"v":29,"t":"Depois que Paulo disse isso, os judeus foram embora discutindo muito entre si."},
{"v":30,"t":"Paulo ficou dois anos inteiros na casa que tinha alugado. Recebia todos os que o visitavam."},
{"v":31,"t":"Pregava o Reino de Deus e ensinava sobre o Senhor Jesus Cristo com toda a coragem, sem ninguém o impedir."},
]})

# Save chapters 21-28
with open('v:/GitHub/orgs/devzolo/bible/static/data/bfl/atos_trans_part3.json', 'w', encoding='utf-8') as f:
    json.dump(chapters, f, ensure_ascii=False)
print(f"Saved chapters 21-{chapters[-1]['c']}, total verses: {sum(len(c['verses']) for c in chapters)}")
